import {expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {OpcPackage,addRelationship} from '../../src/opc/index.ts';import {inspectComments,inspectCommentThreads,setCommentResolved,setCommentThreadResolved,type CommentInfo,type CommentThreadInspection,type CommentThreadReceipt} from '../../src/docx/comments.ts';import {parseXml,elements,attribute,type XmlElement} from '../../src/xml/index.ts';import {commentFixture} from './comments-docx.ts';import {fixturePath,F} from '../../scripts/fixture-inputs.ts';import {OoxmlError} from '../../src/errors.ts';import type {StepBinding} from '../../scripts/gherkin.ts';
const EX='word/commentsExtended.xml',C='word/comments.xml',W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',W15='http://schemas.microsoft.com/office/word/2012/wordml';const roots:string[]=[];export async function cleanupCommentThreads(){await Promise.all(roots.splice(0).map(p=>rm(p,{recursive:true,force:true})));}
type State={p:OpcPackage;source:string;output:string;before:Uint8Array;live:Uint8Array;fixture:Uint8Array;baseline:OpcPackage;layout:string;comments:CommentInfo[];report?:CommentThreadInspection;receipt?:CommentThreadReceipt;reopened?:OpcPackage;error?:unknown;returned?:boolean;expectedXML?:string;marker?:number[];unknown?:boolean;reached?:boolean;counts?:number[];repeatBefore?:Uint8Array};const state=(c:Record<string,unknown>)=>c.threadOutcome as State;
async function nested(p:OpcPackage){const source=p.text(C),match=source.match(/<w:comment\b[^>]*w:id="2"[^]*?<\/w:comment>/)!;expect(match).not.toBeNull();const clone=match[0].replace('w:id="2"','w:id="3"').replaceAll('0E00AF3F','12345678').replace('(this is a threaded reply)','Nested reply');p.set(C,source.replace('</w:comments>',clone+'</w:comments>'));p.set(EX,p.text(EX).replace('</w15:commentsEx>','<w15:commentEx w15:paraId="12345678" w15:paraIdParent="0E00AF3F" w15:done="0"/></w15:commentsEx>'));}
async function setup(c:Record<string,unknown>,layout='pinned',defect?:string,encoding?:string){let p=await commentFixture(defect==='unsupported-body'?'revision-body':defect==='unknown-target'||defect==='missing-root-entry'||defect==='external-settings'?undefined:defect);const fixture=await Bun.file(fixturePath(F.officeWord.comments)).bytes();if(layout==='nested'||layout==='reordered')await nested(p);if(layout==='reordered'){const source=p.text(C),chunks=[...source.matchAll(/<w:comment\b[^]*?<\/w:comment>/g)].map(m=>m[0]);expect(chunks).toHaveLength(4);p.set(C,source.replace(/<w:comment\b[^]*?<\/w:comment>/g,'').replace('</w:comments>',[chunks[3],chunks[2],chunks[0],chunks[1]].join('')+'</w:comments>'));}
 if(defect==='missing-root-entry')p.set(EX,p.text(EX).replace(/<w15:commentEx\b[^>]*w15:paraId="3395B541"[^>]*\/>/,''));if(defect==='external-settings')addRelationship(p,p.mainPart(),'http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings','https://example.invalid/settings',{external:true});
 let marker:number[]|undefined;if(encoding){let x=p.text(EX).replaceAll('w15:','q:').replace('xmlns:w15=','xmlns:q=').replace('q:done="0"',"q:done = 'false'");if(encoding==='UTF-8-BOM'){marker=[239,187,191];p.set(EX,new Uint8Array([...marker,...new TextEncoder().encode(x)]));}else{x=x.replace('UTF-8','UTF-16');const b=new Uint8Array(2+x.length*2),little=encoding==='UTF-16LE';marker=little?[255,254]:[254,255];b.set(marker);const v=new DataView(b.buffer);for(let i=0;i<x.length;i++)v.setUint16(2+i*2,x.charCodeAt(i),little);p.set(EX,b);}}
 const dir=await mkdtemp(join(tmpdir(),'thread-outcomes-'));roots.push(dir);const source=join(dir,'source.docx'),output=join(dir,'output.docx'),before=p.toBytes();await Bun.write(source,before);p=await OpcPackage.open(source);let comments:CommentInfo[]=[];if(!defect)comments=inspectComments(p).comments;c.threadOutcome={p,source,output,before,live:before,fixture,baseline:await OpcPackage.open(before),layout,comments,marker,unknown:defect==='unknown-target'} satisfies State;
}
async function sourceUnchanged(s:State){expect(await Bun.file(s.source).bytes()).toEqual(Uint8Array.from(s.before));expect(await Bun.file(fixturePath(F.officeWord.comments)).bytes()).toEqual(Uint8Array.from(s.fixture));}
function frozen(x:unknown){if(x&&typeof x==='object'){expect(Object.isFrozen(x)).toBe(true);for(const v of Object.values(x))frozen(v);}}
function expectedXML(s:State,resolved:boolean){const xml=s.p.text(EX),selected=new Set(s.comments.filter(c=>c.id!=='0').map(c=>c.paragraphId)),edits:{start:number;end:number;value:string}[]=[];for(const n of elements(parseXml(xml),'commentEx',W15))if(selected.has(attribute(n,'paraId',W15))){const raw=xml.slice(n.start,n.openEnd),m=/\b(?:w15|q):done\s*=\s*(["'])(.*?)\1/.exec(raw)!;expect(m).not.toBeNull();const start=n.start+m.index+m[0].length-m[2]!.length-1;edits.push({start,end:start+m[2]!.length,value:resolved?'1':'0'});}let next=xml;for(const e of edits.sort((a,b)=>b.start-a.start))next=next.slice(0,e.start)+e.value+next.slice(e.end);return next;}
function capture(s:State,op:()=>unknown){s.returned=false;try{op();s.returned=true;}catch(e){s.error=e;}}
export const bindings:StepBinding[]=[
 {pattern:/^fixture (fixture-[a-f0-9]+) prepared as (pinned|nested|reordered) existing threads$/,run:async(c,id,layout)=>{expect(id).toBe(F.officeWord.comments);await setup(c,layout);}},
 {pattern:/^existing comment threads are inspected$/,run:c=>{state(c).report=inspectCommentThreads(state(c).p);}},
 {pattern:/^the (pinned|nested|reordered) thread roots, flat replies, parent IDs and bodies match the pinned expectations$/,run:(c,layout)=>{const s=state(c),r=s.report!;expect(r.unsupported).toEqual([]);expect(r.threads.map(t=>[t.root.id,t.replies.map(c=>c.id)])).toEqual([['0',[]],['1',layout==='pinned'?['2']:layout==='nested'?['2','3']:['3','2']]]);const all=r.threads.flatMap(t=>[t.root,...t.replies]);expect(all.find(c=>c.id==='0')!.text).toBe('This is a great opening');expect(all.find(c=>c.id==='1')!.text).toBe('Classical hubris');expect(all.find(c=>c.id==='2')!.text).toBe('(this is a threaded reply)');expect(all.find(c=>c.id==='2')!.parentId).toBe('1');if(layout!=='pinned'){expect(all.find(c=>c.id==='3')!.text).toBe('Nested reply');expect(all.find(c=>c.id==='3')!.parentId).toBe('2');}expect(all.every(c=>c.author==='Rui Carmo'&&!c.resolved)).toBe(true);}},
 {pattern:/^all returned thread records and unsupported findings are immutable detached snapshots$/,run:c=>{const s=state(c);frozen(s.report);const clone=JSON.stringify(s.report);s.p.transaction(()=>{setCommentResolved(s.p,'1',true);expect(JSON.stringify(s.report)).toBe(clone);setCommentResolved(s.p,'1',false);});}},
 {pattern:/^the existing-thread package and source archive are unchanged$/,run:async c=>{const s=state(c);expect(s.p.toBytes()).toEqual(s.live);await sourceUnchanged(s);}},
 {pattern:/^existing thread member (\d+) is resolved and saved to a new path$/,run:async(c,id)=>{const s=state(c);s.expectedXML=expectedXML(s,true);s.receipt=setCommentThreadResolved(s.p,id!,true);await s.p.save(s.output);s.reopened=await OpcPackage.open(s.output);}},
 {pattern:/^the receipt has root 1, members ([\d,]+) and (\d+) changed flags in the existing extension only$/,run:(c,ids,n)=>expect(state(c).receipt).toEqual({rootId:'1',commentIds:ids!.split(','),changed:Number(n),changedParts:[EX]})},
 {pattern:/^reopened selected members are resolved with their original parents and bodies while root 0 remains open$/,run:c=>{const s=state(c);expect(inspectComments(s.reopened!).comments).toEqual(s.comments.map(c=>c.id==='0'?c:{...c,resolved:true}));}},
 {pattern:/^the reopened package differs only in selected done flags and the source archive is unchanged$/,run:async c=>{const s=state(c),p=s.reopened!;expect(p.text(EX)).toBe(s.expectedXML!);expect(p.names()).toEqual(s.baseline.names());for(const n of p.names())if(n!==EX)expect(p.get(n)).toEqual(s.baseline.get(n));await sourceUnchanged(s);}},
 {pattern:/^the selected thread is reopened and saved again$/,run:async c=>{const s=state(c);const receipt=setCommentThreadResolved(s.reopened!,'1',false);expect(receipt.changed).toBe(s.comments.length-1);await s.reopened!.save(s.output);s.reopened=await OpcPackage.open(s.output);}},
 {pattern:/^the original package member bytes are restored by the fresh read$/,run:c=>{const s=state(c);expect(s.reopened!.names()).toEqual(s.baseline.names());for(const n of s.baseline.names())expect(s.reopened!.get(n)).toEqual(s.baseline.get(n));}},
 {pattern:/^only comment 1 is resolved then thread member 2 is resolved twice$/,run:c=>{const s=state(c);setCommentResolved(s.p,'1',true);expect(inspectComments(s.p).comments.map(c=>[c.id,c.resolved])).toEqual([['0',false],['1',true],['2',false]]);const xml=expectedXML(s,true),wanted=s.comments.map(c=>c.id==='0'?c:{...c,resolved:true});const first=setCommentThreadResolved(s.p,'2',true);expect(first).toEqual({rootId:'1',commentIds:['1','2'],changed:1,changedParts:[EX]});expect(inspectComments(s.p).comments).toEqual(wanted);expect(s.p.text(EX)).toBe(xml);expect(s.p.names()).toEqual(s.baseline.names());for(const n of s.p.names())if(n!==EX)expect(s.p.get(n)).toEqual(s.baseline.get(n));s.repeatBefore=s.p.toBytes();const last=setCommentThreadResolved(s.p,'2',true);expect(last).toEqual({rootId:'1',commentIds:['1','2'],changed:0,changedParts:[]});expect(inspectComments(s.p).comments).toEqual(wanted);s.counts=[first.changed,last.changed];}},
 {pattern:/^the single-comment edit leaves reply 2 open, the first thread edit changes one flag and the second changes zero$/,run:c=>{const s=state(c);expect(s.counts).toEqual([1,0]);expect(inspectComments(s.p).comments).toEqual(s.comments.map(c=>c.id==='0'?c:{...c,resolved:true}));}}, 
 {pattern:/^the repeated thread edit preserves the exact current archive and original source archive$/,run:async c=>{const s=state(c);expect(s.p.toBytes()).toEqual(s.repeatBefore!);await sourceUnchanged(s);}},
 {pattern:/^fixture (fixture-[a-f0-9]+) prepared with thread defect (\S+)$/,run:async(c,id,defect)=>{expect(id).toBe(F.officeWord.comments);await setup(c,'pinned',defect);}},
 {pattern:/^thread member 2 is requested open$/,run:c=>{const s=state(c);capture(s,()=>{s.receipt=setCommentThreadResolved(s.p,s.unknown?'99':'2',false);});}},
 {pattern:/^a typed thread refusal returns no receipt$/,run:c=>{const s=state(c);expect(s.returned).toBe(false);expect(s.receipt).toBeUndefined();expect(s.error).toBeInstanceOf(OoxmlError);}},
 {pattern:/^the main document has a prior unrelated edit$/,run:c=>{const s=state(c);s.p.set(s.p.mainPart(),s.p.text(s.p.mainPart()).replace('</w:body>','<w:p><w:r><w:t>Prior</w:t></w:r></w:p></w:body>'));s.live=s.p.toBytes();}},
 {pattern:/^resolving member 3 fails after (part-write|serialization)$/,run:(c,stage)=>{const s=state(c),p=s.p,set=p.set.bind(p),serialize=p.toBytes.bind(p);s.reached=false;if(stage==='part-write')p.set=(n,v)=>{set(n,v);if(n===EX){s.reached=true;throw Error('injected write');}};else p.toBytes=()=>{s.reached=true;throw Error('injected serialization');};try{capture(s,()=>{s.receipt=setCommentThreadResolved(p,'3',true);});}finally{p.set=set;p.toBytes=serialize;}}},
 {pattern:/^the injected fault was reached and no receipt is returned$/,run:c=>{const s=state(c);expect(s.reached).toBe(true);expect(s.returned).toBe(false);expect(s.receipt).toBeUndefined();expect(String(s.error)).toContain('injected');}},
 {pattern:/^fixture (fixture-[a-f0-9]+) prepared with (UTF-8-BOM|UTF-16LE|UTF-16BE) thread extension$/,run:async(c,id,encoding)=>{expect(id).toBe(F.officeWord.comments);await setup(c,'nested',undefined,encoding);}},
 {pattern:/^the reopened thread has three resolved members and preserves the extension marker and aliased namespace meaning$/,run:c=>{const s=state(c),p=s.reopened!;expect(inspectComments(p).comments).toEqual(s.comments.map(c=>c.id==='0'?c:{...c,resolved:true}));expect([...p.get(EX)!.slice(0,s.marker!.length)]).toEqual(s.marker!);expect(parseXml(p.text(EX)).root.namespaceURI).toBe(W15);expect(p.text(EX)).toContain("q:done = 'false'");}},
 {pattern:/^two immutable root groups and a nonempty unsupported report are returned$/,run:c=>{const r=state(c).report!;expect(r.threads).toHaveLength(2);expect(r.unsupported.length).toBeGreaterThan(0);frozen(r);}},
 {pattern:/^fixture (fixture-[a-f0-9]+) prepared with 10001 extension-free comments$/,run:async(c,id)=>{expect(id).toBe(F.officeWord.comments);await setup(c);const s=state(c),p=s.p;p.set(C,`<w:comments xmlns:w="${W}">${Array.from({length:10001},(_,id)=>`<w:comment w:id="${id}"><w:p/></w:comment>`).join('')}</w:comments>`);p.delete(EX);const rel='word/_rels/document.xml.rels';p.set(rel,p.text(rel).replace(/<Relationship\b[^>]*Type="[^"]*\/commentsExtended"[^>]*\/>/,''));s.before=p.toBytes();await Bun.write(s.source,s.before);s.p=await OpcPackage.open(s.source);s.live=s.before;}},
 {pattern:/^thread inspection and member 0 resolution are attempted$/,run:c=>{const s=state(c),errors:unknown[]=[];for(const op of [()=>inspectCommentThreads(s.p),()=>setCommentThreadResolved(s.p,'0',false)])try{op();errors.push(null);}catch(e){errors.push(e);}s.error=errors;}},
 {pattern:/^both operations return the comment limit refusal and no result$/,run:c=>{const errors=state(c).error as unknown[];expect(errors).toHaveLength(2);for(const e of errors)expect(e).toMatchObject({code:'docx-comments-limit'});}},
];
