import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile,readFile,mkdir,readdir,symlink,readlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {ContractWorkbook,ContractPresentation,OoxmlError,type ContractTextAnchor,type ContractTableCell} from '../../src/index.ts';
import {writeZip} from '../../src/opc/zip.ts';
import {contract20Recipe,contract20Root} from '../helpers/contract20-inputs.ts';
import {archive,xml,all,child,graph,partText,S,P,A,R,CT,masked,changed,sheets,worksheetCell,xlsxValue,calc,slideParts,placeholders,notes,table,tableMatrix,creation} from '../helpers/contract20-observations.ts';
import {sameMembers,type Node} from '../helpers/contract20-oracle.ts';
import type {StepBinding} from '../../scripts/gherkin.ts';
import pin from '../../docs/behaviors/contract20-candidate.json';
const encoder=new TextEncoder(),decoder=new TextDecoder();
type Session=ContractWorkbook|ContractPresentation;
type State={dir:string;source:Uint8Array;sourcePath:string;original:Uint8Array;inputParts:Map<string,Uint8Array>;session:Session;before:Map<string,Uint8Array>;saved?:Map<string,Uint8Array>;reopened?:Session;error?:OoxmlError;anchor?:ContractTextAnchor;cell?:ContractTableCell;observed?:unknown;other?:Session;otherInput?:Uint8Array;otherBefore?:Map<string,Uint8Array>;secondError?:OoxmlError;post?:Map<string,Uint8Array>;operands:{value:object;before:string}[]};
type Action=(s:State)=>unknown|Promise<unknown>;
const states=new Set<State>();
const ledger=await Bun.file(contract20Root+'/ledgers/contract20.json').json();
assert.equal(new Bun.CryptoHasher('sha256').update(await Bun.file(contract20Root+'/ledgers/contract20.json').bytes()).digest('hex'),'1814d45d98ff0c596da99324fcaa2ec47982c89535120ba8b1919c47006a1b43');
const cases=ledger.files.flatMap((f:any)=>f.scenarios.flatMap((s:any)=>s.after.map((c:any)=>({...c,feature:f.path,featureSha256:f.afterSha256}))));
const policy=await Bun.file(contract20Root+'/ledgers/contract20-creation-policy.json').json();
const short=(id:string)=>id.replace('@id-','');
function operand<T extends object>(s:State,value:T):T{s.operands.push({value,before:JSON.stringify(value)});return value;}
function operandCustody(s:State):void{for(const o of s.operands)assert.equal(JSON.stringify(o.value),o.before,'Actual caller operand custody');}
function w(s:State):ContractWorkbook{assert(s.session instanceof ContractWorkbook);return s.session;}
function p(s:State):ContractPresentation{assert(s.session instanceof ContractPresentation);return s.session;}
function current(s:State):Map<string,Uint8Array>{return archive(s.session.package.toBytes());}
function saved(s:State):Map<string,Uint8Array>{assert(s.saved);return s.saved;}
function invoke(s:State,fn:()=>unknown):void{s.error=undefined;try{const result=fn();assert.equal(result,undefined,'Unexpected partial operation result');}catch(e){if(e instanceof OoxmlError)s.error=e;else throw e;}}
function refuse(s:State,code:string):void{assert(s.error instanceof OoxmlError,'Expected typed refusal');assert.equal(s.error.code,code);}
async function initialise(s:State,recipe:string,kind:'xlsx'|'pptx'):Promise<void>{s.source=await contract20Recipe(recipe);s.original=s.source.slice();s.sourcePath=join(s.dir,'source.'+kind);await writeFile(s.sourcePath,s.source);s.inputParts=archive(s.source);graph(s.inputParts);s.session=kind==='xlsx'?await ContractWorkbook.open(s.source):await ContractPresentation.open(s.source);s.before=current(s);sameMembers(s.inputParts,s.before);}
function record(s:State):void{s.before=current(s);}
async function sourceCustody(s:State):Promise<void>{operandCustody(s);assert.deepEqual(s.source,s.original);assert.deepEqual(new Uint8Array(await readFile(s.sourcePath)),s.original);sameMembers(s.inputParts,archive(s.original));}
async function save(s:State):Promise<void>{const path=join(s.dir,'saved.'+(s.session instanceof ContractWorkbook?'xlsx':'pptx'));await s.session.save(path);s.saved=archive(new Uint8Array(await readFile(path)));graph(s.saved);s.reopened=s.session instanceof ContractWorkbook?await ContractWorkbook.open(path):await ContractPresentation.open(path);sameMembers(s.saved,archive(s.reopened.package.toBytes()));}
function allGraphCustody(s:State):void{const before=graph(s.inputParts),after=graph(saved(s));for(const edge of before.edges)assert(after.edges.some(e=>JSON.stringify(e)===JSON.stringify(edge)),'Original relationship identity');for(const [part,type]of before.types)assert.equal(after.types.get(part),type);}
async function saveFaults(s:State):Promise<void>{const before=current(s),prior=join(s.dir,'fault-prior'),link=join(s.dir,'fault-output');await writeFile(prior,'prior destination');await symlink(prior,link);const names=(await readdir(s.dir)).sort();await assert.rejects(()=>s.session.save(link),(e:unknown)=>e instanceof OoxmlError&&e.code==='opc-symlink-destination');assert.equal(await readFile(prior,'utf8'),'prior destination');assert.equal(await readlink(link),prior);assert.deepEqual((await readdir(s.dir)).sort(),names);await assert.rejects(()=>s.session.save(join(s.dir,'absent-parent','output')),(e:unknown)=>(e as NodeJS.ErrnoException).code==='ENOENT');assert.equal(await Bun.file(join(s.dir,'absent-parent','output')).exists(),false);sameMembers(before,current(s));if(s.session instanceof ContractWorkbook)assert(s.session.readCell(s.session.sheetnames[0]!,s.session.sheetnames[0]==='Calc'?'A2':'A1'));else assert(p(s).inspectText(0).length);}
function sameCurrent(s:State,before=s.before):void{sameMembers(before,current(s));}
function changedNodes(s:State,parts:string[]):void{changed(s.inputParts,saved(s),parts);}
function cellValue(s:State,sheet:string,ref:string,expected:unknown):void{assert.deepEqual(xlsxValue(saved(s),sheet,ref),expected);assert(s.reopened instanceof ContractWorkbook);const actual=s.reopened.readCell(sheet,ref)!;if((expected as any).kind==='formula'){assert.equal(actual.formula,(expected as any).formula);assert.equal(actual.cached,(expected as any).cached);}else{assert.equal(actual.kind,(expected as any).kind);assert.equal(actual.value,(expected as any).value);}}
function cellMask(s:State,sheet:string,refs:string[]):void{const part=sheets(s.inputParts).find(x=>x.name===sheet)!.part,a=partText(s.inputParts,part),b=partText(saved(s),part);assert.equal(masked(a,refs.map(r=>worksheetCell(s.inputParts,sheet,r))),masked(b,refs.map(r=>worksheetCell(saved(s),sheet,r))));}
function clearFormulas(s:State):void{for(const [sheet,ref,formula]of [['Model','B1','A1+A2'],['Model','B2','B1*2'],['Summary','A1','Model!B1*3'],['Summary','B1','40+2']]){const c=worksheetCell(saved(s),sheet!,ref!);assert.equal(child(c,'f',S)?.text,formula);assert(!child(c,'v',S));cellValue(s,sheet!,ref!,{kind:'formula',formula,cached:null});}}
function worksheetCacheMask(s:State,part:string,editedRef?:string):void{const a=partText(s.inputParts,part),b=partText(saved(s),part),ar=xml(a),br=xml(b),ac=all(ar,'c',S),bc=all(br,'c',S);assert.deepEqual(ac.map(n=>n.attrs.r),bc.map(n=>n.attrs.r));const spansA:Node[]=[],spansB:Node[]=[];for(const n of ac){const next=bc.find(c=>c.attrs.r===n.attrs.r)!;if(n.attrs.r===editedRef){spansA.push(n);spansB.push(next);}else if(child(n,'f',S)){const v=child(n,'v',S);if(v){const anchor=child(next,'f',S)!;spansA.push(v);spansB.push({...anchor,start:anchor.end,end:anchor.end});}}}assert.equal(masked(a,spansA),masked(b,spansB));}
function calcMask(s:State):void{const a=partText(s.inputParts,'xl/workbook.xml'),b=partText(saved(s),'xl/workbook.xml'),old=all(xml(a),'calcPr',S),next=all(xml(b),'calcPr',S);assert.equal(next.length,1);if(old.length){assert.equal(old.length,1);assert.equal(masked(a,old),masked(b,next));}else assert.equal(a,b.slice(0,next[0]!.start)+b.slice(next[0]!.end));}
function textMask(s:State,part:string,first:number,last:number):void{const a=partText(s.inputParts,part),b=partText(saved(s),part),ap=all(xml(a),'p',A)[0]!,bp=all(xml(b),'p',A)[0]!,old=ap.children.filter(n=>n.ns===A&&n.local==='r'),next=bp.children.filter(n=>n.ns===A&&n.local==='r');assert.equal(masked(a,[{start:old[first]!.start,end:old[last]!.end}]),masked(b,[{start:next[first]!.start,end:next[last]!.end}]));}
function tableTextMask(s:State):void{const a=partText(s.inputParts,'ppt/slides/slide1.xml'),b=partText(saved(s),'ppt/slides/slide1.xml'),old=all(table(s.inputParts,'ppt/slides/slide1.xml',4).cells[0]![0]!,'t',A),next=all(table(saved(s),'ppt/slides/slide1.xml',4).cells[0]![0]!,'t',A);assert.equal(old.length,1);assert.equal(next.length,1);assert.equal(masked(a,old.map(n=>({start:n.openEnd,end:n.closeStart}))),masked(b,next.map(n=>({start:n.openEnd,end:n.closeStart}))));}
function successMask(s:State,id:string):void{switch(id){case 'xlsx-clear-cross-sheet-caches':case 'xlsx-cache-scope-opaque-parts':worksheetCacheMask(s,'xl/worksheets/sheet1.xml','A1');worksheetCacheMask(s,'xl/worksheets/sheet2.xml');calcMask(s);break;case 'xlsx-prefixed-namespace-safe-edits':{const a=partText(s.inputParts,'xl/worksheets/sheet1.xml'),b=partText(saved(s),'xl/worksheets/sheet1.xml'),old=['A1','B1'].map(r=>worksheetCell(s.inputParts,'Prefixed',r)),next=['A1','B1'].map(r=>worksheetCell(saved(s),'Prefixed',r)),v=child(worksheetCell(s.inputParts,'Prefixed','C1'),'v',S)!,f=child(worksheetCell(saved(s),'Prefixed','C1'),'f',S)!;assert.equal(masked(a,[...old,v]),masked(b,[...next,{start:f.end,end:f.end}]));calcMask(s);break;}case 'xlsx-styled-blank-cell-editable':cellMask(s,'StyledBlank',['A1']);break;case 'pptx-cross-run-replace':{const a=partText(s.inputParts,'ppt/slides/slide1.xml'),b=partText(saved(s),'ppt/slides/slide1.xml'),old=all(xml(a),'p',A)[0]!.children.filter(n=>n.local==='r'&&n.ns===A),next=all(xml(b),'p',A)[0]!.children.filter(n=>n.local==='r'&&n.ns===A);assert.equal(masked(a,[{start:old[0]!.start,end:old[1]!.end}]),masked(b,[{start:next[0]!.start,end:next[1]!.end}]));break;}case 'pptx-table-formatting':tableTextMask(s);break;case 'pptx-create-anchor-preservation':textMask(s,'ppt/slides/slide1.xml',0,0);appendMask(s);break;default:throw Error('Missing lexical mask '+id);}}
function appendMask(s:State):void{const after=saved(s),g=graph(s.inputParts),main=g.edges.find(e=>e.owner===''&&e.type===R+'/officeDocument')!.resolved,newSlide=slideParts(after)[1]!,nextGraph=graph(after),edge=nextGraph.edges.find(e=>e.owner===main&&e.type===R+'/slide'&&e.resolved===newSlide);assert(edge);for(const[part,local,ns,select]of [[main,'sldId',P,(n:Node)=>Object.entries(n.attrs).some(([k,v])=>k.endsWith(':id')&&v===edge.id)],['ppt/_rels/presentation.xml.rels','Relationship','http://schemas.openxmlformats.org/package/2006/relationships',(n:Node)=>n.attrs.Id===edge.id],['[Content_Types].xml','Override',CT,(n:Node)=>n.attrs.PartName==='/'+newSlide]] as [string,string,string,(n:Node)=>boolean][]){const a=partText(s.inputParts,part),b=partText(after,part),nodes=all(xml(b),local,ns).filter(select);assert.equal(nodes.length,1);assert.equal(a,b.slice(0,nodes[0]!.start)+b.slice(nodes[0]!.end),'Append lexical allowance '+part);}}
function common(id:string):Action[]{return [save,sourceCustody,s=>successMask(s,id),allGraphCustody,saveFaults];}
const plans=new Map<string,Action[]>();
function set(id:string,actions:Action[]):void{plans.set('@id-'+id,actions);}
set('xlsx-read-rel-linked-shared-strings',[
 s=>initialise(s,'rel-values','xlsx'),record,s=>{s.observed=Object.fromEntries(w(s).sheetnames.map(name=>[name,Object.fromEntries(['A1','B1','C1','D1'].map(ref=>{const c=w(s).readCell(name,ref)!;return [ref,c.kind==='formula'?{kind:c.kind,formula:c.formula,cached:c.cached}:{kind:c.kind,value:c.value}];}))]));},
 s=>assert.deepEqual(sheets(s.inputParts),[{name:'Alpha',part:'xl/worksheets/sheet2.xml'},{name:'Beta',part:'xl/worksheets/sheet1.xml'}]),
 s=>{const expected={Alpha:{A1:{kind:'string',value:'alpha shared'},B1:{kind:'number',value:7},C1:{kind:'boolean',value:false},D1:{kind:'formula',formula:'B1+1',cached:8}},Beta:{A1:{kind:'string',value:'beta shared'},B1:{kind:'number',value:42},C1:{kind:'boolean',value:true},D1:{kind:'formula',formula:'B1*2',cached:84}}};assert.deepEqual(s.observed,expected);for(const[name,cells]of Object.entries(expected))for(const[ref,value]of Object.entries(cells))assert.deepEqual(xlsxValue(s.inputParts,name,ref),value);},
 async s=>{sameCurrent(s);await sourceCustody(s);}
]);
set('xlsx-clear-cross-sheet-caches',[
 s=>initialise(s,'cross-caches','xlsx'),s=>{assert.equal(w(s).readCell('Model','A1')?.value,1);record(s);},s=>w(s).setCellValue('Model','A1',10),...common('xlsx-clear-cross-sheet-caches'),
 s=>{cellValue(s,'Model','A1',{kind:'number',value:10});cellValue(s,'Model','A2',{kind:'number',value:2});},
 s=>{for(const[name,ref,formula]of [['Model','B1','A1+A2'],['Model','B2','B1*2'],['Summary','A1','Model!B1*3'],['Summary','B1','40+2']])assert.equal(child(worksheetCell(saved(s),name!,ref!),'f',S)?.text,formula);},clearFormulas,s=>calc(saved(s)),s=>changedNodes(s,['xl/workbook.xml','xl/worksheets/sheet1.xml','xl/worksheets/sheet2.xml']),
 async s=>{const fresh=await ContractWorkbook.open(s.original);fresh.setCellValue('Model','A1',1);sameMembers(s.inputParts,archive(fresh.toBytes()));}
]);
set('xlsx-prefixed-namespace-safe-edits',[
 s=>initialise(s,'prefixed-cells','xlsx'),record,s=>{w(s).setCellValue('Prefixed','A1','Alpha');w(s).setCellValue('Prefixed','B1',7);},...common('xlsx-prefixed-namespace-safe-edits'),
 s=>{cellValue(s,'Prefixed','A1',{kind:'string',value:'Alpha'});cellValue(s,'Prefixed','B1',{kind:'number',value:7});for(const[ref,style]of [['A1','1'],['B1','2']]){const c=worksheetCell(saved(s),'Prefixed',ref!);assert.equal(c.attrs.r,ref);assert.equal(c.attrs.s,style);assert.equal(c.name,'x:c');}},
 s=>{const a=worksheetCell(saved(s),'Prefixed','A1'),b=worksheetCell(saved(s),'Prefixed','B1');assert.equal(child(a,'is',S)?.name,'x:is');assert.equal(all(a,'t',S)[0]?.name,'x:t');assert.equal(child(b,'v',S)?.name,'x:v');},
 s=>{assert.equal(child(worksheetCell(saved(s),'Prefixed','C1'),'f',S)?.text,'1+1');assert(!child(worksheetCell(saved(s),'Prefixed','C1'),'v',S));},s=>{calc(saved(s));assert.equal(all(xml(partText(saved(s),'xl/workbook.xml')),'calcPr',S)[0]!.name,'x:calcPr');},s=>changedNodes(s,['xl/workbook.xml','xl/worksheets/sheet1.xml']),s=>successMask(s,'xlsx-prefixed-namespace-safe-edits'),s=>{assert.deepEqual(saved(s).get('xl/styles.xml'),s.inputParts.get('xl/styles.xml'));for(const ref of ['A1','B1']){const before=worksheetCell(s.inputParts,'Prefixed',ref),after=worksheetCell(saved(s),'Prefixed',ref);for(const[k,v]of Object.entries(before.attrs))assert.equal(after.attrs[k],v);}}
]);
set('xlsx-phonetic-guides-excluded',[s=>initialise(s,'phonetic-strings','xlsx'),record,s=>{s.observed={A1:w(s).readCell('Phonetics','A1')?.value,B1:w(s).readCell('Phonetics','B1')?.value};},s=>{assert.deepEqual(s.observed,{A1:'Alpha Beta',B1:'Gamma Delta'});assert.equal(xlsxValue(s.inputParts,'Phonetics','A1').value,'Alpha Beta');assert.equal(xlsxValue(s.inputParts,'Phonetics','B1').value,'Gamma Delta');},s=>{for(const v of Object.values(s.observed as Record<string,string>))assert(!v.includes('Guide'));},async s=>{sameCurrent(s);await sourceCustody(s);}]);
set('xlsx-styled-blank-cell-editable',[s=>initialise(s,'styled-blank','xlsx'),s=>{assert.equal(w(s).readCell('StyledBlank','A1')?.value,null);assert.equal(w(s).readCell('StyledBlank','A1')?.styleId,'1');assert.equal(w(s).readCell('StyledBlank','B1')?.value,5);assert.equal(w(s).readCell('StyledBlank','B1')?.styleId,'2');},s=>w(s).setCellValue('StyledBlank','A1','filled'),...common('xlsx-styled-blank-cell-editable'),s=>{cellValue(s,'StyledBlank','A1',{kind:'string',value:'filled'});assert.equal(worksheetCell(saved(s),'StyledBlank','A1').attrs.s,'1');},s=>{cellValue(s,'StyledBlank','B1',{kind:'number',value:5});assert.equal(worksheetCell(saved(s),'StyledBlank','B1').attrs.s,'2');},s=>changedNodes(s,['xl/worksheets/sheet1.xml']),s=>cellMask(s,'StyledBlank',['A1']),s=>{assert.deepEqual(saved(s).get('xl/styles.xml'),s.inputParts.get('xl/styles.xml'));allGraphCustody(s);}]);
for(const[kind,ref]of [['shared','B2'],['array','D2']])set('xlsx-refuse-'+kind+'-formula-overwrite',[s=>initialise(s,'attributed-formulas','xlsx'),async s=>{record(s);await writeFile(join(s.dir,'prior'),'prior');s.observed=w(s).readCell('Calc','A2');},s=>invoke(s,()=>w(s).setCellValue('Calc',ref!,99)),s=>refuse(s,'xlsx-'+kind+'-formula-edit-unsupported'),s=>sameCurrent(s),async s=>{await save(s);sameMembers(s.inputParts,saved(s));},async s=>{await sourceCustody(s);assert.equal(await readFile(join(s.dir,'prior'),'utf8'),'prior');await saveFaults(s);},s=>{assert.deepEqual(w(s).readCell('Calc','A2'),s.observed);w(s).setCellValue('Calc','A2',1);sameCurrent(s);}]);
for(const topology of ['array','dataTable'])plans.set('@id-xlsx-array-input-refusal|'+topology,[s=>initialise(s,'input-'+topology,'xlsx'),s=>{assert.equal(w(s).readCell('Model','A1')?.value,1);assert.equal(child(worksheetCell(s.inputParts,'Summary','A1'),'v',S)?.text,'1');assert.equal(child(worksheetCell(s.inputParts,'Summary','A2'),'v',S)?.text,'2');},async s=>{record(s);await writeFile(join(s.dir,'prior'),'prior');},s=>invoke(s,()=>w(s).setCellValue('Model','A1',10)),s=>refuse(s,'xlsx-cache-topology-unsupported'),s=>sameCurrent(s),async s=>{await save(s);sameMembers(s.inputParts,saved(s));},async s=>{await sourceCustody(s);assert.equal(await readFile(join(s.dir,'prior'),'utf8'),'prior');await saveFaults(s);},s=>{w(s).setCellValue('Model','A1',1);sameCurrent(s);}]);
set('xlsx-cache-scope-opaque-parts',[s=>initialise(s,'opaque-caches','xlsx'),s=>{const g=graph(s.inputParts);for(const[id,type,path]of [['cache1','urn:contract20:opaque/chart','xl/charts/cache-boundary.xml'],['cache2','urn:contract20:opaque/external','xl/externalLinks/cache-boundary.xml']])assert(g.edges.some(e=>e.owner===''&&e.id===id&&e.type===type&&e.resolved===path));assert(!g.edges.some(e=>e.type===R+'/chart'||e.type===R+'/externalLink'));},record,s=>w(s).setCellValue('Model','A1',10,operand(s,{opaqueRetention:true})),...common('xlsx-cache-scope-opaque-parts'),clearFormulas,s=>calc(saved(s)),s=>{for(const part of ['xl/charts/cache-boundary.xml','xl/externalLinks/cache-boundary.xml']){assert.deepEqual(saved(s).get(part),s.inputParts.get(part));assert(partText(saved(s),part).includes('>1<'));}},s=>changedNodes(s,['xl/workbook.xml','xl/worksheets/sheet1.xml','xl/worksheets/sheet2.xml']),async s=>{const parts=new Map(s.inputParts),path='xl/_rels/workbook.xml.rels';parts.set(path,encoder.encode(partText(parts,path).replace('</Relationships>','<Relationship Id="semanticExtra" Type="'+R+'/externalLink" Target="externalLinks/cache-boundary.xml"/></Relationships>')));const input=writeZip(parts),session=await ContractWorkbook.open(input);let error:unknown;try{session.setCellValue('Model','A1',10,operand(s,{opaqueRetention:true}));}catch(e){if(e instanceof OoxmlError)error=e;else throw e;}assert(error instanceof OoxmlError);assert.equal(error.code,'xlsx-cache-topology-unsupported');sameMembers(parts,archive(session.toBytes()));assert.equal(await Bun.file(join(s.dir,'variant-output')).exists(),false);}]);
set('pptx-order-notes-read',[
 async s=>{await initialise(s,'ordered-notes','pptx');s.otherInput=await contract20Recipe('missing-notes');s.other=await ContractPresentation.open(s.otherInput);s.otherBefore=archive(s.otherInput);},record,s=>{s.observed={titles:p(s).slides.map((_,i)=>p(s).inspectText(i)[0]!.text),notes:p(s).slides.map((_,i)=>p(s).readNotes(i))};},
 s=>{assert.deepEqual((s.observed as any).titles,['Chapter 5','Frankenstein Lecture Series','Chapter 4','Chapter 2','Chapter 3']);assert.deepEqual(slideParts(s.inputParts),[5,1,4,2,3].map(i=>'ppt/slides/slide'+i+'.xml'));},
 s=>{const texts=[(s.observed as any).notes[0].text,(s.observed as any).notes[4].text];assert.deepEqual(texts,['Key themes:\ncreation, responsibility, isolation\n\nVisible date: 2026-03-12','Compare to Prometheus myth']);for(let i=0;i<5;i++)assert.deepEqual((s.observed as any).notes[i],notes(s.inputParts,i));},
 s=>{assert(s.other instanceof ContractPresentation);assert.deepEqual(s.other.readNotes(0),{hasNotes:false,text:''});},
 async s=>{sameCurrent(s);sameMembers(s.otherBefore!,archive(s.other!.package.toBytes()));await sourceCustody(s);},
 s=>{const first=(s.observed as any).notes[0].text;assert(!first.includes('\v'));assert(first.includes('\n\nVisible date: 2026-03-12'));}
]);
set('pptx-readable-unsupported-topology',[
 s=>initialise(s,'break-field-title','pptx'),record,s=>{const para=p(s).inspectText(0)[0]!;s.observed=para;s.anchor=para.anchor;},s=>assert.equal((s.observed as any).text,'Chapter\n7 Notes'),
 s=>{assert.deepEqual((s.observed as any).runs,[{text:'Chapter',attrs:{b:'1'}},{text:'\n',attrs:{lang:'en-US'}},{text:'7',attrs:{i:'1'}},{text:' Notes',attrs:{u:'sng'}}]);const para=all(xml(partText(s.inputParts,'ppt/slides/slide1.xml')),'p',A)[0]!;assert.equal(para.children.map(n=>n.local).join(','),'r,br,fld,r');},
 s=>invoke(s,()=>p(s).replaceTextAt(s.anchor!,'Chapter','Section')),s=>refuse(s,'PPTX_UNSUPPORTED_TEXT_TOPOLOGY'),async s=>{sameCurrent(s);await sourceCustody(s);},s=>{assert.equal(p(s).inspectText(0)[0]!.text,'Chapter\n7 Notes');sameCurrent(s);}
]);
set('pptx-cross-run-replace',[
 s=>initialise(s,'fragmented-title','pptx'),s=>{const para=p(s).inspectText(0)[0]!;assert.equal(para.text,'Frankenstein');assert.deepEqual(para.runs,[{text:'Fran',attrs:{b:'1'}},{text:'ken',attrs:{i:'1'}},{text:'stein',attrs:{u:'sng'}}]);s.anchor=para.anchor;},record,s=>p(s).replaceTextAt(s.anchor!,'anken','iend'),...common('pptx-cross-run-replace'),
 s=>{assert.equal(placeholders(saved(s))[0]![0],'Friendstein');assert(s.reopened instanceof ContractPresentation);assert.equal(s.reopened.inspectText(0)[0]!.text,'Friendstein');},
 s=>{const runs=all(xml(partText(saved(s),'ppt/slides/slide1.xml')),'p',A)[0]!.children.filter(n=>n.ns===A&&n.local==='r');assert.deepEqual(runs.map(n=>({text:child(n,'t',A)!.text,attributes:{...(child(n,'rPr',A)?.attrs??{})}})),[{text:'Fr',attributes:{b:'1'}},{text:'iend',attributes:{b:'1'}},{text:'stein',attributes:{u:'sng'}}]);},s=>changedNodes(s,['ppt/slides/slide1.xml']),s=>successMask(s,'pptx-cross-run-replace'),s=>{assert.equal(decoder.decode(saved(s).get('custom/data.bin')),'keep-me-safe');changedNodes(s,['ppt/slides/slide1.xml']);}
]);
set('pptx-stale-anchor-refusal',[
 s=>initialise(s,'plain-title','pptx'),s=>{const para=p(s).inspectText(0)[0]!;assert.equal(para.text,'Frankenstein');s.anchor=para.anchor;},s=>p(s).replaceTextAt(s.anchor!,'Frankenstein','Creature'),s=>{s.post=current(s);},s=>invoke(s,()=>p(s).replaceTextAt(s.anchor!,'Frankenstein','Monster')),s=>refuse(s,'PPTX_STALE_ANCHOR'),async s=>{sameCurrent(s,s.post);await sourceCustody(s);},async s=>{await save(s);sameMembers(s.post!,saved(s));assert.equal(placeholders(saved(s))[0]![0],'Creature');},s=>{const fresh=p(s).inspectText(0)[0]!.anchor;p(s).replaceTextAt(fresh,'Creature','Creature');sameCurrent(s,s.post);allGraphCustody(s);}
]);
async function emptySession(s:State):Promise<void>{s.session=ContractPresentation.create();s.source=s.session.package.toBytes();s.original=s.source.slice();s.inputParts=archive(s.source);s.before=s.inputParts;s.sourcePath=join(s.dir,'scratch-source.pptx');await writeFile(s.sourcePath,s.source);}
set('pptx-create-new-minimal',[
 emptySession,s=>{p(s).addTextSlide('Created title 1','Created subtitle 1');p(s).addTextSlide('Created title 2','Created subtitle 2');},save,s=>{assert.equal(p(s).slides.length,2);assert.equal(p(s).presentation.slideMasterCount,1);assert.equal(p(s).presentation.slideLayoutCount,1);},s=>assert.deepEqual(placeholders(saved(s)),[['Created title 1','Created subtitle 1'],['Created title 2','Created subtitle 2']]),s=>creation(saved(s),policy,2),s=>{creation(saved(s),policy,2);const graphData=graph(saved(s));for(const slide of slideParts(saved(s)))assert.equal(graphData.edges.filter(e=>e.owner===slide&&e.type===R+'/slideLayout').length,1);},s=>{const g=graph(saved(s));assert(!g.edges.some(e=>e.external||/\/(notesSlide|image|externalLink)$/.test(e.type)));for(const slide of slideParts(saved(s)))assert.equal(all(xml(partText(saved(s),slide)),'tbl',A).length,0);assert.equal(slideParts(saved(s)).length,2);},saveFaults
]);
set('pptx-create-anchor-preservation',[
 s=>initialise(s,'title-subtitle-source','pptx'),s=>{const para=p(s).inspectText(0)[0]!;assert.equal(para.text,'Original title');s.anchor=para.anchor;record(s);},s=>p(s).addTextSlide('Appended title','Appended subtitle'),s=>{assert.deepEqual(current(s).get('ppt/slides/slide1.xml'),s.inputParts.get('ppt/slides/slide1.xml'));assert.deepEqual(current(s).get('ppt/slides/_rels/slide1.xml.rels'),s.inputParts.get('ppt/slides/_rels/slide1.xml.rels'));s.post=current(s);},s=>p(s).replaceTextAt(s.anchor!,'Original title','Edited original title'),...common('pptx-create-anchor-preservation'),
 s=>assert.deepEqual(placeholders(saved(s)),[['Edited original title','Original subtitle'],['Appended title','Appended subtitle']]),s=>{textMask(s,'ppt/slides/slide1.xml',0,0);allGraphCustody(s);},s=>{const additions=[...saved(s).keys()].filter(n=>!s.inputParts.has(n));assert.equal(additions.length,2);const slide=slideParts(saved(s))[1]!;assert.deepEqual(additions.slice().sort(),[slide,slide.replace(/\/([^/]+)$/,'/_rels/$1.rels')].sort());assert.equal(graph(saved(s)).edges.filter(e=>e.owner===slide).length,1);assert.equal(graph(saved(s)).edges.find(e=>e.owner===slide)!.type,R+'/slideLayout');},s=>{const additions=[...saved(s).keys()].filter(n=>!s.inputParts.has(n));changed(s.inputParts,saved(s),['[Content_Types].xml','ppt/presentation.xml','ppt/_rels/presentation.xml.rels','ppt/slides/slide1.xml'],additions);textMask(s,'ppt/slides/slide1.xml',0,0);}
]);
set('pptx-create-refusals',[
 async s=>{await emptySession(s);s.otherInput=await contract20Recipe('unsafe-title-layout');s.other=await ContractPresentation.open(s.otherInput);s.otherBefore=archive(s.otherInput);},async s=>{record(s);await writeFile(join(s.dir,'prior'),'prior');},s=>invoke(s,()=>p(s).addTextSlide('bad\u0000','Bad subtitle')),s=>refuse(s,'PPTX_ARGUMENT_INVALID'),s=>{assert(s.other instanceof ContractPresentation);try{s.other.addTextSlide('Unsafe next title','Unsafe next subtitle');}catch(e){if(e instanceof OoxmlError)s.secondError=e;else throw e;}},s=>{assert(s.secondError instanceof OoxmlError);assert.equal(s.secondError.code,'PPTX_LAYOUT_UNSAFE');},s=>{sameCurrent(s);sameMembers(s.otherBefore!,archive(s.other!.package.toBytes()));},async s=>{await sourceCustody(s);assert.equal(await readFile(join(s.dir,'prior'),'utf8'),'prior');sameCurrent(s);await saveFaults({...s,session:s.other!});}
]);
set('pptx-table-roundtrip-geometry',[
 async s=>{await emptySession(s);p(s).addTextSlide('Tables');},s=>p(s).addTable(0,2,3,operand(s,{x:120,y:240,width:1001,height:1003})),s=>{const frames=all(xml(partText(current(s),slideParts(current(s))[0]!)),'graphicFrame',P);assert.equal(frames.length,1);const id=Number(all(frames[0]!,'cNvPr',P)[0]!.attrs.id);p(s).setTableCellText(p(s).selectTableCell(0,id,0,0),'  <Alpha & Beta>  ');},save,
 s=>{const t=geometryTable(s);assert.equal(t.rows.length,2);assert(t.cells.every(r=>r.length===3));assert.deepEqual([t.x,t.y,t.width,t.height],[120,240,1001,1003]);},s=>{const t=geometryTable(s);assert.deepEqual(t.widths,[333,333,335]);assert.deepEqual(t.heights,[501,502]);},s=>{assert.deepEqual(tableMatrix(geometryTable(s)),[['  <Alpha & Beta>  ','',''],['','','']]);assert(s.reopened instanceof ContractPresentation);assert.equal(s.reopened.slides[0]!.tables[0]!.cell(0,0).text,'  <Alpha & Beta>  ');},s=>{assert.equal(placeholders(saved(s))[0]![0],'Tables');const t=geometryTable(s);assert.equal(t.frame.ns,P);assert.equal(t.tbl.ns,A);assert.deepEqual(t.tbl.children.map(n=>n.local),['tblPr','tblGrid','tr','tr']);for(const row of t.cells)for(const c of row){assert.deepEqual(c.children.map(n=>n.local),['txBody','tcPr']);const body=child(c,'txBody',A)!;assert.deepEqual(body.children.map(n=>n.local),['bodyPr','lstStyle','p']);}const ids=all(xml(partText(saved(s),slideParts(saved(s))[0]!)),'cNvPr',P).map(n=>n.attrs.id);assert.equal(new Set(ids).size,ids.length);},s=>creation(saved(s),policy,1),async s=>{operandCustody(s);await saveFaults(s);}
]);
function geometryTable(s:State){const part=slideParts(saved(s))[0]!,frames=all(xml(partText(saved(s),part)),'graphicFrame',P);assert.equal(frames.length,1);return table(saved(s),part,Number(all(frames[0]!,'cNvPr',P)[0]!.attrs.id));}
set('pptx-table-formatting',[
 s=>initialise(s,'styled-table','pptx'),s=>{s.cell=p(s).selectTableCell(0,4,0,0);assert.equal(tableMatrix(table(s.inputParts,'ppt/slides/slide1.xml',4))[0]![0],'Galvanic battery');},record,s=>p(s).setTableCellText(s.cell!,'updated value'),...common('pptx-table-formatting'),s=>{assert.equal(tableMatrix(table(saved(s),'ppt/slides/slide1.xml',4))[0]![0],'updated value');assert(s.reopened instanceof ContractPresentation);assert.equal(s.reopened.slides[0]!.tables[0]!.cell(0,0).text,'updated value');},s=>{const cell=table(saved(s),'ppt/slides/slide1.xml',4).cells[0]![0]!,body=child(cell,'txBody',A)!,para=child(body,'p',A)!;assert.deepEqual({...child(body,'bodyPr',A)!.attrs},{wrap:'square'});assert.deepEqual({...child(cell,'tcPr',A)!.attrs},{marL:'111'});assert.equal(all(cell,'srgbClr',A)[0]!.attrs.val,'FFFF00');assert.deepEqual({...child(para,'pPr',A)!.attrs},{algn:'r'});assert.deepEqual({...all(para,'rPr',A)[0]!.attrs},{b:'1',sz:'1800'});assert.deepEqual({...child(para,'endParaRPr',A)!.attrs},{lang:'en-US'});},s=>changedNodes(s,['ppt/slides/slide1.xml']),tableTextMask
]);
set('pptx-table-stale-handle',[
 s=>initialise(s,'stale-table','pptx'),s=>{s.cell=p(s).selectTableCell(0,4,0,0);assert.equal(tableMatrix(table(s.inputParts,'ppt/slides/slide1.xml',4))[0]![0],'');},s=>p(s).addTable(0,1,1,operand(s,{x:1200,y:100,width:900,height:600})),s=>{s.post=current(s);},s=>invoke(s,()=>p(s).setTableCellText(s.cell!,'stale write')),s=>refuse(s,'PPTX_STALE_TABLE_HANDLE'),async s=>{sameCurrent(s,s.post);await sourceCustody(s);},async s=>{await save(s);sameMembers(s.post!,saved(s));const frames=all(xml(partText(saved(s),'ppt/slides/slide1.xml')),'graphicFrame',P);assert.equal(frames.length,2);for(const f of frames)assert.equal(tableMatrix(table(saved(s),'ppt/slides/slide1.xml',Number(all(f,'cNvPr',P)[0]!.attrs.id)))[0]![0],'');},s=>{const target=p(s).selectTableCell(0,4,0,0);invoke(s,()=>p(s).setTableCellText(target,'\u0000'));refuse(s,'PPTX_ARGUMENT_INVALID');sameCurrent(s,s.post);p(s).setTableCellText(target,'fresh');assert.equal(p(s).slides[0]!.tables[0]!.cell(0,0).text,'fresh');}
]);
for(const[variant,recipe,code]of [['merged-cell','merged-table','PPTX_TABLE_MERGE_UNSUPPORTED'],['malformed-merge','malformed-table','PPTX_TABLE_STRUCTURE_UNSUPPORTED']])plans.set('@id-pptx-table-atomic-refusals|'+variant,[
 s=>initialise(s,recipe!,'pptx'),async s=>{record(s);await writeFile(join(s.dir,'prior'),'prior');},s=>{s.cell=p(s).selectTableCell(0,4,0,0);assert(s.cell);sameCurrent(s);},s=>invoke(s,()=>p(s).setTableCellText(s.cell!,'x')),s=>refuse(s,code!),s=>sameCurrent(s),async s=>{await save(s);sameMembers(s.inputParts,saved(s));},async s=>{await sourceCustody(s);assert.equal(await readFile(join(s.dir,'prior'),'utf8'),'prior');await saveFaults(s);},async s=>{const parts=new Map(s.inputParts),path='ppt/slides/slide1.xml',text=partText(parts,path);let next:string;if(variant==='merged-cell'){next=text.replace(' gridSpan="2"','');const blank='<a:tc><a:txBody><a:bodyPr/><a:lstStyle/><a:p></a:p></a:txBody><a:tcPr/></a:tc>';next=next.replace('</a:tc></a:tr>','</a:tc>'+blank+'</a:tr>');}else next=text.replace(' hMerge="maybe"','');assert.notEqual(next,text);parts.set(path,encoder.encode(next));const session=await ContractPresentation.open(writeZip(parts));session.setTableCellText(session.selectTableCell(0,4,0,0),'x');const output=archive(session.package.toBytes());assert.equal(tableMatrix(table(output,path,4))[0]![0],'x');changed(parts,output,[path]);}
]);
function planKey(c:any):string{if(c.scenarioId==='@id-xlsx-array-input-refusal')return c.scenarioId+'|'+(c.name.includes('dataTable')?'dataTable':'array');if(c.scenarioId==='@id-pptx-table-atomic-refusals')return c.scenarioId+'|'+(c.name.includes('malformed')?'malformed-merge':'merged-cell');return c.scenarioId;}
for(const c of cases){const actions=plans.get(planKey(c));assert(actions,'Missing scenario plan '+c.scenarioId);assert.equal(actions.length,c.steps.length,'Action/predicate count '+c.scenarioId+' '+c.name);}
export async function cleanup():Promise<void>{for(const s of states)await rm(s.dir,{recursive:true,force:true});states.clear();}
const texts=[...new Set<string>(cases.flatMap((c:any)=>c.steps.map((s:any)=>s.text)))];
export const bindings:StepBinding[]=texts.map(text=>({pattern:new RegExp('^'+text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$'),run:async context=>{
 const scenario=(context.scenario as {id:string}).id,name=(context.case as {name:string}).name,feature=context.feature as {path:string;sourceSha256:string},selected=cases.filter((c:any)=>c.scenarioId===scenario&&c.name===name);assert.equal(selected.length,1,'Exact Contract20 case selection');const c=selected[0];assert.equal(feature.path.replace(/^references\/fixtures-ooxml\//,''),c.feature);assert.equal(feature.sourceSha256,c.featureSha256);assert.equal(pin.featureSeals[c.feature as keyof typeof pin.featureSeals],c.featureSha256);
 const index=(context.step as {index:number;text:string}).index;assert.equal(c.steps[index].text,text);let state=context.contract20 as State|undefined;if(!state){assert.equal(index,0);state={dir:await mkdtemp(join(tmpdir(),'contract20-case-')),operands:[]} as unknown as State;context.contract20=state;states.add(state);}
 await plans.get(planKey(c))![index]!(state);
 operandCustody(state);
}}));
/** Route only exact selected candidate predicates; preserve every legacy binding. */
export function withContract20(previous:readonly StepBinding[]):StepBinding[]{
 const selected=(context:Record<string,unknown>)=>{const feature=context.feature as {path:string;sourceSha256:string},id=(context.scenario as {id:string}).id,path=feature.path.replace(/^references\/fixtures-ooxml\//,'');return pin.selectedScenarioIds.includes(id)&&pin.featureSeals[path as keyof typeof pin.featureSeals]===feature.sourceSha256;};
 const execute=(context:Record<string,unknown>)=>{const text=(context.step as {text:string}).text,matches=bindings.filter(b=>b.pattern.test(text));assert.equal(matches.length,1,'Exact Contract20 handler');return matches[0]!.run(context);};
 return [...previous.map(b=>({...b,run:(context:Record<string,unknown>,...captures:string[])=>selected(context)?execute(context):b.run(context,...captures)})),...bindings.filter((_,index)=>!previous.some(old=>old.pattern.test(texts[index]!)))];
}
