import assert from 'node:assert/strict';
import type {StepBinding} from '../../scripts/gherkin.ts';
import {fixturePath} from '../../scripts/fixture-inputs.ts';
import {OpcPackage} from '../../src/opc/index.ts';
import {Presentation} from '../../src/pptx/index.ts';
import {inspectSlideVisibility,type SlideVisibilityObservation} from '../../src/pptx/visibility.ts';
import {parseXml,attribute} from '../../src/xml/index.ts';
const P='http://schemas.openxmlformats.org/presentationml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const sourceId='fixture-e01ded1106a28f94a3439e8368f9a12ec360891f4a9e2810f6504c4c328ed79c',controlId='fixture-fa245a3df00fef7f7bf4739921ee840194040161e06490589e3d52cc9fa7a71d';
type Input={bytes:Uint8Array;before:Uint8Array;pkg:OpcPackage;members:Map<string,Uint8Array>;rows?:readonly SlideVisibilityObservation[];independent?:{id:string;rid:string;part:string;show:string|null;marker:string|null}[]};
type State={source?:Input;control?:Input};const state=(c:Record<string,unknown>)=>c.visibilityEvidence as State;
async function load(id:string):Promise<Input>{const bytes=await Bun.file(fixturePath(id)).bytes(),before=bytes.slice(),pkg=await OpcPackage.open(bytes);return{bytes,before,pkg,members:new Map(pkg.names().map(n=>[n,pkg.get(n)!]))};}
function independentlyInspect(input:Input){const main=input.pkg.mainPart(),root=parseXml(input.pkg.text(main)).root;assert.equal(root.namespaceURI,P);assert.equal(root.localName,'presentation');const lists=root.children.filter(n=>n.localName==='sldIdLst'&&n.namespaceURI===P);assert.equal(lists.length,1);const rels=input.pkg.relationships(main),rows=lists[0]!.children.map(e=>{assert.equal(e.localName,'sldId');assert.equal(e.namespaceURI,P);const id=attribute(e,'id')!,rid=attribute(e,'id',R)!,rel=rels.find(r=>r.id===rid);assert(rel&&!rel.external&&rel.type===R+'/slide'&&rel.resolved);const slide=parseXml(input.pkg.text(rel.resolved!)).root;assert.equal(slide.localName,'sld');assert.equal(slide.namespaceURI,P);return{id,rid,part:rel.resolved!,show:attribute(slide,'show')??null,marker:attribute(slide,'show',P)??null};});assert.equal(new Set(rows.map(r=>r.id)).size,rows.length);assert.equal(new Set(rows.map(r=>r.rid)).size,rows.length);assert.equal(new Set(rows.map(r=>r.part)).size,rows.length);return rows;}
export const bindings:StepBinding[]=[
 {pattern:/^the committed fixture (fixture-[0-9a-f]{64}) is loaded without editing$/,run:async(c,id)=>{assert.equal(id,sourceId);c.visibilityEvidence={source:await load(id!)};}},
 {pattern:/^the committed fixture (fixture-[0-9a-f]{64}) is loaded as a visible control$/,run:async(c,id)=>{assert.equal(id,controlId);state(c).control=await load(id!);}},
 {pattern:/^their four ordered slide identities and root visibility attributes are inspected$/,run:c=>{for(const input of [state(c).source!,state(c).control!]){input.independent=independentlyInspect(input);input.rows=inspectSlideVisibility(input.pkg);assert.equal(input.rows.length,4);assert.deepEqual(input.rows.map(r=>[r.slideId,r.relationshipId,r.part,r.show,r.namespacedShow]),input.independent.map(r=>[r.id,r.rid,r.part,r.show,r.marker]));}}},
 {pattern:/^the source fixture has exactly four slides with slide 3 marked namespaced p:show="0" and slides 1, 2 and 4 unmarked$/,run:c=>{const i=state(c).source!;assert.deepEqual(i.rows!.map(r=>r.namespacedShow),[null,null,'0',null]);assert.deepEqual(i.independent!.map(r=>r.marker),[null,null,'0',null]);assert.deepEqual(i.rows!.map(r=>r.slideId),['256','257','258','259']);}},
 {pattern:/^the source fixture's four slides lack an unqualified show attribute$/,run:c=>{const i=state(c).source!;assert.deepEqual(i.rows!.map(r=>r.show),[null,null,null,null]);assert.deepEqual(i.independent!.map(r=>r.show),[null,null,null,null]);}},
 {pattern:/^the visible control has exactly four slides without a hidden visibility attribute$/,run:c=>{const i=state(c).control!;assert.equal(i.rows!.length,4);assert(i.rows!.every(r=>r.show===null&&r.namespacedShow===null&&!r.declaredHidden));assert(i.independent!.every(r=>r.show===null&&r.marker===null));}},
 {pattern:/^no slide in either retained input is counted as an application-confirmed hidden slide$/,run:c=>{for(const i of[state(c).source!,state(c).control!])assert.equal(i.rows!.filter(r=>r.applicationConfirmedHidden).length,0);}},
 {pattern:/^both source archive bytes remain unchanged$/,run:c=>{for(const i of[state(c).source!,state(c).control!]){assert.deepEqual(i.bytes,i.before);assert.deepEqual(i.pkg.toBytes(),i.before);assert.deepEqual(i.pkg.names(),[...i.members.keys()].sort());for(const[n,b]of i.members)assert(Buffer.from(i.pkg.get(n)!).equals(Buffer.from(b)),n);}}},
 {pattern:/^the reported slide numbers refer to the same slide relationships as the inspected parts$/,run:async c=>{for(const[source,i]of [[true,state(c).source!],[false,state(c).control!]]as const){assert.deepEqual(i.rows!.map(r=>[r.ordinal,r.relationshipId,r.part]),[1,2,3,4].map((n,k)=>[n,'rId'+(source?7+k:2+k),'ppt/slides/slide'+n+'.xml']));const presentation=await Presentation.open(i.bytes);assert.deepEqual(presentation.slides.map(s=>s.partName),i.rows!.map(r=>r.part));assert.deepEqual(presentation.package.toBytes(),i.before);}}},
];
