import assert from 'node:assert/strict';
import type {StepBinding} from '../../scripts/gherkin.ts';
import {analyzeFormulaReferences,insertFormulaReferences,type FormulaReference,type FormulaInsertion,OoxmlError} from '../../src/index.ts';
type Matrix={source:string;refs:FormulaReference[];slices:FormulaReference[][];remapped:string;wrapped:FormulaReference[]};
type State={source?:string;context?:string;result?:string;error?:unknown;tokens?:string[];prefixes?:string[];operators?:string[];matrix?:Matrix[]};const state=(c:Record<string,unknown>)=>c.state as State;
export const scenarioIds=['@id-xlsx-go-static-remap-exact','@id-xlsx-go-static-remap-refusal','@id-xlsx-go-static-reference-properties'];
export const bindings:StepBinding[]=[
 {pattern:/^the formula source is JSON (.+) in context sheet Main$/,run:(c,json)=>{const s=state(c),source:unknown=JSON.parse(json!);assert.equal(typeof source,'string');s.source=source as string;s.context='Main';}},
 {pattern:/^the static remapper inserts (\w+) at (\d+) by (\d+) on sheet JSON (.+)$/,run:(c,axis,at,count,sheet)=>{const s=state(c);assert(s.source!==undefined&&s.context!==undefined);s.result=undefined;s.error=undefined;try{s.result=insertFormulaReferences(s.source,s.context,{axis:axis as FormulaInsertion['axis'],at:Number(at),count:Number(count),sheet:JSON.parse(sheet!)});}catch(error){s.error=error;}}},
 {pattern:/^the complete replacement expression equals JSON (.+)$/,run:(c,json)=>{const s=state(c);assert.equal(s.error,undefined);assert.equal(s.result,JSON.parse(json!));}},
 {pattern:/^it returns an error and an empty replacement expression$/,run:c=>{const s=state(c);assert(s.error instanceof OoxmlError);assert(['xlsx-formula-remap-unsupported','xlsx-formula-unsupported'].includes(s.error.code));assert.equal(s.result,undefined);}},
 {pattern:/^cell tokens A1, \$B2, C\$3 and \$XFD\$9$/,run:c=>{state(c).tokens=['A1','$B2','C$3','$XFD$9'];}},
 {pattern:/^optional prefixes empty, Main! and 'Input Data'! with operators \+, -, \*, \/, & and >=$/,run:c=>{const s=state(c);s.prefixes=['','Main!',"'Input Data'!"];s.operators=['+','-','*','/','&','>='];}},
 {pattern:/^the static analyser checks all 3 by 4 by 4 by 6 source expressions$/,run:c=>{const s=state(c);assert(s.prefixes&&s.tokens&&s.operators);s.matrix=[];for(const prefix of s.prefixes)for(const a of s.tokens)for(const b of s.tokens)for(const op of s.operators){const source=prefix+a+op+prefix+b,bytes=new TextEncoder().encode(source),refs=analyzeFormulaReferences(source);s.matrix.push({source,refs,slices:refs.map(r=>analyzeFormulaReferences(new TextDecoder().decode(bytes.slice(r.start,r.end)))),remapped:insertFormulaReferences(source,'Main',{axis:'row',at:100,count:1,sheet:'Main'}),wrapped:analyzeFormulaReferences('SUM('+source+')')});}}},
 {pattern:/^every expression has two references whose source slices each parse as one matching reference$/,run:c=>{const rows=state(c).matrix;assert(rows);assert.equal(rows.length,288);for(const row of rows){assert.equal(row.refs.length,2);assert.equal(row.slices.length,2);for(let i=0;i<2;i++){const ref=row.refs[i]!;assert.equal(row.slices[i]!.length,1);assert.deepEqual(row.slices[i]![0],{...ref,start:0,end:ref.end-ref.start});}}}},
 {pattern:/^inserting one row at 100 on Main leaves each original expression byte-identical$/,run:c=>{const rows=state(c).matrix;assert(rows);assert.equal(rows.length,288);for(const row of rows)assert.deepEqual(new TextEncoder().encode(row.remapped),new TextEncoder().encode(row.source));}},
 {pattern:/^wrapping each expression in SUM preserves its references after adjusting their byte spans$/,run:c=>{const rows=state(c).matrix;assert(rows);assert.equal(rows.length,288);for(const row of rows){assert.equal(row.wrapped.length,2);for(let i=0;i<2;i++){const ref=row.refs[i]!;assert.deepEqual(row.wrapped[i],{...ref,start:ref.start+4,end:ref.end+4});}}}},
];
