import assert from 'node:assert/strict';
import type {AcceptanceStep,StepBinding} from '../../scripts/gherkin.ts';
import {OpcPackage} from '../../src/opc/package.ts';
import {crc32,readZip,writeZip,type ZipLimits} from '../../src/opc/zip.ts';
import {addPart,removePart,addRelationship,removeRelationship} from '../../src/opc/graph.ts';
import {diffPackages} from '../../src/opc/diff.ts';
import {OoxmlError} from '../../src/errors.ts';
import {getContentType,setPartContentType} from '../../src/opc/content-types.ts';
import {setCellWrapText} from '../../src/xlsx/styles.ts';
import {buildZip} from '../fixtures/zip32.ts';
import {fixturePath} from '../../scripts/fixture-inputs.ts';
import {Presentation as PptxEditor} from '../../src/pptx/index.ts';
import {Workbook as XlsxEditor} from '../../src/xlsx/index.ts';
import {parseXml} from '../../src/xml/index.ts';
import {utf8} from '../fixtures/admission.ts';

type Sample={name:string;bytes:Uint8Array;reason:string};
type State={input?:Uint8Array;before?:Uint8Array;output?:Map<string,Uint8Array>;members?:Map<string,Uint8Array>;archive?:Uint8Array;repeat?:Uint8Array;samples?:Sample[];invalid?:Uint8Array;bounds?:ZipLimits[];fault?:unknown;pkg?:OpcPackage;saved?:Uint8Array;called?:boolean;failure?:Error;diff?:ReturnType<typeof diffPackages>;payload?:Uint8Array;kind?:string;sourceXml?:string;owner?:string;error?:unknown;result?:unknown;roundTrip?:PptxEditor|XlsxEditor};
const parseValue=(text:string)=>JSON.parse(text.replaceAll('\n','\\n').replaceAll('\r','\\r'));
const state=(c:Record<string,unknown>)=>c.state as State;
const hex=(s:string)=>{assert(/^(?:[0-9a-fA-F]{2})*$/.test(s));return Uint8Array.from(s.match(/../g)??[],v=>parseInt(v,16));};
function source(s:State,b:Uint8Array){s.input=b;s.before=b.slice();}
function custody(s:State){assert(s.input&&s.before);assert.deepEqual(s.input,s.before);}
function errorReason(e:unknown,reason:string){assert(e instanceof OoxmlError);assert.equal(e.code,reason);}
function readFailure(b:Uint8Array,limits?:ZipLimits){const before=b.slice();let output:unknown,error:unknown;try{output=readZip(b,limits);}catch(e){error=e;}assert.equal(output,undefined);assert(error);assert.deepEqual(b,before);return error;}
function table(c:Record<string,unknown>){const rows=(c.step as AcceptanceStep).argument?.dataTable;assert(rows&&rows.length>1);assert.deepEqual(rows[0],['member','method','payload_json']);return rows.slice(1).map(([name,method,payload])=>{assert(name&&payload&&(method==='STORED'||method==='DEFLATED'));const text=JSON.parse(payload);assert.equal(typeof text,'string');return {name,method:method==='STORED'?0:8,blob:utf8(text)};});}
const cn='http://schemas.openxmlformats.org/package/2006/content-types',rn='http://schemas.openxmlformats.org/package/2006/relationships';
function envelope(main:string,opaque:Uint8Array){return writeZip(new Map([
 ['[Content_Types].xml',utf8(`<Types xmlns="${cn}"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="bin" ContentType="application/octet-stream"/><Override PartName="/doc/main.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`)],
 ['_rels/.rels',utf8(`<Relationships xmlns="${rn}"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="doc/main.xml"/></Relationships>`)],['doc/main.xml',utf8(`<document>${main}</document>`)],['custom/data.bin',opaque],
]));}
async function openEnvelope(s:State){assert(s.input);s.pkg=await OpcPackage.open(s.input);}
function unrelated(s:State,changed:ReadonlySet<string>){assert(s.input&&s.saved);const a=readZip(s.input),b=readZip(s.saved);for(const [n,bytes] of a)if(!changed.has(n))assert.deepEqual(b.get(n),bytes,n);for(const n of b.keys())if(!changed.has(n))assert(a.has(n),n);custody(s);}
function methods(b:Uint8Array){const v=new DataView(b.buffer,b.byteOffset,b.byteLength),end=b.length-22,offset=v.getUint32(end+16,true),count=v.getUint16(end+10,true);let p=offset;const out=[];for(let i=0;i<count;i++){assert.equal(v.getUint32(p,true),0x02014b50);out.push({flags:v.getUint16(p+8,true),method:v.getUint16(p+10,true)});p+=46+v.getUint16(p+28,true)+v.getUint16(p+30,true)+v.getUint16(p+32,true);}assert.equal(p,end);return out;}
function unsafe():Sample[]{const a={name:'a.bin',blob:utf8('a'),method:0};return [
 {name:'duplicate',bytes:buildZip([a,a]),reason:'zip-duplicate-entry'},
 {name:'case-collision',bytes:buildZip([a,{...a,name:'A.bin'}]),reason:'zip-case-collision'},
 {name:'traversal',bytes:buildZip([{...a,name:'../a.bin'}]),reason:'zip-name-invalid'},
 {name:'encryption',bytes:buildZip([{...a,flags:0x0801}]),reason:'zip-encryption-unsupported'},
 {name:'method',bytes:buildZip([{...a,method:12}]),reason:'zip-method-unsupported'},
 {name:'multi-disk',bytes:buildZip([a],{diskNumber:1}),reason:'zip-multi-disk-unsupported'},
 {name:'missing-ZIP64',bytes:buildZip([a],{diskEntries:65535,totalEntries:65535}),reason:'zip-structure-invalid'},
 {name:'local-name',bytes:buildZip([{...a,localName:'b.bin'}]),reason:'zip-local-metadata-mismatch'},
 {name:'CRC',bytes:buildZip([{...a,crc:0xdeadbeef}]),reason:'zip-crc-mismatch'},
 {name:'stored-size',bytes:buildZip([{...a,fileSize:99,compressedSize:99}]),reason:'zip-size-mismatch'},
 {name:'trailing-byte',bytes:Uint8Array.from([...buildZip([a]),10]),reason:'zip-end-record-missing'},
];}
const entries:StepBinding[]=[];
function bind(text:string,run:StepBinding['run']){entries.push({pattern:new RegExp('^'+text.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$'),run});}
// Concrete sealed recipes augment the historical lane without replacing its bindings.
bind("a single-disk UTF-8 ZIP32 archive has these central-directory ordered members and no data descriptors",c=>{const s=state(c),rows=table(c);s.members=new Map(rows.filter(r=>!r.name.endsWith('/')).map(r=>[r.name,r.blob]));source(s,buildZip(rows,{archiveComment:utf8('kept as declared ZIP comment')}));});
bind("the production ZIP reader reads the archive with default limits",c=>{const s=state(c);assert(s.input);s.output=readZip(s.input);});
bind("the three returned payloads equal their declared strings with lengths 6, 4 and 6 and matching independent CRC32 values",c=>{const s=state(c);assert(s.output&&s.members);assert.equal(s.output.size,s.members.size);for(const [n,b]of s.members){assert.deepEqual(s.output.get(n),b);const independent=(input:Uint8Array)=>{let crc=0xffffffff;for(const value of input){crc^=value;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;};assert.equal(crc32(s.output.get(n)!),independent(b));}});
bind("returned file names are exactly [\"z.bin\",\"a.xml\",\"m.bin\"] in central-directory order and dir/ is absent",c=>{const s=state(c);assert(s.output);assert.deepEqual([...s.output.keys()],['z.bin','a.xml','m.bin']);assert(!s.output.has('dir/'));custody(s);});
bind("the caller's source archive bytes remain unchanged",c=>{const s=state(c);custody(s);assert(new TextDecoder().decode(s.input).endsWith('kept as declared ZIP comment'));});
bind("the eleven strict ZIP32 unsafe-structure recipes duplicate, case-collision, traversal, encryption, method, multi-disk, missing-ZIP64, local-name, CRC, stored-size and trailing-byte",c=>{state(c).samples=unsafe();});
bind("the production ZIP reader checks every recipe with default limits",c=>{const s=state(c);assert(s.samples);for(const sample of s.samples){const e=readFailure(sample.bytes);errorReason(e,sample.reason);}});
bind("each recipe refuses with its exact documented zip reason and no member result",c=>{assert.equal(state(c).samples?.length,11);});
bind("a raw-DEFLATE ZIP32 budget archive contains a.bin with 4096 A bytes followed by b.bin with two b bytes",c=>{const s=state(c);source(s,buildZip([{name:'a.bin',method:8,blob:utf8('A'.repeat(4096))},{name:'b.bin',method:8,blob:utf8('bb')}]));assert.deepEqual([...readZip(s.input!).keys()],['a.bin','b.bin']);});
bind("a sibling archive retains that declared geometry but replaces the compressed a.bin body with eight FF bytes",c=>{state(c).invalid=buildZip([{name:'a.bin',method:8,blob:utf8('A'.repeat(4096)),data:new Uint8Array(8).fill(255)},{name:'b.bin',method:8,blob:utf8('bb')}]);});
bind("each archive is read separately with one limit maxArchiveBytes length-minus-one, maxEntries 1, maxEntryBytes 8, maxTotalBytes 8 or maxCompressionRatio 2",c=>{const s=state(c);assert(s.input&&s.invalid);s.bounds=[{maxArchiveBytes:s.input.length-1},{maxEntries:1},{maxEntryBytes:8},{maxTotalBytes:8},{maxCompressionRatio:2}];const reasons=['zip-archive-too-large','zip-too-many-entries','zip-entry-too-large','zip-total-too-large','zip-compression-ratio-exceeded'];for(const [i,limits]of s.bounds.entries())for(const b of [s.input,s.invalid])errorReason(readFailure(b,i===0?{maxArchiveBytes:b.length-1}:limits),reasons[i]!);s.fault=readFailure(s.invalid);});
bind("both archives refuse the same respective reasons zip-archive-too-large, zip-too-many-entries, zip-entry-too-large, zip-total-too-large and zip-compression-ratio-exceeded before member output",c=>{const s=state(c);assert.equal(s.bounds?.length,5);custody(s);});
bind("default reading of the valid archive returns the two exact payloads and default reading of the invalid-DEFLATE sibling refuses a payload error",c=>{const s=state(c);assert(s.fault instanceof OoxmlError);assert.equal(s.fault.code,'zip-data-invalid');assert(s.input);const payloads=readZip(s.input);assert.deepEqual([...payloads.keys()],['a.bin','b.bin']);assert.deepEqual(payloads.get('a.bin'),utf8('A'.repeat(4096)));assert.deepEqual(payloads.get('b.bin'),utf8('bb'));custody(s);});
bind("the production ZIP writer writes the same members twice using its deterministic ZIP32 profile",c=>{const s=state(c);assert(s.members);s.archive=writeZip(s.members);s.repeat=writeZip(s.members);});
bind("both outputs are byte-identical ZIP32 archives and reopen with the three exact member names and payloads",c=>{const s=state(c);assert(s.members&&s.archive&&s.repeat);assert.deepEqual(s.archive,s.repeat);for(const bytes of [s.archive,s.repeat]){const reopened=readZip(bytes);assert.equal(reopened.size,s.members.size);for(const[n,b]of s.members)assert.deepEqual(reopened.get(n),b);}});
bind("every file uses STORED or DEFLATED encoding and this input emits at least one of each method",c=>{const s=state(c);assert(s.archive);const headers=methods(s.archive);assert.equal(headers.length,3);assert(headers.every(h=>h.flags===0x800&&(h.method===0||h.method===8)));assert.deepEqual(new Set(headers.map(h=>h.method)),new Set([0,8]));});
bind('the custody envelope contains main XML part doc/main.xml with decoded text Original and opaque custom/data.bin payload hexadecimal 00FF01FE02FD',async c=>{const s=state(c);source(s,envelope('Original',hex('00FF01FE02FD')));await openEnvelope(s);});
const graphFixture='fixture-535910216e3531e4f70959cccf83038f1c51febbf4a149f9f46abfbfa8667d90';
bind('its declared archive comment is JSON "kept as declared ZIP comment" and all CRC32 and sizes agree with the exact UTF-8 payloads',c=>{const s=state(c);assert(s.input&&s.members);const v=new DataView(s.input.buffer,s.input.byteOffset,s.input.byteLength);let p=0;for(const [name,bytes] of [['z.bin',utf8('z-last')],['dir/',utf8('')],['a.xml',utf8('<a/>')],['m.bin',utf8('middle')]] as const){assert.equal(v.getUint32(p,true),0x04034b50);assert.equal(v.getUint16(p+6,true),0x800);assert.equal(v.getUint32(p+14,true),crc32(bytes));assert.equal(v.getUint32(p+22,true),bytes.length);assert.equal(new TextDecoder().decode(s.input.slice(p+30,p+30+v.getUint16(p+26,true))),name);p+=30+v.getUint16(p+26,true)+v.getUint16(p+28,true)+v.getUint32(p+18,true);}});
for(const [text,names,reasons] of [
 ['duplicate and case-collision refuse as zip-duplicate-entry and zip-case-collision',['duplicate','case-collision'],['zip-duplicate-entry','zip-case-collision']],
 ['traversal refuses as zip-name-invalid',['traversal'],['zip-name-invalid']],
 ['encryption and method refuse as zip-encryption-unsupported and zip-method-unsupported',['encryption','method'],['zip-encryption-unsupported','zip-method-unsupported']],
 ['multi-disk and missing-ZIP64 refuse as zip-multi-disk-unsupported and zip-structure-invalid',['multi-disk','missing-ZIP64'],['zip-multi-disk-unsupported','zip-structure-invalid']],
 ['local-name refuses as zip-local-metadata-mismatch',['local-name'],['zip-local-metadata-mismatch']],
 ['CRC, stored-size and trailing-byte refuse as zip-crc-mismatch, zip-size-mismatch and zip-end-record-missing with every caller archive unchanged',['CRC','stored-size','trailing-byte'],['zip-crc-mismatch','zip-size-mismatch','zip-end-record-missing']],
] as const)bind(text,c=>{const samples=state(c).samples;assert(samples);for(const [i,name]of names.entries()){const sample:Sample|undefined=samples.find(s=>s.name===name);assert(sample);errorReason(readFailure(sample.bytes),reasons[i]!);}});
bind('every caller archive remains unchanged',c=>{const s=state(c);custody(s);assert(s.invalid);readFailure(s.invalid);});
bind('ordered ZIP writer members are [Content_Types].xml with UTF-8 JSON "<Types/>", custom/data.bin with bytes 00 through FF and word/document.xml with UTF-8 <w:document> followed by 2048 A characters and </w:document>',c=>{state(c).members=new Map([['[Content_Types].xml',utf8('<Types/>')],['custom/data.bin',Uint8Array.from({length:256},(_,i)=>i)],['word/document.xml',utf8('<w:document>'+'A'.repeat(2048)+'</w:document>')]]);});
bind('every local and central member name uses the UTF-8 ZIP flag',c=>{const s=state(c);assert(s.archive);assert(methods(s.archive).every(h=>h.flags===0x800));const v=new DataView(s.archive.buffer,s.archive.byteOffset,s.archive.byteLength);let p=0;for(let i=0;i<3;i++){assert.equal(v.getUint32(p,true),0x04034b50);assert.equal(v.getUint16(p+6,true),0x800);p+=30+v.getUint16(p+26,true)+v.getUint16(p+28,true)+v.getUint32(p+18,true);}});
bind('an independent writer input word/document.xml=one and WORD/document.xml=two refuses as zip-case-collision with no archive and unchanged caller members',c=>{const input=new Map([['word/document.xml',utf8('one')],['WORD/document.xml',utf8('two')]]),before=new Map([...input].map(([n,b])=>[n,b.slice()]));let output:unknown,error:unknown;try{output=writeZip(input);}catch(e){error=e;}errorReason(error,'zip-case-collision');assert.equal(output,undefined);assert.deepEqual(input,before);});
bind('an immediate production transaction sets main XML text to rolled back, sets custom/data.bin to hexadecimal 09080706 and then raises callback-failure after both writes',c=>{const s=state(c);assert(s.pkg);s.failure=Error('callback-failure');try{s.result=s.pkg.transactionWithMode('immediate',()=>{s.pkg!.set('doc/main.xml','<document>rolled back</document>');s.pkg!.set('custom/data.bin',hex('09080706'));assert.equal(s.pkg!.text('doc/main.xml'),'<document>rolled back</document>');assert.deepEqual(s.pkg!.get('custom/data.bin'),hex('09080706'));s.called=true;throw s.failure;});}catch(e){s.error=e;}});
bind('callback-failure propagates with no transaction result and the whole current archive equals its original bytes',c=>{const s=state(c);assert(s.called&&s.pkg&&s.input);assert.equal(s.error,s.failure);assert.equal(s.result,undefined);assert.deepEqual(s.pkg.toBytes(),s.input);custody(s);});
bind('doc/main.xml still decodes to Original, custom/data.bin is exactly 00FF01FE02FD and every original member remains present',async c=>{const s=state(c);assert(s.pkg&&s.input);const p=await OpcPackage.open(s.pkg.toBytes());assert.equal(p.text('doc/main.xml'),'<document>Original</document>');assert.deepEqual(p.get('custom/data.bin'),hex('00FF01FE02FD'));assert.deepEqual(p.names(),[...readZip(s.input).keys()]);});
bind('a production text edit sets doc/main.xml value text to JSON "Updated <value>" and saves then reopens the package',async c=>{const s=state(c);assert(s.pkg);const source=s.pkg.text('doc/main.xml');assert.equal(source,'<document>Original</document>');s.pkg.set('doc/main.xml',source.replace('Original','Updated &lt;value&gt;'));s.saved=s.pkg.toBytes();s.pkg=await OpcPackage.open(s.saved);});
bind('doc/main.xml decodes to JSON "Updated <value>" and custom/data.bin is exactly 00FF01FE02FD',c=>{const s=state(c);assert(s.pkg);assert.equal(parseXml(s.pkg.text('doc/main.xml')).root.text,'Updated <value>');assert.deepEqual(s.pkg.get('custom/data.bin'),hex('00FF01FE02FD'));});
bind("the member-name set is unchanged, every other member payload is unchanged and the caller's original archive bytes remain unchanged",c=>{const s=state(c);assert(s.saved&&s.input);assert.deepEqual(new Set(readZip(s.saved).keys()),new Set(readZip(s.input).keys()));unrelated(s,new Set(['doc/main.xml']));});
bind(`graph fixture ${graphFixture} is opened through the production package editor`,async c=>{const s=state(c);source(s,new Uint8Array(await Bun.file(fixturePath(graphFixture)).arrayBuffer()));s.pkg=await OpcPackage.open(s.input!);});
bind('custom/data.bin with hexadecimal payload 070809 and type application/octet-stream is added with internal root relationship rIdData of type urn:test/data',c=>{const s=state(c);assert(s.pkg);s.pkg.transactionWithMode('immediate',()=>{addPart(s.pkg!,'custom/data.bin',hex('070809'),'application/octet-stream');addRelationship(s.pkg!,'','urn:test/data','custom/data.bin',{id:'rIdData'});});s.saved=s.pkg.toBytes();});
bind('saving and reopening returns custom/data.bin with exact payload 070809, effective type application/octet-stream and root edge rIdData resolving to custom/data.bin',async c=>{const s=state(c);assert(s.saved);const p=await OpcPackage.open(s.saved);assert.deepEqual(p.get('custom/data.bin'),hex('070809'));assert.equal(getContentType(p,'custom/data.bin'),'application/octet-stream');const r=p.relationships('').find(r=>r.id==='rIdData');assert(r);assert.equal(r.type,'urn:test/data');assert.equal(r.resolved,'custom/data.bin');});
bind('every original member except [Content_Types].xml and _rels/.rels retains its exact payload and no other member is added or removed',c=>{const s=state(c);assert(s.saved&&s.input);assert.deepEqual(new Set(readZip(s.saved).keys()),new Set([...readZip(s.input).keys(),'custom/data.bin']));unrelated(s,new Set(['[Content_Types].xml','_rels/.rels','custom/data.bin']));});
bind(`graph fixture ${graphFixture} has custom/data.bin payload 070809 with type application/octet-stream and internal root edge rIdData of type urn:test/data`,async c=>{const s=state(c),p=await OpcPackage.open(fixturePath(graphFixture));p.transactionWithMode('immediate',()=>{addPart(p,'custom/data.bin',hex('070809'),'application/octet-stream');addRelationship(p,'','urn:test/data','custom/data.bin',{id:'rIdData'});});source(s,p.toBytes());s.pkg=await OpcPackage.open(s.input!);});
bind('removal of custom/data.bin is attempted without detaching rIdData',c=>{const s=state(c);assert(s.pkg);try{s.result=removePart(s.pkg,'custom/data.bin');}catch(e){s.error=e;}});
bind('graph editing refuses with code "opc-part-referenced" and no successful edit result',c=>{const s=state(c);errorReason(s.error,'opc-part-referenced');assert.equal(s.result,undefined);});
bind('the whole current archive and every current part remain exactly unchanged after the refusal',async c=>{const s=state(c);assert(s.pkg&&s.input);assert.deepEqual(s.pkg.toBytes(),s.input);const p=await OpcPackage.open(s.pkg.toBytes());assert.deepEqual(p.names(),s.pkg.names());for(const n of p.names())assert.deepEqual(p.get(n),readZip(s.input).get(n));custody(s);});
bind('root relationship rIdData is explicitly detached and custom/data.bin is removed',c=>{const s=state(c);assert(s.pkg);s.pkg.transactionWithMode('immediate',()=>{removeRelationship(s.pkg!,'','rIdData');removePart(s.pkg!,'custom/data.bin');});s.saved=s.pkg.toBytes();});
bind('saving and reopening has no custom/data.bin, no /custom/data.bin content-type override and no rIdData root edge',async c=>{const s=state(c);assert(s.saved);const p=await OpcPackage.open(s.saved);assert.equal(p.get('custom/data.bin'),undefined);assert(!p.text('[Content_Types].xml').includes('/custom/data.bin'));assert(!p.relationships('').some(r=>r.id==='rIdData'));});
bind('every retained internal relationship target resolves and every original non-registry member retains its exact payload',async c=>{const s=state(c);assert(s.saved&&s.input);const p=await OpcPackage.open(s.saved);assert.deepEqual(new Set(p.names()),new Set([...readZip(s.input).keys()].filter(n=>n!=='custom/data.bin')));for(const owner of ['',...p.names().filter(n=>!n.endsWith('.rels')&&n!=='[Content_Types].xml')])for(const r of p.relationships(owner))if(!r.external)assert(r.resolved&&p.get(r.resolved));unrelated(s,new Set(['custom/data.bin','[Content_Types].xml','_rels/.rels']));});
bind(`graph fixture ${graphFixture} is opened twice as independent package snapshots`,async c=>{const s=state(c);source(s,new Uint8Array(await Bun.file(fixturePath(graphFixture)).arrayBuffer()));s.pkg=await OpcPackage.open(s.input!);s.payload=s.pkg.get('word/document.xml');assert(s.payload);});
bind('only the effective content type of word/document.xml in the second snapshot is set to application/vnd.test.document+xml',async c=>{const s=state(c);assert(s.input);const second=await OpcPackage.open(s.input);setPartContentType(second,'word/document.xml','application/vnd.test.document+xml');s.saved=second.toBytes();});
bind('the production payload-and-content-type diff reports changed members ["[Content_Types].xml","word/document.xml"] and no added or removed members',async c=>{const s=state(c);assert(s.pkg&&s.saved);s.diff=diffPackages(s.pkg,await OpcPackage.open(s.saved));assert.deepEqual(s.diff.changed,['[Content_Types].xml','word/document.xml']);assert.deepEqual(s.diff.added,[]);assert.deepEqual(s.diff.removed,[]);});
bind('word/document.xml retains identical payload bytes and its original MIME changes to application/vnd.test.document+xml',async c=>{const s=state(c);assert(s.pkg&&s.saved&&s.payload);const second=await OpcPackage.open(s.saved);assert.deepEqual(second.get('word/document.xml'),s.payload);assert.equal(getContentType(second,'word/document.xml'),'application/vnd.test.document+xml');assert.notEqual(getContentType(s.pkg,'word/document.xml'),getContentType(second,'word/document.xml'));});
bind('all unrelated payloads, the first snapshot and caller input bytes remain unchanged',c=>{const s=state(c);assert(s.pkg&&s.input);assert.deepEqual(s.pkg.toBytes(),s.input);unrelated(s,new Set(['[Content_Types].xml']));});
entries.push({pattern:/^Office relationship fixture (fixture-[a-f0-9]{64}) for (pptx|xlsx) has (its main-part officeDocument relationship prefix renamed from r to link without changing the namespace URI|only the main-part r namespace URI changed from officeDocument relationships to package relationships)$/,run:async(c,id,kind,mutation)=>{assert(id&&kind);const s=state(c),p=await OpcPackage.open(fixturePath(id));s.owner=p.mainPart();s.kind=kind;const original=p.text(s.owner);assert(original.includes('r:id'));s.sourceXml=mutation!.startsWith('its ')?original.replaceAll('xmlns:r=','xmlns:link=').replaceAll('r:id=','link:id='):original.replaceAll('http://schemas.openxmlformats.org/officeDocument/2006/relationships',rn);assert.notEqual(s.sourceXml,original);p.set(s.owner,s.sourceXml);source(s,p.toBytes());}});
entries.push({pattern:/^the production (pptx|xlsx) editor sets (first slide first text|Sheet!A1 with wrap text) to JSON ([\s\S]+) and saves then reopens$/,run:async(c,kind,target,json)=>{const s=state(c);assert(s.input&&kind===s.kind);const value=parseValue(json!);if(kind==='pptx'){assert.equal(target,'first slide first text');const p=await PptxEditor.open(s.input),slide=p.slides[0]!;const t=slide.inspectText('')[0]!;slide.replaceTextAt(t.anchor,t.text,value);s.saved=p.package.toBytes();s.roundTrip=await PptxEditor.open(s.saved);}else{assert.equal(target,'Sheet!A1 with wrap text');const w=await XlsxEditor.open(s.input);w.worksheet('Sheet').setCellValue('A1',value);setCellWrapText(w,'Sheet','A1',true);s.saved=w.package.toBytes();s.roundTrip=await XlsxEditor.open(s.saved);}}});
entries.push({pattern:/^the exact value JSON ([\s\S]+) is read at (first slide first text|Sheet!A1 with wrap text) and every internal relationship target resolves$/,run:async(c,json,target)=>{const s=state(c);assert(s.roundTrip&&s.saved);const expected=parseValue(json!);if(s.kind==='pptx'){assert.equal(target,'first slide first text');assert.equal((s.roundTrip as PptxEditor).slides[0]!.inspectText('')[0]!.text,expected);}else{assert.equal(target,'Sheet!A1 with wrap text');const w=s.roundTrip as XlsxEditor;assert.equal(w.worksheet('Sheet').getCell('A1')?.value,expected);const sheet=w.package.related(w.package.mainPart(),'worksheet');assert(sheet);const doc=parseXml(w.package.text(sheet));const cell=doc.elements.find(e=>e.localName==='c'&&e.attributes.r==='A1');assert(cell);const style=Number(cell.attributes.s??0),styles=w.package.related(w.package.mainPart(),'styles');assert(styles);const model=parseXml(w.package.text(styles));const xfs=model.elements.find(e=>e.localName==='cellXfs');assert(xfs?.children[style]);assert(xfs.children[style]!.children.some(e=>e.localName==='alignment'&&['1','true'].includes(e.attributes.wrapText??'')));}const p=await OpcPackage.open(s.saved);for(const owner of ['',...p.names().filter(n=>!n.endsWith('.rels')&&n!=='[Content_Types].xml')])for(const r of p.relationships(owner))if(!r.external)assert(r.resolved&&p.get(r.resolved));}});
bind("the saved main part retains link:id attributes without r:id attributes and the caller's archive bytes remain unchanged",async c=>{const s=state(c);assert(s.saved&&s.owner&&s.sourceXml);const xml=(await OpcPackage.open(s.saved)).text(s.owner),values=[...s.sourceXml.matchAll(/\blink:id="([^"]*)"/g)].map(m=>m[1]);assert(values.length);assert.deepEqual([...xml.matchAll(/\blink:id="([^"]*)"/g)].map(m=>m[1]),values);assert(!/\br:id=/.test(xml));custody(s);});
entries.push({pattern:/^the production (pptx|xlsx) reader attempts to open the namespace-mismatched document$/,run:async(c,kind)=>{const s=state(c);assert(s.input&&kind===s.kind);try{s.result=kind==='pptx'?await PptxEditor.open(s.input):await XlsxEditor.open(s.input);}catch(e){s.error=e;}}});
entries.push({pattern:/^the reader refuses with structured reason (PPTX_PRESENTATION_INVALID|xlsx-workbook-invalid) and no document result$/,run:(c,reason)=>{const s=state(c);errorReason(s.error,reason!);assert.equal(s.result,undefined);custody(s);}});

export const bindings=entries;
export function withPackageAlignment(base:StepBinding[]):StepBinding[]{return [...base,...entries];}
