import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import type {StepBinding} from '../../scripts/gherkin.ts';
import {fixturePath,fixturesRoot} from '../../scripts/fixture-inputs.ts';
import {Presentation} from '../../src/pptx/index.ts';import {OpcPackage} from '../../src/opc/index.ts';
import {parseXml,elements,attribute,type XmlElement} from '../../src/xml/index.ts';
import {OoxmlError} from '../../src/errors.ts';
import {omitOpeningAttributes} from '../helpers/xml-formatting-custody.ts';
import {assertChangedMembers as retainedChangedMembers} from './retained-style-word.ts';
import {assertChangedMembers as retainedTableChangedMembers} from './retained-table.ts';
const P='http://schemas.openxmlformats.org/presentationml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const folders=new Set<string>();export async function cleanup(){for(const f of folders)await rm(f,{recursive:true,force:true});folders.clear();}
type State={record:any;deck:Presentation;saved?:Presentation;pkg?:OpcPackage;input:Uint8Array;before:Uint8Array;members:Map<string,Uint8Array>;handles:Presentation['slides'];error?:unknown;output?:Uint8Array};const state=(c:Record<string,unknown>)=>c.state as State;
const cs=(e:XmlElement,n:string,ns=A)=>e.children.filter(c=>c.localName===n&&c.namespaceURI===ns),one=(e:XmlElement,n:string,ns=A)=>{const c=cs(e,n,ns);assert.equal(c.length,1,n);return c[0]!;};
function target(xml:string,r:any){const d=parseXml(xml);if(r.family==='slide-visibility')return d.root;const sp=elements(d,'sp',P).find(sp=>elements(sp,'cNvPr',P)[0]?.attributes.id==='4')!;assert(sp);if(r.family==='shape-geometry')return one(one(sp,'spPr',P),'xfrm');const p=cs(one(sp,'txBody',P),'p')[0]!;if(r.family==='paragraph-formatting')return one(p,'pPr');const run=cs(p,'r')[r.kind==='run-bold'?1:0]!;return cs(run,'rPr')[0];}
function protectedXml(xml:string,r:any){const t=target(xml,r);if(r.family==='slide-visibility')return xml.slice(t!.openEnd);if(!t){const d=parseXml(xml),sp=elements(d,'sp',P).find(sp=>elements(sp,'cNvPr',P)[0]?.attributes.id==='4')!,run=cs(cs(one(sp,'txBody',P),'p')[0]!,'r')[1]!;return xml.slice(0,run.openEnd)+'#property#'+xml.slice(run.openEnd);}return xml.slice(0,t.start)+'#property#'+xml.slice(t.end);}
function unpatchedProperty(xml:string,r:any){const node=target(xml,r);if(!node)return '';let raw=xml.slice(node.start,r.family==='slide-visibility'?node.openEnd:node.end);const attrs:Record<string,string[]>={'hide':['show'],'unhide':['show'],'visibility-order':['show'],'move':['x','y'],'resize':['cx','cy'],'transform':['rot','flipH','flipV'],'run-bold':['b'],'run-unbold':['b'],'run-italic':['i'],'run-underline':['u'],'run-size':['sz'],'run-inherit':['b','i','u','sz'],'paragraph-align':['algn'],'paragraph-indent':['marL','indent']};raw=omitOpeningAttributes(raw,new Set(attrs[r.kind]??[]));const children:Record<string,string[]>={'run-font':['latin'],'run-color':['solidFill'],'run-inherit':['solidFill','latin'],'paragraph-spacing':['spcBef','spcAft'],'paragraph-line':['lnSpc']};for(const name of children[r.kind]??[])for(const child of cs(node,name).sort((a,b)=>b.start-a.start))raw=raw.replace(xml.slice(child.start,child.end),'');return raw;}
function graph(p:OpcPackage){const main=p.mainPart(),rels=p.relationships(main);return elements(parseXml(p.text(main)),'sldId',P).map(e=>{const rid=attribute(e,'id',R),edge=rels.find(r=>r.id===rid)!;return {id:e.attributes.id,rid,part:edge.resolved,target:edge.target,links:p.relationships(edge.resolved!)};});}
export async function perform(d:Presentation,kind:string){const s=d.slides[1]!;switch(kind){case'hide':return s.setHidden(true);case'unhide':s.setHidden(true);return s.setHidden(false);case'visibility-order':s.setHidden(true);return d.reorderSlides([2,0,1]);case'visibility-refusal':return s.setHidden('hidden' as unknown as boolean);case'move':return s.patchShapeGeometry(4,{x:914400,y:1828800});case'resize':return s.patchShapeGeometry(4,{width:3657600,height:1828800});case'transform':return s.patchShapeGeometry(4,{rotation:5400000,flipH:true,flipV:false});case'geometry-refusal':return s.patchShapeGeometry(4,{x:914400,width:-1});case'run-bold':return s.patchTextRun(4,0,1,{bold:true});case'run-unbold':return s.patchTextRun(4,0,0,{bold:false});case'run-italic':return s.patchTextRun(4,0,0,{italic:true});case'run-underline':return s.patchTextRun(4,0,0,{underline:'none'});case'run-size':return s.patchTextRun(4,0,0,{size:2400});case'run-font':return s.patchTextRun(4,0,0,{typeface:'Aptos Display'});case'run-color':return s.patchTextRun(4,0,0,{color:'A1B2C3'});case'run-inherit':return s.patchTextRun(4,0,0,{bold:null,italic:null,underline:null,size:null,typeface:null,color:null});case'paragraph-align':return s.patchParagraph(4,0,{alignment:'ctr'});case'paragraph-indent':return s.patchParagraph(4,0,{leftMargin:457200,indent:-228600});case'paragraph-spacing':return s.patchParagraph(4,0,{spaceBefore:1200,spaceAfter:600});case'paragraph-line':return s.patchParagraph(4,0,{linePercent:150000});default:throw Error('Unbound formatting '+kind);}}
const entries:StepBinding[]=[];
entries.push({pattern:/^retained formatting fixture (fixture-[a-f0-9]+) has ordered slides \["Alpha","Beta","Gamma"\]$/,run:async(c,id)=>{const ledger=await Bun.file(join(fixturesRoot(),'ledgers/pptx-formatting.json')).json(),record=ledger.records.find((r:any)=>r.id===(c.scenario as {id:string}).id);assert(record);assert.equal(id,record.fixtureId);const input=await Bun.file(fixturePath(id!)).bytes(),deck=await Presentation.open(input);Object.assign(state(c),{record,deck,input,before:input.slice(),members:new Map(deck.package.names().map(n=>[n,deck.package.get(n)!])),handles:[...deck.slides]});}});
entries.push({pattern:/^formatting target (.+) has the exact original direct properties and lexical snapshot$/,run:(c,t)=>{const s=state(c);assert.equal(t,s.record.target);assert(s.members.size===20);assert.deepEqual(graph(s.deck.package).map(r=>r.part),['ppt/slides/slide1.xml','ppt/slides/slide2.xml','ppt/slides/slide3.xml']);}});
entries.push({pattern:/^production PPTX formatting APIs (.+)$/,run:async(c,op)=>{const s=state(c);assert.equal(op,s.record.operation);if(s.record.expected.refusal){try{await perform(s.deck,s.record.kind);}catch(e){s.error=e;}assert(s.error instanceof OoxmlError);}else await perform(s.deck,s.record.kind);}});
entries.push({pattern:/^the result or unchanged refusal session is saved to a new path and independently parsed and reopened$/,run:async c=>{const s=state(c),folder=await mkdtemp(join(tmpdir(),'pptx-formatting-'));folders.add(folder);const path=join(folder,'saved.pptx');await s.deck.save(path);s.output=await Bun.file(path).bytes();s.pkg=await OpcPackage.open(path);s.saved=await Presentation.open(path);for(const n of s.pkg.names())if(n.endsWith('.xml')||n.endsWith('.rels'))parseXml(s.pkg.text(n));}});
entries.push({pattern:/^formatting target (.+) has exact saved properties JSON (.+)$/,run:(c,t,j)=>{const s=state(c),r=s.record,e=JSON.parse(j!);assert.equal(t,r.target);assert.deepEqual(e,r.expected);if(e.refusal)return;const xml=s.pkg!.text('ppt/slides/slide2.xml'),node=target(xml,r)!;if(r.family==='slide-visibility'){assert.equal(s.saved!.slides.find(slide=>slide.partName==='ppt/slides/slide2.xml')!.hidden,true===e.hidden||r.kind==='visibility-order');if(e.show)assert.equal(node.attributes.show,e.show);if(r.kind==='visibility-order'){assert.deepEqual(graph(s.pkg!).map(row=>row.part),['ppt/slides/slide3.xml','ppt/slides/slide1.xml','ppt/slides/slide2.xml']);assert.deepEqual(s.saved!.slides.flatMap((slide,index)=>slide.hidden?[index+1]:[]),e.hiddenOrdinals);}}else if(r.family==='shape-geometry'){const off=one(node,'off'),ext=one(node,'ext');assert.deepEqual([Number(off.attributes.x),Number(off.attributes.y),Number(ext.attributes.cx),Number(ext.attributes.cy)],[e.x,e.y,e.width,e.height]);if(e.rotation!==undefined){assert.equal(Number(node.attributes.rot),e.rotation);assert.equal(node.attributes.flipH,'1');assert.equal(node.attributes.flipV,'0');}}else if(r.family==='text-formatting'){for(const[k,v]of Object.entries(e)){if(['b','i','u','sz'].includes(k))assert.equal(node.attributes[k],v);else if(k==='typeface')assert.equal(one(node,'latin').attributes.typeface,v);else if(k==='color')assert.equal(one(one(node,'solidFill'),'srgbClr').attributes.val,v);else if(k==='absent')for(const n of v as string[])assert(n==='latin'||n==='solidFill'?cs(node,n).length===0:node.attributes[n]===undefined);else if(k==='retainedLanguage')assert.equal(node.attributes.lang,v);}}else{for(const[k,v]of Object.entries(e)){if(['algn','marL','indent'].includes(k))assert.equal(node.attributes[k],v);else if(k==='before')assert.equal(Number(one(one(node,'spcBef'),'spcPts').attributes.val),v);else if(k==='after')assert.equal(Number(one(one(node,'spcAft'),'spcPts').attributes.val),v);else if(k==='linePercent')assert.equal(Number(one(one(node,'lnSpc'),'spcPct').attributes.val),v);}}}});
entries.push({pattern:/^the exact changed original member set is (.+) with no additions or removals$/,run:(c,j)=>{if(c.retainedTable)return retainedTableChangedMembers(c,j!);if(c.retainedState)return retainedChangedMembers(c,j!);const s=state(c),changed=[...s.members].filter(([n,b])=>!Buffer.from(b).equals(Buffer.from(s.pkg!.get(n)!))).map(([n])=>n).sort();assert.deepEqual(changed,JSON.parse(j!).sort());assert.deepEqual(s.pkg!.names().sort(),[...s.members.keys()].sort());}});
entries.push({pattern:/^every original text leaf, unselected run, paragraph, shape and unrelated member retains its original bytes$/,run:c=>{const s=state(c),before=parseXml(new TextDecoder().decode(s.members.get('ppt/slides/slide2.xml')!)),after=parseXml(s.pkg!.text('ppt/slides/slide2.xml'));assert.deepEqual(elements(after,'t',A).map(t=>s.pkg!.text('ppt/slides/slide2.xml').slice(t.start,t.end)),elements(before,'t',A).map(t=>new TextDecoder().decode(s.members.get('ppt/slides/slide2.xml')!).slice(t.start,t.end)));for(const[n,b]of s.members)if(!s.record.changedMembers.includes(n))assert(Buffer.from(b).equals(Buffer.from(s.pkg!.get(n)!)),n);}});
entries.push({pattern:/^only the selected property span may change and all unpatched attributes and child fragments retain their exact bytes$/,run:c=>{const s=state(c),r=s.record,old=new TextDecoder().decode(s.members.get('ppt/slides/slide2.xml')!),now=s.pkg!.text('ppt/slides/slide2.xml');if(r.expected.refusal){assert.equal(now,old);return;}assert.equal(protectedXml(now,r),protectedXml(old,r));if(r.kind!=='run-bold')assert.equal(unpatchedProperty(now,r),unpatchedProperty(old,r));const a=target(old,r),b=target(now,r)!;if(a){const patched:Record<string,string[]>={'hide':['show'],'unhide':['show'],'visibility-order':['show'],'move':[],'resize':[],'transform':['rot','flipH','flipV'],'run-bold':['b'],'run-unbold':['b'],'run-italic':['i'],'run-underline':['u'],'run-size':['sz'],'run-inherit':['b','i','u','sz'],'paragraph-align':['algn'],'paragraph-indent':['marL','indent']};for(const[k,v]of Object.entries(a.attributes))if(!(patched[r.kind]??[]).includes(k))assert.equal(b.attributes[k],v);const changedChildren:Record<string,string[]>={'move':['off'],'resize':['ext'],'run-font':['latin'],'run-color':['solidFill'],'run-inherit':['latin','solidFill'],'paragraph-spacing':['spcBef','spcAft'],'paragraph-line':['lnSpc']};for(const child of a.children)if(!(changedChildren[r.kind]??[]).includes(child.localName)){const after=cs(b,child.localName,child.namespaceURI);assert.equal(after.length,1);assert.equal(now.slice(after[0]!.start,after[0]!.end),old.slice(child.start,child.end));}}if(r.kind==='visibility-order'){const prior=new TextDecoder().decode(s.members.get('ppt/presentation.xml')!),saved=s.pkg!.text('ppt/presentation.xml'),x=one(parseXml(prior).root,'sldIdLst',P),y=one(parseXml(saved).root,'sldIdLst',P);assert.equal(prior.slice(0,x.openEnd)+prior.slice(x.closeStart),saved.slice(0,y.openEnd)+saved.slice(y.closeStart));assert.deepEqual(new Set(y.children.map(n=>saved.slice(n.start,n.end))),new Set(x.children.map(n=>prior.slice(n.start,n.end))));}}});
entries.push({pattern:/^caller archive, original slide IDs, relationship IDs, targets, layout and notes links retain custody$/,run:async c=>{const s=state(c);assert.deepEqual(s.input,s.before);const old=graph(await OpcPackage.open(s.before)),after=graph(s.pkg!);for(const row of old)assert.deepEqual(after.find(r=>r.part===row.part),row);}});
entries.push({pattern:/^refusal reason (invalid-visibility|invalid-geometry) leaves session bytes and held identities unchanged before save$/,run:(c,reason)=>{const s=state(c);assert(s.error instanceof OoxmlError);assert.equal(s.error.code,reason==='invalid-visibility'?'PPTX_VISIBILITY_INVALID':'PPTX_GEOMETRY_INVALID');assert.deepEqual(s.deck.package.toBytes(),s.before);assert.deepEqual(s.deck.slides,s.handles);assert.deepEqual(s.output,s.before);}});
export const bindings=entries;
