import {expect} from 'bun:test';
import type {StepBinding} from '../../scripts/gherkin.ts';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';import {tmpdir} from 'node:os';
import {Presentation} from '../../src/pptx/index.ts';
import {addPart,addRelationship,OpcPackage} from '../../src/opc/index.ts';
import {parseXml,elements} from '../../src/xml/index.ts';
const P='http://schemas.openxmlformats.org/presentationml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const folders=new Set<string>();export async function cleanup(){for(const f of folders)await rm(f,{recursive:true,force:true});folders.clear();}
type State={kind:string;deck:Presentation;input:Uint8Array;before:Uint8Array;parts:Map<string,Uint8Array>;main:string;slide:string;result?:unknown;error?:unknown;saved?:Presentation;file?:string;shape?:number};
const state=(c:Record<string,unknown>)=>c.state as State;
export async function deckFor(kind:string){const d=Presentation.create();for(const title of ['Alpha','Beta','Gamma'])d.addTextSlide(title,'Subtitle');if(kind.includes('body')||kind.startsWith('bullet')||kind==='clear-bullets')d.slides[1]!.addTextBox('Existing',{x:1,y:2,width:1000,height:1000},{name:'Body'});if(kind.includes('notes')){const p=d.package,n='ppt/notesSlides/notesSlide1.xml';addPart(p,n,`<p:notes xmlns:p="${P}" xmlns:a="${A}"><p:cSld><p:spTree><p:sp><p:nvSpPr><p:cNvPr id="2" name="Notes"/><p:cNvSpPr/><p:nvPr><p:ph type="body"/></p:nvPr></p:nvSpPr><p:spPr/><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>Original notes</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld></p:notes>`,'application/vnd.openxmlformats-officedocument.presentationml.notesSlide+xml');addRelationship(p,d.slides[0]!.partName,R+'/notesSlide','../notesSlides/notesSlide1.xml');}return Presentation.open(d.package.toBytes());}
function identity(d:Presentation,index:number,name:string){const matches=d.slides[index]!.inspectTextShapes().filter(s=>name==='Body'?s.name===name:name==='title'?s.placeholder==='ctrTitle'||s.placeholder==='title':s.placeholder==='subTitle');expect(matches).toHaveLength(1);return matches[0]!.shapeId;}
const shapeIndex=(k:string)=>k.includes('body')||k.startsWith('bullet')||k==='clear-bullets'?1:0;
const name=(k:string)=>shapeIndex(k)===1?'Body':k==='patch-subtitle'?'subtitle':'title';
export const bindings:StepBinding[]=[
 {pattern:/^the concrete PPTX manipulation input is (\S+)$/,run:async(c,k)=>{expect(k).toBeDefined();const prepared=await deckFor(k!),input=prepared.package.toBytes(),before=input.slice(),d=await Presentation.open(input),s=state(c);Object.assign(s,{kind:k,deck:d,input,before,parts:new Map(d.package.names().map(n=>[n,d.package.get(n)!])),main:d.package.mainPart(),slide:d.slides[shapeIndex(k!)]!.partName});if(k!.startsWith('patch')||k==='append-title'||k!.startsWith('bullet')||k==='clear-bullets'||k!.startsWith('autofit'))s.shape=identity(d,shapeIndex(k!),name(k!));}},
 {pattern:/^the production manipulation is performed for (\S+)$/,run:(c,k)=>{const s=state(c),d=s.deck,slide=d.slides[shapeIndex(k!)]!;expect(k).toBe(s.kind);switch(k){
 case 'patch-title':s.result=slide.setShapeText(s.shape!,'New Title');break;
 case 'patch-body':s.result=slide.setShapeText(s.shape!,'Updated bullet');break;
 case 'patch-subtitle':s.result=slide.setShapeText(s.shape!,'New Subtitle');break;
 case 'append-title':s.result=slide.setShapeText(s.shape!,' - Appended',true);break;
 case 'bullet-default':s.result=slide.addBullet(s.shape!,'New bullet point');break;
 case 'bullet-sequence':slide.clearShapeText(s.shape!);slide.addBullet(s.shape!,'First bullet');s.result=slide.addBullet(s.shape!,'Second bullet');break;
 case 'bullet-level':s.result=slide.addBullet(s.shape!,'Sub-bullet point',1);break;
 case 'bullet-bold-label':s.result=slide.addBullet(s.shape!,'This is the description',0,'Key Point');break;
 case 'clear-bullets':s.result=slide.clearShapeText(s.shape!);break;
 case 'autofit-shrink':case 'autofit-none':case 'autofit-resize':s.result=slide.setShapeAutofit(s.shape!,k.slice(8) as 'shrink'|'none'|'resize');break;
 case 'insert-start':s.result=d.insertTextSlide(0,'First Slide','Inserted subtitle');break;
 case 'insert-middle':s.result=d.insertTextSlide(1,'Middle Slide','Inserted subtitle');break;
 case 'reorder':s.result=d.reorderSlides([0,2,1]);break;
 case 'reorder-refusal':try{s.result=d.reorderSlides([0,1,2,3,4,5]);}catch(e){s.error=e;}break;
 case 'table-values':{slide.addTable(3,3,{x:914400,y:1828800,width:10058400,height:2743200});for(const[r,row]of [['Name','Value','Status'],['Item 1','100','OK'],['Item 2','200','Pending']].entries())for(const[col,value]of row.entries())slide.tables[0]!.cell(r,col).text=value;break;}
 case 'table-geometry':slide.addTable(2,2,{x:914400,y:1828800,width:10058400,height:2743200});break;
 case 'set-notes':case 'notes-readback':{const a=slide.inspectNotesText();expect(a).toBeDefined();s.result=slide.replaceNotesAt(a,k==='set-notes'?'These are speaker notes':'Speaker notes content\nsecond line');break;}
 default:throw Error('Unbound manipulation '+k);
 }}},
 {pattern:/^the saved PPTX is reopened for (\S+)$/,run:async(c,k)=>{const s=state(c);if(k==='reorder-refusal'){expect(s.error).toBeDefined();expect(s.result).toBeUndefined();expect(s.deck.package.toBytes()).toEqual(s.before);return;}const folder=await mkdtemp(join(tmpdir(),'bun-pptx-next20-'));folders.add(folder);s.file=join(folder,'edited.pptx');await s.deck.save(s.file);s.saved=await Presentation.open(s.file);}},
 {pattern:/^the exact manipulated values and XML properties match (\S+)$/,run:c=>{const s=state(c),k=s.kind;if(k==='reorder-refusal')return;const d=s.saved!,i=shapeIndex(k),slide=d.slides[i]!;if(s.shape){const sh=slide.inspectTextShapes().find(x=>x.shapeId===s.shape)!;expect(sh).toBeDefined();const expected:Record<string,string>={'patch-title':'New Title','patch-body':'Updated bullet','patch-subtitle':'New Subtitle','append-title':'Alpha\n - Appended','bullet-default':'Existing\nNew bullet point','bullet-sequence':'First bullet\nSecond bullet','bullet-level':'Existing\nSub-bullet point','bullet-bold-label':'Existing\nKey Point: This is the description','clear-bullets':''};if(Object.hasOwn(expected,k))expect(sh.text).toBe(expected[k]!);const xml=parseXml(d.package.text(slide.partName)),sp=elements(xml,'sp',P).find(e=>elements(e,'cNvPr',P)[0]?.attributes.id===String(s.shape))!;if(k==='bullet-level')expect(elements(sp,'pPr',A).at(-1)!.attributes.lvl).toBe('1');if(k.startsWith('bullet'))expect(elements(sp,'buChar',A).at(-1)!.attributes.char).toBe('•');if(k==='bullet-bold-label'){const runs=elements(sp,'r',A).slice(-2);expect(elements(runs[0]!,'rPr',A)[0]!.attributes.b).toBe('1');expect(elements(runs[1]!,'rPr',A)).toHaveLength(0);}if(k.startsWith('autofit')){const fit=({ 'autofit-shrink':'normAutofit','autofit-none':'noAutofit','autofit-resize':'spAutoFit'} as Record<string,string>)[k]!;expect(elements(sp,fit,A)).toHaveLength(1);}}
 if(k==='insert-start'||k==='insert-middle')expect(d.slides.map(s=>s.inspectText('saved')[0]!.text)).toEqual(k==='insert-start'?['First Slide','Alpha','Beta','Gamma']:['Alpha','Middle Slide','Beta','Gamma']);if(k==='reorder')expect(d.slides.map(s=>s.inspectText('saved')[0]!.text)).toEqual(['Alpha','Gamma','Beta']);if(k==='table-values')expect(Array.from({length:slide.tables[0]!.rows},(_,r)=>Array.from({length:slide.tables[0]!.columns},(_,c)=>slide.tables[0]!.cell(r,c).text))).toEqual([['Name','Value','Status'],['Item 1','100','OK'],['Item 2','200','Pending']]);if(k==='table-geometry'){const doc=parseXml(d.package.text(slide.partName)),x=elements(doc,'xfrm',P).at(-1)!;expect(elements(x,'off',A)[0]!.attributes).toEqual({x:'914400',y:'1828800'});expect(elements(x,'ext',A)[0]!.attributes).toEqual({cx:'10058400',cy:'2743200'});expect(elements(doc,'gridCol',A).reduce((n,e)=>n+Number(e.attributes.w),0)).toBe(10058400);expect(elements(doc,'tr',A).reduce((n,e)=>n+Number(e.attributes.h),0)).toBe(2743200);}if(k==='set-notes'||k==='notes-readback')expect(slide.readNotesText()).toBe(k==='set-notes'?'These are speaker notes':'Speaker notes content\nsecond line');}},
 {pattern:/^unrelated payloads and the supplied archive retain custody for (\S+)$/,run:async c=>{const s=state(c),k=s.kind;if(k==='reorder-refusal'){expect(s.deck.package.toBytes()).toEqual(s.before);expect(s.input).toEqual(s.before);return;}expect(s.input).toEqual(s.before);expect(s.before).toEqual((await OpcPackage.open(s.before)).toBytes());const d=s.saved!,changed=new Set<string>();if(k.startsWith('insert')){changed.add(s.main);changed.add('[Content_Types].xml');changed.add('ppt/_rels/presentation.xml.rels');}else if(k==='reorder')changed.add(s.main);else if(k.includes('notes'))changed.add('ppt/notesSlides/notesSlide1.xml');else changed.add(s.slide);for(const[n,b]of s.parts)if(!changed.has(n))expect(d.package.get(n)).toEqual(b);if(!k.startsWith('insert'))expect(new Set(d.package.names())).toEqual(new Set(s.parts.keys()));}},
];
