import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import type {StepBinding} from '../../scripts/gherkin.ts';
import pin from '../../docs/behaviors/pptx-manipulation-candidate.json';
import {fixturesRoot,fixturePath} from '../../scripts/fixture-inputs.ts';
import {Presentation} from '../../src/pptx/index.ts';
import {OpcPackage} from '../../src/opc/index.ts';
import {OoxmlError} from '../../src/errors.ts';
import {parseXml,elements,attribute,type XmlElement} from '../../src/xml/index.ts';
import {bindings as predecessor} from './pptx-next20.ts';
const P='http://schemas.openxmlformats.org/presentationml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const folders=new Set<string>();
export async function cleanup(){for(const folder of folders)await rm(folder,{recursive:true,force:true});folders.clear();}
type Recipe={id:string;kind:string;target:string;operation:string;fixtureId:string;expected:Record<string,any>;changedMembers:string[]};
type State={recipe:Recipe;kind:string;deck:Presentation;input:Uint8Array;before:Uint8Array;parts:Map<string,Uint8Array>;main:string;slide:string;shape?:number;result?:unknown;error?:unknown;saved?:Presentation;pkg?:OpcPackage;handles?:Presentation['slides'];};
const state=(c:Record<string,unknown>)=>c.state as State;
const one=(node:XmlElement,name:string,ns=A)=>{const matches=elements(node,name,ns);assert.equal(matches.length,1,name);return matches[0]!;};
const paragraphs=(node:XmlElement)=>elements(node,'p',A).map(p=>elements(p,'t',A).map(t=>t.text).join(''));
function graph(pkg:OpcPackage){const xml=parseXml(pkg.text(pkg.mainPart())),links=pkg.relationships(pkg.mainPart());return elements(xml,'sldId',P).map(node=>{const rid=attribute(node,'id',R),link=links.find(l=>l.id===rid);assert(link?.resolved);return {id:node.attributes.id,rid,target:link.target,part:link.resolved,links:pkg.relationships(link.resolved)};});}
function protectedXml(xml:string,kind:string,shape?:number){const doc=parseXml(xml);if(kind==='reorder'||kind.startsWith('insert')){const list=one(doc.root,'sldIdLst',P);return xml.slice(0,list.openEnd)+'#selected#'+xml.slice(list.closeStart);}
 if(kind.includes('notes')){const body=elements(doc,'sp',P).find(sp=>elements(sp,'ph',P).some(ph=>ph.attributes.type==='body'));assert(body);const tx=one(body,'txBody',P);return xml.slice(0,tx.start)+'#selected#'+xml.slice(tx.end);}
 if(kind.startsWith('table')){const tableFrames=elements(doc,'graphicFrame',P).filter(frame=>elements(frame,'tbl',A).length);if(!tableFrames.length)return xml;assert.equal(tableFrames.length,1);const frame=tableFrames[0]!;return xml.slice(0,frame.start)+xml.slice(frame.end);}
 const sp=elements(doc,'sp',P).find(sp=>elements(sp,'cNvPr',P)[0]?.attributes.id===String(shape));assert(sp);const tx=one(sp,'txBody',P);if(kind.startsWith('autofit')){const pr=one(sp,'bodyPr');return xml.slice(0,pr.start)+'#selected#'+xml.slice(pr.end);}return xml.slice(0,tx.start)+'#selected#'+xml.slice(tx.end);}
const entries:StepBinding[]=[];
entries.push({pattern:/^the sealed PPTX fixture (fixture-[a-f0-9]+) with ordered titles \["Alpha","Beta","Gamma"\]$/,run:async(c,id)=>{const s=state(c),ledger=await Bun.file(join(fixturesRoot(),'ledgers/pptx-manipulation.json')).json(),scenario=(c.scenario as {id:string}).id,recipe=ledger.records.find((r:Recipe)=>r.id===scenario);assert(recipe&&pin.selectedScenarioIds.includes(scenario));assert.equal(recipe.fixtureId,id);const input=await Bun.file(fixturePath(id!)).bytes(),deck=await Presentation.open(input),k=recipe.kind,i=k.includes('body')||k.startsWith('bullet')||k==='clear-bullets'?1:0;Object.assign(s,{recipe,kind:k,deck,input,before:input.slice(),parts:new Map(deck.package.names().map(n=>[n,deck.package.get(n)!])),main:deck.package.mainPart(),slide:deck.slides[i]!.partName,handles:[...deck.slides]});if(k.startsWith('patch')||k==='append-title'||k.startsWith('bullet')||k==='clear-bullets'||k.startsWith('autofit'))s.shape=k==='patch-subtitle'?3:i===1?4:2;assert.deepEqual(deck.slides.map(slide=>slide.inspectTextShapes()[0]!.text),['Alpha','Beta','Gamma']);}});
entries.push({pattern:/^(.+) is selected by its original part and unique identity$/,run:(c,target)=>{const s=state(c);assert.equal(target,s.recipe.target);if(s.shape)assert.equal(s.deck.slides.find(slide=>slide.partName===s.slide)!.inspectTextShapes().filter(sh=>sh.shapeId===s.shape).length,1);}});
entries.push({pattern:/^production presentation editing APIs (.+)$/,run:async(c,operation)=>{const s=state(c);assert.equal(operation,s.recipe.operation);await predecessor[1]!.run(c,s.kind);if(s.kind==='reorder-refusal'){assert(s.error instanceof OoxmlError);assert.equal(s.error.code,'PPTX_ORDER_UNSUPPORTED');assert.deepEqual(s.deck.slides,s.handles);}}});
entries.push({pattern:/^the resulting presentation is saved to a new path and independently parsed and reopened$/,run:async c=>{const s=state(c),folder=await mkdtemp(join(tmpdir(),'bun-pptx-manipulation-'));folders.add(folder);const path=join(folder,'edited.pptx');await s.deck.save(path);s.pkg=await OpcPackage.open(path);s.saved=await Presentation.open(path);for(const n of s.pkg.names())if(n.endsWith('.xml')||n.endsWith('.rels'))parseXml(s.pkg.text(n));}});
entries.push({pattern:/^the saved (.+) has exact properties JSON (.+)$/,run:(c,target,json)=>{const s=state(c),expected=JSON.parse(json!),k=s.kind,pkg=s.pkg!;assert.equal(target,s.recipe.target);assert.deepEqual(expected,s.recipe.expected);
 if(s.shape){const xml=parseXml(pkg.text(s.slide)),sp=elements(xml,'sp',P).find(sp=>elements(sp,'cNvPr',P)[0]?.attributes.id===String(s.shape));assert(sp);const ps=paragraphs(sp);if(expected.paragraphs)assert.deepEqual(ps,expected.paragraphs);assert.equal(ps.join('\n'),expected.text);
 const originalXml=new TextDecoder().decode(s.parts.get(s.slide)!),originalSp=elements(parseXml(originalXml),'sp',P).find(sp=>elements(sp,'cNvPr',P)[0]?.attributes.id===String(s.shape))!;
 for(const name of k.startsWith('autofit')?['lstStyle']:['bodyPr','lstStyle']){const old=one(originalSp,name),now=one(sp,name);assert.equal(pkg.text(s.slide).slice(now.start,now.end),originalXml.slice(old.start,old.end));}
 if(k.startsWith('bullet')){const bulletPs=elements(sp,'p',A).filter(p=>elements(p,'buChar',A).length);const specs=expected.bullets??[expected.bullet];assert.equal(bulletPs.length,specs.length);for(const[p,index]of bulletPs.map((p,i)=>[p,i] as const)){assert.equal(one(p,'buChar').attributes.char,specs[index].character);assert.equal(Number(one(p,'pPr').attributes.lvl),specs[index].level);}if(expected.runs){const runs=elements(bulletPs.at(-1)!,'r',A);assert.equal(runs.length,2);assert.deepEqual(runs.map(run=>({text:one(run,'t').text,bold:['1','true'].includes(elements(run,'rPr',A)[0]?.attributes.b??'0')})),expected.runs);}}
 if(k==='clear-bullets'){assert.equal(elements(sp,'p',A).length,1);assert.equal(elements(sp,'buChar',A).length,0);assert.equal(elements(sp,'pPr',A).length,0);}
 if(k.startsWith('autofit')){const pr=one(sp,'bodyPr'),fits=pr.children.filter(e=>e.namespaceURI===A&&['normAutofit','noAutofit','spAutoFit'].includes(e.localName));assert.equal(fits.length,1);assert.equal(fits[0]!.localName,expected.autofit);const old=parseXml(new TextDecoder().decode(s.parts.get(s.slide)!)),oldsp=elements(old,'sp',P).find(sp=>elements(sp,'cNvPr',P)[0]?.attributes.id===String(s.shape))!;assert.deepEqual(pr.attributes,one(oldsp,'bodyPr').attributes);assert.deepEqual(one(sp,'lstStyle').attributes,one(oldsp,'lstStyle').attributes);}
 }
 if(expected.titles){assert.deepEqual(s.saved!.slides.map(slide=>slide.inspectTextShapes()[0]!.text),expected.titles);if(k.startsWith('insert')){const inserted=s.saved!.slides[k==='insert-start'?0:1]!;assert.equal(inserted.inspectTextShapes()[1]!.text,expected.insertedSubtitle);const xml=parseXml(pkg.text(inserted.partName)),ids=elements(xml,'cNvPr',P).map(n=>n.attributes.id);assert.equal(new Set(ids).size,ids.length);}}
 if(k.startsWith('table')){const xml=parseXml(pkg.text(s.slide)),tbl=one(xml.root,'tbl'),frames=elements(xml,'graphicFrame',P).filter(frame=>elements(frame,'tbl',A).length);assert.equal(frames.length,1);const xfrm=one(frames[0]!,'xfrm',P);assert.deepEqual({...one(xfrm,'off').attributes},{x:String(expected.x),y:String(expected.y)});assert.deepEqual({...one(xfrm,'ext').attributes},{cx:String(expected.width),cy:String(expected.height)});const rows=elements(tbl,'tr',A),grid=elements(tbl,'gridCol',A);assert.equal(rows.length,expected.rows);assert.equal(grid.length,expected.columns);assert.equal(rows.reduce((n,e)=>n+Number(e.attributes.h),0),expected.height);assert.equal(grid.reduce((n,e)=>n+Number(e.attributes.w),0),expected.width);if(expected.columnWidths)assert.deepEqual(grid.map(e=>Number(e.attributes.w)),expected.columnWidths);if(expected.rowHeights)assert.deepEqual(rows.map(e=>Number(e.attributes.h)),expected.rowHeights);assert.deepEqual(rows.map(row=>elements(row,'tc',A).map(cell=>paragraphs(cell).join('\n'))),expected.cells);}
 if(k.includes('notes')){const xml=parseXml(pkg.text('ppt/notesSlides/notesSlide1.xml')),body=elements(xml,'sp',P).find(sp=>elements(sp,'ph',P).some(ph=>ph.attributes.type==='body'))!;assert.deepEqual(paragraphs(body),expected.paragraphs);assert.equal(s.saved!.slides[0]!.readNotesText(),expected.text);}
 if(expected.refusal){assert.deepEqual(s.deck.package.toBytes(),s.before);assert.deepEqual(s.deck.slides,s.handles);assert.equal((s.error as OoxmlError).code,'PPTX_ORDER_UNSUPPORTED');}
 }});
entries.push({pattern:/^only original member payloads (.+) may change$/,run:(c,json)=>{const s=state(c),allowed=JSON.parse(json!);assert.deepEqual(allowed,s.recipe.changedMembers);const changed=[...s.parts].filter(([n,b])=>!Buffer.from(b).equals(Buffer.from(s.pkg!.get(n)!))).map(([n])=>n);assert.deepEqual(changed.sort(),[...allowed].sort());}});
entries.push({pattern:/^the original member name set is unchanged$/,run:c=>{const s=state(c);assert.deepEqual(s.pkg!.names().sort(),[...s.parts.keys()].sort());}});
entries.push({pattern:/^exactly one slide XML part and its one layout relationship part are added with valid unique IDs and a resolved original layout; no members are removed$/,run:c=>{const s=state(c),pkg=s.pkg!,added=pkg.names().filter(n=>!s.parts.has(n));assert.equal(added.length,2);const slide=added.find(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n));assert(slide);assert(added.includes('ppt/slides/_rels/'+slide.split('/').at(-1)+'.rels'));for(const n of s.parts.keys())assert(pkg.names().includes(n));
 for(const meta of ['[Content_Types].xml','ppt/_rels/presentation.xml.rels']){const old=new TextDecoder().decode(s.parts.get(meta)!),xml=pkg.text(meta),before=parseXml(old).root,after=parseXml(xml).root;assert.equal(old.slice(0,before.openEnd),xml.slice(0,after.openEnd));assert.equal(old.slice(before.closeStart),xml.slice(after.closeStart));const known=new Set(before.children.map(e=>old.slice(e.start,e.end)));let stripped=xml;for(const e of [...after.children].reverse())if(!known.has(xml.slice(e.start,e.end)))stripped=stripped.slice(0,e.start)+stripped.slice(e.end);assert.equal(stripped,old,meta+' lexical custody');}
 const rels=pkg.relationships(slide);assert.equal(rels.length,1);assert.equal(rels[0]!.type,R+'/slideLayout');assert(s.parts.has(rels[0]!.resolved!));const identities=graph(pkg);assert.equal(new Set(identities.map(i=>i.id)).size,4);assert.equal(new Set(identities.map(i=>i.rid)).size,4);assert.equal(new Set(identities.map(i=>i.part)).size,4);}});
entries.push({pattern:/^the supplied archive, unrelated member payloads and unaffected lexical XML spans retain their original bytes(, and the refusal returns invalid-permutation without changing session or handles)?$/,run:async(c,refusal)=>{const s=state(c),pkg=s.pkg!,k=s.kind;assert.deepEqual(s.input,s.before);for(const[n,b]of s.parts)if(!s.recipe.changedMembers.includes(n))assert.deepEqual(pkg.get(n),b,n);if(refusal){assert.equal(k,'reorder-refusal');assert.deepEqual(s.deck.package.toBytes(),s.before);assert.deepEqual(s.deck.slides,s.handles);}else{const selected=k==='reorder'||k.startsWith('insert')?s.main:k.includes('notes')?'ppt/notesSlides/notesSlide1.xml':s.slide;assert.equal(protectedXml(pkg.text(selected),k,s.shape),protectedXml(new TextDecoder().decode(s.parts.get(selected)!),k,s.shape));} }});
entries.push({pattern:/^all pre-existing slides retain their original IDs, relationship IDs, targets, layout links and notes links$/,run:async c=>{const s=state(c),before=graph(await OpcPackage.open(s.before)),after=graph(s.pkg!);for(const old of before)assert.deepEqual(after.find(row=>row.part===old.part),old);if(s.kind==='reorder')assert.deepEqual(after.map(row=>row.part),[before[0]!.part,before[2]!.part,before[1]!.part]);}});
export const bindings=entries;
