import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {Presentation} from '../../src/pptx/index.ts';import {Document} from '../../src/docx/index.ts';import {OpcPackage} from '../../src/opc/index.ts';
import {parseXml,elements,attribute,type XmlElement} from '../../src/xml/index.ts';import {fixturePath,fixturesRoot} from '../../scripts/fixture-inputs.ts';import type {StepBinding} from '../../scripts/gherkin.ts';
import {omitOpeningAttributes} from '../helpers/xml-formatting-custody.ts';
import {routed as routeRetainedTable} from './retained-table.ts';
const A='http://schemas.openxmlformats.org/drawingml/2006/main',P='http://schemas.openxmlformats.org/presentationml/2006/main',W='http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const dirs=new Set<string>();export async function cleanup(){for(const d of dirs)await rm(d,{recursive:true,force:true});dirs.clear();}
type State={record:any;input:Uint8Array;before:Uint8Array;members:Map<string,Uint8Array>;doc:Presentation|Document;held:any;pkg?:OpcPackage;saved?:Presentation|Document;error?:any;output?:Uint8Array};const state=(c:Record<string,unknown>)=>c.retainedState as State;
const cs=(e:XmlElement,n:string,ns:string)=>e.children.filter(c=>c.namespaceURI===ns&&c.localName===n),one=(e:XmlElement,n:string,ns:string)=>{const r=cs(e,n,ns);assert.equal(r.length,1,n);return r[0]!;};
const part=(s:State)=>s.record.format==='pptx'?'ppt/slides/slide2.xml':'word/document.xml';
function target(xml:string,r:any){const d=parseXml(xml);if(r.format==='pptx'){const sp=elements(d,'sp',P).find(s=>elements(s,'cNvPr',P)[0]?.attributes.id==='4')!;assert(sp);if(r.family==='shape-style')return one(sp,'spPr',P);const body=one(sp,'txBody',P);if(r.family==='text-frame-properties')return one(body,'bodyPr',A);return one(cs(cs(body,'p',A)[0]!,'r',A)[0]!,'rPr',A);}const body=one(d.root,'body',W),p=cs(body,'p',W)[0]!;return r.family==='paragraphs'?one(p,'pPr',W):one(cs(p,'r',W)[0]!,'rPr',W);}
// Explicit direct-run selection; avoid the all-runs legacy adapter.
function selected(xml:string,r:any){if(r.format==='pptx'&&r.family==='text-formatting'){const d=parseXml(xml),sp=elements(d,'sp',P).find(s=>elements(s,'cNvPr',P)[0]?.attributes.id==='4')!,p=cs(one(sp,'txBody',P),'p',A)[0]!,run=cs(p,'r',A)[0]!;return one(run,'rPr',A);}return target(xml,r);}
export function perform(doc:Presentation|Document,r:any){if(r.format==='pptx'){const slide=(doc as Presentation).slides[1]!;if(r.family==='shape-style')return slide.patchShapeStyle(4,r.patch);if(r.family==='text-frame-properties')return slide.patchTextFrame(4,r.patch);return slide.patchRetainedRunEffects(4,0,0,r.patch);}const paragraph=(doc as Document).paragraphs[0]!;return r.family==='paragraphs'?paragraph.patchRetainedProperties(r.patch):paragraph.patchRetainedRun(0,r.patch);}
export function assertChangedMembers(c:Record<string,unknown>,raw:string){const s=state(c);assert.deepEqual(JSON.parse(raw),s.record.changedMembers);assert.deepEqual(s.pkg!.names(),[...s.members.keys()].sort());const actual=[...s.members].filter(([n,b])=>!Buffer.from(b).equals(Buffer.from(s.pkg!.get(n)!))).map(([n])=>n).sort();assert.deepEqual(actual,[...s.record.changedMembers].sort());}
function masked(xml:string,r:any){const root=selected(xml,r),owner=r.mask.owner?one(root,r.mask.owner,r.format==='pptx'?A:W):root;let snippet=xml.slice(owner.start,owner.end);const attrs=new Set<string>(r.mask.attributes??[]);if(r.format==='docx')for(const key of Object.keys(owner.attributes))if(owner.attributeNamespaces[key]===W&&attrs.has(key.split(':').at(-1)!))attrs.add(key);snippet=omitOpeningAttributes(snippet,attrs);for(const c of owner.children.filter(c=>r.mask.children?.includes(c.localName)).sort((a,b)=>b.start-a.start))snippet=snippet.replace(xml.slice(c.start,c.end),'');return xml.slice(0,owner.start)+snippet+xml.slice(owner.end);}
export function assertRetainedCustody(s:State){const old=new TextDecoder().decode(s.members.get(part(s))!),now=s.pkg!.text(part(s));assert.equal(masked(now,s.record),masked(old,s.record));for(const[n,b]of s.members)if(!s.record.changedMembers.includes(n))assert(Buffer.from(b).equals(Buffer.from(s.pkg!.get(n)!)),n);assert.deepEqual(s.input,s.before);}
function exact(s:State){const r=s.record;if(r.refusal){assert(s.error);assert.equal(s.error.code,'PPTX_STYLE_INVALID');return;}const node=selected(s.pkg!.text(part(s)),r),ns=r.format==='pptx'?A:W,e=r.expected;if(r.format==='pptx'){if(r.family==='shape-style'){for(const[k,v]of Object.entries(e)){const owner=k.startsWith('line')?one(node,'ln',A):node;if(k==='fill'||k==='lineColor'){if(v==='none')assert.equal(cs(owner,'noFill',A).length,1);else assert.equal(one(one(owner,'solidFill',A),'srgbClr',A).attributes.val,v);}else if(k==='lineWidth')assert.equal(Number(owner.attributes.w),v);else if(k==='lineDash')assert.equal(one(owner,'prstDash',A).attributes.val,v);else if(k==='absent')for(const n of v as string[])assert.equal(cs(node,n,A).length,0);}}else for(const[k,v]of Object.entries(e))assert.equal(node.attributes[k],typeof v==='boolean'?v?'1':'0':String(v));}else{const leaves:Record<string,string>={strike:'strike',underline:'u',color:'color',highlight:'highlight',sizeHalfPoints:'sz',verticalAlign:'vertAlign',caps:'caps',smallCaps:'smallCaps',vanish:'vanish',jc:'jc',keepLines:'keepLines',keepNext:'keepNext',pageBreakBefore:'pageBreakBefore',outlineLvl:'outlineLvl'};for(const[k,v]of Object.entries(e)){if(k==='absent')for(const n of v as string[])assert.equal(cs(node,n,W).length,0);else if(k==='retained')for(const n of v as string[])assert.equal(cs(node,n,W).length,1);else if(k==='ascii'||k==='hAnsi')assert.equal(attribute(one(node,'rFonts',W),k,W),v);else if(['before','after','line','lineRule'].includes(k))assert.equal(attribute(one(node,'spacing',W),k,W),String(v));else if(['left','right','hanging'].includes(k))assert.equal(attribute(one(node,'ind',W),k,W),String(v));else assert.equal(attribute(one(node,leaves[k]!,W),'val',W),typeof v==='boolean'?v?'1':'0':String(v));}}}
const RUN=['rStyle','rFonts','b','bCs','i','iCs','caps','smallCaps','strike','dstrike','outline','shadow','emboss','imprint','noProof','snapToGrid','vanish','webHidden','color','spacing','w','kern','position','sz','szCs','highlight','u','effect','bdr','shd','fitText','vertAlign','rtl','cs','em','lang','eastAsianLayout','specVanish','oMath'];const PARA=['pStyle','keepNext','keepLines','pageBreakBefore','framePr','widowControl','numPr','suppressLineNumbers','pBdr','shd','tabs','suppressAutoHyphens','kinsoku','wordWrap','overflowPunct','topLinePunct','autoSpaceDE','autoSpaceDN','bidi','adjustRightInd','snapToGrid','spacing','ind','contextualSpacing','mirrorIndents','suppressOverlap','jc','textDirection','textAlignment','textboxTightWrap','outlineLvl','divId','cnfStyle','rPr','sectPr'];
function childOrder(s:State){const r=s.record,n=selected(s.pkg!.text(part(s)),r);let order=r.format==='docx'?r.family==='paragraphs'?PARA:RUN:r.family==='shape-style'?['xfrm','prstGeom','noFill','solidFill','ln']:r.family==='text-formatting'?['solidFill','latin']:['noAutofit','normAutofit','spAutoFit'];let prior=-1;for(const c of n.children){const rank=order.indexOf(c.localName);assert(rank>prior,'schema order '+c.localName);prior=rank;}if(r.family==='shape-style'){const line=one(n,'ln',A),names=['noFill','solidFill','prstDash'];prior=-1;for(const c of line.children){const rank=names.indexOf(c.localName);assert(rank>prior);prior=rank;}}}
const bindings:StepBinding[]=[
 {pattern:/^retained (pptx|docx) input (fixture-[a-f0-9]+) has its sealed original property and identity snapshot$/,run:async(c,format,id)=>{const l=await Bun.file(join(fixturesRoot(),'ledgers/retained-style-word.json')).json(),r=l.records.find((r:any)=>r.id===(c.scenario as {id:string}).id);assert(r);assert.equal(r.format,format);assert.equal(r.fixtureId,id);const input=await Bun.file(fixturePath(id!)).bytes(),before=input.slice(),pkg=await OpcPackage.open(input),doc=format==='pptx'?await Presentation.open(input):await Document.open(input);c.retainedState={record:r,input,before,doc,members:new Map(pkg.names().map(n=>[n,pkg.get(n)!])),held:format==='pptx'?(doc as Presentation).slides[1]:(doc as Document).paragraphs[0]};}},
 {pattern:/^retained edit target (.+) is uniquely selected with a held identity$/,run:(c,t)=>{const s=state(c);assert.equal(t,s.record.target);assert(s.held);}},
 {pattern:/^production retained (pptx|docx) editing applies (.+) patch JSON (.+)$/,run:(c,f,k,p)=>{const s=state(c);assert.equal(f,s.record.format);assert.equal(k,s.record.kind);assert.deepEqual(JSON.parse(p!),s.record.patch);if(s.record.refusal){try{perform(s.doc,s.record);}catch(e){s.error=e;}assert(s.error);}else perform(s.doc,s.record);}},
 {pattern:/^the result or unchanged refusal session is saved and independently parsed and reopened$/,run:async c=>{const s=state(c),dir=await mkdtemp(join(tmpdir(),'retained40-'));dirs.add(dir);const path=join(dir,'output.'+s.record.format);await s.doc.save(path);s.output=await Bun.file(path).bytes();s.pkg=await OpcPackage.open(path);s.saved=s.record.format==='pptx'?await Presentation.open(path):await Document.open(path);for(const n of s.pkg.names())if(n.endsWith('.xml')||n.endsWith('.rels'))parseXml(s.pkg.text(n));}},
 {pattern:/^retained target (.+) has exact saved properties JSON (.+)$/,run:(c,t,e)=>{const s=state(c);assert.equal(t,s.record.target);assert.deepEqual(JSON.parse(e!),s.record.expected);exact(s);}},
 {pattern:/^saved direct property children remain in schema order$/,run:c=>childOrder(state(c))},
 {pattern:/^every unpatched selected-property attribute and child retains its literal original bytes$/,run:c=>assertRetainedCustody(state(c))},
 {pattern:/^all other XML spans, text leaves, runs, paragraphs and unrelated member payloads retain custody$/,run:c=>assertRetainedCustody(state(c))},
 {pattern:/^actual caller input, original identities, relationships and content-type graph are unchanged$/,run:async c=>{const s=state(c);assert.deepEqual(s.input,s.before);const before=await OpcPackage.open(s.before);for(const n of before.names())if(n.endsWith('.rels')||n==='[Content_Types].xml')assert(Buffer.from(before.get(n)!).equals(Buffer.from(s.pkg!.get(n)!)));}},
 {pattern:/^refusal reason invalid-style preserves session bytes and held target usability before save$/,run:c=>{const s=state(c);assert.deepEqual(s.doc.package.toBytes(),s.before);assert.deepEqual(s.output,s.before);assert.equal((s.doc as Presentation).slides[1],s.held);assert.equal(s.held.patchTextRun(4,0,0,{bold:true}).changed,0);assert.deepEqual(s.doc.package.toBytes(),s.before);}}
];
const routedBindings=bindings.map(b=>({...b,run:(c:Record<string,unknown>,...args:string[])=>((c.scenario as {id:string}).id.startsWith('@id-pptx-table-properties-')||(c.scenario as {id:string}).id.startsWith('@id-docx-table-properties-'))?routeRetainedTable(b.pattern,c,...args):b.run(c,...args)}));
export {routedBindings as bindings};
