import {expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {OpcPackage,addRelationship} from '../../src/opc/index.ts';import {inspectRevisions,resolveRevisions,type Revision,type RevisionProfile} from '../../src/docx/revisions.ts';import type {StepBinding} from '../../scripts/gherkin.ts';import {openRevisionFixture} from './revisions-docx.ts';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',W14='http://schemas.microsoft.com/office/word/2010/wordml',REL='http://schemas.openxmlformats.org/officeDocument/2006/relationships/',profile='text-properties-and-moves' as const;
const parts=['word/document.xml','word/header1.xml','word/footer1.xml','word/footer2.xml','word/footnotes.xml','word/endnotes.xml','word/comments.xml'],labels=['Body','Header','Footer','Nested footer','Footnote','Endnote','Comment'];
const runs='<w:r><w:rPr><w:b/><w:color w:val="112233"/></w:rPr><w:t xml:space="preserve">Moved </w:t></w:r><w:r><w:t>text</w:t></w:r>',meta=' w:author="Reviewer" w:date="2026-09-27T00:00:00Z"';
const from=`<w:moveFromRangeStart w:id="100" w:name="move-one"${meta}/><w:moveFrom w:id="101"${meta}>${runs}</w:moveFrom><w:moveFromRangeEnd w:id="100"/>`,to=`<w:moveToRangeStart w:id="102" w:name="move-one"${meta}/><w:moveTo w:id="103"${meta}>${runs}</w:moveTo><w:moveToRangeEnd w:id="102"/>`;
const props='<w:r><w:rPr><w:b/><w:rPrChange w:id="80" w:author="Reviewer"><w:rPr><w:i/></w:rPr></w:rPrChange></w:rPr><w:t>Stable</w:t></w:r>',from2=from.replaceAll('move-one','move-two').replaceAll('100','200').replaceAll('101','201'),to2=to.replaceAll('move-one','move-two').replaceAll('102','202').replaceAll('103','203');
const aliases=runs.replaceAll('w:','q:'),fromAlias=from.replace(`<w:moveFrom w:id="101"${meta}>${runs}`,`<w:moveFrom xmlns:q="${W}" w:id="101"${meta}>${aliases}`),toAlias=to.replace(`<w:moveTo w:id="103"${meta}>${runs}`,`<w:moveTo xmlns:q="${W}" w:id="103"${meta}>${aliases}`),lifted=aliases.replaceAll('<q:r>',`<q:r xmlns:q="${W}">`);
const roots:string[]=[];export async function cleanupRevisionMoves(){await Promise.all(roots.splice(0).map(p=>rm(p,{recursive:true,force:true})));}
type State={p:OpcPackage;baseline:OpcPackage;before:Uint8Array;sourceBytes:Uint8Array;source:string;output:string;selected:string[];expected:Map<string,string>;read?:OpcPackage;receipt?:{resolved:number;changedParts:string[]};report?:ReturnType<typeof inspectRevisions>;errors:unknown[];returns:unknown[];encoding?:string;defect?:string;guard?:string;stage?:string;reached?:boolean;ordering?:boolean};const state=(c:Record<string,unknown>)=>c.moveOutcome as State;
function encode(xml:string,encoding?:string){if(!encoding)return new TextEncoder().encode(xml);if(encoding==='UTF-8-BOM')return new Uint8Array([239,187,191,...new TextEncoder().encode(xml)]);const b=new Uint8Array(2+2*xml.length);b.set(encoding==='UTF-16LE'?[255,254]:[254,255]);const v=new DataView(b.buffer);for(let i=0;i<xml.length;i++)v.setUint16(2+2*i,xml.charCodeAt(i),encoding==='UTF-16LE');return b;}
function alter(s:string,d:string):string{switch(d){case'missing-range-end':return s.replace('<w:moveFromRangeEnd w:id="100"/>','');case'missing-destination':return s.replace(to,'');case'duplicate-name':return s.replace(to,to+to.replaceAll('102','104').replaceAll('103','105'));case'duplicate-range-id':return s.replaceAll('102','100');case'duplicate-wrapper-id':return s.replace('w:id="103"','w:id="101"');case'wrong-wrapper':return s.replace(from,from.replace('<w:moveFrom w:','<w:moveTo w:').replace('</w:moveFrom>','</w:moveTo>'));case'overlapping-ranges':return s.replace(from,from.replace('</w:moveFrom>',to+'</w:moveFrom>'));case'unowned-wrapper':return s.replace(to,to+`<w:moveFrom w:id="190"${meta}>${runs}</w:moveFrom>`);case'mismatched-text':return s.replace(to,to.replace('>text<','>changed<'));case'mismatched-properties':return s.replace(to,to.replace('<w:b/>','<w:i/>'));case'mixed-content':return s.replace(from,from.replace('<w:moveFrom w:','UNOWNED<w:moveFrom w:'));case'nested-revision':return s.replace(from,from.replace('<w:r>',`<w:ins w:id="150"${meta}><w:r>`).replace('</w:r>','</w:r></w:ins>'));case'unsupported-properties':return s.replace(from,from.replace('<w:b/>','<w:glow/>'));case'paragraph-mark':return s.replace(from,'<w:pPr>'+from+'</w:pPr>');case'missing-author':return s.replace(from,from.replace(' w:author="Reviewer"',''));case'decorated-marker':return s.replace('w:name="move-one"','w:name="move-one" w:colFirst="0"');case'text-id-collision':return s.replace('w:id="101"','w:id="3"');default:throw Error('Unknown move defect '+d);}}
async function setup(c:Record<string,unknown>,o:{defect?:string;encoding?:string;scope?:boolean;guard?:string;side?:string;date?:string;ordering?:boolean}={}){const p=await openRevisionFixture('all-stories');for(const part of parts)p.set(part,p.text(part).replace('</w:p>',props+from+'<w:r><w:t>Middle</w:t></w:r>'+to+'</w:p>'));
 if(o.defect==='cross-story'){p.set(parts[0]!,p.text(parts[0]!).replace(to,''));p.set(parts[1]!,p.text(parts[1]!).replace(from,''));}else if(o.defect){const xml=p.text(parts[1]!),next=alter(xml,o.defect);expect(next).not.toBe(xml);p.set(parts[1]!,next);}
 if(o.scope)p.set(parts[3]!,p.text(parts[3]!).replace('w:name="move-one"','w:name="unpaired"'));
 if(o.encoding){let xml=p.text(parts[0]!).replace(from,fromAlias).replace(to,toAlias);if(o.encoding!=='UTF-8-BOM')xml=xml.replace('encoding="UTF-8"','encoding="UTF-16"');p.set(parts[0]!,encode(xml,o.encoding));}
 if(o.date){const side=o.side==='from'?from:to,modified=o.date==='missing-date'?side.replace(' w:date="2026-09-27T00:00:00Z"',''):side.replace('w:date="2026-09-27T00:00:00Z"','date="2026-09-27T00:00:00Z"');expect(modified).not.toBe(side);p.set(parts[0]!,p.text(parts[0]!).replace(side,modified));}
 if(o.ordering)p.set(parts[0]!,p.text(parts[0]!).replace('</w:body>','<w:p>'+to2+'</w:p><w:p>'+from2+'</w:p></w:body>'));
 if(o.guard){resolveRevisions(p,'accept',{profile});if(o.guard==='external-settings')addRelationship(p,p.mainPart(),REL+'settings','https://example.invalid/settings',{external:true});else{p.set('word/settings.xml',o.guard==='protection'?`<w:settings xmlns:w="${W}"><w:documentProtection w:enforcement="1"/></w:settings>`:`<w:wrong xmlns:w="${W}"/>`);addRelationship(p,p.mainPart(),REL+'settings','settings.xml');}}
 const dir=await mkdtemp(join(tmpdir(),'paired-move-'));roots.push(dir);const source=join(dir,'source.docx'),output=join(dir,'output.docx'),bytes=p.toBytes();await Bun.write(source,bytes);c.moveOutcome={p:await OpcPackage.open(source),baseline:await OpcPackage.open(source),sourceBytes:bytes,before:bytes,source,output,selected:[...parts],expected:new Map(),errors:[],returns:[],...o} satisfies State;
}
function records(part:string,i:number):Revision[]{return [{part,id:String(2*i+1),kind:'deletion',author:'A',date:'2026-06-01T09:30:00Z',text:labels[i]+' historic.'},{part,id:String(2*i+2),kind:'insertion',author:'A',date:'2026-06-01T09:30:00Z',text:labels[i]+' modernized.'},{part,id:'80',kind:'run-properties',author:'Reviewer',date:undefined,text:'Stable'},{part,id:'101',kind:'move-from',author:'Reviewer',date:'2026-09-27T00:00:00Z',text:'Moved text'},{part,id:'103',kind:'move-to',author:'Reviewer',date:'2026-09-27T00:00:00Z',text:'Moved text'}];}
// Independent source transformations, never resolver-derived comparison output.
function expected(s:State,part:string,a:'accept'|'reject'){let xml=s.baseline.text(part),left=from,right=to,content=runs;if(part===parts[0]&&s.encoding){left=fromAlias;right=toAlias;content=lifted;}expect(xml).toContain(left);expect(xml).toContain(right);xml=xml.replace(left,a==='accept'?'':content).replace(right,a==='accept'?content:'').replace(props,a==='accept'?'<w:r><w:rPr><w:b/></w:rPr><w:t>Stable</w:t></w:r>':'<w:r><w:rPr><w:i/></w:rPr><w:t>Stable</w:t></w:r>');if(part===parts[0]&&s.ordering)xml=xml.replace(from2,a==='accept'?'':runs).replace(to2,a==='accept'?runs:'');return xml.replace(/<w:(ins|del)\b([^>]*)>([^]*?)<\/w:\1>/g,(_m,kind:string,attrs:string,inner:string)=>{if((a==='accept')!==(kind==='ins'))return '';if(attrs.includes('xmlns:w14='))inner=inner.replaceAll('<w:r>',`<w:r xmlns:w14="${W14}">`);return inner.replaceAll('w:delText','w:t');});}
async function resolveSave(s:State,a:'accept'|'reject',selected:string[]){s.selected=selected;for(const part of selected)s.expected.set(part,expected(s,part,a));expect(s.output).not.toBe(s.source);s.receipt=resolveRevisions(s.p,a,{profile,parts:selected});await s.p.save(s.output);s.read=await OpcPackage.open(s.output);}
function exact(s:State){for(const p of s.selected){expect(s.read!.text(p)).toBe(s.expected.get(p)!);expect(s.read!.get(p)).toEqual(encode(s.expected.get(p)!,p===parts[0]?s.encoding:undefined));}}
async function source(s:State){expect(await Bun.file(s.source).bytes()).toEqual(Uint8Array.from(s.sourceBytes));}
async function custody(s:State){expect(s.read!.names()).toEqual(s.baseline.names());for(const p of s.baseline.names())if(!s.selected.includes(p))expect(s.read!.get(p)).toEqual(s.baseline.get(p));await source(s);}
function attempt(s:State,op:()=>unknown){try{s.returns.push(op());}catch(e){s.errors.push(e);}}
function refused(s:State,count:number,code='docx-revisions-unsupported'){expect(s.returns).toEqual([]);expect(s.errors).toHaveLength(count);for(const e of s.errors)expect(e).toMatchObject({code});}
export const bindings:StepBinding[]=[
 {pattern:/^a paired-move source archive with text and property revisions in seven reachable stories$/,run:c=>setup(c)},
 {pattern:/^the move-enabled profile inspects all selected stories$/,run:c=>{const s=state(c);s.report=inspectRevisions(s.p,{profile});}},
 {pattern:/^35 revisions have exact source-ordered kinds, wrapper IDs, metadata and text with no unsupported findings$/,run:c=>expect(state(c).report).toEqual({revisions:parts.flatMap(records),unsupported:[]})},
 {pattern:/^the move package and source archive remain unchanged$/,run:async c=>{const s=state(c);expect(s.p.toBytes()).toEqual(s.before);await source(s);}},
 {pattern:/^all paired-move stories are resolved by (accept|reject) and saved to a new path$/,run:(c,a)=>resolveSave(state(c),a as 'accept'|'reject',[...parts])},
 {pattern:/^the receipt counts 35 revisions and exactly seven changed story parts$/,run:c=>expect(state(c).receipt).toEqual({resolved:35,changedParts:parts})},
 {pattern:/^the reopened move XML and bytes equal the independent (accept|reject) expectations$/,run:c=>{const s=state(c);exact(s);expect(inspectRevisions(s.read!,{profile})).toEqual({revisions:[],unsupported:[]});}},
 {pattern:/^unselected member bytes and the move source archive remain unchanged$/,run:c=>custody(state(c))},
 {pattern:/^repeated move (accept|reject) resolution returns an exact archive no-op$/,run:(c,a)=>{const p=state(c).read!,bytes=p.toBytes();expect(resolveRevisions(p,a as 'accept'|'reject',{profile})).toEqual({resolved:0,changedParts:[]});expect(p.toBytes()).toEqual(bytes);}},
 {pattern:/^a paired-move source saved with an unmatched move name in nested footer2$/,run:c=>setup(c,{scope:true})},
 {pattern:/^only header1 paired revisions are resolved by (accept|reject) and saved to a new path$/,run:(c,a)=>resolveSave(state(c),a as 'accept'|'reject',[parts[1]!])},
 {pattern:/^exactly five header revisions resolve with exact expected XML while all unselected members retain their bytes$/,run:async c=>{const s=state(c);expect(s.receipt).toEqual({resolved:5,changedParts:[parts[1]!]});exact(s);await custody(s);}},
 {pattern:/^the body still exposes its five original revision records and footer2 reports unsupported moves$/,run:c=>{const r=inspectRevisions(state(c).read!,{profile});expect(r.revisions.filter(r=>r.part===parts[0])).toEqual(records(parts[0]!,0));expect(r.revisions.filter(r=>r.part===parts[1])).toEqual([]);expect(r.unsupported.length).toBeGreaterThan(0);expect(r.unsupported.every(f=>f.part===parts[3]&&f.kind==='move')).toBe(true);}},
 {pattern:/^the move source archive remains unchanged$/,run:c=>source(state(c))},
 {pattern:/^the earlier (text-only|text-and-run-properties) profile inspects and attempts both resolution actions$/,run:(c,p)=>{const s=state(c);s.report=inspectRevisions(s.p,{profile:p as RevisionProfile});for(const a of ['accept','reject'] as const)attempt(s,()=>resolveRevisions(s.p,a,{profile:p as RevisionProfile}));}},
 {pattern:/^move findings are explicit and both typed refusals return no receipt$/,run:c=>{const s=state(c);for(const part of parts)expect(s.report!.unsupported.some(f=>f.part===part&&f.kind==='move')).toBe(true);refused(s,2);}},
 {pattern:/^a paired-move source archive with later header defect (\S+)$/,run:(c,d)=>setup(c,{defect:d})},
 {pattern:/^both move-enabled resolution actions are attempted$/,run:c=>{const s=state(c);s.report=inspectRevisions(s.p,{profile});for(const a of ['accept','reject'] as const)attempt(s,()=>resolveRevisions(s.p,a,{profile}));}},
 {pattern:/^unsupported findings identify the defective selected story and both typed refusals return no receipt$/,run:c=>{const s=state(c),r=s.report!;expect(r.unsupported.some(f=>f.part===parts[1]&&f.kind===(s.defect==='text-id-collision'?'identifier':'move'))).toBe(true);if(s.defect==='cross-story')expect(r.unsupported.some(f=>f.part===parts[0]&&f.kind==='move')).toBe(true);else expect(r.unsupported.every(f=>f.part===parts[1])).toBe(true);refused(s,2);}},
 {pattern:/^a paired-move source with wrapper-local aliases and body encoding (UTF-8-BOM|UTF-16LE|UTF-16BE)$/,run:(c,e)=>setup(c,{encoding:e})},
 {pattern:/^only body paired revisions are resolved by (accept|reject) and saved to a new path$/,run:(c,a)=>resolveSave(state(c),a as 'accept'|'reject',[parts[0]!])},
 {pattern:/^exactly five body revisions resolve and every output byte matches the aliased (accept|reject) expectation and encoding marker$/,run:c=>{const s=state(c);expect(s.receipt).toEqual({resolved:5,changedParts:[parts[0]!]});exact(s);expect(inspectRevisions(s.read!,{profile}).revisions.filter(r=>r.part===parts[0])).toEqual([]);}},
 {pattern:/^a prior unrelated body edit is remembered after saving the move source$/,run:c=>{const s=state(c);s.p.set(parts[0]!,s.p.text(parts[0]!).replace('</w:body>','<w:p><w:r><w:t>Prior</w:t></w:r></w:p></w:body>'));s.before=s.p.toBytes();}},
 {pattern:/^rejecting paired moves fails at (later-write|serialization|post-write-validation)$/,run:(c,stage)=>{const s=state(c),p=s.p,set=p.set.bind(p),serialize=p.toBytes.bind(p);s.stage=stage;s.reached=false;if(stage==='serialization')p.toBytes=()=>{s.reached=true;throw Error('injected move serialize');};else p.set=(n,v)=>{set(n,v);if(n===parts[1]){s.reached=true;if(stage==='later-write')throw Error('injected move write');set(n,p.text(n).replace('</w:p>',from+to+'</w:p>'));}};try{attempt(s,()=>resolveRevisions(p,'reject',{profile}));}finally{p.set=set;p.toBytes=serialize;}}},
 {pattern:/^the move fault hook was reached and no successful receipt is returned$/,run:c=>{const s=state(c);expect(s.reached).toBe(true);expect(s.returns).toEqual([]);expect(s.errors).toHaveLength(1);if(s.stage==='post-write-validation')expect(s.errors[0]).toMatchObject({code:'docx-revisions-validation'});else expect(String(s.errors[0])).toContain('injected');}},
 {pattern:/^a fully resolved move package saved with guard (protection|external-settings|malformed-settings)$/,run:(c,g)=>setup(c,{guard:g})},
 {pattern:/^the move-enabled profile requests rejection again$/,run:c=>{const s=state(c);expect(inspectRevisions(s.p,{profile})).toEqual({revisions:[],unsupported:[]});attempt(s,()=>resolveRevisions(s.p,'reject',{profile}));}},
 {pattern:/^the exact (protection|external-settings|malformed-settings) refusal returns no receipt$/,run:c=>refused(state(c),1,'docx-revisions-protected')},
 {pattern:/^a paired-move source whose (from|to) range start has (missing-date|unqualified-date)$/,run:(c,side,date)=>setup(c,{side,date})},
 {pattern:/^move-enabled resolution (accept|reject) is attempted$/,run:(c,a)=>{const s=state(c);attempt(s,()=>resolveRevisions(s.p,a as 'accept'|'reject',{profile}));}},
 {pattern:/^a typed unsupported move refusal returns no receipt$/,run:c=>refused(state(c),1)},
 {pattern:/^a paired-move source with a second body pair in separate paragraphs and its destination before its source$/,run:c=>setup(c,{ordering:true})},
 {pattern:/^body move wrapper IDs are 101,103,203,201 in source order with the declared text and metadata$/,run:c=>{const s=state(c),expected=records(parts[0]!,0).filter(r=>r.kind.startsWith('move'));expected.push({...expected[1]!,id:'203'},{...expected[0]!,id:'201'});expect(s.report!.unsupported).toEqual([]);expect(s.report!.revisions.filter(r=>r.part===parts[0]&&r.kind.startsWith('move'))).toEqual(expected);}},
 {pattern:/^exactly seven body revisions resolve with independent expected XML and no body findings$/,run:c=>{const s=state(c);expect(s.receipt).toEqual({resolved:7,changedParts:[parts[0]!]});exact(s);const r=inspectRevisions(s.read!,{profile});expect(r.revisions.filter(r=>r.part===parts[0])).toEqual([]);expect(r.unsupported).toEqual([]);}},
];
