import {expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {OpcPackage,addRelationship} from '../../src/opc/index.ts';import {parseXml,elements,attribute} from '../../src/xml/index.ts';import {inspectRevisions,resolveRevisions,type Revision} from '../../src/docx/revisions.ts';import type {StepBinding} from '../../scripts/gherkin.ts';import {openRevisionFixture} from './revisions-docx.ts';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',W14='http://schemas.microsoft.com/office/word/2010/wordml',REL='http://schemas.openxmlformats.org/officeDocument/2006/relationships/',profile='text-and-run-properties' as const;
const parts=['word/document.xml','word/header1.xml','word/footer1.xml','word/footer2.xml','word/footnotes.xml','word/endnotes.xml','word/comments.xml'];const labels=['Body','Header','Footer','Nested footer','Footnote','Endnote','Comment'];
const current='<w:b/><w:color w:val="112233"/>',previous='<w:i/><w:color w:val="445566"/>',saved='<w:rPr>'+previous+'</w:rPr>',change='<w:rPrChange w:id="80" w:author="Editor" w:date="2026-09-27T00:00:00Z">'+saved+'</w:rPrChange>',properties='<w:rPr>'+current+change+'</w:rPr>',run='<w:r>'+properties+'<w:t>Stable</w:t></w:r>';
const dirs:string[]=[];export async function cleanupRevisionProperties(){await Promise.all(dirs.splice(0).map(d=>rm(d,{recursive:true,force:true})));}
type State={p:OpcPackage;baseline:OpcPackage;before:Uint8Array;sourceBytes:Uint8Array;source:string;output:string;selected:string[];read?:OpcPackage;receipt?:{resolved:number;changedParts:string[]};report?:ReturnType<typeof inspectRevisions>;errors?:unknown[];returned?:unknown[];reached?:boolean;stage?:string;guard?:string;encoding?:string;snapshot?:string;bodyProperties:string;restored:string;expected:Map<string,string>};const state=(c:Record<string,unknown>)=>c.propertyOutcome as State;
function encode(xml:string,mode?:string):Uint8Array{if(mode==='UTF-8-BOM')return new Uint8Array([239,187,191,...new TextEncoder().encode(xml)]);if(!mode)return new TextEncoder().encode(xml);const bytes=new Uint8Array(2+xml.length*2);bytes.set(mode==='UTF-16LE'?[255,254]:[254,255]);const v=new DataView(bytes.buffer);for(let i=0;i<xml.length;i++)v.setUint16(2+i*2,xml.charCodeAt(i),mode==='UTF-16LE');return bytes;}
const defect:(d:string,s:string)=>string=(d,s)=>{switch(d){case'missing-snapshot':return s.replace(saved,'');case'duplicate-snapshot':return s.replace(saved,saved+saved);case'duplicate-change':return s.replace(change,change+change.replace('80','81'));case'nested-change':return s.replace(previous,previous+change.replace('80','81'));case'wrong-parent':return s.replace(properties,properties.replace(change,'')+change);case'non-text-run':return s.replace('<w:t>Stable</w:t>','<w:drawing/>');case'unknown-property':return s.replace('<w:i/>','<w:unknown/>');case'duplicate-property':return s.replace('<w:i/>','<w:i/><w:i/>');case'decorated-property':return s.replace('<w:i/>','<w:i vendor="x"/>');case'invalid-value':return s.replace('<w:i/>','<w:i w:val="maybe"/>');case'duplicate-id':return s.replace('w:id="80"','w:id="3"');case'property-order':return s.replace(previous,'<w:color w:val="445566"/><w:i/>');case'mixed-content':return s.replace(previous,'UNOWNED'+previous);case'missing-author':return s.replace(' w:author="Editor"','');case'foreign-property':return s.replace('<w:i/>','<q:i xmlns:q="urn:foreign"/>');case'nested-insertion':return s.replace(run,'<w:ins w:id="90" w:author="Editor">'+run+'</w:ins>');default:throw Error('Unknown defect '+d);}};
async function remember(s:State){s.sourceBytes=s.p.toBytes();await Bun.write(s.source,s.sourceBytes);s.p=await OpcPackage.open(s.source);s.before=s.p.toBytes();s.baseline=await OpcPackage.open(s.sourceBytes);}
async function setup(c:Record<string,unknown>,options:{defect?:string;encoding?:string;snapshot?:string;guard?:string}={}){const p=await openRevisionFixture('all-stories');for(const part of parts)p.set(part,p.text(part).replace('</w:p>',run+'</w:p>'));const dir=await mkdtemp(join(tmpdir(),'revision-properties-'));dirs.push(dir);const s:State={p,baseline:p,before:new Uint8Array(),sourceBytes:new Uint8Array(),source:join(dir,'source.docx'),output:join(dir,'output.docx'),selected:[...parts],bodyProperties:properties,restored:saved,expected:new Map(),...options};
 if(options.defect){const xml=p.text(parts[1]!),changed=defect(options.defect,xml);expect(changed).not.toBe(xml);p.set(parts[1]!,changed);}
 if(options.encoding){s.bodyProperties=`<w:rPr xmlns:z="${W}">${current}<w:rPrChange xmlns:q="${W}" w:id="80" w:author="Editor"><q:rPr><q:i/><z:color z:val='445566'/></q:rPr></w:rPrChange></w:rPr>`;s.restored=`<q:rPr xmlns:z="${W}" xmlns:q="${W}"><q:i/><z:color z:val='445566'/></q:rPr>`;let xml=p.text(parts[0]!).replace(properties,s.bodyProperties);if(options.encoding!=='UTF-8-BOM')xml=xml.replace('encoding="UTF-8"','encoding="UTF-16"');p.set(parts[0]!,encode(xml,options.encoding));}
 if(options.snapshot){const prior=options.snapshot==='empty'?'<w:rPr/>':`<w:rPr xmlns:q="${W}"><q:i/></w:rPr>`;s.bodyProperties='<w:rPr>'+current+`<w:rPrChange xmlns:q="urn:outer" w:id="80" w:author="Editor">${prior}</w:rPrChange></w:rPr>`;s.restored=options.snapshot==='empty'?'<w:rPr xmlns:q="urn:outer"/>':prior;p.set(parts[0]!,p.text(parts[0]!).replace(properties,s.bodyProperties));}
 if(options.guard){resolveRevisions(p,'accept',{profile});if(options.guard==='external-settings')addRelationship(p,p.mainPart(),REL+'settings','https://example.invalid/settings',{external:true});else if(options.guard!=='invalid-profile'){p.set('word/settings.xml',options.guard==='protection'?`<w:settings xmlns:w="${W}"><w:documentProtection w:enforcement="1"/></w:settings>`:`<w:wrong xmlns:w="${W}"/>`);addRelationship(p,p.mainPart(),REL+'settings','settings.xml');}}
 await remember(s);c.propertyOutcome=s;
}
async function unchangedSource(s:State){expect(await Bun.file(s.source).bytes()).toEqual(Uint8Array.from(s.sourceBytes));}
// Expected bytes are derived solely from the specified source fixture transformations,
// never by invoking either resolver on a comparison package.
function expected(s:State,part:string,action:string):string{let xml=s.baseline.text(part);if(part===parts[0]&&s.bodyProperties!==properties){expect(action).toBe('reject');expect(xml).toContain(s.bodyProperties);xml=xml.replace(s.bodyProperties,s.restored);}else{expect(xml).toContain(properties);xml=xml.replace(properties,action==='accept'?'<w:rPr>'+current+'</w:rPr>':saved);}
 return xml.replace(/<w:(ins|del)\b([^>]*)>([^]*?)<\/w:\1>/g,(_m,kind:string,attrs:string,inner:string)=>{if((action==='accept')!==(kind==='ins'))return '';let content=inner;if(attrs.includes('xmlns:w14='))content=content.replaceAll('<w:r>',`<w:r xmlns:w14="${W14}">`);if(kind==='del')content=content.replaceAll('w:delText','w:t');return content;});}
async function resolveSave(s:State,action:'accept'|'reject',selected:string[]){s.selected=selected;for(const part of selected)s.expected.set(part,expected(s,part,action));s.receipt=resolveRevisions(s.p,action,{profile,parts:selected});expect(s.output).not.toBe(s.source);await s.p.save(s.output);s.read=await OpcPackage.open(s.output);}
function exact(s:State){for(const part of s.selected){expect(s.read!.text(part)).toBe(s.expected.get(part)!);expect(s.read!.get(part)).toEqual(encode(s.expected.get(part)!,part===parts[0]?s.encoding:undefined));}}
async function custody(s:State){expect(s.read!.names()).toEqual(s.baseline.names());for(const n of s.baseline.names())if(!s.selected.includes(n))expect(s.read!.get(n)).toEqual(s.baseline.get(n));await unchangedSource(s);}
function attempt(s:State,op:()=>unknown){try{s.returned!.push(op());}catch(e){s.errors!.push(e);}}
function both(s:State){s.errors=[];s.returned=[];for(const a of ['accept','reject'] as const)attempt(s,()=>resolveRevisions(s.p,a,{profile}));}
export const bindings:StepBinding[]=[
 {pattern:/^the all-stories revision package with one direct-run property snapshot per story saved as a source archive$/,run:c=>setup(c)},
 {pattern:/^the text-and-run-properties profile inspects all stories$/,run:c=>{const s=state(c);s.report=inspectRevisions(s.p,{profile});}},
 {pattern:/^21 revisions have exact source-ordered IDs, kinds, authors, dates and text with no unsupported findings$/,run:c=>{const wanted:Revision[]=parts.flatMap<Revision>((part,i)=>[{part,id:String(2*i+1),kind:'deletion',author:'A',date:'2026-06-01T09:30:00Z',text:labels[i]+' historic.'},{part,id:String(2*i+2),kind:'insertion',author:'A',date:'2026-06-01T09:30:00Z',text:labels[i]+' modernized.'},{part,id:'80',kind:'run-properties',author:'Editor',date:'2026-09-27T00:00:00Z',text:'Stable'}]);expect(state(c).report).toEqual({revisions:wanted,unsupported:[]});}},
 {pattern:/^revision inspection leaves the package and source archive unchanged$/,run:async c=>{const s=state(c);expect(s.p.toBytes()).toEqual(s.before);await unchangedSource(s);}},
 {pattern:/^all selected text and run-property revisions are resolved by (accept|reject) and saved to a new path$/,run:(c,a)=>resolveSave(state(c),a as 'accept'|'reject',[...parts])},
 {pattern:/^the receipt resolves 21 revisions in all seven story parts$/,run:c=>expect(state(c).receipt).toEqual({resolved:21,changedParts:parts})},
 {pattern:/^reopened story XML equals the exact (accept|reject) text and complete property expectations$/,run:(c,a)=>{const s=state(c);exact(s);expect(inspectRevisions(s.read!,{profile})).toEqual({revisions:[],unsupported:[]});for(const [i,part]of parts.entries()){const text=elements(parseXml(s.read!.text(part)),'t',W).map(n=>n.text).join('');expect(text).toBe(labels[i]+(a==='accept'?' modernized.':' historic.')+'Stable');}}},
 {pattern:/^every other member and the source archive retain their original bytes$/,run:c=>custody(state(c))},
 {pattern:/^repeated (accept|reject) resolution returns zero changes and keeps the exact current archive$/,run:(c,a)=>{const p=state(c).read!,bytes=p.toBytes();expect(resolveRevisions(p,a as 'accept'|'reject',{profile})).toEqual({resolved:0,changedParts:[]});expect(p.toBytes()).toEqual(bytes);}},
 {pattern:/^an all-stories revision source saved with an unsupported body snapshot outside the selected header$/,run:async c=>{await setup(c);const s=state(c);s.p.set(parts[0]!,s.p.text(parts[0]!).replace('<w:i/>','<w:unknown/>'));await remember(s);}},
 {pattern:/^only header1 revisions are resolved by (accept|reject) and saved to a new path$/,run:(c,a)=>resolveSave(state(c),a as 'accept'|'reject',[parts[1]!])},
 {pattern:/^the receipt resolves three header revisions and all unselected member bytes are unchanged$/,run:async c=>{const s=state(c);expect(s.receipt).toEqual({resolved:3,changedParts:[parts[1]!]});await custody(s);}},
 {pattern:/^the header XML equals the exact (accept|reject) expectation while 17 supported revisions plus one unsupported body format finding remain visible$/,run:c=>{const s=state(c);exact(s);const r=inspectRevisions(s.read!,{profile});expect(r.revisions).toHaveLength(17);expect(r.unsupported).toHaveLength(1);expect(r.unsupported[0]).toMatchObject({part:parts[0],kind:'format'});expect(r.revisions.some(r=>r.part===parts[1])).toBe(false);}},
 {pattern:/^the source archive retains its original bytes$/,run:c=>unchangedSource(state(c))},
 {pattern:/^the default text-only profile inspects and attempts resolution$/,run:c=>{const s=state(c);s.report=inspectRevisions(s.p);s.errors=[];s.returned=[];for(const a of ['accept','reject'] as const)attempt(s,()=>resolveRevisions(s.p,a));}},
 {pattern:/^inspection returns 14 text revisions and seven format findings and both actions refuse without a receipt$/,run:c=>{const s=state(c);expect(s.report!.revisions).toHaveLength(14);expect(s.report!.unsupported.map(f=>[f.part,f.kind])).toEqual(parts.map(p=>[p,'format']));expect(s.errors).toHaveLength(2);for(const e of s.errors!)expect(e).toMatchObject({code:'docx-revisions-unsupported'});expect(s.returned).toEqual([]);}},
 {pattern:/^the all-stories revision package with a later header snapshot defect (\S+)$/,run:(c,d)=>setup(c,{defect:d})},
 {pattern:/^both property-profile resolution actions are attempted$/,run:c=>{const s=state(c);s.report=inspectRevisions(s.p,{profile});both(s);}},
 {pattern:/^unsupported findings identify the header and both typed refusals return no receipt$/,run:c=>{const s=state(c);expect(s.report!.unsupported.length).toBeGreaterThan(0);expect(s.report!.unsupported.every(f=>f.part===parts[1])).toBe(true);expect(s.errors).toHaveLength(2);for(const e of s.errors!)expect(e).toMatchObject({code:'docx-revisions-unsupported'});expect(s.returned).toEqual([]);}},
 {pattern:/^the all-stories revision package with an aliased (UTF-8-BOM|UTF-16LE|UTF-16BE) body property snapshot$/,run:(c,e)=>setup(c,{encoding:e})},
 {pattern:/^only body revisions are rejected and saved to a new path$/,run:c=>resolveSave(state(c),'reject',[parts[0]!])},
 {pattern:/^the receipt resolves three body revisions and the exact expected aliased snapshot survives with its encoding marker$/,run:c=>{const s=state(c);expect(s.receipt).toEqual({resolved:3,changedParts:[parts[0]!]});exact(s);const r=elements(parseXml(s.read!.text(parts[0]!)),'rPr',W).find(r=>r.name==='q:rPr')!;expect(r.children.map(c=>[c.namespaceURI,c.localName])).toEqual([[W,'i'],[W,'color']]);expect(attribute(r.children[1]!,'val',W)).toBe('445566');}},
 {pattern:/^a prior unrelated main-part edit is retained in memory$/,run:c=>{const s=state(c);s.p.set(parts[0]!,s.p.text(parts[0]!).replace('</w:body>','<w:p><w:r><w:t>Prior edit</w:t></w:r></w:p></w:body>'));s.before=s.p.toBytes();}},
 {pattern:/^property-profile rejection fails after (later-write|serialization|post-write-validation)$/,run:(c,stage)=>{const s=state(c),p=s.p,set=p.set.bind(p),serialize=p.toBytes.bind(p);s.stage=stage;s.reached=false;s.errors=[];s.returned=[];if(stage==='serialization')p.toBytes=()=>{s.reached=true;throw Error('injected serialization');};else p.set=(n,v)=>{set(n,v);if(n===parts[1]){s.reached=true;if(stage==='later-write')throw Error('injected later write');set(n,p.text(n).replace(saved,properties));}};try{attempt(s,()=>resolveRevisions(p,'reject',{profile}));}finally{p.set=set;p.toBytes=serialize;}}},
 {pattern:/^the injected hook was reached and no successful receipt is returned$/,run:c=>{const s=state(c);expect(s.reached).toBe(true);expect(s.returned).toEqual([]);expect(s.errors).toHaveLength(1);if(s.stage==='post-write-validation')expect(s.errors![0]).toMatchObject({code:'docx-revisions-validation'});else expect(String(s.errors![0])).toContain('injected');}},
 {pattern:/^the all-stories revision package with a (empty|shadowed-alias) previous body property snapshot$/,run:(c,s)=>setup(c,{snapshot:s})},
 {pattern:/^the body properties equal only the (empty|shadowed-alias) previous set and the exact expected XML$/,run:(c,snapshot)=>{const s=state(c);expect(s.receipt).toEqual({resolved:3,changedParts:[parts[0]!]});exact(s);const run=elements(parseXml(s.read!.text(parts[0]!)),'r',W).find(r=>r.children.some(t=>t.text==='Stable'))!,pr=run.children[0]!;expect(pr.localName).toBe('rPr');expect(pr.children.map(c=>[c.namespaceURI,c.localName])).toEqual(snapshot==='empty'?[]:[[W,'i']]);}},
 {pattern:/^a fully resolved revision package with guard (\S+)$/,run:(c,g)=>setup(c,{guard:g})},
 {pattern:/^the extended revision profile is requested again$/,run:c=>{const s=state(c);expect(inspectRevisions(s.p,{profile})).toEqual({revisions:[],unsupported:[]});s.errors=[];s.returned=[];attempt(s,()=>resolveRevisions(s.p,'reject',{profile:s.guard==='invalid-profile'?'unknown' as typeof profile:profile}));}},
 {pattern:/^a typed (protection|external-settings|malformed-settings|invalid-profile) refusal returns no receipt$/,run:(c,g)=>{const s=state(c);expect(s.returned).toEqual([]);expect(s.errors).toHaveLength(1);expect(s.errors![0]).toMatchObject({code:g==='invalid-profile'?'docx-revisions-invalid-profile':'docx-revisions-protected'});}},
];
