import {expect} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {Document,OpcPackage} from '../../src/index.ts';import {type Table,type TableCell,type Paragraph} from '../../src/docx/index.ts';
import {addPart,addRelationship} from '../../src/opc/index.ts';
import {parseXml,elements,attribute,type XmlElement} from '../../src/xml/index.ts';
import type {StepBinding} from '../../scripts/gherkin.ts';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',SETTINGS='http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings';
const roots:string[]=[];export async function cleanupTableMerging(){await Promise.all(roots.splice(0).map(p=>rm(p,{recursive:true,force:true})));}
type State={d:Document;source:string;output:string;before:Uint8Array;parts:ReadonlyMap<string,Uint8Array>;xml:string;table:Table;cell:TableCell;paragraph:Paragraph;range:[number,number,number];errors:unknown[];reopened?:Document;current?:Table;rangeError?:boolean;encoding?:string};
const state=(c:Record<string,unknown>)=>c.merge as State;
const pkg=(d:Document)=>(d as unknown as {opcPackage:OpcPackage}).opcPackage;
const word=(n:XmlElement,name:string)=>n.namespaceURI===W&&n.localName===name;
function structure(xml:string){const tree=parseXml(xml),table=elements(tree,'tbl',W)[0]!,rows=table.children.filter(n=>word(n,'tr'));return {tree,table,rows,cells:rows.map(r=>r.children.filter(n=>word(n,'tc'))),grid:table.children.find(n=>word(n,'tblGrid'))!};}
function slice(xml:string,n:XmlElement){return xml.slice(n.start,n.end);}
function replaceCell(p:OpcPackage,r:number,c:number,change:(s:string)=>string){const xml=p.text(p.mainPart()),n=structure(xml).cells[r]![c]!;p.set(p.mainPart(),xml.slice(0,n.start)+change(slice(xml,n))+xml.slice(n.end));}
async function setup(c:Record<string,unknown>,change?:(p:OpcPackage)=>void){const d=Document.create();d.addParagraph('Before');d.addTable(2,4);d.tables[0]!.cell(0,0).text='Keep & <text>';d.tables[0]!.cell(1,3).text='Tail';d.tables[0]!.cell(0,0).setProperties({shading:'ABCDEF',verticalAlign:'center'});d.addParagraph('After');const p=await OpcPackage.open(d.package.toBytes());addPart(p,'customXml/opaque.bin',new Uint8Array([0,255,42]),'application/octet-stream');change?.(p);const root=await mkdtemp(join(tmpdir(),'merge-outcomes-'));roots.push(root);const source=join(root,'source.docx'),output=join(root,'output.docx'),before=p.toBytes();await Bun.write(source,before);const loaded=await Document.open(source);c.merge={d:loaded,source,output,before,parts:loaded.package.parts,xml:p.text(p.mainPart()),table:loaded.tables[0]!,cell:loaded.tables[0]!.cell(0,0),paragraph:loaded.paragraphs[0]!,range:[0,0,2],errors:[]} satisfies State;}
async function save(s:State,row=0,first=0,last=2){s.range=[row,first,last];s.current=s.table.mergeRowCells(row,first,last);await s.d.save(s.output);s.reopened=await Document.open(s.output);}
function capture(s:State,fn:()=>unknown){try{fn();s.errors.push(null);}catch(e){s.errors.push(e);}}
function ownerWithoutMerge(xml:string,n:XmlElement){const pr=n.children.find(c=>word(c,'tcPr'))!;const remove=pr.children.filter(c=>word(c,'tcW')||word(c,'gridSpan'));const raw=slice(xml,n);let result=raw;for(const c of remove.sort((a,b)=>b.start-a.start))result=result.slice(0,c.start-n.start)+result.slice(c.end-n.start);return result;}
export const bindings:StepBinding[]=[
 {pattern:/^a saved Word horizontal merge source with a two by four table$/,run:async c=>setup(c)},
 {pattern:/^row (\d+) columns (\d+) through (\d+) are merged and saved to a new path$/,run:async(c,r,a,b)=>save(state(c),Number(r),Number(a),Number(b))},
 {pattern:/^row zero columns zero through two are merged and saved to a new path$/,run:async c=>save(state(c))},
 {pattern:/^the reopened table has two rows and four grid columns with a gridSpan of (\d+) at row (\d+) column (\d+)$/,run:(c,span,row,col)=>{const s=state(c),d=s.reopened!,x=structure(pkg(d).text(pkg(d).mainPart()));expect(d.tables).toHaveLength(1);expect(d.tables[0]!.rows).toBe(2);expect(d.tables[0]!.columns).toBe(4);expect(x.grid.children).toHaveLength(4);const cell=x.cells[Number(row)]![Number(col)]!,flags=cell.children[0]!.children.filter(n=>word(n,'gridSpan'));expect(flags).toHaveLength(1);expect(attribute(flags[0]!,'val',W)).toBe(span!);}},
 {pattern:/^the merged width is (\d+) twips and that row has (\d+) physical cells$/,run:(c,width,count)=>{const s=state(c),x=structure(pkg(s.reopened!).text(pkg(s.reopened!).mainPart())),[r,f]=s.range;expect(x.cells[r]).toHaveLength(Number(count));expect(attribute(x.cells[r]![f]!.children[0]!.children.find(n=>word(n,'tcW'))!,'w',W)).toBe(width!);}},
 {pattern:/^the reopened retained paragraph sequence matches the source minus only the absorbed empty paragraphs$/,run:c=>{const s=state(c),[r,a,b]=s.range,source=structure(s.xml),removed=new Set(source.cells[r]!.slice(a+1,b+1).flatMap(n=>n.children.filter(n=>word(n,'p')).map(n=>n.start))),paragraphs=elements(source.tree,'p',W).filter(n=>!removed.has(n.start));expect(s.reopened!.paragraphs.map(p=>p.text)).toEqual(paragraphs.map(p=>source.tree.elements.filter(n=>word(n,'t')&&n.start>p.start&&n.end<p.end).map(n=>n.text).join('')));}},
 {pattern:/^the grid, unselected cells and rows, unrelated members and source archive are unchanged$/,run:async c=>{const s=state(c),d=s.reopened!,after=pkg(d).text(pkg(d).mainPart()),old=structure(s.xml),next=structure(after),[r,a,b]=s.range;expect(slice(after,next.grid)).toBe(slice(s.xml,old.grid));for(let row=0;row<2;row++)if(row!==r)expect(slice(after,next.rows[row]!)).toBe(slice(s.xml,old.rows[row]!));for(let col=0;col<4;col++)if(col<a||col>b){const index=col>b?col-(b-a):col;expect(slice(after,next.cells[r]![index]!)).toBe(slice(s.xml,old.cells[r]![col]!));}expect(ownerWithoutMerge(after,next.cells[r]![a]!)).toBe(ownerWithoutMerge(s.xml,old.cells[r]![a]!));expect([...d.package.parts.keys()]).toEqual([...s.parts.keys()]);for(const[n,bytes]of s.parts)if(n!==pkg(d).mainPart())expect(d.package.get(n)).toEqual(bytes);expect(await Bun.file(s.source).bytes()).toEqual(Uint8Array.from(s.before));}},
 {pattern:/^a saved Word horizontal merge source whose absorbed cell has (text|space-text|cell-shading|paragraph-format|empty-run|lexical-comment)$/,run:async(c,kind)=>setup(c,p=>replaceCell(p,0,1,raw=>{if(kind==='text'||kind==='space-text')return raw.replace(/<w:p\b[^>]*\/>/,`<w:p><w:r><w:t xml:space="preserve">${kind==='text'?'Do not lose me':' '}</w:t></w:r></w:p>`);if(kind==='cell-shading')return raw.replace('</w:tcPr>','<w:shd w:val="clear" w:fill="ABCDEF"/></w:tcPr>');if(kind==='paragraph-format')return raw.replace(/<w:p\b[^>]*\/>/,'<w:p><w:pPr><w:keepNext/></w:pPr></w:p>');if(kind==='empty-run')return raw.replace(/<w:p\b[^>]*\/>/,'<w:p><w:r><w:t/></w:r></w:p>');return raw.replace('<w:tcPr>','<!--retain--><w:tcPr>');}))},
 {pattern:/^row zero columns zero through two are merged$/,run:c=>{const s=state(c);capture(s,()=>s.table.mergeRowCells(0,0,2));}},
 {pattern:/^the merge refuses and the archive and held source handles are unchanged$/,run:async c=>{const s=state(c);expect(s.errors).toHaveLength(1);expect(s.errors[0]).toBeInstanceOf(s.rangeError?RangeError:Error);expect(s.d.package.toBytes()).toEqual(s.before);expect(s.table.rows).toBe(2);expect(s.table.columns).toBe(4);expect(s.cell.text).toBe('Keep & <text>');expect(s.paragraph.text).toBe('Before');expect(await Bun.file(s.source).bytes()).toEqual(Uint8Array.from(s.before));expect(await Bun.file(s.output).exists()).toBe(false);}},
 {pattern:/^a saved Word horizontal merge source with (existing-vertical|missing-grid|width-mismatch|nested-unselected|protected|external-settings)$/,run:async(c,kind)=>setup(c,p=>{if(kind==='existing-vertical')replaceCell(p,1,0,s=>s.replace('<w:tcPr>','<w:tcPr><w:vMerge w:val="restart"/>'));if(kind==='missing-grid')p.set(p.mainPart(),p.text(p.mainPart()).replace(/<w:tblGrid>[\s\S]*?<\/w:tblGrid>/,''));if(kind==='width-mismatch')replaceCell(p,1,0,s=>s.replace('w:w="2160"','w:w="100"'));if(kind==='nested-unselected')replaceCell(p,1,3,s=>s.replace('<w:tcPr>','<w:tbl/><w:tcPr>'));if(kind==='protected'){addPart(p,'word/settings.xml',`<w:settings xmlns:w="${W}"><w:documentProtection w:enforcement="1"/></w:settings>`,'application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml');addRelationship(p,p.mainPart(),SETTINGS,'settings.xml');}if(kind==='external-settings')addRelationship(p,p.mainPart(),SETTINGS,'https://example.invalid/settings',{external:true});})},
 {pattern:/^the merge is requested with (singleton|reversed|outside|fractional) coordinates$/,run:(c,kind)=>{const s=state(c),args:Record<string,[number,number,number]>={singleton:[0,0,0],reversed:[0,2,1],outside:[0,0,4],fractional:[0,0.5,2]};s.rangeError=true;capture(s,()=>s.table.mergeRowCells(...args[kind!]!));}},
 {pattern:/^the merge fails after (part-write|serialization)$/,run:(c,stage)=>{const s=state(c),p=pkg(s.d),set=p.set.bind(p),serialize=p.toBytes.bind(p);let reached=false;if(stage==='part-write')p.set=(n,v)=>{set(n,v);if(n===p.mainPart()){reached=true;throw Error('injected part-write');}};else p.toBytes=()=>{reached=true;throw Error('injected serialization');};try{capture(s,()=>s.table.mergeRowCells(0,0,2));}finally{p.set=set;p.toBytes=serialize;}expect(reached).toBe(true);expect(String(s.errors[0])).toContain('injected');}},
 {pattern:/^a saved Word horizontal merge source encoded as (UTF-8-BOM|UTF-16LE|UTF-16BE)$/,run:async(c,encoding)=>{await setup(c,p=>{let xml=p.text(p.mainPart());if(encoding==='UTF-8-BOM')p.set(p.mainPart(),new Uint8Array([239,187,191,...new TextEncoder().encode(xml)]));else{xml=xml.replaceAll('w:','q:').replaceAll('xmlns:w=','xmlns:q=').replace('UTF-8','UTF-16').replace('<q:document ','<q:document xmlns:w="urn:foreign" ');const bytes=new Uint8Array(2+xml.length*2),little=encoding==='UTF-16LE';bytes.set(little?[255,254]:[254,255]);const view=new DataView(bytes.buffer);for(let i=0;i<xml.length;i++)view.setUint16(2+i*2,xml.charCodeAt(i),little);p.set(p.mainPart(),bytes);}});state(c).encoding=encoding;}},
 {pattern:/^the reopened encoding marker and namespace meaning match the source$/,run:c=>{const s=state(c),d=s.reopened!,n=pkg(d).mainPart(),length=s.encoding==='UTF-8-BOM'?3:2;expect(d.package.get(n)!.slice(0,length)).toEqual(s.parts.get(n)!.slice(0,length));const tree=parseXml(pkg(d).text(n));expect(tree.root.namespaceURI).toBe(W);expect(elements(tree,'gridSpan',W).map(n=>attribute(n,'val',W))).toEqual(['3']);if(s.encoding!=='UTF-8-BOM')expect(tree.root.attributes['xmlns:w']).toBe('urn:foreign');}},
 {pattern:/^row zero columns zero through two are merged in the editing session$/,run:c=>{const s=state(c);s.current=s.table.mergeRowCells(0,0,2);}},
 {pattern:/^(old-handles|merged-cells) operations refuse without changing the merged archive$/,run:(c,kind)=>{const s=state(c),before=s.d.package.toBytes(),ops=kind==='old-handles'?[()=>s.table.rows,()=>s.cell.text,()=>s.paragraph.text]:[()=>s.current!.cell(0,0),()=>s.current!.cell(0,1),()=>s.current!.cell(0,2),()=>s.current!.insertRow(0),()=>s.current!.mergeRowCells(1,0,1)];for(const op of ops){expect(op).toThrow();expect(s.d.package.toBytes()).toEqual(before);}}},
 {pattern:/^the current unmerged tail cell still reads Tail$/,run:c=>expect(state(c).current!.cell(1,3).text).toBe('Tail')},
];
