import {expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {Document,OpcPackage,type TemplateInspection} from '../../src/index.ts';import type {Paragraph,Table} from '../../src/docx/index.ts';import {addPart,addRelationship} from '../../src/opc/index.ts';import {parseXml,elements} from '../../src/xml/index.ts';import type {StepBinding} from '../../scripts/gherkin.ts';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',SETTINGS='http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings';const roots:string[]=[];export async function cleanupTemplateInventory(){await Promise.all(roots.splice(0).map(p=>rm(p,{recursive:true,force:true})));}
const pkg=(d:Document)=>(d as unknown as {opcPackage:OpcPackage}).opcPackage;
type State={d:Document;source:string;before:Uint8Array;live:Uint8Array;paragraph?:Paragraph;table?:Table;report?:TemplateInspection;prior?:TemplateInspection;error?:unknown;returned?:boolean;marker?:number[]};const state=(c:Record<string,unknown>)=>c.templateInventory as State;
async function setup(c:Record<string,unknown>,kind='sample',change?:(p:OpcPackage)=>void){const d=Document.create();if(kind==='sample'){d.addParagraph('Statement for <Customer>').setProperties({outlineLevel:0});d.addParagraph('Use <Project> and [TBD].');d.addTable(2,2);const t=d.tables[0]!;for(const[r,col,text]of [[0,0,'Role'],[0,1,'Hours'],[1,0,'<Role>'],[1,1,'40']] as const)t.cell(r,col).text=text;d.addParagraph('Delivery').setProperties({outlineLevel:1});d.addParagraph('No placeholder');}else if(kind==='plain')d.addParagraph('Simple text');else if(kind==='tokens'){d.addParagraph('😀 <Cus').appendRun('tomer> <Customer> <<nested>> <> < > [TBD]');d.addParagraph('<unfinished');d.addParagraph('ending>');}const p=await OpcPackage.open(d.package.toBytes());addPart(p,'customXml/opaque.bin',new Uint8Array([0,255,42]),'application/octet-stream');change?.(p);const dir=await mkdtemp(join(tmpdir(),'template-inventory-'));roots.push(dir);const source=join(dir,'source.docx'),before=p.toBytes();await Bun.write(source,before);const read=await Document.open(source);c.templateInventory={d:read,source,before,live:before,paragraph:read.paragraphs[0],table:read.tables[0]} satisfies State;}
function expected():TemplateInspection{const texts=['Statement for <Customer>','Use <Project> and [TBD].','Role','Hours','<Role>','40','Delivery','No placeholder'],body=[0,1,2,2,2,2,3,4];return {scope:'main-body-and-tables',counts:{paragraphs:8,sections:2,tables:1,placeholders:3},paragraphs:texts.map((text,index)=>({index,bodyIndex:body[index]!,text,styleId:null,outlineLevel:index===0?0:index===6?1:null,...(index>=2&&index<=5?{table:{index:0,row:Math.floor((index-2)/2),column:(index-2)%2,paragraph:0}}:{})})),sections:[{paragraphIndex:0,bodyIndex:0,text:texts[0]!,level:1},{paragraphIndex:6,bodyIndex:3,text:'Delivery',level:2}],tables:[{index:0,bodyIndex:2,rows:2,columns:2,cells:[['Role','Hours'],['<Role>','40']]}],placeholders:[{paragraphIndex:0,bodyIndex:0,start:14,end:24,text:'<Customer>',name:'Customer'},{paragraphIndex:1,bodyIndex:1,start:4,end:13,text:'<Project>',name:'Project'},{paragraphIndex:4,bodyIndex:2,start:0,end:6,text:'<Role>',name:'Role'}]};}
async function custody(s:State){expect(await Bun.file(s.source).bytes()).toEqual(Uint8Array.from(s.before));expect(s.d.package.toBytes()).toEqual(s.live);}
function replaceCell(p:OpcPackage,index:number,change:(s:string)=>string){const xml=p.text(p.mainPart()),n=elements(parseXml(xml),'tc',W)[index]!;p.set(p.mainPart(),xml.slice(0,n.start)+change(xml.slice(n.start,n.end))+xml.slice(n.end));}
function frozen(value:unknown){if(value&&typeof value==='object'){expect(Object.isFrozen(value)).toBe(true);for(const v of Object.values(value))frozen(v);}}
export const bindings:StepBinding[]=[
 {pattern:/^a saved concrete Word inventory sample$/,run:async c=>setup(c)},
 {pattern:/^the concrete template reader inspects the saved document$/,run:c=>{const s=state(c);s.report=s.d.inspectTemplate();}},
 {pattern:/^the inventory scope is main-body-and-tables with counts 8 paragraphs, 2 sections, 1 table and 3 placeholders$/,run:c=>{const r=state(c).report!;expect(r.scope).toBe('main-body-and-tables');expect(r.counts).toEqual({paragraphs:8,sections:2,tables:1,placeholders:3});}},
 {pattern:/^every paragraphIndex, body location, table coordinate, section level, table value and placeholder offset equals the concrete sample expectation$/,run:c=>expect(state(c).report).toEqual(expected())},
 {pattern:/^the source archive and held paragraph and table handles are unchanged$/,run:async c=>{const s=state(c);await custody(s);expect(s.paragraph!.text).toBe('Statement for <Customer>');expect(s.table!.rows).toBe(2);expect(s.table!.cell(1,1).text).toBe('40');}},
 {pattern:/^the source archive is unchanged$/,run:async c=>custody(state(c))},
 {pattern:/^a saved (empty|plain) Word inventory source$/,run:async(c,kind)=>setup(c,kind)},
 {pattern:/^the (empty|plain) inventory has exact empty collections and literal paragraph values$/,run:(c,kind)=>expect(state(c).report).toEqual({scope:'main-body-and-tables',counts:{paragraphs:kind==='plain'?1:0,sections:0,tables:0,placeholders:0},paragraphs:kind==='plain'?[{index:0,bodyIndex:0,text:'Simple text',styleId:null,outlineLevel:null}]:[],sections:[],tables:[],placeholders:[]})},
 {pattern:/^a saved Word inventory source with split-run Unicode placeholders and paragraph boundaries$/,run:async c=>setup(c,'tokens')},
 {pattern:/^its two placeholder occurrences have names Customer and offsets 3 through 13 and 14 through 24 in paragraphIndex 0$/,run:c=>expect(state(c).report!.placeholders).toEqual([{paragraphIndex:0,bodyIndex:0,start:3,end:13,text:'<Customer>',name:'Customer'},{paragraphIndex:0,bodyIndex:0,start:14,end:24,text:'<Customer>',name:'Customer'}])},
 {pattern:/^no nested, blank, bracketed or cross-paragraph placeholder is reported$/,run:c=>{expect(state(c).report!.counts.placeholders).toBe(2);expect(state(c).report!.placeholders.every(p=>p.paragraphIndex===0&&p.name==='Customer')).toBe(true);}},
 {pattern:/^a saved concrete Word inventory sample with (late-field|body-control|nested-cell|merged-cell|row-before|row-after|width-mismatch|missing-width|grid-comment|stale-wrapper)$/,run:async(c,defect)=>{await setup(c,'sample',p=>{let xml=p.text(p.mainPart());if(defect==='late-field')xml=xml.replace('No placeholder','No placeholder</w:t><w:instrText>DATE</w:instrText><w:t>');if(defect==='body-control')xml=xml.replace('<w:body>','<w:body><w:sdt><w:sdtContent><w:p/></w:sdtContent></w:sdt>');if(defect==='nested-cell')xml=xml.replace('<w:tcPr>','<w:tbl/><w:tcPr>');if(defect==='merged-cell')xml=xml.replace('<w:tcPr>','<w:tcPr><w:vMerge/>');if(defect==='row-before'||defect==='row-after'){const at=xml.lastIndexOf('<w:tr>');xml=xml.slice(0,at)+xml.slice(at).replace('<w:tr>',`<w:tr><w:trPr><w:${defect==='row-before'?'gridBefore':'gridAfter'} w:val="1"/></w:trPr>`);}if(defect==='grid-comment')xml=xml.replace('<w:tblGrid>','<w:tblGrid><!--retain-->');p.set(p.mainPart(),xml);if(defect==='width-mismatch')replaceCell(p,2,s=>s.replace('w:w="4320"','w:w="100"'));if(defect==='missing-width')replaceCell(p,2,s=>s.replace(/<w:tcW[^>]*\/>/,''));});if(defect==='stale-wrapper'){const s=state(c),p=pkg(s.d);p.set(p.mainPart(),p.text(p.mainPart()).replace('No placeholder','External'));s.live=p.toBytes();}}},
 {pattern:/^the concrete template reader attempts inspection$/,run:c=>{const s=state(c);s.returned=false;try{s.report=s.d.inspectTemplate();s.returned=true;}catch(e){s.error=e;}}},
 {pattern:/^inspection refuses without returning an inventory$/,run:c=>{const s=state(c);expect(s.returned).toBe(false);expect(s.report).toBeUndefined();expect(s.error).toBeInstanceOf(Error);}},
 {pattern:/^a saved Word inventory source with (10001-paragraphs|10001-placeholders|1001-tables) above the supported bound$/,run:async(c,limit)=>setup(c,'empty',p=>{let fragment='';if(limit==='10001-paragraphs')fragment='<w:p/>'.repeat(10001);else if(limit==='10001-placeholders')fragment='<w:p><w:r><w:t>'+('&lt;A&gt;'.repeat(10001))+'</w:t></w:r></w:p>';else fragment=(`<w:tbl><w:tblPr/><w:tblGrid><w:gridCol w:w="8640"/></w:tblGrid><w:tr><w:tc><w:tcPr><w:tcW w:w="8640" w:type="dxa"/></w:tcPr><w:p/></w:tc></w:tr></w:tbl>`).repeat(1001);p.set(p.mainPart(),p.text(p.mainPart()).replace('<w:body>','<w:body>'+fragment));})},
 {pattern:/^inspection refuses with the template limit error and no inventory$/,run:c=>{const s=state(c);expect(s.returned).toBe(false);expect(s.report).toBeUndefined();expect(s.error).toMatchObject({code:'docx-template-limit'});}},
 {pattern:/^a saved concrete Word inventory sample encoded as (UTF-8-BOM|UTF-16BE)$/,run:async(c,encoding)=>{await setup(c,'sample',p=>{let xml=p.text(p.mainPart());if(encoding==='UTF-8-BOM')p.set(p.mainPart(),new Uint8Array([239,187,191,...new TextEncoder().encode(xml)]));else{xml=xml.replaceAll('w:','q:').replaceAll('xmlns:w=','xmlns:q=').replace('UTF-8','UTF-16').replace('<q:document ','<q:document xmlns:w="urn:foreign" ');const bytes=new Uint8Array(2+xml.length*2);bytes.set([254,255]);const view=new DataView(bytes.buffer);for(let i=0;i<xml.length;i++)view.setUint16(2+i*2,xml.charCodeAt(i),false);p.set(p.mainPart(),bytes);}});state(c).marker=encoding==='UTF-8-BOM'?[239,187,191]:[254,255];}},
 {pattern:/^the source archive and encoding bytes are unchanged$/,run:async c=>{const s=state(c);await custody(s);expect([...s.d.package.get('word/document.xml')!.slice(0,s.marker!.length)]).toEqual(s.marker!);}},
 {pattern:/^the concrete template reader returns a snapshot then the final paragraph becomes Changed <New>$/,run:c=>{const s=state(c);s.prior=s.d.inspectTemplate();s.d.paragraphs.at(-1)!.setText('Changed <New>');s.report=s.d.inspectTemplate();}},
 {pattern:/^the prior snapshot remains deeply immutable with No placeholder and three placeholders$/,run:c=>{const s=state(c);expect(s.prior).toEqual(expected());frozen(s.prior);}},
 {pattern:/^a new snapshot reports Changed <New> and four placeholders$/,run:c=>{const r=state(c).report!;expect(r.paragraphs.at(-1)!.text).toBe('Changed <New>');expect(r.counts.placeholders).toBe(4);expect(r.placeholders.at(-1)).toEqual({paragraphIndex:7,bodyIndex:4,start:8,end:13,text:'<New>',name:'New'});}},
 {pattern:/^the saved source archive is unchanged$/,run:async c=>expect(await Bun.file(state(c).source).bytes()).toEqual(Uint8Array.from(state(c).before))},
 {pattern:/^a saved concrete Word inventory sample with (protected|header) context$/,run:async(c,kind)=>setup(c,'sample',p=>{if(kind==='protected'){addPart(p,'word/settings.xml',`<w:settings xmlns:w="${W}"><w:documentProtection w:enforcement="1"/></w:settings>`,'application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml');addRelationship(p,p.mainPart(),SETTINGS,'settings.xml');}else{addPart(p,'word/header1.xml',`<w:hdr xmlns:w="${W}"><w:p><w:r><w:t>&lt;Header&gt;</w:t></w:r></w:p></w:hdr>`,'application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml');addRelationship(p,p.mainPart(),'http://schemas.openxmlformats.org/officeDocument/2006/relationships/header','header1.xml');}})},
];
