import {expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Document,OpcPackage} from '../../src/index.ts';import type {Table,TableCell,Paragraph} from '../../src/docx/index.ts';import {addPart,addRelationship} from '../../src/opc/index.ts';import {parseXml,elements,attribute,type XmlElement} from '../../src/xml/index.ts';import type {StepBinding} from '../../scripts/gherkin.ts';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',SETTINGS='http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings';const roots:string[]=[];
export async function cleanupVerticalMerging(){await Promise.all(roots.splice(0).map(p=>rm(p,{recursive:true,force:true})));}
const pkg=(d:Document)=>(d as unknown as {opcPackage:OpcPackage}).opcPackage,word=(n:XmlElement,s:string)=>n.namespaceURI===W&&n.localName===s;
type State={d:Document;source:string;output:string;before:Uint8Array;xml:string;parts:ReadonlyMap<string,Uint8Array>;paragraphs:string[];table:Table;cell:TableCell;paragraph:Paragraph;reopened?:Document;current?:Table;errors:unknown[];rangeError?:boolean;range:[number,number,number];encoding?:string};
const state=(c:Record<string,unknown>)=>c.verticalMerge as State;
function rows(xml:string){return elements(parseXml(xml),'tbl',W)[0]!.children.filter(n=>word(n,'tr')).map(r=>r.children.filter(n=>word(n,'tc')));}
function replaceCell(p:OpcPackage,r:number,c:number,change:(s:string)=>string){const xml=p.text(p.mainPart()),n=rows(xml)[r]![c]!;p.set(p.mainPart(),xml.slice(0,n.start)+change(xml.slice(n.start,n.end))+xml.slice(n.end));}
async function setup(c:Record<string,unknown>,change?:(p:OpcPackage)=>void){const d=Document.create();d.addParagraph('Before');d.addTable(3,3);d.tables[0]!.cell(0,1).text='Keep & <text>';d.tables[0]!.cell(0,1).setProperties({shading:'ABCDEF',verticalAlign:'center'});d.tables[0]!.cell(2,2).text='Tail';d.addParagraph('After');const p=await OpcPackage.open(d.package.toBytes());addPart(p,'customXml/opaque.bin',new Uint8Array([0,255,42]),'application/octet-stream');change?.(p);const root=await mkdtemp(join(tmpdir(),'vertical-outcomes-'));roots.push(root);const source=join(root,'source.docx'),output=join(root,'output.docx'),before=p.toBytes();await Bun.write(source,before);const read=await Document.open(source);c.verticalMerge={d:read,source,output,before,xml:p.text(p.mainPart()),parts:read.package.parts,paragraphs:read.paragraphs.map(p=>p.text),table:read.tables[0]!,cell:read.tables[0]!.cell(0,1),paragraph:read.paragraphs[0]!,errors:[],range:[1,0,2]} satisfies State;}
async function save(s:State,column=1,first=0,last=2){s.range=[column,first,last];s.current=s.table.mergeColumnCells(column,first,last);await s.d.save(s.output);s.reopened=await Document.open(s.output);}
function capture(s:State,fn:()=>unknown){try{fn();s.errors.push(null);}catch(e){s.errors.push(e);}}
export const bindings:StepBinding[]=[
 {pattern:/^a saved Word vertical merge source with a three by three table$/,run:async c=>setup(c)},
 {pattern:/^column (\d+) rows (\d+) through (\d+) are merged and saved to a new path$/,run:async(c,col,a,b)=>save(state(c),Number(col),Number(a),Number(b))},
 {pattern:/^column one rows zero through two are merged and saved to a new path$/,run:async c=>save(state(c))},
 {pattern:/^the reopened table has three rows, three grid columns and nine physical cells$/,run:c=>{const d=state(c).reopened!,xml=pkg(d).text(pkg(d).mainPart());expect(d.tables).toHaveLength(1);expect(d.tables[0]!.rows).toBe(3);expect(d.tables[0]!.columns).toBe(3);expect(rows(xml).map(r=>r.length)).toEqual([3,3,3]);expect(elements(parseXml(xml),'gridCol',W)).toHaveLength(3);}},
 {pattern:/^column (\d+) has restart at row (\d+) and explicit continue through row (\d+)$/,run:(c,col,a,b)=>{const s=state(c),[column,first,last]=[Number(col),Number(a),Number(b)],r=rows(pkg(s.reopened!).text(pkg(s.reopened!).mainPart()));expect([column,first,last]).toEqual(s.range);for(let row=0;row<3;row++)for(let cell=0;cell<3;cell++){const flags=r[row]![cell]!.children.find(n=>word(n,'tcPr'))!.children.filter(n=>word(n,'vMerge'));const wanted=cell===column&&row>=first&&row<=last;expect(flags).toHaveLength(wanted?1:0);if(wanted)expect(attribute(flags[0]!,'val',W)).toBe(row===first?'restart':'continue');}}},
 {pattern:/^removing only the inserted vertical markers reproduces the complete source document XML$/,run:c=>{const s=state(c),xml=pkg(s.reopened!).text(pkg(s.reopened!).mainPart()),flags=elements(parseXml(xml),'vMerge',W).sort((a,b)=>b.start-a.start);expect(flags).toHaveLength(s.range[2]-s.range[1]+1);let stripped=xml;for(const n of flags)stripped=stripped.slice(0,n.start)+stripped.slice(n.end);expect(stripped).toBe(s.xml);}},
 {pattern:/^the reopened paragraph sequence, unrelated members and source archive are unchanged$/,run:async c=>{const s=state(c),d=s.reopened!;expect(d.paragraphs.map(p=>p.text)).toEqual(s.paragraphs);expect([...d.package.parts.keys()]).toEqual([...s.parts.keys()]);for(const[n,b]of s.parts)if(n!==pkg(d).mainPart())expect(d.package.get(n)).toEqual(b);expect(await Bun.file(s.source).bytes()).toEqual(Uint8Array.from(s.before));}},
 {pattern:/^a saved Word vertical merge source whose continuation cell has (text|space-text|cell-shading|paragraph-format|empty-run|lexical-comment)$/,run:async(c,kind)=>setup(c,p=>replaceCell(p,1,1,raw=>kind==='text'||kind==='space-text'?raw.replace(/<w:p\b[^>]*\/>/,`<w:p><w:r><w:t xml:space="preserve">${kind==='text'?'Do not lose me':' '}</w:t></w:r></w:p>`):kind==='cell-shading'?raw.replace('</w:tcPr>','<w:shd w:val="clear" w:fill="ABCDEF"/></w:tcPr>'):kind==='paragraph-format'?raw.replace(/<w:p\b[^>]*\/>/,'<w:p><w:pPr><w:keepNext/></w:pPr></w:p>'):kind==='empty-run'?raw.replace(/<w:p\b[^>]*\/>/,'<w:p><w:r><w:t/></w:r></w:p>'):raw.replace('<w:tcPr>','<!--retain--><w:tcPr>')))},
 {pattern:/^column one rows zero through two are merged$/,run:c=>{const s=state(c);capture(s,()=>s.table.mergeColumnCells(1,0,2));}},
 {pattern:/^the vertical merge refuses and the archive and held source handles are unchanged$/,run:async c=>{const s=state(c);expect(s.errors).toHaveLength(1);expect(s.errors[0]).toBeInstanceOf(s.rangeError?RangeError:Error);expect(s.d.package.toBytes()).toEqual(s.before);expect(s.table.rows).toBe(3);expect(s.table.columns).toBe(3);expect(s.cell.text).toBe('Keep & <text>');expect(s.paragraph.text).toBe('Before');expect(await Bun.file(s.source).bytes()).toEqual(Uint8Array.from(s.before));expect(await Bun.file(s.output).exists()).toBe(false);}},
 {pattern:/^a saved Word vertical merge source with (existing-vertical|missing-grid|width-mismatch|nested-unselected|protected|external-settings)$/,run:async(c,kind)=>setup(c,p=>{if(kind==='existing-vertical')replaceCell(p,2,0,s=>s.replace('<w:tcPr>','<w:tcPr><w:vMerge w:val="restart"/>'));if(kind==='missing-grid')p.set(p.mainPart(),p.text(p.mainPart()).replace(/<w:tblGrid>[\s\S]*?<\/w:tblGrid>/,''));if(kind==='width-mismatch')replaceCell(p,2,0,s=>s.replace('w:w="2880"','w:w="100"'));if(kind==='nested-unselected')replaceCell(p,2,0,s=>s.replace('<w:tcPr>','<w:tbl/><w:tcPr>'));if(kind==='protected'){addPart(p,'word/settings.xml',`<w:settings xmlns:w="${W}"><w:documentProtection w:enforcement="1"/></w:settings>`,'application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml');addRelationship(p,p.mainPart(),SETTINGS,'settings.xml');}if(kind==='external-settings')addRelationship(p,p.mainPart(),SETTINGS,'https://example.invalid/settings',{external:true});})},
 {pattern:/^the vertical merge is requested with (singleton|reversed|outside|fractional) coordinates$/,run:(c,kind)=>{const s=state(c),args:Record<string,[number,number,number]>={singleton:[1,0,0],reversed:[1,2,1],outside:[3,0,2],fractional:[1,0.5,2]};s.rangeError=true;capture(s,()=>s.table.mergeColumnCells(...args[kind!]!));}},
 {pattern:/^the vertical merge fails after (part-write|serialization)$/,run:(c,stage)=>{const s=state(c),p=pkg(s.d),set=p.set.bind(p),serialize=p.toBytes.bind(p);let reached=false;if(stage==='part-write')p.set=(n,v)=>{set(n,v);if(n===p.mainPart()){reached=true;throw Error('injected write');}};else p.toBytes=()=>{reached=true;throw Error('injected serialization');};try{capture(s,()=>s.table.mergeColumnCells(1,0,2));}finally{p.set=set;p.toBytes=serialize;}expect(reached).toBe(true);expect(String(s.errors[0])).toContain('injected');}},
 {pattern:/^a saved Word vertical merge source encoded as (UTF-8-BOM|UTF-16LE|UTF-16BE)$/,run:async(c,encoding)=>{await setup(c,p=>{let xml=p.text(p.mainPart());if(encoding==='UTF-8-BOM')p.set(p.mainPart(),new Uint8Array([239,187,191,...new TextEncoder().encode(xml)]));else{xml=xml.replaceAll('w:','q:').replaceAll('xmlns:w=','xmlns:q=').replace('UTF-8','UTF-16').replace('<q:document ','<q:document xmlns:w="urn:foreign" ');const bytes=new Uint8Array(2+xml.length*2),little=encoding==='UTF-16LE';bytes.set(little?[255,254]:[254,255]);const v=new DataView(bytes.buffer);for(let i=0;i<xml.length;i++)v.setUint16(2+i*2,xml.charCodeAt(i),little);p.set(p.mainPart(),bytes);}});state(c).encoding=encoding;}},
 {pattern:/^the reopened vertical encoding marker and namespace meaning match the source$/,run:c=>{const s=state(c),p=pkg(s.reopened!),name=p.mainPart(),length=s.encoding==='UTF-8-BOM'?3:2;expect(p.get(name)!.slice(0,length)).toEqual(s.parts.get(name)!.slice(0,length));const tree=parseXml(p.text(name));expect(tree.root.namespaceURI).toBe(W);if(s.encoding!=='UTF-8-BOM')expect(tree.root.attributes['xmlns:w']).toBe('urn:foreign');}},
 {pattern:/^column one rows zero through two are merged in the editing session$/,run:c=>{const s=state(c);s.current=s.table.mergeColumnCells(1,0,2);}},
 {pattern:/^vertical (old-handles|merged-cells) operations refuse without changing the merged archive$/,run:(c,kind)=>{const s=state(c),before=s.d.package.toBytes(),ops=kind==='old-handles'?[()=>s.table.rows,()=>s.cell.text,()=>s.paragraph.text]:[()=>s.current!.cell(0,1),()=>s.current!.cell(1,1),()=>s.current!.cell(2,1),()=>s.current!.insertRow(0),()=>s.current!.mergeColumnCells(0,0,2),()=>s.current!.mergeRowCells(0,0,1)];for(const op of ops){expect(op).toThrow();expect(s.d.package.toBytes()).toEqual(before);}}},
 {pattern:/^the current unmerged vertical tail cell still reads Tail$/,run:c=>expect(state(c).current!.cell(2,2).text).toBe('Tail')},
];
