import assert from 'node:assert/strict';
import {parseXml,attribute,applyEdits,type XmlDocument,type XmlElement,type XmlParserLimits} from '../../src/xml/index.ts';
import {classifyXmlOperationFailure} from '../../src/errors.ts';
import type {StepBinding,AcceptanceStep} from '../../scripts/gherkin.ts';
type Result={source:string;original:string;expected?:string;document?:XmlDocument;error?:unknown;edits?:any[];editsBefore?:string;output?:string};
type State={source?:string;original?:string;document?:XmlDocument;error?:unknown;limits?:XmlParserLimits;results?:Result[];edits?:any[];editsBefore?:string;output?:string};
const state=(c:Record<string,unknown>)=>{c.lexical??={};return c.lexical as State;};
const table=(c:Record<string,unknown>,header:string[])=>{const rows=(c.step as AcceptanceStep).argument?.dataTable;assert(rows);assert.deepEqual(rows[0],header);return rows.slice(1);};
const parse=(r:Result,limits?:XmlParserLimits)=>{try{r.document=parseXml(r.source,limits);}catch(error){r.error=error;}};
const jsonString=(x:string)=>{const v:unknown=JSON.parse(x);assert.equal(typeof v,'string');return v as string;};
export const bindings:StepBinding[]=[
 {pattern:/^the lexical XML input is JSON (.+)$/,run:(c,value)=>{const s=state(c);s.source=jsonString(value!);s.original=s.source;}},
 {pattern:/^the lexical XML input is parsed without rewriting its source$/,run:c=>{const s=state(c);assert(s.source!==undefined);try{s.document=parseXml(s.source);}catch(e){s.error=e;}}},
 {pattern:/^exactly two elements expose these decoded values and UTF-16 half-open offsets$/,run:c=>{const s=state(c);assert.equal(s.error,undefined);assert(s.document);assert.equal(s.document.elements.length,2);const rows=table(c,['element','qualified_name','local_name','namespace_uri','text_json','start','open_end','close_start','end','self_closing']);assert.equal(rows.length,2);for(const r of rows){const el:XmlElement=r[0]==='root'?s.document.root:s.document.root.children[0]!;assert.deepEqual([el.name,el.localName,el.namespaceURI,el.directText],[r[1],r[2],r[3],jsonString(r[4]!)]);assert.deepEqual([el.start,el.openEnd,el.closeStart,el.end],[r[5],r[6],r[7],r[8]].map(Number));assert.equal(el.selfClosing,r[9]==='true');}}},
 {pattern:/^the root has no parent, its sole child links back to it, and both root links identify that same root$/,run:c=>{const d=state(c).document;assert(d);assert.equal(d.root.parent,undefined);assert.equal(d.root.children.length,1);const ch=d.root.children[0]!;assert.equal(ch.parent,d.root);assert.equal(ch.root,d.root);assert.equal(d.root.root,d.root);assert.equal(ch.children.length,0);}},
 {pattern:/^slicing the original source at each returned range yields its exact element markup and the source is unchanged$/,run:c=>{const s=state(c),d=s.document;assert(d&&s.source);assert.equal(s.source.slice(d.root.start,d.root.end),'<p:r xmlns="urn:default" xmlns:p="urn:p" xmlns:x="urn:x" a="1 &amp; 2">pre😀<x:c x:b="v"/>mid<![CDATA[<tail>]]></p:r>');assert.equal(s.source.slice(d.root.children[0]!.start,d.root.children[0]!.end),'<x:c x:b="v"/>');assert.equal(s.source,s.original);}},
 {pattern:/^the root decoded text equals JSON (.+)$/,run:(c,v)=>{const d=state(c).document;assert(d);assert.equal(d.root.directText,jsonString(v!));}},
 {pattern:/^the child s range is UTF-16 \[(\d+),(\d+)\) and slices the original source to JSON (.+)$/,run:(c,start,end,v)=>{const s=state(c),d=s.document;assert(d&&s.source);assert.equal(d.root.children.length,1);const ch=d.root.children[0]!;assert.equal(ch.name,'s');assert.deepEqual([ch.start,ch.end],[Number(start),Number(end)]);assert.equal(s.source.slice(ch.start,ch.end),jsonString(v!));}},
 {pattern:/^the original source including its raw line endings is unchanged$/,run:c=>{const s=state(c);assert.equal(s.source,s.original);assert(s.source?.includes('\r\n'));}},
 {pattern:/^parsing returns category malformed-xml with no document result and unchanged source$/,run:c=>{const s=state(c);assert.equal(classifyXmlOperationFailure(s.error),'malformed-xml');assert.equal(s.document,undefined);assert.equal(s.source,s.original);}},
 {pattern:/^the root expanded name is urn:unicode\/名 and its expanded attribute urn:unicode\/é equals JSON (.+)$/,run:(c,v)=>{const d=state(c).document;assert(d);assert.deepEqual([d.root.namespaceURI,d.root.localName],['urn:unicode','名']);assert.equal(attribute(d.root,'é','urn:unicode'),jsonString(v!));}},
 {pattern:/^its sole child expanded name is urn:unicode\/𐐀 with UTF-16 range \[(\d+),(\d+)\) slicing to JSON (.+)$/,run:(c,start,end,v)=>{const s=state(c),d=s.document;assert(d&&s.source);assert.equal(d.root.children.length,1);const ch=d.root.children[0]!;assert.deepEqual([ch.namespaceURI,ch.localName,ch.start,ch.end],['urn:unicode','𐐀',Number(start),Number(end)]);assert.equal(s.source.slice(ch.start,ch.end),jsonString(v!));}},
 {pattern:/^the root UTF-16 range is \[(\d+),(\d+)\) and the original source is unchanged$/,run:(c,start,end)=>{const s=state(c);assert(s.document);assert.deepEqual([s.document.root.start,s.document.root.end],[Number(start),Number(end)]);assert.equal(s.source,s.original);}},
 {pattern:/^these exact XML refusal inputs and documented categories$/,run:c=>{state(c).results=table(c,['variant','source_json','category']).map(r=>({source:jsonString(r[1]!),original:jsonString(r[1]!),expected:r[2]}));}},
 {pattern:/^every refusal input is parsed through the production lexical XML API$/,run:c=>{const s=state(c);assert.equal(s.results?.length,15);for(const r of s.results!)parse(r);}},
 {pattern:/^every input returns its documented category with no document result$/,run:c=>{const rs=state(c).results;assert.equal(rs?.length,15);for(const r of rs!){assert.equal(r.document,undefined);assert.equal(classifyXmlOperationFailure(r.error),r.expected);}}},
 {pattern:/^every original source remains unchanged$/,run:c=>{const rs=state(c).results;assert(rs?.length);for(const r of rs!)assert.equal(r.source,r.original);}},
 {pattern:/^XML parser limits maxDepth (\d+), maxNodes (\d+) and maxSourceUnits (\d+) measured in UTF-16 units$/,run:(c,d,n,u)=>{state(c).limits={maxDepth:Number(d),maxNodes:Number(n),maxSourceUnits:Number(u)};}},
 {pattern:/^these exact XML resource-limit recipes$/,run:c=>{const make:Record<string,string>={'five nested n elements':'<n>'.repeat(5)+'</n>'.repeat(5),'root r with six self-closing n children':'<r>'+'<n/>'.repeat(6)+'</r>','root r containing fifty-eight x characters':'<r>'+'x'.repeat(58)+'</r>'};state(c).results=table(c,['recipe','category']).map(r=>{assert(Object.hasOwn(make,r[0]!));return{source:make[r[0]!]!,original:make[r[0]!]!,expected:r[1]};});}},
 {pattern:/^every recipe is parsed through the production lexical XML API with those limits$/,run:c=>{const s=state(c);assert(s.limits&&s.results?.length===3);for(const r of s.results!)parse(r,s.limits);}},
 {pattern:/^every recipe returns its documented category with no partial document$/,run:c=>{const rs=state(c).results;assert.equal(rs?.length,3);for(const r of rs!){assert.equal(r.document,undefined);assert.equal(classifyXmlOperationFailure(r.error),r.expected);}}},
 {pattern:/^independent depth-four, six-node and sixty-four-source-unit controls each parse successfully$/,run:c=>{const limits=state(c).limits;assert(limits);for(const source of ['<n>'.repeat(4)+'</n>'.repeat(4),'<r>'+'<n/>'.repeat(5)+'</r>','<r>'+'x'.repeat(57)+'</r>'])assert(parseXml(source,limits).root);}},
 {pattern:/^these disjoint UTF-16 half-open replacements in reverse source order$/,run:c=>{const s=state(c);s.edits=table(c,['start','end','value_json']).map(r=>({start:Number(r[0]),end:Number(r[1]),value:jsonString(r[2]!)}));s.editsBefore=JSON.stringify(s.edits);}},
 {pattern:/^the production XML editor applies those replacements atomically$/,run:c=>{const s=state(c);assert(s.source&&s.edits);s.output=applyEdits(s.source,s.edits);}},
 {pattern:/^the complete output equals JSON (.+) and reparses to root text JSON (.+) with sole child x$/,run:(c,out,text)=>{const s=state(c);assert.equal(s.output,jsonString(out!));const d=parseXml(s.output!);assert.equal(d.root.text,jsonString(text!));assert.equal(d.root.children.length,1);assert.equal(d.root.children[0]!.name,'x');}},
 {pattern:/^these independent edit batches refuse with no changed text$/,run:c=>{const s=state(c);s.results=table(c,['source_json','edits_json','category']).map(r=>{const source=jsonString(r[0]!),edits=JSON.parse(jsonString(r[1]!)),item:Result={source,original:source,edits,editsBefore:JSON.stringify(edits),expected:r[2]};try{item.output=applyEdits(source,edits);}catch(error){item.error=error;}assert.equal(item.output,undefined);assert.equal(classifyXmlOperationFailure(item.error),item.expected);return item;});assert.equal(s.results.length,3);}},
 {pattern:/^every original source and replacement list remains unchanged$/,run:c=>{const s=state(c);assert.equal(s.source,s.original);assert.equal(JSON.stringify(s.edits),s.editsBefore);for(const r of s.results!){assert.equal(r.source,r.original);assert.equal(JSON.stringify(r.edits),r.editsBefore);}}},
];
