import {OoxmlError} from '../errors.ts';
import {applyEdits,attribute,escapeAttribute,type XmlElement} from '../xml/index.ts';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',N='http://www.w3.org/2000/xmlns/';
const fail=(m:string):never=>{throw new OoxmlError('docx-retained-format-unsupported',m);};
const is=(e:XmlElement,n:string)=>e.namespaceURI===W&&e.localName===n;
const cs=(e:XmlElement,n:string)=>e.children.filter(c=>is(c,n));
const RORDER=['rStyle','rFonts','b','bCs','i','iCs','caps','smallCaps','strike','dstrike','outline','shadow','emboss','imprint','noProof','snapToGrid','vanish','webHidden','color','spacing','w','kern','position','sz','szCs','highlight','u','effect','bdr','shd','fitText','vertAlign','rtl','cs','em','lang','eastAsianLayout','specVanish','oMath'];
const PORDER=['pStyle','keepNext','keepLines','pageBreakBefore','framePr','widowControl','numPr','suppressLineNumbers','pBdr','shd','tabs','suppressAutoHyphens','kinsoku','wordWrap','overflowPunct','topLinePunct','autoSpaceDE','autoSpaceDN','bidi','adjustRightInd','snapToGrid','spacing','ind','contextualSpacing','mirrorIndents','suppressOverlap','jc','textDirection','textAlignment','textboxTightWrap','outlineLvl','divId','cnfStyle','rPr','sectPr'];
export type RetainedWordRunPatch={strike?:boolean;underline?:'none'|'single'|'double';color?:string;highlight?:'none'|'yellow';sizeHalfPoints?:number;font?:string;verticalAlign?:'baseline'|'superscript'|'subscript';caps?:boolean;smallCaps?:boolean;vanish?:boolean;remove?:Array<'rFonts'|'color'|'sz'|'highlight'|'u'|'vertAlign'>};
export type RetainedWordParagraphPatch={jc?:'left'|'center'|'right'|'both';before?:number;after?:number;left?:number;right?:number;hanging?:number;line?:number;lineRule?:'auto'|'exact'|'atLeast';keepLines?:boolean;keepNext?:boolean;pageBreakBefore?:boolean;outlineLvl?:number};
function plain(v:unknown,allowed:string[]){if(!v||typeof v!=='object'||Object.getPrototypeOf(v)!==Object.prototype)fail('Expected plain patch');const keys=Reflect.ownKeys(v as object);if(!keys.length||keys.some(k=>typeof k!=='string'||!allowed.includes(k)))fail('Unknown/empty patch');for(const k of keys)if(!('value'in Object.getOwnPropertyDescriptor(v as object,k)!))fail('Executable patch');return v as Record<string,unknown>;}
function integer(v:unknown,min:number,max:number){if(!Number.isSafeInteger(v)||Number(v)<min||Number(v)>max)fail('Scalar out of bounds');return Number(v);}
function gaps(xml:string,e:XmlElement){if(e.selfClosing)return;let at=e.openEnd;for(const c of e.children){if(!/^[ \t\r\n]*$/.test(xml.slice(at,c.start)))fail('Lexical/mixed-content barrier');at=c.end;}if(!/^[ \t\r\n]*$/.test(xml.slice(at,e.closeStart)))fail('Lexical/mixed-content barrier');}
function order(xml:string,e:XmlElement,names:string[]){gaps(xml,e);let last=-1;for(const c of e.children){const rank=names.indexOf(c.localName);if(c.namespaceURI!==W||rank<0||rank<=last||c.children.length)fail('Unsupported/ambiguous/revised property');gaps(xml,c);last=rank;}}
function attrs(e:XmlElement,allowed:string[]){for(const k of Object.keys(e.attributes))if(e.attributeNamespaces[k]!==N&&(e.attributeNamespaces[k]!==W||!allowed.includes(k.split(':').at(-1)!)))fail('Unexpected property attribute');}
function paragraph(xml:string,p:XmlElement){if(!is(p,'p')||!p.parent||!is(p.parent,'body'))fail('Direct body paragraph required');gaps(xml,p);const props=cs(p,'pPr');if(props.length>1||props.length&&p.children[0]!==props[0])fail('Misplaced properties');for(const r of p.children){if(is(r,'pPr'))continue;if(!is(r,'r'))fail('Fields/hyperlinks/tracked content unsupported');gaps(xml,r);const prs=cs(r,'rPr');if(prs.length>1||prs.length&&r.children[0]!==prs[0]||r.children.some(c=>!is(c,'rPr')&&!is(c,'t')))fail('Complex direct run');for(const t of cs(r,'t'))if(t.children.length||!t.selfClosing&&xml.slice(t.openEnd,t.closeStart).includes('<'))fail('Nonordinary text');}return props[0];}
function replaceProperties(xml:string,parent:XmlElement,pr:XmlElement|undefined,name:string,changes:Record<string,string|null>,names:string[]){const edits:{start:number;end:number;value:string}[]=[],additions:{name:string;value:string}[]=[];for(const[n,value]of Object.entries(changes)){const old=pr?cs(pr,n):[];if(old.length>1)fail('Duplicate property');if(old[0])edits.push({start:old[0].start,end:old[0].end,value:value??''});else if(value!==null)additions.push({name:n,value});}additions.sort((a,b)=>names.indexOf(a.name)-names.indexOf(b.name));if(!pr){const v=additions.map(a=>a.value).join('');if(!v)return xml;return applyEdits(xml,[{start:parent.openEnd,end:parent.openEnd,value:'<w:'+name+' xmlns:w="'+W+'">'+v+'</w:'+name+'>'}]);}if(pr.selfClosing){if(!additions.length)return applyEdits(xml,edits);edits.push({start:pr.start,end:pr.end,value:xml.slice(pr.start,pr.end).replace(/\/\s*>$/,()=> '>'+additions.map(a=>a.value).join('')+'</'+pr.name+'>')});}else{const inserts=new Map<number,string>();for(const a of additions){const next=pr.children.find(c=>names.indexOf(c.localName)>names.indexOf(a.name)),at=next?.start??pr.closeStart;inserts.set(at,(inserts.get(at)??'')+a.value);}for(const[start,value]of inserts)edits.push({start,end:start,value});}return applyEdits(xml,edits);}
const leaf=(n:string,v:string)=>'<w:'+n+' xmlns:w="'+W+'" w:val="'+escapeAttribute(v)+'"/>';
export function patchRetainedWordRun(xml:string,p:XmlElement,ordinal:number,value:RetainedWordRunPatch){paragraph(xml,p);const patch=plain(value,['strike','underline','color','highlight','sizeHalfPoints','font','verticalAlign','caps','smallCaps','vanish','remove']),runs=cs(p,'r');if(!Number.isInteger(ordinal)||!runs[ordinal])fail('Missing run');const run=runs[ordinal]!,pr=cs(run,'rPr')[0];if(pr){attrs(pr,[]);order(xml,pr,RORDER);for(const c of pr.children){attrs(c,c.localName==='rFonts'?['ascii','hAnsi']:c.localName==='lang'?['val','eastAsia','bidi']:['val']);if(c.localName==='rFonts'&&(attribute(c,'ascii',W)!==attribute(c,'hAnsi',W)||!attribute(c,'ascii',W)))fail('Unsupported font slots');
 const v=attribute(c,'val',W);if(['b','bCs','i','iCs','caps','smallCaps','strike','dstrike','outline','shadow','emboss','imprint','vanish'].includes(c.localName)&&v!==undefined&&!['0','1','true','false','on','off'].includes(v))fail('Malformed original Boolean');
 if(c.localName==='color'&&(v===undefined||!(/^[0-9A-F]{6}$/.test(v)||v==='auto')))fail('Malformed original colour');
 if(['sz','szCs'].includes(c.localName)&&(v===undefined||!/^\d+$/.test(v)||Number(v)<1||Number(v)>800))fail('Malformed original size');
 }}

 const changes:Record<string,string|null>={};for(const[k,v]of Object.entries(patch)){const n=({underline:'u',sizeHalfPoints:'sz',font:'rFonts',verticalAlign:'vertAlign'} as Record<string,string>)[k]??k;if(k==='remove'){if(Object.keys(patch).length!==1||!Array.isArray(v)||!v.length||new Set(v).size!==v.length||v.some(n=>!['rFonts','color','sz','highlight','u','vertAlign'].includes(n)))fail('Invalid removal list');for(const n of v as string[])changes[n]=null;}else if(['strike','caps','smallCaps','vanish'].includes(k)){if(typeof v!=='boolean')fail('Boolean required');changes[n]=leaf(n,v?'1':'0');}else if(k==='sizeHalfPoints')changes.sz=leaf('sz',String(integer(v,1,800)));else if(k==='font'){if(typeof v!=='string'||!v||v.trim()!==v||[...v].length>128||/[\u0000-\u001f]/.test(v))fail('Invalid font');const encoded=escapeAttribute(v as string);changes.rFonts='<w:rFonts xmlns:w="'+W+'" w:ascii="'+encoded+'" w:hAnsi="'+encoded+'"/>';}else{const options:Record<string,string[]>={underline:['none','single','double'],highlight:['none','yellow'],verticalAlign:['baseline','superscript','subscript']};if(typeof v!=='string'||(k==='color'?!/^[0-9A-F]{6}$/.test(v):!options[k]?.includes(v)))fail('Invalid appearance enum');changes[n]=leaf(n,v as string);}}
 const enabled=(name:string)=>changes[name]?changes[name]!.includes('w:val="1"'):pr?cs(pr,name).some(c=>!['0','false','off'].includes(attribute(c,'val',W)??'1')):false;if(enabled('caps')&&enabled('smallCaps')||enabled('strike')&&enabled('dstrike'))fail('Incompatible effects');return replaceProperties(xml,run,pr,'rPr',changes,RORDER);
}
// Attribute-value splices preserve every unrequested spacing/indent token.
function opening(xml:string,e:XmlElement,values:Record<string,string>){const raw=xml.slice(e.start,e.openEnd),tokens:{key:string;start:number;end:number}[]=[];let at=raw.match(/^<[^\s/>]+/)![0].length;while(at<raw.length){if(/^\s*\/?\s*>$/.test(raw.slice(at)))break;const m=raw.slice(at).match(/^(\s+)([^\s=/>]+)(\s*=\s*)(["'])([^]*?)\4/);if(!m)fail('Invalid lexical opening');const start=at+m![1]!.length+m![2]!.length+m![3]!.length+1;tokens.push({key:m![2]!,start,end:start+m![5]!.length});at+=m![0].length;}
 const edits=[];let add='';for(const[k,v]of Object.entries(values)){const match=tokens.find(t=>e.attributeNamespaces[t.key]===W&&t.key.split(':').at(-1)===k);if(match)edits.push({start:match.start,end:match.end,value:escapeAttribute(v)});else add+=' w:'+k+'="'+escapeAttribute(v)+'"';}let result=raw;for(const e of edits.sort((a,b)=>b.start-a.start))result=result.slice(0,e.start)+e.value+result.slice(e.end);if(add)result=result.replace(/\/?\s*>$/,m=>(Object.hasOwn(e.attributes,'xmlns:w')?'':' xmlns:w="'+W+'"')+add+m);return result;
}
export function patchRetainedWordParagraph(xml:string,p:XmlElement,value:RetainedWordParagraphPatch){const pr=paragraph(xml,p),patch=plain(value,['jc','before','after','left','right','hanging','line','lineRule','keepLines','keepNext','pageBreakBefore','outlineLvl']);if(pr){attrs(pr,[]);order(xml,pr,PORDER);
 for(const node of pr.children){if(['keepNext','keepLines','pageBreakBefore','widowControl'].includes(node.localName)){attrs(node,['val']);const v=attribute(node,'val',W);if(v!==undefined&&!['0','1','true','false','on','off'].includes(v))fail('Malformed paragraph Boolean');}
 if(node.localName==='spacing'){attrs(node,['before','after','line','lineRule']);for(const k of ['before','after','line']){const v=attribute(node,k,W);if(v!==undefined&&(!/^\d+$/.test(v)||Number(v)<(k==='line'?1:0)||Number(v)>31680))fail('Malformed spacing');}const rule=attribute(node,'lineRule',W);if(rule!==undefined&&!['auto','exact','atLeast'].includes(rule))fail('Malformed line rule');}
 if(node.localName==='ind'){attrs(node,['left','right','hanging','firstLine']);if(attribute(node,'firstLine',W)!==undefined&&attribute(node,'hanging',W)!==undefined)fail('Conflicting indentation');}
 }
 }const changes:Record<string,string|null>={},grouped:Record<string,Record<string,string>>={spacing:{},ind:{}};for(const[k,v]of Object.entries(patch)){if(['before','after','line','lineRule'].includes(k)){if(k==='lineRule'){if(typeof v!=='string'||!['auto','exact','atLeast'].includes(v))fail('Invalid line rule');grouped.spacing![k]=v as string;}else grouped.spacing![k]=String(integer(v,k==='line'?1:0,31680));}else if(['left','right','hanging'].includes(k))grouped.ind![k]=String(integer(v,0,31680));else if(k==='jc'){if(typeof v!=='string'||!['left','center','right','both'].includes(v))fail('Alignment');changes.jc=leaf('jc',v as string);}else if(k==='outlineLvl')changes.outlineLvl=leaf('outlineLvl',String(integer(v,0,9)));else{if(typeof v!=='boolean')fail('Paragraph Boolean');changes[k]=leaf(k,v?'1':'0');}}
 for(const[n,v]of Object.entries(grouped))if(Object.keys(v).length){const old=pr?cs(pr,n)[0]:undefined;if(old){attrs(old,n==='spacing'?['before','after','line','lineRule']:['left','right','hanging','firstLine']);if(n==='ind'&&attribute(old,'firstLine',W)!==undefined&&v.hanging!==undefined)fail('FirstLine/hanging conflict');const raw=xml.slice(old.start,old.end);changes[n]=opening(xml,old,v)+raw.slice(old.openEnd-old.start);}else changes[n]='<w:'+n+' xmlns:w="'+W+'"'+Object.entries(v).map(([k,v])=>' w:'+k+'="'+v+'"').join('')+'/>';}
 return replaceProperties(xml,p,pr,'pPr',changes,PORDER);
}
