import {OoxmlError} from '../errors.ts';
import {parseXml,elements,applyEdits,escapeAttribute,type XmlElement} from '../xml/index.ts';
const P='http://schemas.openxmlformats.org/presentationml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',N='http://www.w3.org/2000/xmlns/';
const fail=(m:string,code='PPTX_FORMAT_UNSUPPORTED'):never=>{throw new OoxmlError(code,m);};
const is=(e:XmlElement,n:string,ns=A)=>e.localName===n&&e.namespaceURI===ns;
const children=(e:XmlElement,n:string,ns=A)=>e.children.filter(c=>is(c,n,ns));
const one=(e:XmlElement,n:string,ns=A)=>{const nodes=children(e,n,ns);if(nodes.length!==1)fail('Expected one direct '+n);return nodes[0]!;};
const keys=(e:XmlElement)=>Object.keys(e.attributes).filter(k=>e.attributeNamespaces[k]!==N);
function gaps(xml:string,e:XmlElement){if(e.selfClosing)return;let at=e.openEnd;for(const c of e.children){if(xml.slice(at,c.start).trim())fail('Lexical barrier');at=c.end;}if(xml.slice(at,e.closeStart).trim())fail('Lexical barrier');}
function shape(xml:string,id:number){if(!Number.isInteger(id)||id<1||id>2147483647)fail('Invalid shape ID');const d=parseXml(xml),root=d.root;if(!is(root,'sld',P))fail('Expected slide root');const tree=one(one(root,'cSld',P),'spTree',P);const ids=new Set<number>();for(const e of elements(d,'cNvPr',P)){const raw=e.attributes.id,n=raw&&/^\d+$/.test(raw)?Number(raw):NaN;if(!Number.isSafeInteger(n)||n<1||n>2147483647||ids.has(n))fail('Duplicate or invalid shape identity');ids.add(n);}const selected=tree.children.filter(e=>is(e,'sp',P)&&one(one(e,'nvSpPr',P),'cNvPr',P).attributes.id===String(id));if(selected.length!==1)fail('Missing unique direct shape');const sp=selected[0]!;for(const e of d.elements.filter(e=>{for(let n:XmlElement|undefined=e;n;n=n.parent)if(n===sp)return true;return false;})){if(['fld','br','hlinkClick','hlinkMouseOver','extLst','grpSp'].includes(e.localName))fail('Unsupported shape metadata');if(e.namespaceURI!==A&&e.namespaceURI!==P)fail('Foreign shape namespace');if(is(e,'spLocks')&&(keys(e).length!==1||e.attributes.noGrp!=='1'||e.children.length))fail('Protected shape');}return sp;}
const runOrder=['ln','noFill','solidFill','gradFill','blipFill','pattFill','grpFill','effectLst','effectDag','highlight','uLnTx','uLn','uFillTx','uFill','latin','ea','cs','sym','hlinkClick','hlinkMouseOver','rtl','extLst'];
const paraOrder=['lnSpc','spcBef','spcAft','buClrTx','buClr','buSzTx','buSzPct','buSzPts','buFontTx','buFont','buNone','buAutoNum','buChar','buBlip','tabLst','defRPr','extLst'];
function order(xml:string,e:XmlElement,names:string[]){gaps(xml,e);let last=-1;const seen=new Set<string>();for(const c of e.children){const at=names.indexOf(c.localName);if(c.namespaceURI!==A||at<0||at<=last||seen.has(c.localName))fail('Ambiguous property order');seen.add(c.localName);last=at;
 if(['gradFill','blipFill','pattFill','grpFill','effectLst','effectDag','highlight','uLnTx','uLn','uFillTx','uFill','rtl'].includes(c.localName))fail('Unsupported direct formatting child');
 if(c.localName==='solidFill'){const colors=csAny(c);if(colors.length!==1||!is(colors[0]!,'srgbClr')||colors[0]!.children.length||!/^([0-9A-F]{6})$/.test(colors[0]!.attributes.val??'')||keys(colors[0]!).length!==1)fail('Unsupported/ambiguous direct fill');gaps(xml,c);}
 if(c.localName==='latin'&&(c.children.length||keys(c).length!==1||!c.attributes.typeface))fail('Unsupported Latin font');
 if(['lnSpc','spcBef','spcAft'].includes(c.localName)){const spacing=c.children;if(spacing.length!==1||spacing[0]!.namespaceURI!==A||!['spcPts','spcPct'].includes(spacing[0]!.localName)||spacing[0]!.children.length||keys(spacing[0]!).length!==1||!/^\d+$/.test(spacing[0]!.attributes.val??''))fail('Ambiguous spacing');gaps(xml,c);}
 }}
const csAny=(e:XmlElement)=>e.children;
function textBody(xml:string,sp:XmlElement){const body=one(sp,'txBody',P);gaps(xml,body);const bp=one(body,'bodyPr'),ls=one(body,'lstStyle'),ps=children(body,'p');if(!ps.length||body.children[0]!==bp||body.children[1]!==ls||body.children.length!==ps.length+2)fail('Invalid text body order');for(const p of ps){gaps(xml,p);const pps=children(p,'pPr');if(pps.length>1||pps.length&&p.children[0]!==pps[0])fail('Invalid paragraph properties');if(pps.length)order(xml,pps[0]!,paraOrder);if(p.children.some(c=>!is(c,'pPr')&&!is(c,'r')&&!is(c,'endParaRPr')))fail('Unsupported paragraph topology');for(const r of children(p,'r')){gaps(xml,r);const t=one(r,'t'),rps=children(r,'rPr');if(t.children.length||r.children.length!==1+rps.length||rps.length>1||rps.length&&r.children[0]!==rps[0])fail('Invalid run topology');if(!t.selfClosing&&xml.slice(t.openEnd,t.closeStart).includes('<'))fail('Mixed text leaf');if(rps.length){order(xml,rps[0]!,runOrder);if(rps[0]!.children.filter(c=>['solidFill','noFill'].includes(c.localName)).length>1)fail('Ambiguous fill choice');}}}return {body,ps};}
function ordinal(n:number,length:number){if(!Number.isInteger(n)||n<0||n>=length)fail('Invalid direct ordinal');return n;}
const integer=(n:unknown,min:number,max:number,code='PPTX_FORMAT_UNSUPPORTED')=>{if(!Number.isSafeInteger(n)||Number(n)<min||Number(n)>max)fail('Invalid bounded integer',code);return Number(n);};
function plain(v:unknown,allowed:string[]){if(!v||typeof v!=='object'||Object.getPrototypeOf(v)!==Object.prototype||Reflect.ownKeys(v).some(k=>typeof k!=='string'||!allowed.includes(k)))fail('Patch must be bounded plain data');for(const k of Object.keys(v as object))if(!Object.hasOwn(Object.getOwnPropertyDescriptor(v as object,k)!,'value'))fail('Executable patch refused');return v as Record<string,unknown>;}
function openTag(xml:string,e:XmlElement,patch:Record<string,string|null>){
 const tag=xml.slice(e.start,e.openEnd),tokens:{name:string;start:number;valueStart:number;valueEnd:number;end:number}[]=[];
 let at=tag.match(/^<[^\s/>]+/)?.[0].length??0;
 while(at<tag.length){const rest=tag.slice(at);if(/^\s*\/?\s*>$/.test(rest))break;const m=rest.match(/^(\s+)([^\s=/>]+)(\s*=\s*)(["'])([^]*?)\4/);if(!m)fail('Unsupported lexical opening tag');const valueStart=at+m![1]!.length+m![2]!.length+m![3]!.length+1;tokens.push({name:m![2]!,start:at,valueStart,valueEnd:valueStart+m![5]!.length,end:at+m![0].length});at+=m![0].length;}
 const edits:{start:number;end:number;value:string}[]=[];let additions='';for(const[k,v]of Object.entries(patch)){const matches=tokens.filter(t=>t.name===k);if(matches.length>1)fail('Duplicate lexical attribute');const token=matches[0];if(token){if(v===null)edits.push({start:token.start,end:token.end,value:''});else if(e.attributes[k]!==v)edits.push({start:token.valueStart,end:token.valueEnd,value:escapeAttribute(v)});}else if(v!==null)additions+=' '+k+'="'+escapeAttribute(v)+'"';}
 if(additions){const end=tag.lastIndexOf(e.selfClosing?'/>':'>');edits.push({start:end,end,value:additions});}let result=tag;for(const change of edits.sort((a,b)=>b.start-a.start))result=result.slice(0,change.start)+change.value+result.slice(change.end);return result;
}
function withAttributes(xml:string,e:XmlElement,patch:Record<string,string|null>){return applyEdits(xml,[{start:e.start,end:e.openEnd,value:openTag(xml,e,patch)}]);}
export type ShapeGeometryPatch={x?:number;y?:number;width?:number;height?:number;rotation?:number;flipH?:boolean;flipV?:boolean};
export function patchShapeGeometry(xml:string,id:number,value:ShapeGeometryPatch){let p:Record<string,unknown>;try{p=plain(value,['x','y','width','height','rotation','flipH','flipV']);}catch(e){fail('Invalid geometry patch','PPTX_GEOMETRY_INVALID');}for(const k of Object.keys(p!))if(p![k]===null||p![k]===undefined)fail('Null/undefined geometry scalar','PPTX_GEOMETRY_INVALID');const sp=shape(xml,id),pr=one(sp,'spPr',P),xf=one(pr,'xfrm');gaps(xml,xf);const off=one(xf,'off'),ext=one(xf,'ext');if(xf.children.length!==2||xf.children[0]!==off||xf.children[1]!==ext||keys(xf).some(k=>!['rot','flipH','flipV'].includes(k))||off.children.length||ext.children.length||keys(off).sort().join(',')!=='x,y'||keys(ext).sort().join(',')!=='cx,cy')fail('Unsupported shape transform');for(const k of ['flipH','flipV'])if(xf.attributes[k]!==undefined&&!['0','1','true','false'].includes(xf.attributes[k]!))fail('Invalid existing flip');if(xf.attributes.rot!==undefined)integer(Number(xf.attributes.rot),0,21599999);const x=integer(p!.x??Number(off.attributes.x),0,100000000,'PPTX_GEOMETRY_INVALID'),y=integer(p!.y??Number(off.attributes.y),0,100000000,'PPTX_GEOMETRY_INVALID'),w=integer(p!.width??Number(ext.attributes.cx),1,100000000,'PPTX_GEOMETRY_INVALID'),h=integer(p!.height??Number(ext.attributes.cy),1,100000000,'PPTX_GEOMETRY_INVALID');if(x+w>100000000||y+h>100000000)fail('Geometry exceeds bounds','PPTX_GEOMETRY_INVALID');const xp:Record<string,string|null>={};if(Object.hasOwn(p!,'rotation'))xp.rot=String(integer(p!.rotation,0,21599999,'PPTX_GEOMETRY_INVALID'));for(const k of ['flipH','flipV'])if(Object.hasOwn(p!,k)){if(typeof p![k]!=='boolean')fail('Flip must be Boolean','PPTX_GEOMETRY_INVALID');xp[k]=p![k]?'1':'0';}const edits=[];if(Object.hasOwn(p!,'x')||Object.hasOwn(p!,'y'))edits.push({start:off.start,end:off.openEnd,value:openTag(xml,off,{...(Object.hasOwn(p!,'x')?{x:String(x)}:{}),...(Object.hasOwn(p!,'y')?{y:String(y)}:{})})});if(Object.hasOwn(p!,'width')||Object.hasOwn(p!,'height'))edits.push({start:ext.start,end:ext.openEnd,value:openTag(xml,ext,{...(Object.hasOwn(p!,'width')?{cx:String(w)}:{}),...(Object.hasOwn(p!,'height')?{cy:String(h)}:{})})});if(Object.keys(xp).length)edits.push({start:xf.start,end:xf.openEnd,value:openTag(xml,xf,xp)});return applyEdits(xml,edits);}
export type DirectTextRunPatch={bold?:boolean|null;italic?:boolean|null;underline?:'sng'|'none'|null;size?:number|null;typeface?:string|null;color?:string|null};
export function patchTextRun(xml:string,id:number,pIndex:number,rIndex:number,value:DirectTextRunPatch){const patch=plain(value,['bold','italic','underline','size','typeface','color']),sp=shape(xml,id),{ps}=textBody(xml,sp),p=ps[ordinal(pIndex,ps.length)]!,runs=children(p,'r'),r=runs[ordinal(rIndex,runs.length)]!,attrs:Record<string,string|null>={},nested:Record<string,string|null>={};for(const[k,a]of [['bold','b'],['italic','i']])if(Object.hasOwn(patch,k!)){const v=patch[k!];if(v!==null&&typeof v!=='boolean')fail('Run flag must be Boolean/null');attrs[a!]=v===null?null:v?'1':'0';}if(Object.hasOwn(patch,'underline')){if(patch.underline!==null&&(typeof patch.underline!=='string'||!['sng','none'].includes(patch.underline)))fail('Invalid underline');attrs.u=patch.underline===null?null:String(patch.underline);}if(Object.hasOwn(patch,'size'))attrs.sz=patch.size===null?null:String(integer(patch.size,100,400000));if(Object.hasOwn(patch,'typeface')){const v=patch.typeface;if(v!==null&&(typeof v!=='string'||!v||v.length>128))fail('Invalid typeface');nested.latin=v===null?null:'<a:latin xmlns:a="'+A+'" typeface="'+escapeAttribute(v as string)+'"/>';}
 if(Object.hasOwn(patch,'color')){const v=patch.color;if(v!==null&&(typeof v!=='string'||!/^([0-9A-F]{6})$/.test(v)))fail('Invalid RGB');nested.solidFill=v===null?null:'<a:solidFill xmlns:a="'+A+'"><a:srgbClr val="'+v+'"/></a:solidFill>';}
 return editProperty(xml,r,'rPr',attrs,nested,runOrder);
}
function editProperty(xml:string,parent:XmlElement,name:string,attrs:Record<string,string|null>,nested:Record<string,string|null>,names:string[]){const existing=children(parent,name);if(existing.length>1)fail('Duplicate direct properties');if(!existing.length){const a=Object.entries(attrs).filter(([,v])=>v!==null).map(([k,v])=>' '+k+'="'+escapeAttribute(v!)+'"').join(''),body=names.filter(n=>nested[n]!=null).map(n=>nested[n]).join('');if(!a&&!body)return xml;return applyEdits(xml,[{start:parent.openEnd,end:parent.openEnd,value:'<a:'+name+' xmlns:a="'+A+'"'+a+(body?'>'+body+'</a:'+name+'>':'/>')}]);}
 const e=existing[0]!;order(xml,e,names);const edits:{start:number;end:number;value:string}[]=[{start:e.start,end:e.openEnd,value:openTag(xml,e,attrs)}];let addToSelf='';for(const n of names.filter(n=>Object.hasOwn(nested,n))){const value=nested[n]!;const old=children(e,n);if(old.length){edits.push({start:old[0]!.start,end:old[0]!.end,value:value??''});}else if(value!==null){if(e.selfClosing){addToSelf+=value;continue;}const at=e.children.find(c=>names.indexOf(c.localName)>names.indexOf(n))?.start??e.closeStart;edits.push({start:at,end:at,value});}}
 if(addToSelf){edits[0]!.end=e.end;edits[0]!.value=openTag(xml,e,attrs).replace(/\/\s*>$/,()=> '>'+addToSelf+'</'+e.name+'>');}return applyEdits(xml,edits);
}
export type DirectParagraphPatch={alignment?:'l'|'ctr'|'r'|null;leftMargin?:number|null;indent?:number|null;spaceBefore?:number|null;spaceAfter?:number|null;linePercent?:number|null};
export function patchParagraph(xml:string,id:number,pIndex:number,value:DirectParagraphPatch){const patch=plain(value,['alignment','leftMargin','indent','spaceBefore','spaceAfter','linePercent']),sp=shape(xml,id),{ps}=textBody(xml,sp),p=ps[ordinal(pIndex,ps.length)]!,attrs:Record<string,string|null>={},nested:Record<string,string|null>={};if(Object.hasOwn(patch,'alignment')){if(patch.alignment!==null&&(typeof patch.alignment!=='string'||!['l','ctr','r'].includes(patch.alignment)))fail('Invalid alignment');attrs.algn=patch.alignment===null?null:String(patch.alignment);}for(const[k,a,min,max]of [['leftMargin','marL',0,100000000],['indent','indent',-100000000,100000000]] as const)if(Object.hasOwn(patch,k))attrs[a]=patch[k]===null?null:String(integer(patch[k],min,max));for(const[k,n]of [['spaceBefore','spcBef'],['spaceAfter','spcAft'],['linePercent','lnSpc']] as const)if(Object.hasOwn(patch,k)){const v=patch[k],pct=k==='linePercent';nested[n]=v===null?null:'<a:'+n+' xmlns:a="'+A+'"><a:'+(pct?'spcPct':'spcPts')+' val="'+integer(v,pct?1:0,pct?13200000:158400)+'"/></a:'+n+'>';}
 return editProperty(xml,p,'pPr',attrs,nested,paraOrder);
}
export function slideVisibility(xml:string){const root=parseXml(xml).root;if(!is(root,'sld',P))fail('Invalid slide root');const foreign=keys(root).filter(k=>k.split(':').at(-1)==='show'&&k!=='show');if(foreign.length)fail('Namespaced visibility requires explicit policy');const value=root.attributes.show;if(value!==undefined&&!['0','1','false','true'].includes(value))fail('Invalid visibility');return value==='0'||value==='false';}
export function patchSlideVisibility(xml:string,hidden:boolean){if(typeof hidden!=='boolean')fail('Visibility must be Boolean','PPTX_VISIBILITY_INVALID');slideVisibility(xml);return withAttributes(xml,parseXml(xml).root,{show:hidden?'0':'1'});}
