import {OoxmlError} from '../errors.ts';
import {parseXml,elements,attribute,applyEdits,type XmlElement} from '../xml/index.ts';
export type GradientColorTransform={kind:'tint'|'shade'|'lumMod'|'lumOff'|'alpha';value:number};
export type GradientColor={kind:'srgb'|'scheme';value:string;transforms?:GradientColorTransform[]};
export type GradientStop={position:number;color:GradientColor};
export type LinearGradient={angle:number;scaled:boolean;stops:GradientStop[]};
const P='http://schemas.openxmlformats.org/presentationml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',N='http://www.w3.org/2000/xmlns/';
const colors=['dk1','lt1','dk2','lt2','accent1','accent2','accent3','accent4','accent5','accent6','hlink','folHlink','bg1','tx1','bg2','tx2','phClr'],transforms=['tint','shade','lumMod','lumOff','alpha'];
function fail(message:string):never{throw new OoxmlError('PPTX_GRADIENT_UNSUPPORTED',message);}
function plain(value:unknown,allowed:string[]):Record<string,unknown>{if(!value||typeof value!=='object'||![Object.prototype,null].includes(Object.getPrototypeOf(value)))fail('Gradient requires plain data');const copy:Record<string,unknown>={};for(const key of Reflect.ownKeys(value)){if(typeof key!=='string'||!allowed.includes(key))fail('Unknown gradient field');const d=Object.getOwnPropertyDescriptor(value,key)!;if(!('value'in d))fail('Gradient accessors are unsupported');copy[key]=d.value;}return copy;}
function integer(v:unknown,max:number):number{if(typeof v!=='number'||!Number.isInteger(v)||v<0||v>max)fail('Gradient requires bounded integers');return v;}
function list(v:unknown,min:number,max:number):unknown[]{if(!Array.isArray(v)||Object.getPrototypeOf(v)!==Array.prototype||v.length<min||v.length>max)fail('Gradient list exceeds bounds');if(Reflect.ownKeys(v).some(k=>k!=='length'&&(typeof k!=='string'||!/^\d+$/.test(k)||String(Number(k))!==k||Number(k)>=v.length)))fail('Unknown gradient array property');const copy:unknown[]=[];for(let i=0;i<v.length;i++){const d=Object.getOwnPropertyDescriptor(v,String(i));if(!d||!('value'in d))fail('Gradient list accessors are unsupported');copy.push(d.value);}return copy;}
function color(value:unknown):GradientColor{
 const c=plain(value,['kind','value','transforms']);if(!(c.kind==='srgb'&&typeof c.value==='string'&&/^[0-9A-F]{6}$/.test(c.value)||c.kind==='scheme'&&typeof c.value==='string'&&colors.includes(c.value)))fail('Unsupported gradient colour reference');const seen=new Set<string>(),rows=list(Object.hasOwn(c,'transforms')?c.transforms:[],0,5).map(v=>{const t=plain(v,['kind','value']);if(typeof t.kind!=='string'||!transforms.includes(t.kind)||seen.has(t.kind))fail('Unsupported or duplicate colour transform');seen.add(t.kind);return {kind:t.kind as GradientColorTransform['kind'],value:integer(t.value,100000)};});return {kind:c.kind as GradientColor['kind'],value:c.value as string,transforms:rows};
}
function request(value:unknown):LinearGradient{
 const g=plain(value,['angle','scaled','stops']);if(typeof g.scaled!=='boolean')fail('Gradient scaling requires a Boolean');let previous=-1;const stops=list(g.stops,2,16).map(v=>{const s=plain(v,['position','color']),position=integer(s.position,100000);if(position<=previous)fail('Gradient stop positions must ascend strictly');previous=position;return {position,color:color(s.color)};});if(stops[0]!.position!==0||stops.at(-1)!.position!==100000)fail('Gradient requires exact boundary stops');return {angle:integer(g.angle,21599999),scaled:g.scaled,stops};
}
function attrs(n:XmlElement,allowed:string[],required:string[]=[]){const k=Object.keys(n.attributes).filter(k=>n.attributeNamespaces[k]!==N);if(k.some(k=>n.attributeNamespaces[k]!==''||!allowed.includes(k))||required.some(name=>!k.includes(name)))fail('Unsupported fill attributes');}
function gaps(source:string,n:XmlElement){if(n.selfClosing)return;let cursor=n.openEnd;for(const c of n.children){if(source.slice(cursor,c.start).trim())fail('Gradient lexical barrier');cursor=c.end;}if(source.slice(cursor,n.closeStart).trim())fail('Gradient lexical barrier');}
function number(n:XmlElement,key:string):number{const v=attribute(n,key);if(v===undefined||!/^\d+$/.test(v))fail('Invalid gradient integer attribute');return Number(v);}
function bool(n:XmlElement,key:string,defaultValue?:boolean):boolean{const v=attribute(n,key);if(v===undefined&&defaultValue!==undefined)return defaultValue;if(v==='0'||v==='false')return false;if(v==='1'||v==='true')return true;return fail('Invalid gradient Boolean');}
function readColor(source:string,n:XmlElement):GradientColor{if(n.namespaceURI!==A||!['srgbClr','schemeClr'].includes(n.localName))fail('Unsupported colour class');attrs(n,['val'],['val']);gaps(source,n);const rows=n.children.map(t=>{if(t.namespaceURI!==A||!transforms.includes(t.localName)||t.children.length)fail('Unsupported colour transform');attrs(t,['val'],['val']);gaps(source,t);return {kind:t.localName,value:number(t,'val')};});return color({kind:n.localName==='srgbClr'?'srgb':'scheme',value:attribute(n,'val'),transforms:rows});}
function read(source:string,n:XmlElement):LinearGradient{
 attrs(n,['rotWithShape'],['rotWithShape']);if(!bool(n,'rotWithShape'))fail('Gradient must rotate with shape');gaps(source,n);if(n.children.length!==2||n.children[0]!.namespaceURI!==A||n.children[0]!.localName!=='gsLst'||n.children[1]!.namespaceURI!==A||n.children[1]!.localName!=='lin')fail('Only bounded linear gradients are supported');const stops=n.children[0]!,lin=n.children[1]!;attrs(stops,[]);gaps(source,stops);attrs(lin,['ang','scaled'],['ang','scaled']);gaps(source,lin);if(lin.children.length)fail('Decorated linear gradient');return request({angle:number(lin,'ang'),scaled:bool(lin,'scaled'),stops:stops.children.map(s=>{if(s.namespaceURI!==A||s.localName!=='gs'||s.children.length!==1)fail('Invalid gradient stop');attrs(s,['pos'],['pos']);gaps(source,s);return {position:number(s,'pos'),color:readColor(source,s.children[0]!)};})});
}
function selected(source:string,id:number){
 if(!Number.isInteger(id)||id<1||id>2147483647)fail('Invalid gradient shape ID');const doc=parseXml(source);if(doc.root.namespaceURI!==P||doc.root.localName!=='sld')fail('Expected slide root');const trees=doc.root.children.filter(n=>n.namespaceURI===P&&n.localName==='cSld').flatMap(n=>n.children.filter(c=>c.namespaceURI===P&&c.localName==='spTree'));if(trees.length!==1)fail('Missing unique shape tree');const seen=new Set<number>();for(const n of elements(doc,'cNvPr',P)){const v=number(n,'id');if(!Number.isSafeInteger(v)||v<1||v>2147483647||seen.has(v))fail('Invalid or duplicate shape identity');seen.add(v);}
 const nodes=trees[0]!.children.filter(n=>n.namespaceURI===P&&n.localName==='sp'&&n.children.find(c=>c.namespaceURI===P&&c.localName==='nvSpPr')?.children.some(c=>c.namespaceURI===P&&c.localName==='cNvPr'&&number(c,'id')===id));if(nodes.length!==1)fail('Missing unique direct shape');const props=nodes[0]!.children.filter(n=>n.namespaceURI===P&&n.localName==='spPr');if(props.length!==1)fail('Missing unique shape properties');const pr=props[0]!,order=['xfrm','prstGeom','custGeom','noFill','solidFill','gradFill','blipFill','pattFill','grpFill','ln','effectLst','effectDag','scene3d','sp3d','extLst'];let last=-1;gaps(source,pr);for(const n of pr.children){const i=order.indexOf(n.localName);if(n.namespaceURI!==A||i<0||i<=last)fail('Ambiguous shape property order');last=i;}
 const choices=pr.children.filter(n=>['noFill','solidFill','gradFill','blipFill','pattFill','grpFill'].includes(n.localName));if(choices.length>1)fail('Duplicate fill choices');const fill=choices[0];let value:LinearGradient|null=null;
 if(fill){if(fill.localName==='gradFill')value=read(source,fill);else if(fill.localName==='solidFill'){attrs(fill,[]);gaps(source,fill);if(fill.children.length!==1)fail('Ambiguous solid colour');readColor(source,fill.children[0]!);}else if(fill.localName==='noFill'){attrs(fill,[]);gaps(source,fill);if(fill.children.length)fail('Decorated noFill');}else fail('Unsupported source fill');}
 return {pr,fill,value};
}
export function getLinearGradientXml(source:string,id:number):LinearGradient|null{return selected(source,id).value;}
export function setLinearGradientXml(source:string,id:number,input:LinearGradient):string{
 const gradient=request(input),{pr,fill,value}=selected(source,id);if(value&&JSON.stringify(value)===JSON.stringify(gradient))return source;
 const stops=gradient.stops.map(s=>{const tag=s.color.kind==='srgb'?'srgbClr':'schemeClr';return `<a:gs pos="${s.position}"><a:${tag} val="${s.color.value}">${s.color.transforms!.map(t=>`<a:${t.kind} val="${t.value}"/>`).join('')}</a:${tag}></a:gs>`;}).join(''),next=`<a:gradFill xmlns:a="${A}" rotWithShape="1"><a:gsLst>${stops}</a:gsLst><a:lin ang="${gradient.angle}" scaled="${gradient.scaled?'1':'0'}"/></a:gradFill>`;
 if(fill)return applyEdits(source,[{start:fill.start,end:fill.end,value:next}]);
 if(pr.selfClosing)return applyEdits(source,[{start:pr.start,end:pr.end,value:source.slice(pr.start,pr.openEnd).replace(/\/\s*>$/,()=>`>${next}</${pr.name}>`)}]);
 const at=pr.children.find(n=>['ln','effectLst','effectDag','scene3d','sp3d','extLst'].includes(n.localName))?.start??pr.closeStart;return applyEdits(source,[{start:at,end:at,value:next}]);
}
