import {OoxmlError} from '../errors.ts';
import {applyEdits,type XmlElement} from '../xml/index.ts';
import {retainedFormattingXml as x} from './formatting.ts';
const A='http://schemas.openxmlformats.org/drawingml/2006/main',P='http://schemas.openxmlformats.org/presentationml/2006/main';
const fail=(m:string,code='PPTX_STYLE_UNSUPPORTED'):never=>{throw new OoxmlError(code,m);};
export type ShapeStylePatch={fill?:string|null;lineColor?:string|null;lineWidth?:number;lineDash?:'solid'|'dash'|'dot'};
export type TextFramePatch={anchor?:'t'|'ctr'|'b';vert?:'horz'|'vert';wrap?:'none'|'square';lIns?:number;tIns?:number;rIns?:number;bIns?:number;anchorCtr?:boolean;rot?:number;numCol?:number;spcCol?:number;rtlCol?:boolean};
export type RetainedRunEffectsPatch={strike?:'noStrike'|'sngStrike'|'dblStrike';cap?:'none'|'small'|'all';baseline?:number;spc?:number};
const raw=(xml:string,e:XmlElement)=>xml.slice(e.start,e.end);
function unqualified(e:XmlElement){for(const key of x.keys(e))if(e.attributeNamespaces[key]!=='')fail('Foreign direct property attribute');}
function rgb(v:unknown,none=true):string|null{if(v===null)return null;if(typeof v!=='string'||!(none&&v==='none'||/^[0-9A-F]{6}$/.test(v)))fail('Invalid colour','PPTX_STYLE_INVALID');return v as string;}
function propertyOrder(xml:string,owner:XmlElement,names:string[]){x.gaps(xml,owner);let last=-1;for(const c of owner.children){const i=names.indexOf(c.localName);if(c.namespaceURI!==A||i<0||i<=last)fail('Unsupported/ambiguous property order');last=i;}}
const fills=['noFill','solidFill'];
function fillChoice(xml:string,owner:XmlElement){const choices=owner.children.filter(c=>['noFill','solidFill','gradFill','blipFill','pattFill','grpFill'].includes(c.localName));if(choices.length>1)fail('Ambiguous fill');for(const c of choices){unqualified(c);x.gaps(xml,c);if(c.localName==='noFill'){if(x.keys(c).length||c.children.length)fail('Decorated noFill');}else if(c.localName==='solidFill'){const color=x.one(c,'srgbClr');unqualified(color);if(c.children.length!==1||x.keys(c).length||color.children.length||x.keys(color).join()!=='val'||!/^[0-9A-F]{6}$/.test(color.attributes.val??''))fail('Unsupported solid fill');x.gaps(xml,color);}else fail('Unsupported fill choice');}return choices[0];}
function replaceChild(xml:string,owner:XmlElement,old:XmlElement|undefined,value:string,order:string[],name:string){if(old)return applyEdits(xml,[{start:old.start,end:old.end,value}]);if(!value)return xml;if(owner.selfClosing)return applyEdits(xml,[{start:owner.start,end:owner.end,value:xml.slice(owner.start,owner.openEnd).replace(/\/\s*>$/,()=> '>'+value+'</'+owner.name+'>')}]);const next=owner.children.find(c=>order.indexOf(c.localName)>order.indexOf(name));return applyEdits(xml,[{start:next?.start??owner.closeStart,end:next?.start??owner.closeStart,value}]);}
function fillXml(v:string|null){return v===null?'':v==='none'?'<a:noFill xmlns:a="'+A+'"/>':'<a:solidFill xmlns:a="'+A+'"><a:srgbClr val="'+v+'"/></a:solidFill>';}
const shapeOrder=['xfrm','prstGeom','noFill','solidFill','ln'],lineOrder=['noFill','solidFill','prstDash'];
export function patchShapeStyle(xml:string,id:number,value:ShapeStylePatch):string{
 let patch:Record<string,unknown>;try{patch=x.plain(value,['fill','lineColor','lineWidth','lineDash']);}catch{fail('Invalid style patch','PPTX_STYLE_INVALID');}if(!Object.keys(patch!).length)fail('Empty patch','PPTX_STYLE_INVALID');
 const colors:Record<string,string|null>={};for(const k of ['fill','lineColor'])if(Object.hasOwn(patch!,k))colors[k]=rgb(patch![k]);if(Object.hasOwn(patch!,'lineWidth'))x.integer(patch!.lineWidth,0,20116800,'PPTX_STYLE_INVALID');if(Object.hasOwn(patch!,'lineDash')&&!['solid','dash','dot'].includes(patch!.lineDash as string))fail('Invalid line dash','PPTX_STYLE_INVALID');
 const sp=x.shape(xml,id),pr=x.one(sp,'spPr',P),ln=x.one(pr,'ln');propertyOrder(xml,pr,shapeOrder);propertyOrder(xml,ln,lineOrder);unqualified(ln);if(x.keys(ln).some(k=>!['w','cap','cmpd','algn'].includes(k)))fail('Unsupported line attributes');if(ln.attributes.w!==undefined)x.integer(Number(ln.attributes.w),0,20116800);const oldFill=fillChoice(xml,pr),oldLineFill=fillChoice(xml,ln);const dash=x.children(ln,'prstDash');if(dash.length>1||dash.some(c=>c.children.length||x.keys(c).join()!=='val'||!['solid','dash','dot'].includes(c.attributes.val??'')))fail('Invalid existing dash');
 let next=xml;if(Object.hasOwn(colors,'fill'))next=replaceChild(next,pr,oldFill,fillXml(colors.fill!),shapeOrder,colors.fill==='none'?'noFill':'solidFill');
 // Reparse after each independent splice; do not reuse offsets after length changes.
 let current=x.one(x.one(x.shape(next,id),'spPr',P),'ln');if(Object.hasOwn(colors,'lineColor')){next=replaceChild(next,current,fillChoice(next,current),fillXml(colors.lineColor!),lineOrder,colors.lineColor==='none'?'noFill':'solidFill');current=x.one(x.one(x.shape(next,id),'spPr',P),'ln');}
 if(Object.hasOwn(patch!,'lineDash')){next=replaceChild(next,current,x.children(current,'prstDash')[0],'<a:prstDash xmlns:a="'+A+'" val="'+patch!.lineDash+'"/>',lineOrder,'prstDash');current=x.one(x.one(x.shape(next,id),'spPr',P),'ln');}
 if(Object.hasOwn(patch!,'lineWidth'))next=x.withAttributes(next,current,{w:String(patch!.lineWidth)});return next;
}
export function patchTextFrame(xml:string,id:number,value:TextFramePatch):string{
 const patch=x.plain(value,['anchor','vert','wrap','lIns','tIns','rIns','bIns','anchorCtr','rot','numCol','spcCol','rtlCol']);if(!Object.keys(patch).length)fail('Empty body patch');const sp=x.shape(xml,id);x.textBody(xml,sp);const bp=x.one(x.one(sp,'txBody',P),'bodyPr');unqualified(bp);x.gaps(xml,bp);const fit=bp.children;if(fit.length>1||fit.some(c=>c.namespaceURI!==A||!['noAutofit','normAutofit','spAutoFit'].includes(c.localName)||c.children.length))fail('Unsupported body properties');const attrs:Record<string,string>={};for(const[k,v]of Object.entries(patch)){if(['anchorCtr','rtlCol'].includes(k)){if(typeof v!=='boolean')fail('Body Boolean required');attrs[k]=v?'1':'0';}else if(['anchor','vert','wrap'].includes(k)){const values=k==='anchor'?['t','ctr','b']:k==='vert'?['horz','vert']:['none','square'];if(typeof v!=='string'||!values.includes(v))fail('Body enum invalid');attrs[k]=v as string;}else attrs[k]=String(x.integer(v,k==='rot'?-21600000:k==='numCol'?1:0,k==='rot'?21600000:k==='numCol'?16:100000000));}
 for(const key of ['anchorCtr','rtlCol'])if(bp.attributes[key]!==undefined&&!['0','1','true','false'].includes(bp.attributes[key]!))fail('Malformed existing body Boolean');
 for(const [key,values]of [['anchor',['t','ctr','b']],['vert',['horz','vert']],['wrap',['none','square']]] as const)if(bp.attributes[key]!==undefined&&!(values as readonly string[]).includes(bp.attributes[key]!))fail('Malformed existing body enum');
 for(const key of ['rot','numCol','lIns','rIns','tIns','bIns','spcCol'])if(bp.attributes[key]!==undefined){if(!/^-?\d+$/.test(bp.attributes[key]!))fail('Malformed existing body scalar');x.integer(Number(bp.attributes[key]),key==='rot'?-21600000:key==='numCol'?1:0,key==='rot'?21600000:key==='numCol'?16:100000000);}return x.withAttributes(xml,bp,attrs);
}
export function patchRetainedRunEffects(xml:string,id:number,paragraph:number,run:number,value:RetainedRunEffectsPatch):string{
 const patch=x.plain(value,['strike','cap','baseline','spc']);if(!Object.keys(patch).length)fail('Empty effect patch');const sp=x.shape(xml,id),{ps}=x.textBody(xml,sp);if(!Number.isInteger(paragraph)||!ps[paragraph])fail('Missing paragraph');const runs=x.children(ps[paragraph]!,'r');if(!Number.isInteger(run)||!runs[run])fail('Missing run');const r=runs[run]!,existing=x.children(r,'rPr')[0];if(existing){unqualified(existing);for(const key of ['baseline','spc'])if(existing.attributes[key]!==undefined){if(!/^-?\d+$/.test(existing.attributes[key]!))fail('Malformed run scalar');x.integer(Number(existing.attributes[key]),key==='baseline'?-100000:-400000,key==='baseline'?100000:400000);}}const attrs:Record<string,string>={};for(const[k,v]of Object.entries(patch)){if(k==='strike'||k==='cap'){if(typeof v!=='string'||!(k==='strike'?['noStrike','sngStrike','dblStrike']:['none','small','all']).includes(v))fail('Invalid run enum');attrs[k]=v as string;}else attrs[k]=String(x.integer(v,k==='baseline'?-100000:-400000,k==='baseline'?100000:400000));}return x.editProperty(xml,r,'rPr',attrs,{},x.runOrder);
}
