import {OoxmlError} from '../errors.ts';
import {parseXml,elements,applyEdits,escapeText,escapeAttribute,type XmlElement} from '../xml/index.ts';
const P='http://schemas.openxmlformats.org/presentationml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',N='http://www.w3.org/2000/xmlns/';
const fail=(message:string):never=>{throw new OoxmlError('PPTX_SHAPE_TEXT_UNSUPPORTED',message);};
const is=(e:XmlElement,name:string,ns=P)=>e.localName===name&&e.namespaceURI===ns;
const one=(e:XmlElement,name:string,ns=P)=>{const nodes=e.children.filter(n=>is(n,name,ns));if(nodes.length!==1)fail(`Expected one ${name}`);return nodes[0]!;};
function gaps(xml:string,node:XmlElement){if(node.selfClosing)return;let at=node.openEnd;for(const c of node.children){if(!/^[ \t\r\n]*$/.test(xml.slice(at,c.start)))fail('Lexical barriers require explicit policy');at=c.end;}if(!/^[ \t\r\n]*$/.test(xml.slice(at,node.closeStart)))fail('Lexical barriers require explicit policy');}
function shapeModel(xml:string){const doc=parseXml(xml),root=doc.root;if(!is(root,'sld'))fail('Expected slide root');const tree=one(one(root,'cSld'),'spTree');gaps(xml,tree);const ids=new Set<number>();for(const e of elements(doc,'cNvPr',P)){const raw=e.attributes.id,id=raw&&/^\d+$/.test(raw)?Number(raw):NaN;if(!Number.isSafeInteger(id)||id<1||id>2147483647||ids.has(id))fail('Invalid or duplicate shape ID');ids.add(id);}return tree.children.filter(e=>is(e,'sp'));}
function target(xml:string,id:number){if(!Number.isInteger(id)||id<1||id>2147483647)fail('Shape ID must be a bounded integer');const matches=shapeModel(xml).filter(e=>Number(one(one(e,'nvSpPr'),'cNvPr').attributes.id)===id);if(matches.length!==1)fail('Missing or ambiguous direct text shape');const shape=matches[0]!,body=one(shape,'txBody'),pr=one(body,'bodyPr',A),style=one(body,'lstStyle',A);const paragraphs=body.children.filter(e=>is(e,'p',A));if(!paragraphs.length||body.children.some(e=>e!==pr&&e!==style&&!paragraphs.includes(e)))fail('Unsupported text body');gaps(xml,body);
 for(const lock of elements(shape,'spLocks',A)){const attrs=Object.keys(lock.attributes).filter(k=>lock.attributeNamespaces[k]!==N);if(attrs.length!==1||attrs[0]!=='noGrp'||lock.attributes.noGrp!=='1'||lock.children.length)fail('Text shape is locked');}
 for(const p of paragraphs){gaps(xml,p);if(p.children.some(e=>!is(e,'pPr',A)&&!is(e,'r',A)&&!is(e,'endParaRPr',A)))fail('Fields and breaks require another text policy');if(p.children.filter(e=>is(e,'pPr',A)).length>1)fail('Ambiguous paragraph properties');for(const r of p.children.filter(e=>is(e,'r',A))){gaps(xml,r);const leaf=one(r,'t',A);if(leaf.children.length||!leaf.selfClosing&&xml.slice(leaf.openEnd,leaf.closeStart).includes('<'))fail('Mixed text-leaf markup requires another policy');if(r.children.some(e=>!is(e,'t',A)&&!is(e,'rPr',A))||r.children.filter(e=>is(e,'rPr',A)).length>1)fail('Unsupported run');for(const rp of r.children.filter(e=>is(e,'rPr',A)))if(rp.children.length)fail('Run links/extensions require another policy');}}
 return {shape,body,pr,paragraphs};}
export type TextShape={shapeId:number;name:string;placeholder?:string;text:string;paragraphs:{text:string;level:number}[]};
export function inspectTextShapes(xml:string):TextShape[]{return shapeModel(xml).filter(s=>s.children.some(e=>is(e,'txBody'))).map(s=>{const nv=one(s,'nvSpPr'),identity=one(nv,'cNvPr'),id=Number(identity.attributes.id),m=target(xml,id),ph=elements(nv,'ph',P);const paragraphs=m.paragraphs.map(p=>{const raw=p.children.find(e=>is(e,'pPr',A))?.attributes.lvl??'0';if(!/^[0-8]$/.test(raw))fail('Invalid paragraph level');return {text:p.children.filter(e=>is(e,'r',A)).map(r=>one(r,'t',A).text).join(''),level:Number(raw)};});return {shapeId:id,name:identity.attributes.name??'',...(ph.length?{placeholder:ph[0]!.attributes.type??'obj'}:{}),text:paragraphs.map(p=>p.text).join('\n'),paragraphs};});}
function text(value:string){if(typeof value!=='string')fail('Text must be a string');escapeText(value);return value.replace(/\r\n/g,'\n');}
const line=(value:string)=>`<a:p xmlns:a="${A}"><a:r><a:t xml:space="preserve">${escapeText(value)}</a:t></a:r></a:p>`;
function replaceParagraphs(xml:string,id:number,newParagraphs:string,append=false){const m=target(xml,id),first=m.paragraphs[0]!,last=m.paragraphs.at(-1)!;for(const [i,p]of m.paragraphs.entries())if(i&&xml.slice(m.paragraphs[i-1]!.end,p.start).trim())fail('Paragraph lexical barriers');if(append)return applyEdits(xml,[{start:last.end,end:last.end,value:newParagraphs}]);return applyEdits(xml,[{start:first.start,end:last.end,value:newParagraphs}]);}
/** A bounded plain-text replacement; line feeds delimit paragraphs, including empty ones. */
export function patchShapeText(xml:string,id:number,value:string,append=false):string{if(typeof append!=='boolean')fail('Append must be boolean');return replaceParagraphs(xml,id,text(value).split('\n').map(line).join(''),append);}
export function clearShapeText(xml:string,id:number):string{return replaceParagraphs(xml,id,line(''));}
export function appendShapeBullet(xml:string,id:number,value:string,level=0,boldLabel?:string):string{const v=text(value);if(v.includes('\n')||!Number.isInteger(level)||level<0||level>8)fail('Bullet requires one text line and level 0..8');if(boldLabel!==undefined&&(typeof boldLabel!=='string'||!boldLabel||text(boldLabel).includes('\n')))fail('Bold label must be one nonempty line');const run=(v:string,bold=false)=>`<a:r>${bold?'<a:rPr b="1"/>':''}<a:t xml:space="preserve">${escapeText(v)}</a:t></a:r>`;const bullet=`<a:p xmlns:a="${A}"><a:pPr lvl="${level}"><a:buChar char="${escapeAttribute('•')}"/></a:pPr>${boldLabel!==undefined?run(boldLabel+': ',true):''}${run(v)}</a:p>`;const m=target(xml,id);const empty=m.paragraphs.length===1&&m.paragraphs[0]!.text==='';return replaceParagraphs(xml,id,bullet,!empty);}
export function setShapeAutofit(xml:string,id:number,mode:'shrink'|'none'|'resize'):string{if(!['shrink','none','resize'].includes(mode))fail('Unknown autofit mode');const name=({shrink:'normAutofit',none:'noAutofit',resize:'spAutoFit'} as Record<string,string>)[mode]!;const pr=target(xml,id).pr;gaps(xml,pr);const fits=pr.children.filter(e=>e.namespaceURI===A&&['normAutofit','noAutofit','spAutoFit'].includes(e.localName));if(fits.length>1||pr.children.some(e=>e.namespaceURI!==A||!['normAutofit','noAutofit','spAutoFit','prstTxWarp','scene3d','sp3d','flatTx','extLst'].includes(e.localName)))fail('Ambiguous or unsupported body properties');const child=`<a:${name} xmlns:a="${A}"/>`;if(fits.length){const f=fits[0]!;return applyEdits(xml,[{start:f.start,end:f.end,value:child}]);}if(pr.selfClosing)return applyEdits(xml,[{start:pr.start,end:pr.end,value:xml.slice(pr.start,pr.openEnd).replace(/\/\s*>$/,`>${child}</${pr.name}>`)}]);const at=pr.children.find(e=>['scene3d','sp3d','flatTx','extLst'].includes(e.localName))?.start??pr.closeStart;return applyEdits(xml,[{start:at,end:at,value:child}]);}
