/** Executable usage check: real fixture input, separate output, saved/reopened effect. */
import { Document, Presentation, Workbook } from "../src/index.ts";
import { join } from "node:path";
import { mkdir } from "node:fs/promises";
const root = join(import.meta.dir,"..");
const output = join(root,"artifacts/examples");
await mkdir(output,{recursive:true});
const fixtures = join(root,"fixtures/go-ooxml/testdata");
const doc = await Document.open(join(fixtures,"word/single_paragraph.docx"));
const paragraph = doc.paragraphs[0];
if (!paragraph?.text) throw new Error("Missing fixture paragraph");
paragraph.find(paragraph.text)[0]!.replace("Bun-native edited paragraph.");
await doc.save(join(output,"edited.docx"));
const checkedDoc = await Document.open(join(output,"edited.docx"));
if (checkedDoc.paragraphs[0]?.text !== "Bun-native edited paragraph.") throw new Error("DOCX edit lost");
const deck = await Presentation.open(join(fixtures,"pptx/title_slide.pptx"));
const slide = deck.slides[0];
if (!slide) throw new Error("Missing fixture slide");
const block = slide.inspectText("").find(x=>x.text.length>0);
if (!block) throw new Error("Missing fixture text");
slide.replaceTextAt(block.anchor,block.text,"Bun-native edited slide.");
await deck.save(join(output,"edited.pptx"));
const checkedDeck = await Presentation.open(join(output,"edited.pptx"));
if (!checkedDeck.slides[0]!.inspectText("Bun-native edited slide.").length) throw new Error("PPTX edit lost");
const wb = await Workbook.open(join(fixtures,"excel/data_types.xlsx"));
const sheet = wb.worksheet(wb.sheetnames[0]!);
sheet.setCellValue("A2","Bun-native edited cell.");
await wb.save(join(output,"edited.xlsx"));
const checkedWb = await Workbook.open(join(output,"edited.xlsx"));
if (checkedWb.worksheet(wb.sheetnames[0]!).getCell("A2")?.value !== "Bun-native edited cell.") throw new Error("XLSX edit lost");
console.log("DOCX, PPTX and XLSX examples saved and reopened with expected edits.");
