import { join } from "node:path";
import { inventoryFeatures } from "./gherkin.ts";
const root = join(import.meta.dir,"..");
const inventory = await inventoryFeatures(root);
const ledger = await Bun.file(join(root,"docs/contracts/parity-ledger.json")).json();
const manifest = await Bun.file(join(root,"references/manifest.json")).json();
const lines = ["# Behaviour coverage", "", "Generated by `bun run scripts/coverage.ts` from Gherkin and the behaviour ledger.", "This inventory describes mappings, not execution success. Run `make check` for", "current per-step results in `artifacts/acceptance.json`.", "", "| Inventory | Implemented | Planned | Total |", "|---|---:|---:|---:|"];
for (const key of ["features","scenarios","cases","steps"] as const) {
 const value=inventory.counts[key]; lines.push(`| ${key} | ${value.implemented} | ${value.planned} | ${value.total} |`);
}
lines.push("", "## Source/test mappings", "", "| Source | Source files | Test files | Mapped | Gaps/partial |", "|---|---:|---:|---:|---:|");
for (const source of manifest.sources) {
 const rows=ledger.rows.filter((r:any)=>r.source===source.id);
 if (!rows.length)continue;
 lines.push(`| ${source.id} | ${rows.filter((r:any)=>r.role==="source").length} | ${rows.filter((r:any)=>r.role==="test").length} | ${rows.filter((r:any)=>r.state==="mapped").length} | ${rows.filter((r:any)=>r.state!=="mapped").length} |`);
}
lines.push("", "Both rcarmo fixture corpora contain 37 Office archives, 74 total. All imported", `${manifest.files.length} files are hash-pinned. Module/test file gaps require API/test-case`, "refinement and reviewed Gherkin step mappings before receiving parity credit.", "", "## Feature files", "");
for (const f of inventory.features)lines.push(`* \`${f.path}\`: ${f.lifecycle}, ${f.scenarios.length} scenario(s), ${f.scenarios.reduce((n,s)=>n+s.cases.length,0)} expanded case(s).`);
const text=lines.join("\n")+"\n";
const destination=join(root,"docs/contracts/behaviour-coverage.md");
if(Bun.argv.includes("--check")) {
 if(!await Bun.file(destination).exists() || await Bun.file(destination).text()!==text) throw new Error("Coverage report stale; run bun run scripts/coverage.ts");
 console.log("Coverage inventory matches checked-in report.");
} else { await Bun.write(destination,text); console.log("Wrote docs/contracts/behaviour-coverage.md"); }
