import {join,basename} from 'node:path';import {OpcPackage,inspectRevisions,resolveRevisions} from '../src/index.ts';
export type MultistoryMode='source'|'accept'|'reject'|'unsupported';
type Run={text:string;bold:boolean;italic:boolean;elements:string[]};type Story={kind:string;part:string;revisions:{kind:string;id:string}[];paragraphs:{runs:Run[]}[]};
const parts=['word/document.xml','word/header1.xml','word/footer1.xml','word/footnotes.xml'];
const run=(text:string,bold=false,italic=false,elements?:string[]):Run=>({text,bold,italic,elements:elements??(bold||italic?['rPr','t']:['t'])});
/** Literal semantic expectations, independent of SDK output and Bun XML traversal. */
export function expectedStories(mode:MultistoryMode):Story[]{const revision=mode==='source'||mode==='unsupported';return ['Body','Header','Footer','Footnote'].map((label,i)=>{
 const paragraphs=[{runs:[run(label+' unchanged')]},{runs:revision?[run(label+' original',false,false,['delText']),run(label+' revised')]:[run(label+(mode==='accept'?' revised':' original'))]},{runs:[run(label+' formatted',mode!=='reject',mode==='reject')]},{runs:revision?[run(label+' moved',true),run(label+' middle'),run(label+' moved',true)]:mode==='accept'?[run(label+' middle'),run(label+' moved',true)]:[run(label+' moved',true),run(label+' middle')]}];
 if(i===0)paragraphs.push({runs:[run('',false,false,['footnoteReference'])]});
 if(i===3){paragraphs.unshift({runs:[run('',false,false,['separator'])]},{runs:[run('',false,false,['continuationSeparator'])]});if(mode==='unsupported')paragraphs.push({runs:[run('Unsupported paragraph history')]});}
 const revisions=revision?[{kind:'del',id:'1'},{kind:'ins',id:'2'},{kind:'rPrChange',id:'3'},{kind:'moveFrom',id:'11'},{kind:'moveTo',id:'13'}]:[];if(i===3&&mode==='unsupported')revisions.push({kind:'pPrChange',id:'900'});
 return {kind:['body','header','footer','footnotes'][i]!,part:parts[i]!,revisions,paragraphs};});}
const check=(ok:unknown,message:string)=>{if(!ok)throw Error('Multistory oracle: '+message);};
function stable(value:unknown):string{if(Array.isArray(value))return '['+value.map(stable).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+stable((value as Record<string,unknown>)[k])).join(',')+'}';return JSON.stringify(value);}
export function verifyMultistoryEvidence(raw:unknown,file:string,hash:string,mode:MultistoryMode):Story[]{const r=raw as any;check(r?.schemaVersion===1&&r.validator==='DocumentFormat.OpenXml'&&typeof r.version==='string'&&/^3\.5\.1(?:\+|$)/.test(r.version)&&r.profile==='Office2019'&&r.status==='passed','reader identity/status');check(Array.isArray(r.results)&&r.results.length===1,'one explicit file required');const row=r.results[0];check(row.file===basename(file)&&row.sha256===hash&&/^[a-f0-9]{64}$/.test(hash),'file custody identity');check(Array.isArray(row.errors)&&row.errors.length===0&&row.truncated===false&&!('exception'in row),'schema/refusal result');check(stable(row.wordStories)===stable(expectedStories(mode)),'story readback differs');return row.wordStories;}
const sha=(b:Uint8Array)=>new Bun.CryptoHasher('sha256').update(b).digest('hex');
type Command=(args:string[])=>Promise<{exit:number|null;stdout:string;stderr:string;timedOut?:boolean;outputLimited?:boolean}>;
/** Development-only producer + schema + reader + exact package payload comparison. */
export async function runMultistoryOracle(out:string,validator:string,command:Command){const generated=await command(['dotnet',validator,'--generate-multistory',out]);check(generated.exit===0&&!generated.timedOut&&!generated.outputLimited,'SDK producer failed');const g=JSON.parse(generated.stdout);check(g.schemaVersion===1&&g.producer==='DocumentFormat.OpenXml'&&typeof g.version==='string'&&/^3\.5\.1(?:\+|$)/.test(g.version),'producer identity');const inputs=['source','accept','reject','unsupported'].map(m=>join(out,`multistory-${m}.docx`));check(stable(g.files)===stable(inputs),'producer file inventory');const hashes=await Promise.all(inputs.map(async p=>sha(await Bun.file(p).bytes()))),evidence:any[]=[];
 async function read(path:string,mode:MultistoryMode){const hash=sha(await Bun.file(path).bytes()),r=await command(['dotnet',validator,path]);check(r.exit===0&&!r.timedOut&&!r.outputLimited,'SDK reader failed');const result=JSON.parse(r.stdout),stories=verifyMultistoryEvidence(result,path,hash,mode);check(sha(await Bun.file(path).bytes())===hash,'reader modified file');return {file:basename(path),sha256:hash,stories,reader:result};}
 for(const [i,mode]of (['source','accept','reject','unsupported'] as const).entries())evidence.push(await read(inputs[i]!,mode));
 const source=await OpcPackage.open(inputs[0]!),sourceBytes=source.toBytes(),inspection=inspectRevisions(source,{profile:'text-properties-and-moves'});check(inspection.unsupported.length===0&&inspection.revisions.length===20,'native source inventory');for(const part of parts)check(inspection.revisions.filter(r=>r.part===part).map(r=>r.kind).join(',')==='deletion,insertion,run-properties,move-from,move-to','all four revision families must occur per story');check(Buffer.compare(source.toBytes(),sourceBytes)===0,'inspection mutated source');
 const outputs:any[]=[];
 for(const [index,action]of (['accept','reject'] as const).entries()){
  const pkg=await OpcPackage.open(inputs[0]!),expected=await OpcPackage.open(inputs[index+1]!),receipt=resolveRevisions(pkg,action,{profile:'text-properties-and-moves',parts});check(stable(receipt)===stable({resolved:20,changedParts:parts}),'native receipt');const path=join(out,`native-${action}.docx`);await pkg.save(path);const readback=await OpcPackage.open(path);check(stable(readback.names())===stable(source.names())&&stable(expected.names())===stable(source.names()),'part inventory changed');
  for(const part of source.names())check(Buffer.compare(readback.get(part)!,parts.includes(part)?expected.get(part)!:source.get(part)!)===0,'unexpected bytes in '+part);
  check(stable(inspectRevisions(readback,{profile:'text-properties-and-moves'}))===stable({revisions:[],unsupported:[]}),'native unresolved output');const before=readback.toBytes();check(stable(resolveRevisions(readback,action,{profile:'text-properties-and-moves'}))===stable({resolved:0,changedParts:[]}),'native no-op receipt');check(Buffer.compare(before,readback.toBytes())===0,'native no-op changed bytes');outputs.push({...await read(path,action),receipt});
 }
 const negative=await OpcPackage.open(inputs[3]!),negativeBytes=negative.toBytes(),findings=inspectRevisions(negative,{profile:'text-properties-and-moves'});check(findings.revisions.length===20&&findings.unsupported.length===1&&findings.unsupported[0]?.part===parts[3]&&findings.unsupported[0]?.kind==='format','unsupported footnote evidence');for(const action of ['accept','reject'] as const){let error:unknown;try{resolveRevisions(negative,action,{profile:'text-properties-and-moves',parts});}catch(e){error=e;}check((error as any)?.code==='docx-revisions-unsupported','unsupported selected story did not refuse');check(Buffer.compare(negative.toBytes(),negativeBytes)===0,'unsupported refusal changed package');}
 for(const [i,path]of inputs.entries())check(sha(await Bun.file(path).bytes())===hashes[i],'source/expectation archive changed');
 // Independently read deliberately wrong but schema-valid output: protocol must reject.
 const controls:any[]=[];for(const mode of ['text','format','order']){const bad=await OpcPackage.open(inputs[1]!),part=parts[1]!,xml=bad.text(part);let changed=mode==='text'?xml.replace('Header revised','Wrong revised'):mode==='format'?xml.replace('<w:b />','<w:i />').replace('<w:b/>','<w:i/>'):xml.replace(/(<w:r><w:t xml:space="preserve">Header middle<\/w:t><\/w:r>)(<w:r><w:rPr><w:b\s*\/><\/w:rPr><w:t xml:space="preserve">Header moved<\/w:t><\/w:r>)/,'$2$1');check(changed!==xml,'negative mutation did not reach '+mode);bad.set(part,changed);const path=join(out,`negative-${mode}.docx`);await bad.save(path);const hash=sha(await Bun.file(path).bytes()),r=await command(['dotnet',validator,path]);check(r.exit===0&&!r.timedOut&&!r.outputLimited,'negative must remain schema valid');const raw=JSON.parse(r.stdout);check(raw.schemaVersion===1&&raw.validator==='DocumentFormat.OpenXml'&&raw.status==='passed'&&raw.results?.length===1&&raw.results[0]?.file===basename(path)&&raw.results[0]?.sha256===hash&&raw.results[0]?.errors?.length===0&&raw.results[0]?.truncated===false&&!('exception' in raw.results[0]),'negative needs successful independent schema evidence');let refused=false;try{verifyMultistoryEvidence(raw,path,hash,'accept');}catch{refused=true;}check(refused,'negative readback passed '+mode);check(sha(await Bun.file(path).bytes())===hash,'negative input mutated');controls.push({mode,sha256:hash,status:'rejected'});}
 return {status:'passed',producer:{name:g.producer,version:g.version},inputs:evidence,outputs,unsupported:{findings:findings.unsupported,actions:['accept','reject'],unchanged:true},controls,scope:'SDK-authored source and independently authored expected documents, four named stories, supported text/property/move profiles; no Word UI/rendering or general revision compatibility'};
}
