import {OoxmlError} from './errors.ts';
import {applyEdits,attribute,escapeAttribute,type XmlElement} from './xml/index.ts';
export const A='http://schemas.openxmlformats.org/drawingml/2006/main',P='http://schemas.openxmlformats.org/presentationml/2006/main',W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',XMLNS='http://www.w3.org/2000/xmlns/';
export const fail=(m:string,code='TABLE_PROPERTIES_UNSUPPORTED'):never=>{throw new OoxmlError(code,m);};
export const direct=(e:XmlElement,n:string,ns:string)=>e.children.filter(c=>c.localName===n&&c.namespaceURI===ns);
export function one(e:XmlElement,n:string,ns:string){const list=direct(e,n,ns);if(list.length!==1)fail('Expected unique direct '+n);return list[0]!;}
export function ordinal(v:number,n:number){if(!Number.isSafeInteger(v)||v<0||v>=n)fail('Missing direct index');return v;}
export function integer(v:unknown,min:number,max:number){if(!Number.isSafeInteger(v)||Number(v)<min||Number(v)>max)fail('Invalid bounded integer','TABLE_PROPERTIES_INVALID');return Number(v);}
export function plain(v:unknown,keys:readonly string[]):Record<string,unknown>{if(!v||typeof v!=='object'||![Object.prototype,null].includes(Object.getPrototypeOf(v)))fail('Expected plain data patch','TABLE_PROPERTIES_INVALID');const out:Record<string,unknown>={};for(const key of Reflect.ownKeys(v as object)){if(typeof key!=='string'||!keys.includes(key))fail('Unknown table property','TABLE_PROPERTIES_INVALID');const d=Object.getOwnPropertyDescriptor(v as object,key)!;if(!('value'in d))fail('Executable property','TABLE_PROPERTIES_INVALID');out[key as string]=d.value;}if(!Object.keys(out).length)fail('Empty patch','TABLE_PROPERTIES_INVALID');return out;}
export function rgb(v:unknown){if(typeof v!=='string'||!/^[0-9A-F]{6}$/.test(v))fail('Invalid RGB','TABLE_PROPERTIES_INVALID');return v as string;}
export function gaps(xml:string,e:XmlElement){if(e.selfClosing)return;let at=e.openEnd;for(const c of e.children){if(!/^[ \t\r\n]*$/.test(xml.slice(at,c.start)))fail('Lexical/mixed-content barrier');at=c.end;}if(!/^[ \t\r\n]*$/.test(xml.slice(at,e.closeStart)))fail('Lexical/mixed-content barrier');}
export function order(xml:string,e:XmlElement,ns:string,names:readonly string[]){gaps(xml,e);let last=-1;for(const c of e.children){const rank=names.indexOf(c.localName);if(c.namespaceURI!==ns||rank<0||rank<=last)fail('Unsupported property order/duplicate');last=rank;}}
export function attrs(e:XmlElement,ns:string,names:readonly string[]){for(const key of Object.keys(e.attributes))if(e.attributeNamespaces[key]!==XMLNS&&(e.attributeNamespaces[key]!==ns||!names.includes(key.split(':').at(-1)!)))fail('Unsupported property attributes');}
export function leaf(xml:string,e:XmlElement,ns:string,names:readonly string[]){attrs(e,ns,names);gaps(xml,e);if(e.children.length)fail('Unsupported leaf child');}
export function opening(xml:string,e:XmlElement,ns:string,values:Record<string,string|null>,prefix:string){const raw=xml.slice(e.start,e.openEnd),tokens:{name:string;start:number;end:number;vs:number;ve:number}[]=[];let at=raw.match(/^<[^\s/>]+/)![0].length;while(at<raw.length){if(/^\s*\/?\s*>$/.test(raw.slice(at)))break;const m=raw.slice(at).match(/^(\s+)([^\s=/>]+)(\s*=\s*)(["'])([^]*?)\4/);if(!m)throw new OoxmlError('TABLE_PROPERTIES_UNSUPPORTED','Invalid quoted opening');const vs=at+m[1]!.length+m[2]!.length+m[3]!.length+1;tokens.push({name:m[2]!,start:at,end:at+m[0].length,vs,ve:vs+m[5]!.length});at+=m[0].length;}
const edits:{start:number;end:number;value:string}[]=[],extras:string[]=[];for(const[k,v]of Object.entries(values)){const matches=tokens.filter(t=>e.attributeNamespaces[t.name]===ns&&t.name.split(':').at(-1)===k);if(matches.length>1)fail('Duplicate expanded property');const t=matches[0];if(t){if(v===null)edits.push({start:t.start,end:t.end,value:''});else if(attribute(e,k,ns)!==v)edits.push({start:t.vs,end:t.ve,value:escapeAttribute(v)});}else if(v!==null)extras.push(' '+(prefix?prefix+':':'')+k+'="'+escapeAttribute(v)+'"');}let result=raw;for(const change of edits.sort((a,b)=>b.start-a.start))result=result.slice(0,change.start)+change.value+result.slice(change.end);if(extras.length)result=result.replace(/\/?\s*>$/,m=>(prefix&&!Object.hasOwn(e.attributes,'xmlns:'+prefix)?' xmlns:'+prefix+'="'+ns+'"':'')+extras.join('')+m);return result;}
export function setAttrs(xml:string,e:XmlElement,ns:string,values:Record<string,string|null>,prefix=''){return applyEdits(xml,[{start:e.start,end:e.openEnd,value:opening(xml,e,ns,values,prefix)}]);}
export function replaceChild(xml:string,owner:XmlElement,ns:string,name:string,value:string|null,names:readonly string[]){const old=direct(owner,name,ns);if(old.length>1)fail('Duplicate direct '+name);if(old[0]){if(value===null)return applyEdits(xml,[{start:old[0].start,end:old[0].end,value:''}]);if(xml.slice(old[0].start,old[0].end)===value)return xml;return applyEdits(xml,[{start:old[0].start,end:old[0].end,value}]);}if(value===null)return xml;if(owner.selfClosing)return applyEdits(xml,[{start:owner.start,end:owner.end,value:xml.slice(owner.start,owner.end).replace(/\/\s*>$/,()=> '>'+value+'</'+owner.name+'>')}]);const next=owner.children.find(c=>names.indexOf(c.localName)>names.indexOf(name)),at=next?.start??owner.closeStart;return applyEdits(xml,[{start:at,end:at,value}]);}
export const xmlLeaf=(ns:string,prefix:string,name:string,values:Record<string,string|number>)=>'<'+prefix+':'+name+' xmlns:'+prefix+'="'+ns+'"'+Object.entries(values).map(([k,v])=>' '+(ns===W?prefix+':':'')+k+'="'+escapeAttribute(String(v))+'"').join('')+'/>';
