import {beforeSharedPlannedExpansion} from './mapping-history.ts';
import {test,expect} from 'bun:test';import {outcomeMappingReport,reconcileOutcomeMappingSets,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';import {inventoryTestSource} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {join} from 'node:path';
const path='tests/unit/package-admission.test.ts',canonical=['workflows/package/zip-admission.feature','workflows/package/xml-member-admission.feature','workflows/package/admission-limit-configuration.feature'];
const pins=[path,'tests/acceptance/package-admission.ts','tests/fixtures/admission.ts','src/opc/admission.ts','src/opc/package.ts','src/opc/zip.ts','src/xml/index.ts','src/xml/encoding.ts','src/index.ts','src/errors.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts',...canonical];
async function sample(){const ledger=await Bun.file('docs/behaviors/package-admission-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of pins)sources[p]=await Bun.file(canonical.includes(p)?join(fixturesRoot(),p):p).text();return {inventory:{cases:inventoryTestSource(path,sources[path]!),unresolved:[]},sets:[{name:'package-admission',expectedScopePaths:[path],ledger,features:canonical.map(p=>parseFeature(p,sources[p]!)),sources}]};}
test('admission ledger accounts for 11 declarations and 36 expressions across three canonical files preserving 461 rows',async()=>{
 const r=await outcomeMappingReport(),rows=r.mappings.filter(m=>m.ledger==='package-admission');expect(rows).toHaveLength(11);expect(rows.reduce((n,m)=>n+m.assertions.length,0)).toBe(36);expect(r.ledgers.find(l=>l.name==='package-admission')!.scopePaths).toEqual([path]);expect(rows.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([13]);expect(new Set(rows[8]!.scenarioIds).size).toBe(4);expect(rows.every(m=>m.status==='partial'&&m.executionCredit===false&&m.gaps.length&&m.outcomes.length)).toBe(true);expect(r.mappedDeclarations).toBe(590);expect(r.unmappedTestIds.length).toBe(r.totalDeclarations-590);expect(r.runtimeLeafCount).toBeNull();expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(beforeSharedPlannedExpansion(r.mappings.filter(m=>!['package-admission','tracking-settings','heading-classification','nullable-cell','table-merging','template-inventory','comment-threads','revision-properties','revision-moves'].includes(m.ledger))))).digest('hex')).toBe('146c23e8d48a2aa3bc15653cbe54577a66d40537ab3ffdbfcb1d367e9f0bc69b');
});
test('admission gaps preserve graph-independent success controls BZIP2 framing and syntax-only boundary scope',async()=>{
 const rows=(await outcomeMappingReport()).mappings.filter(m=>m.ledger==='package-admission');expect(rows[0]!.gaps.join(' ')).toContain('positive');expect(rows[5]!.gaps.join(' ')).toContain('four-byte');expect(rows[7]!.gaps.join(' ')).toContain('BZIP2 decoding');expect(rows[8]!.gaps.join(' ')).toContain('aggregate');expect(rows[9]!.gaps.join(' ')).toContain('network');expect(rows[10]!.gaps.join(' ')).toContain('timing');expect(rows[10]!.gaps.join(' ')).toContain('parser');
});
test('admission scope assertions and missing second canonical feature cannot silently pass',async()=>{
 const a=await sample();a.sets[0]!.ledger.scopePaths=[];expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('scope');const b=await sample();b.sets[0]!.ledger.mappings.pop();expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('Missing scoped');const c=await sample();c.sets[0]!.ledger.mappings[0]!.assertions.pop();expect(()=>reconcileOutcomeMappingSets(c.inventory,c.sets)).toThrow('assertion');for(const p of canonical){const d=await sample();d.sets[0]!.features=d.sets[0]!.features.filter(f=>f.path!==p);expect(()=>reconcileOutcomeMappingSets(d.inventory,d.sets)).toThrow('scenario');}const e=await sample();e.sets[0]!.ledger.mappings[0]!.caseKeys=['@id-opc-add-related-part'];expect(()=>reconcileOutcomeMappingSets(e.inventory,e.sets)).toThrow('case');
});
test('admission pins require both canonical sources and each runtime helper and test source',async()=>{
 for(const p of pins){const a=await sample();expect(Object.hasOwn(a.sets[0]!.ledger.sourceSha256,p)).toBe(true);a.sets[0]!.sources[p]+=' ';expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('Stale source');const b=await sample();delete b.sets[0]!.ledger.sourceSha256[p];expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('pin');}
});
test('admission reconciliation preserves inputs direct deferred assertion sets and review flags without runtime leaves',async()=>{
 const a=await sample(),before=JSON.stringify(a),r=reconcileOutcomeMappingSets(a.inventory,a.sets);expect(JSON.stringify(a)).toBe(before);expect(r.mappings.map(m=>m.assertions)).toEqual(a.inventory.cases.map(m=>m.assertions));expect(r.mappings.map(m=>m.deferredAssertions)).toEqual(a.inventory.cases.map(m=>m.deferredAssertions));expect(r.mappings.map(m=>m.reviewReasons)).toEqual(a.inventory.cases.map(m=>m.reviewReasons));expect(r.executionCredit).toBe(false);expect(r.runtimeLeafCount).toBeNull();
});
