import {test,expect} from 'bun:test';import {join} from 'node:path';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {inventoryNativeTests} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {outcomeMappingReport,reconcileOutcomeMappings,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';
async function input(){const ledger=await Bun.file('docs/behaviors/comment-threads-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of Object.keys(ledger.sourceSha256))sources[p]=await Bun.file(p.startsWith('workflows/')?join(fixturesRoot(),p):p).text();const feature=parseFeature('workflows/docx/comments.feature',sources['workflows/docx/comments.feature']!,{allowDuplicateCaseNames:true});return {ledger,sources,inventory:await inventoryNativeTests(),features:[{...feature,scenarios:feature.scenarios.filter(s=>s.scenarioId.startsWith('@id-docx-existing-thread-'))}]};}
test('existing-thread mappings add16 partial records and23 exact case keys preserving546 prior rows except four totals',async()=>{const x=await input(),r=reconcileOutcomeMappings(x.inventory,x.ledger,x.features,x.sources);expect(r.mappedDeclarations).toBe(16);expect(r.mappings.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([23]);expect(r.mappings.every(m=>m.status==='partial'&&m.gaps.length>0&&m.scenarioIds.every(id=>id.startsWith('@id-docx-existing-thread-')))).toBe(true);const all=await outcomeMappingReport(),prior=structuredClone(all.mappings.filter(m=>m.ledger!=='comment-threads'&&m.ledger!=='revision-properties'&&m.ledger!=='revision-moves'));expect(prior).toHaveLength(546);let corrected=0;for(const row of prior)if(row.assertions.includes('expect(inv.counts.cases.implemented).toBe(726)')){row.assertions=row.assertions.map(a=>a.replace('counts.cases.implemented).toBe(726)','counts.cases.implemented).toBe(625)'));corrected++;}expect(corrected).toBe(4);expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(prior)).digest('hex')).toBe('d128b3f44c699b4b1a6ad3a826ebb6219d29a3b444a1b1bc064d48f54f9fd93a');expect(all.mappedDeclarations).toBe(590);expect(all.executionCredit).toBe(false);});
test('thread mappings refuse omitted declarations stale helpers authored case credit and invented assertions',async()=>{const x=await input();for(const change of [(l:OutcomeMappingLedger)=>l.mappings.pop(),(l:OutcomeMappingLedger)=>{l.sourceSha256['tests/acceptance/comment-threads.ts']='0'.repeat(64);},(l:OutcomeMappingLedger)=>{l.mappings[0]!.scenarioIds=['@id-python-comments-resolution'];},(l:OutcomeMappingLedger)=>{l.mappings[0]!.assertions[0]='invented';}]){const l=structuredClone(x.ledger);change(l);expect(()=>reconcileOutcomeMappings(x.inventory,l,x.features,x.sources)).toThrow();}});
test('reviewed native thread titles retain their own scenario families and outcome predicates',async()=>{const l=await Bun.file('docs/behaviors/comment-threads-mappings.json').json();const expected:[string,string[],string][]=[
 ['thread inspection returns two nonempty roots',['inspection'],'frozen detached report'],
 ['resolving a reply updates its complete existing thread',['resolution'],'Reply02 selects root1'],
 ['mixed states only change mismatched flags',['noop'],'repeat changes zero'],
 ['nested descendants and out-of-order extension entries',['inspection','resolution'],'Nested member3 selects root1'],
 ['missing root metadata refuses',['refusal'],'Missing root commentEx entry'],
 ['invalid arguments unsafe graphs',['refusal'],'Invalid arguments, malformed graphs'],
 ['thread inspection retains explicit unsupported findings',['unsupported'],'frozen nonempty unsupported finding'],
 ['injected write or serialization failure',['rollback'],'Reached write and serialization hooks'],
 ['thread updates retain alias namespaces',['encoding'],'UTF8 BOM and UTF16 LE/BE'],
 ['single-comment edits also retain',['inspection','encoding'],'empty-package thread inspection'],
 ['comment source order including descendants',['inspection','resolution'],'Reordered body3,2,0,1'],
 ['batched flag edits preserve every unrelated character',['resolution','encoding'],'entity value replaced and absent done inserted'],
 ['thread operation count bound refuses',['limit'],'docx-comments-limit'],
 ['existing-extension threads do not activate',['inspection'],'All nine authored-comment profiles remain planned'],
 ];expect(expected).toHaveLength(14);for(const [title,scenarios,phrase] of expected){const rows=l.mappings.filter((m:any)=>m.testId.includes('docx-comment-threads.test.ts:'+title));expect(rows).toHaveLength(1);expect(rows[0].scenarioIds).toEqual(scenarios.map(n=>'@id-docx-existing-thread-'+n));expect(rows[0].outcomes.join(' ')).toContain(phrase);expect(rows[0].caseKeys).toEqual([]);}});
