import {test,expect} from 'bun:test';import {outcomeMappingReport,reconcileOutcomeMappingSets,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';import {inventoryTestSource} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {join} from 'node:path';
const common=['src/index.ts','src/xml/index.ts','src/xml/comparison.ts','src/xml/encoding.ts','src/errors.ts','tests/fixtures/admission.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts'];
const definitions=[
 {name:'xml-comparison',path:'tests/unit/xml-comparison.test.ts',canonical:'workflows/xml/comparison.feature',count:14,assertions:42,cases:10,sources:['tests/acceptance/xml-comparison.ts','src/opc/admission.ts','src/opc/zip.ts',...common]},
 {name:'package-comparison',path:'tests/unit/package-comparison.test.ts',canonical:'workflows/package/semantic-diff.feature',count:12,assertions:32,cases:1,sources:['tests/acceptance/package-comparison.ts','src/opc/comparison.ts','src/opc/admission.ts','src/opc/zip.ts','src/opc/diff.ts','src/opc/package.ts','src/docx/index.ts',...common]},
];
async function sample(d:typeof definitions[number]){const ledger=await Bun.file(`docs/behaviors/${d.name}-mappings.json`).json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of [d.path,...d.sources,d.canonical])sources[p]=await Bun.file(p===d.canonical?join(fixturesRoot(),p):p).text();return {inventory:{cases:inventoryTestSource(d.path,sources[d.path]!),unresolved:[]},sets:[{name:d.name,expectedScopePaths:[d.path],ledger,features:[parseFeature(d.canonical,sources[d.canonical]!)],sources}]};}
test('comparison ledgers cover 26 declarations and 74 expressions preserving 347 predecessor mappings',async()=>{
 const r=await outcomeMappingReport();for(const d of definitions){const rows=r.mappings.filter(m=>m.ledger===d.name);expect(rows).toHaveLength(d.count);expect(rows.reduce((n,m)=>n+m.assertions.length,0)).toBe(d.assertions);expect(r.ledgers.find(l=>l.name===d.name)!.scopePaths).toEqual([d.path]);expect(rows.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([d.cases]);expect(rows.every(m=>m.status==='partial'&&m.executionCredit===false&&m.gaps.length&&m.outcomes.length)).toBe(true);}expect(r.mappedDeclarations).toBe(472);expect(r.unmappedTestIds.length).toBe(r.totalDeclarations-472);expect(r.runtimeLeafCount).toBeNull();expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(r.mappings.filter(m=>['slide-order','effective-formatting','xml-values','pptx-core','docx-model','docx-anchors','xlsx-comments','xlsx-styles','pptx-text-boxes','docx-page-layout','docx-paragraph-styles','docx-style-authoring','formula-references'].includes(m.ledger)))).digest('hex')).toBe('3305a748dafe7016415e00c7242f6af878205e13d68ffb1b7bbbf20567be5378');
});
test('comparison mapping gaps preserve aggregate wrappers QName policies resource and unchanged-list limits',async()=>{
 const r=await outcomeMappingReport(),xml=r.mappings.filter(m=>m.ledger==='xml-comparison'),pkg=r.mappings.filter(m=>m.ledger==='package-comparison');expect(xml[0]!.caseKeys).toEqual([]);expect(xml[2]!.gaps.join(' ')).toContain('Type');expect(xml[8]!.gaps.join(' ')).toContain('aggregate');expect(xml[9]!.gaps.join(' ')).toContain('timing');expect(xml[12]!.gaps.join(' ')).toContain('not schema');expect(pkg[0]!.gaps.join(' ')).toContain('no OPC');expect(pkg[6]!.gaps.join(' ')).toContain('single');expect(pkg[9]!.gaps.join(' ')).toContain('unchanged');expect(pkg[9]!.gaps.join(' ')).toContain('aggregate');expect(pkg[11]!.outcomes.join(' ')).toContain('byte diff');expect(pkg.every(m=>m.gaps.join(' ').includes('no new execution'))).toBe(true);
});
test('comparison scopes declarations literal assertions and canonical case ownership cannot shrink or cross features',async()=>{
 for(const d of definitions){const a=await sample(d);a.sets[0]!.ledger.scopePaths=[];expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('scope');const b=await sample(d);b.sets[0]!.ledger.mappings.pop();expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('Missing scoped');const c=await sample(d);c.sets[0]!.ledger.mappings[0]!.assertions.pop();expect(()=>reconcileOutcomeMappingSets(c.inventory,c.sets)).toThrow('assertion');const e=await sample(d);e.sets[0]!.ledger.mappings[0]!.caseKeys=['@id-docx-final-section-layout|{"kind":"landscape"}'];expect(()=>reconcileOutcomeMappingSets(e.inventory,e.sets)).toThrow('case');}
});
test('comparison runtime binding fixture-builder and canonical pins fail independently when stale or absent',async()=>{
 for(const d of definitions)for(const p of [d.path,...d.sources,d.canonical]){const a=await sample(d);expect(Object.hasOwn(a.sets[0]!.ledger.sourceSha256,p)).toBe(true);a.sets[0]!.sources[p]+=' ';expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('Stale source');const b=await sample(d);delete b.sets[0]!.ledger.sourceSha256[p];expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('pin');}
});
test('comparison reconciliation preserves inputs direct and deferred assertions dynamic flags and unknown leaves',async()=>{
 for(const d of definitions){const a=await sample(d),before=JSON.stringify(a),r=reconcileOutcomeMappingSets(a.inventory,a.sets);expect(JSON.stringify(a)).toBe(before);expect(r.mappings.map(m=>m.assertions)).toEqual(a.inventory.cases.map(m=>m.assertions));expect(r.mappings.map(m=>m.deferredAssertions)).toEqual(a.inventory.cases.map(m=>m.deferredAssertions));expect(r.mappings.map(m=>m.reviewReasons)).toEqual(a.inventory.cases.map(m=>m.reviewReasons));expect(r.executionCredit).toBe(false);expect(r.runtimeLeafCount).toBeNull();}
});
