import {test,expect} from 'bun:test';
import {Workbook,Presentation,ContractWorkbook,ContractPresentation,OoxmlError} from '../../src/index.ts';
import {mkdtemp,rm,mkdir,readFile,writeFile,symlink,readlink,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {readZip,writeZip} from '../../src/opc/zip.ts';
import {contract20Recipe} from '../helpers/contract20-inputs.ts';
const decoder=new TextDecoder(),encoder=new TextEncoder();
const text=(bytes:Uint8Array,p:string)=>decoder.decode(readZip(bytes).get(p));
function category(fn:()=>unknown):string|undefined{try{fn();return undefined;}catch(e){if(e instanceof OoxmlError)return e.code;throw e;}}
function sameMembers(a:Uint8Array,b:Uint8Array){const x=readZip(a),y=readZip(b);expect([...y.keys()].sort()).toEqual([...x.keys()].sort());for(const[p,v]of x)expect(y.get(p)).toEqual(v);}

test('Contract20 independent input reads exclude both rich-string phonetic guides',async()=>{const bytes=await contract20Recipe('phonetic-strings'),w=await Workbook.open(bytes);expect(w.worksheet('Phonetics').getCell('A1')?.value).toBe('Alpha Beta');expect(w.worksheet('Phonetics').getCell('B1')?.value).toBe('Gamma Delta');sameMembers(bytes,w.toBytes());});
test('Contract20 numeric no-op preserves all caches and calculation flags',async()=>{const bytes=await contract20Recipe('cross-caches'),w=await ContractWorkbook.open(bytes);w.setCellValue('Model','A1',1);sameMembers(bytes,w.toBytes());});
test('Contract20 prefixed blanks retain x while C1 value cache is absent',async()=>{const w=await ContractWorkbook.open(await contract20Recipe('prefixed-cells'));w.setCellValue('Prefixed','A1','Alpha');w.setCellValue('Prefixed','B1',7);const xml=text(w.toBytes(),'xl/worksheets/sheet1.xml');expect(xml).toContain('<x:is>');expect(xml).toContain('<x:v>7</x:v>');expect(xml).not.toMatch(/<x:c r="C1"[^>]*>[\s\S]*?<x:v/);});
test('Contract20 all-four cache invalidation retains independent formula body',async()=>{const w=await Workbook.open(await contract20Recipe('cross-caches'));w.worksheet('Model').setCellValue('A1',10);expect(w.worksheet('Summary').getCell('B1')).toMatchObject({kind:'formula',formula:'40+2',cached:null});expect(text(w.toBytes(),'xl/workbook.xml')).toContain('forceFullCalc="1"');});
test('Contract20 opaque semantic owner edge refuses before mutation',async()=>{const parts=readZip(await contract20Recipe('opaque-caches')),path='xl/_rels/workbook.xml.rels';parts.set(path,encoder.encode(decoder.decode(parts.get(path)).replace('</Relationships>','<Relationship Id="semanticExtra" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/externalLink" Target="externalLinks/cache-boundary.xml"/></Relationships>')));const bytes=writeZip(parts),w=await ContractWorkbook.open(bytes);expect(category(()=>w.setCellValue('Model','A1',10,{opaqueRetention:true}))).toBe('xlsx-cache-topology-unsupported');sameMembers(bytes,w.toBytes());});
test('Contract20 from-scratch creator rejects NUL title with argument category',()=>{const p=ContractPresentation.create(),before=p.package.toBytes();expect(category(()=>p.addTextSlide('bad\u0000','Bad subtitle'))).toBe('PPTX_ARGUMENT_INVALID');sameMembers(before,p.package.toBytes());});
test('Contract20 missing notes is a non-mutating false/empty observation',async()=>{const bytes=await contract20Recipe('missing-notes'),p=await ContractPresentation.open(bytes);expect(p.readNotes(0)).toEqual({hasNotes:false,text:''});sameMembers(bytes,p.package.toBytes());});
for(const [recipe,code]of [['merged-table','PPTX_TABLE_MERGE_UNSUPPORTED'],['malformed-table','PPTX_TABLE_STRUCTURE_UNSUPPORTED']])test('Contract20 '+recipe+' intake succeeds before typed cell edit refusal',async()=>{const bytes=await contract20Recipe(recipe!),p=await ContractPresentation.open(bytes),cell=p.selectTableCell(0,4,0,0);expect(cell).toBeDefined();expect(category(()=>p.setTableCellText(cell,'x'))).toBe(code);sameMembers(bytes,p.package.toBytes());});
test('Contract20 foreign text anchor refuses across equal-part equal-text sessions',async()=>{const bytes=await contract20Recipe('plain-title'),p=await ContractPresentation.open(bytes),other=await ContractPresentation.open(bytes),anchor=other.inspectText(0)[0]!.anchor;expect(category(()=>p.replaceTextAt(anchor,'Frankenstein','Foreign'))).toBe('PPTX_STALE_ANCHOR');sameMembers(bytes,p.package.toBytes());});
test('Contract20 cross-run input produces exact Friendstein starting-run properties',async()=>{const p=await Presentation.open(await contract20Recipe('fragmented-title')),s=p.slides[0]!,a=s.inspectText('title')[0]!.anchor;s.replaceTextAt(a,'anken','iend');expect(s.inspectText('title')[0]).toMatchObject({text:'Friendstein',runs:[{text:'Fr',attrs:{b:'1'}},{text:'iend',attrs:{b:'1'}},{text:'stein',attrs:{u:'sng'}}]});});
test('Contract20 styled cell updates only existing text leaf',async()=>{const bytes=await contract20Recipe('styled-table'),p=await Presentation.open(bytes);p.slides[0]!.tables[0]!.cell(0,0).text='updated value';expect(text(p.package.toBytes(),'ppt/slides/slide1.xml')).toBe(text(bytes,'ppt/slides/slide1.xml').replace('Galvanic battery','updated value'));});

test('Contract20 refusal leaves held ordinary cell and unchanged source session usable',async()=>{const bytes=await contract20Recipe('attributed-formulas'),w=await ContractWorkbook.open(bytes);expect(w.readCell('Calc','A2')).toMatchObject({kind:'number',value:1});expect(category(()=>w.setCellValue('Calc','B2',99))).toBe('xlsx-shared-formula-edit-unsupported');sameMembers(bytes,w.toBytes());expect(w.readCell('Calc','A2')).toMatchObject({kind:'number',value:1});expect(category(()=>w.setCellValue('Calc','D2',99))).toBe('xlsx-array-formula-edit-unsupported');sameMembers(bytes,w.toBytes());});
test('Contract20 same-part table mutation stales old cell; foreign and late invalid operands do not consume fresh handles',async()=>{const bytes=await contract20Recipe('stale-table'),p=await ContractPresentation.open(bytes),other=await ContractPresentation.open(bytes),held=p.selectTableCell(0,4,0,0),foreign=other.selectTableCell(0,4,0,0);expect(category(()=>p.setTableCellText(foreign,'foreign'))).toBe('PPTX_STALE_TABLE_HANDLE');p.addTable(0,1,1,{x:1200,y:100,width:900,height:600});const state=p.package.toBytes();expect(category(()=>p.setTableCellText(held,'stale'))).toBe('PPTX_STALE_TABLE_HANDLE');sameMembers(state,p.package.toBytes());const fresh=p.selectTableCell(0,4,0,0);expect(category(()=>p.setTableCellText(fresh,'\u0000'))).toBe('PPTX_ARGUMENT_INVALID');sameMembers(state,p.package.toBytes());p.setTableCellText(fresh,'fresh');expect(p.slides[0]!.tables[0]!.cell(0,0).text).toBe('fresh');});
test('Contract20 anchor survives unrelated append but forged and invalid late operations refuse',async()=>{const p=await ContractPresentation.open(await contract20Recipe('title-subtitle-source')),anchor=p.inspectText(0)[0]!.anchor,before=p.package.get(anchor.part);p.addTextSlide('Appended title','Appended subtitle');expect(p.package.get(anchor.part)).toEqual(before);expect(category(()=>p.replaceTextAt({...anchor},'Original title','forged'))).toBe('PPTX_STALE_ANCHOR');expect(category(()=>p.replaceTextAt(anchor,'Original title','\u0000'))).toBe('PPTX_ARGUMENT_INVALID');p.replaceTextAt(anchor,'Original title','Edited original title');expect(p.inspectText(0)[0]!.text).toBe('Edited original title');expect(category(()=>p.replaceTextAt(anchor,'Original title','stale'))).toBe('PPTX_STALE_ANCHOR');});
test('Contract20 save failure publishes nothing and preserves existing or absent destination',async()=>{const dir=await mkdtemp(join(tmpdir(),'contract20-native-'));try{const w=await ContractWorkbook.open(await contract20Recipe('styled-blank')),p=ContractPresentation.create();p.addTextSlide('Safe','Subtitle');const prior=join(dir,'destination');await writeFile(prior,'prior destination');await mkdir(join(dir,'blocked'));for(const session of [w,p]){const before=session.package.toBytes();await expect(session.save(join(dir,'blocked'))).rejects.toBeDefined();expect(await readFile(prior,'utf8')).toBe('prior destination');await expect(session.save(join(dir,'missing','absent'))).rejects.toBeDefined();expect(await Bun.file(join(dir,'missing','absent')).exists()).toBe(false);sameMembers(before,session.package.toBytes());}}finally{await rm(dir,{recursive:true,force:true});}});
test('Contract20 failed symlink publication preserves actual destination and leaves no staged output',async()=>{const dir=await mkdtemp(join(tmpdir(),'contract20-destination-'));try{const prior=join(dir,'prior'),link=join(dir,'output'),w=await ContractWorkbook.open(await contract20Recipe('styled-blank'));await writeFile(prior,'keep existing');await symlink(prior,link);const names=(await readdir(dir)).sort();await expect(w.save(link)).rejects.toMatchObject({code:'opc-symlink-destination'});expect(await readFile(prior,'utf8')).toBe('keep existing');expect(await readlink(link)).toBe(prior);expect((await readdir(dir)).sort()).toEqual(names);}finally{await rm(dir,{recursive:true,force:true});}});
test('Contract20 opaque retention refuses extra semantic root worksheet edge with full custody',async()=>{const parts=readZip(await contract20Recipe('opaque-caches')),path='_rels/.rels';parts.set(path,encoder.encode(decoder.decode(parts.get(path)).replace('</Relationships>','<Relationship Id="extra" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="xl/worksheets/sheet1.xml"/></Relationships>')));const input=writeZip(parts),w=await ContractWorkbook.open(input),dir=await mkdtemp(join(tmpdir(),'contract20-extra-root-'));try{const destination=join(dir,'prior');await writeFile(destination,'prior output');expect(category(()=>w.setCellValue('Model','A1',10,{opaqueRetention:true}))).toBe('xlsx-cache-topology-unsupported');sameMembers(input,w.toBytes());expect(await readFile(destination,'utf8')).toBe('prior output');expect((await readdir(dir)).sort()).toEqual(['prior']);}finally{await rm(dir,{recursive:true,force:true});}});
test('Contract20 changed-input sweep refuses shared-result topology without consuming source state',async()=>{const parts=readZip(await contract20Recipe('cross-caches')),path='xl/worksheets/sheet2.xml';parts.set(path,encoder.encode(decoder.decode(parts.get(path)).replace('<f>40+2</f>','<f t="shared" si="0" ref="B1:B2">40+2</f>')));const input=writeZip(parts),w=await ContractWorkbook.open(input);expect(category(()=>w.setCellValue('Model','A1',10))).toBe('xlsx-cache-topology-unsupported');sameMembers(input,w.toBytes());w.setCellValue('Model','A1',1);sameMembers(input,w.toBytes());});
test('Contract20 table target refuses foreign graphicData URI without editing hidden payload',async()=>{const parts=readZip(await contract20Recipe('styled-table')),path='ppt/slides/slide1.xml';parts.set(path,encoder.encode(decoder.decode(parts.get(path)).replace('uri="http://schemas.openxmlformats.org/drawingml/2006/table"','uri="urn:foreign:not-table"')));const input=writeZip(parts),p=await ContractPresentation.open(input);expect(p.slides[0]!.tables).toHaveLength(0);expect(category(()=>{const c=p.selectTableCell(0,4,0,0);p.setTableCellText(c,'tampered');})).toBe('PPTX_TABLE_STRUCTURE_UNSUPPORTED');sameMembers(input,p.package.toBytes());});
test('Contract20 retained cell text refuses multiple visible runs without discarding siblings',async()=>{const parts=readZip(await contract20Recipe('styled-table')),path='ppt/slides/slide1.xml';parts.set(path,encoder.encode(decoder.decode(parts.get(path)).replace('<a:t>Galvanic battery</a:t></a:r>','<a:t>Galvanic battery</a:t></a:r><a:r><a:rPr i="1"/><a:t> INTACT</a:t></a:r>')));const input=writeZip(parts),p=await ContractPresentation.open(input),cell=p.selectTableCell(0,4,0,0);expect(category(()=>p.setTableCellText(cell,'updated value'))).toBe('PPTX_UNSUPPORTED_TEXT_TOPOLOGY');sameMembers(input,p.package.toBytes());expect(p.slides[0]!.tables[0]!.cell(0,0).text).toBe('Galvanic battery INTACT');});
test('Contract20 opaque retention refuses styles relationship aimed at workbook role',async()=>{const parts=readZip(await contract20Recipe('opaque-caches')),path='xl/_rels/workbook.xml.rels';parts.set(path,encoder.encode(decoder.decode(parts.get(path)).replace('</Relationships>','<Relationship Id="extra" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="workbook.xml"/></Relationships>')));const input=writeZip(parts),w=await ContractWorkbook.open(input);expect(category(()=>w.setCellValue('Model','A1',10,{opaqueRetention:true}))).toBe('xlsx-cache-topology-unsupported');sameMembers(input,w.toBytes());});
test('Contract20 opaque retention refuses unreferenced worksheet edge aimed at workbook',async()=>{const parts=readZip(await contract20Recipe('opaque-caches')),path='xl/_rels/workbook.xml.rels';parts.set(path,encoder.encode(decoder.decode(parts.get(path)).replace('</Relationships>','<Relationship Id="extra" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="workbook.xml"/></Relationships>')));const input=writeZip(parts),w=await ContractWorkbook.open(input);expect(category(()=>w.setCellValue('Model','A1',10,{opaqueRetention:true}))).toBe('xlsx-cache-topology-unsupported');sameMembers(input,w.toBytes());});
