import {test,expect} from 'bun:test';import {outcomeMappingReport,reconcileOutcomeMappingSets,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';import {inventoryTestSource} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {join} from 'node:path';
const definitions=[
 {name:'docx-paragraph-styles',path:'tests/unit/docx-paragraph-style.test.ts',canonical:'workflows/docx/paragraph-style.feature',count:17,assertions:62,cases:19,sources:['tests/helpers/shared-scenarios.ts','tests/acceptance/paragraph-style.ts','src/docx/index.ts','src/docx/paragraph-style.ts','src/opc/package.ts','src/opc/graph.ts','src/xml/index.ts','src/errors.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts']},
 {name:'docx-style-authoring',path:'tests/unit/docx-style-authoring.test.ts',canonical:'workflows/docx/style-authoring.feature',count:11,assertions:43,cases:24,sources:['tests/acceptance/style-authoring.ts','tests/acceptance/paragraph-style.ts','src/docx/index.ts','src/docx/style-authoring.ts','src/docx/paragraph-style.ts','src/opc/package.ts','src/opc/graph.ts','src/opc/content-types.ts','src/xml/index.ts','src/errors.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts']},
];
async function sample(d:typeof definitions[number]){const ledger=await Bun.file(`docs/behaviors/${d.name}-mappings.json`).json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of [d.path,...d.sources,d.canonical])sources[p]=await Bun.file(p===d.canonical?join(fixturesRoot(),p):p).text();return {inventory:{cases:inventoryTestSource(d.path,sources[d.path]!),unresolved:[]},sets:[{name:d.name,expectedScopePaths:[d.path],ledger,features:[parseFeature(d.canonical,sources[d.canonical]!)],sources}]};}
test('DOCX style ledgers enumerate 28 declarations and 105 direct expressions preserving 319 previous mappings',async()=>{
 const r=await outcomeMappingReport();for(const d of definitions){const rows=r.mappings.filter(m=>m.ledger===d.name);expect(rows).toHaveLength(d.count);expect(rows.reduce((n,m)=>n+m.assertions.length,0)).toBe(d.assertions);expect(r.ledgers.find(l=>l.name===d.name)!.scopePaths).toEqual([d.path]);expect(rows.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([d.cases]);expect(rows.every(m=>m.status==='partial'&&m.executionCredit===false&&m.gaps.length&&m.outcomes.length)).toBe(true);}expect(r.mappedDeclarations).toBe(501);expect(r.unmappedTestIds.length).toBe(r.totalDeclarations-501);expect(r.runtimeLeafCount).toBeNull();expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(r.mappings.filter(m=>['slide-order','effective-formatting','xml-values','pptx-core','docx-model','docx-anchors','xlsx-comments','xlsx-styles','pptx-text-boxes','docx-page-layout','formula-references'].includes(m.ledger)))).digest('hex')).toBe('9b5c940cb8cd5593e85d34273ba4ee1acca90fcc10335ee44f6b1392fb63f5cd');
});
test('DOCX style descriptions retain byte versus path live getter and unasserted flag limits',async()=>{
 const r=await outcomeMappingReport(),selection=r.mappings.filter(m=>m.ledger==='docx-paragraph-styles'),authoring=r.mappings.filter(m=>m.ledger==='docx-style-authoring');for(const rows of [selection,authoring]){expect(rows[0]!.gaps.join(' ')).toContain('aggregate');expect(rows[0]!.gaps.join(' ')).toContain('byte reopen');expect(rows[0]!.gaps.join(' ')).toContain('no path save');}expect(selection[3]!.gaps.join(' ')).toContain('live');expect(selection[6]!.gaps.join(' ')).toContain('UTF-16LE only');expect(selection[15]!.outcomes.join(' ')).toContain('disk');expect(selection[15]!.gaps.join(' ')).toContain('text');expect(authoring[2]!.gaps.join(' ')).toContain('new definition');expect(authoring[8]!.gaps.join(' ')).toContain('flags');expect(authoring[10]!.outcomes.join(' ')).toContain('disk');expect(authoring[10]!.caseKeys).toEqual([]);
});
test('DOCX style scope assertions and case ownership cannot silently shrink or cross features',async()=>{
 for(const d of definitions){const a=await sample(d);a.sets[0]!.ledger.scopePaths=[];expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('scope');const b=await sample(d);b.sets[0]!.ledger.mappings.pop();expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('Missing scoped');const c=await sample(d);c.sets[0]!.ledger.mappings[0]!.assertions.pop();expect(()=>reconcileOutcomeMappingSets(c.inventory,c.sets)).toThrow('assertion');const e=await sample(d);e.sets[0]!.ledger.mappings[0]!.caseKeys=['@id-docx-final-section-layout|{"kind":"landscape"}'];expect(()=>reconcileOutcomeMappingSets(e.inventory,e.sets)).toThrow('case');}
});
test('DOCX style runtime helper and canonical pins are individually mandatory and fresh',async()=>{
 for(const d of definitions)for(const p of [d.path,...d.sources,d.canonical]){const a=await sample(d);expect(Object.hasOwn(a.sets[0]!.ledger.sourceSha256,p)).toBe(true);a.sets[0]!.sources[p]+=' ';expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('Stale source');const b=await sample(d);delete b.sets[0]!.ledger.sourceSha256[p];expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('pin');}
});
test('DOCX style reconciliation preserves evidence nested assertions flags and unknown runtime leaves',async()=>{
 for(const d of definitions){const a=await sample(d),before=JSON.stringify(a),r=reconcileOutcomeMappingSets(a.inventory,a.sets);expect(JSON.stringify(a)).toBe(before);expect(r.mappings.map(m=>m.assertions)).toEqual(a.inventory.cases.map(m=>m.assertions));expect(r.mappings.map(m=>m.deferredAssertions)).toEqual(a.inventory.cases.map(m=>m.deferredAssertions));expect(r.mappings.map(m=>m.reviewReasons)).toEqual(a.inventory.cases.map(m=>m.reviewReasons));expect(r.executionCredit).toBe(false);expect(r.runtimeLeafCount).toBeNull();}
});
