import {test,expect} from 'bun:test';import {outcomeMappingReport,reconcileOutcomeMappingSets,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';import {inventoryTestSource} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {join} from 'node:path';
const path='tests/unit/docx-comments.test.ts',canonical='workflows/docx/comments.feature',ids=['@id-docx-comments-inspection','@id-docx-comments-resolution','@id-docx-comments-noop','@id-docx-comments-refusal'];
const pins=[path,'tests/acceptance/comments-docx.ts','src/docx/comments.ts','src/docx/index.ts','src/index.ts','src/opc/package.ts','src/opc/graph.ts','src/opc/content-types.ts','src/xml/index.ts','src/errors.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts',canonical];
async function sample(){const ledger=await Bun.file('docs/behaviors/docx-comments-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of pins)sources[p]=await Bun.file(p===canonical?join(fixturesRoot(),p):p).text();return {inventory:{cases:inventoryTestSource(path,sources[path]!),unresolved:[]},sets:[{name:'docx-comments',expectedScopePaths:[path],ledger,features:[parseFeature(canonical,sources[canonical]!)],sources}]};}
test('DOCX comment ledger enumerates 19 declarations and 60 expressions preserving 373 previous mappings',async()=>{
 const r=await outcomeMappingReport(),rows=r.mappings.filter(m=>m.ledger==='docx-comments');expect(rows).toHaveLength(19);expect(rows.reduce((n,m)=>n+m.assertions.length,0)).toBe(60);expect(r.ledgers.find(l=>l.name==='docx-comments')!.scopePaths).toEqual([path]);expect(rows.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([14]);expect(new Set(rows.flatMap(m=>m.scenarioIds))).toEqual(new Set(ids));expect(rows.every(m=>m.status==='partial'&&m.executionCredit===false&&m.gaps.length&&m.outcomes.length)).toBe(true);expect(r.mappedDeclarations).toBe(407);expect(r.unmappedTestIds.length).toBe(r.totalDeclarations-407);expect(r.runtimeLeafCount).toBeNull();expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(r.mappings.filter(m=>['slide-order','effective-formatting','xml-values','pptx-core','docx-model','docx-anchors','xlsx-comments','xlsx-styles','pptx-text-boxes','docx-page-layout','docx-paragraph-styles','docx-style-authoring','xml-comparison','package-comparison','formula-references'].includes(m.ledger)))).digest('hex')).toBe('0c943212897540b5b26edc5d792bc409ec8376f4791b0943d31cb4dd371fbefb');
});
test('DOCX comment mapping wording limits wrapper bytes thread policy registry absence and direct disk readback',async()=>{
 const rows=(await outcomeMappingReport()).mappings.filter(m=>m.ledger==='docx-comments');expect(rows[0]!.gaps.join(' ')).toContain('aggregate');expect(rows[0]!.gaps.join(' ')).toContain('byte reopen');expect(rows[0]!.gaps.join(' ')).toContain('OoxmlError');expect(rows[0]!.gaps.join(' ')).toContain('member');expect(rows[1]!.gaps.join(' ')).toContain('unrelated');expect(rows[9]!.gaps.join(' ')).toContain('receipt');expect(rows[14]!.gaps.join(' ')).toContain('UTF-16LE');expect(rows[16]!.gaps.join(' ')).toContain('does not create');expect(rows[17]!.outcomes.join(' ')).toContain('disk');expect(rows[17]!.caseKeys).toEqual([]);expect(rows.every(m=>m.scenarioIds.every(id=>!id.includes('python')))).toBe(true);
});
test('DOCX comment scope and assertions cannot shrink or borrow authored-comment case keys',async()=>{
 const a=await sample();a.sets[0]!.ledger.scopePaths=[];expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('scope');const b=await sample();b.sets[0]!.ledger.mappings.pop();expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('Missing scoped');const c=await sample();c.sets[0]!.ledger.mappings[0]!.assertions.pop();expect(()=>reconcileOutcomeMappingSets(c.inventory,c.sets)).toThrow('assertion');const d=await sample();d.sets[0]!.ledger.mappings[0]!.caseKeys=['@id-python-comments-reply-root-resolution'];expect(()=>reconcileOutcomeMappingSets(d.inventory,d.sets)).toThrow('case');
});
test('DOCX comment runtime helper public export and canonical pins fail independently when stale or absent',async()=>{
 for(const p of pins){const a=await sample();expect(Object.hasOwn(a.sets[0]!.ledger.sourceSha256,p)).toBe(true);a.sets[0]!.sources[p]+=' ';expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('Stale source');const b=await sample();delete b.sets[0]!.ledger.sourceSha256[p];expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('pin');}
});
test('DOCX comment reconciliation preserves evidence dynamic and deferred assertions with unknown runtime leaves',async()=>{
 const a=await sample(),before=JSON.stringify(a),r=reconcileOutcomeMappingSets(a.inventory,a.sets);expect(JSON.stringify(a)).toBe(before);expect(r.mappings.map(m=>m.assertions)).toEqual(a.inventory.cases.map(m=>m.assertions));expect(r.mappings.map(m=>m.deferredAssertions)).toEqual(a.inventory.cases.map(m=>m.deferredAssertions));expect(r.mappings.map(m=>m.reviewReasons)).toEqual(a.inventory.cases.map(m=>m.reviewReasons));expect(r.executionCredit).toBe(false);expect(r.runtimeLeafCount).toBeNull();
});
