import {test,expect} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {Document,OpcPackage} from '../../src/index.ts';import {addPart,addRelationship,getContentType} from '../../src/opc/index.ts';
const CP='http://schemas.openxmlformats.org/package/2006/metadata/core-properties',DC='http://purl.org/dc/elements/1.1/',DCT='http://purl.org/dc/terms/',XSI='http://www.w3.org/2001/XMLSchema-instance',REL='http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties',MIME='application/vnd.openxmlformats-package.core-properties+xml';
const props={title:'Doc Title',creator:'Doc Author',subject:'Doc Subject',description:'Doc Description',keywords:'one;two',category:'Category',language:'en-US',contentStatus:'Draft',identifier:'urn:example:doc',lastModifiedBy:'Reviewer',revision:'2',version:'1.0',created:'2026-02-03T00:00:00Z',modified:'2026-02-03T01:00:00Z',lastPrinted:'2026-02-03T02:00:00Z'};
async function fixture(xml:string,path='docProps/core.xml',type=MIME){const d=Document.create();d.addParagraph('Untouched');const p=await OpcPackage.open(d.package.toBytes());addPart(p,path,xml,type);addRelationship(p,'',REL,path);return Document.open(p.toBytes());}
const wrap=(value:string)=>`<cp:coreProperties xmlns:cp="${CP}" xmlns:dc="${DC}" xmlns:dcterms="${DCT}" xmlns:xsi="${XSI}">${value}</cp:coreProperties>`;

test('all fifteen core fields survive real path save/reopen with exact unrelated payload custody',async()=>{
 const d=Document.create();d.addParagraph('Untouched');const held=d.paragraphs[0]!,before=d.package.parts;expect(Object.values(d.getCoreProperties()).every(v=>v===null)).toBe(true);expect(d.setCoreProperties(props)).toEqual({changed:15});expect(d.getCoreProperties()).toEqual(props);expect(held.text).toBe('Untouched');
 const p=await OpcPackage.open(d.package.toBytes()),rel=p.relationships('').filter(r=>r.type===REL);expect(rel).toHaveLength(1);expect(rel[0]!.resolved).toBe('docProps/core.xml');expect(getContentType(p,'docProps/core.xml')).toBe(MIME);
 const dir=await mkdtemp(join(tmpdir(),'core-properties-'));try{const path=join(dir,'meta.docx');await d.save(path);const after=await Document.open(path);expect(after.getCoreProperties()).toEqual(props);for(const[n,b]of before)if(n!=='[Content_Types].xml'&&n!=='_rels/.rels')expect(after.package.get(n)).toEqual(b);}finally{await rm(dir,{recursive:true,force:true});}
});

test('same-value patches retain archive and lexical values while detached getter data and null removals remain independent',async()=>{
 const source=wrap('<dc:title>A&#x26;B</dc:title><cp:revision>02</cp:revision>'),d=await fixture(source),before=d.package.toBytes();expect(d.setCoreProperties({title:'A&B',revision:'02'})).toEqual({changed:0});expect(d.package.toBytes()).toEqual(before);const got=d.getCoreProperties();got.title='Changed';expect(d.getCoreProperties().title).toBe('A&B');expect(d.setCoreProperties({title:null,subject:undefined})).toEqual({changed:1});expect(d.getCoreProperties().title).toBeNull();expect(new TextDecoder().decode(d.package.get('docProps/core.xml'))).toBe(source.replace('<dc:title>A&#x26;B</dc:title>',''));expect(d.getCoreProperties().revision).toBe('02');
 const empty=Document.create(),eb=empty.package.toBytes();expect(empty.setCoreProperties({title:null})).toEqual({changed:0});expect(empty.package.toBytes()).toEqual(eb);expect(empty.package.has('docProps/core.xml')).toBe(false);
});

test('aliased properties at nondefault path preserve unselected fragments and qualified timestamp type',async()=>{
 const title='<q:title xmlns:q="'+DC+'">  Old &amp; 雪  </q:title>',source=`<c:coreProperties xmlns:c="${CP}" xmlns:w="urn:foreign">${title}<c:category>Keep</c:category></c:coreProperties>`,d=await fixture(source,'metadata/props.xml'),before=d.package.parts;d.setCoreProperties({subject:' A < B & 😀 ',created:props.created});const after=await Document.open(d.package.toBytes());expect(after.getCoreProperties().subject).toBe(' A < B & 😀 ');expect(after.getCoreProperties().created).toBe(props.created);expect(new TextDecoder().decode(after.package.get('metadata/props.xml'))).toContain(title);expect(after.getCoreProperties().category).toBe('Keep');for(const[n,b]of before)if(n!=='metadata/props.xml')expect(after.package.get(n)).toEqual(b);
});

test('self-closing root, empty strings and XML metacharacters preserve distinct absent/empty values',async()=>{
 const d=await fixture(`<c:coreProperties xmlns:c="${CP}"/>`);expect(d.setCoreProperties({title:'',description:' <雪> & "quote"\nnext '})).toEqual({changed:2});expect(d.getCoreProperties().title).toBe('');expect(d.getCoreProperties().description).toBe(' <雪> & "quote"\nnext ');expect((await Document.open(d.package.toBytes())).getCoreProperties().description).toBe(' <雪> & "quote"\nnext ');
});

test('invalid patches, timestamps and executable fields refuse without partial creation',()=>{
 const d=Document.create(),before=d.package.toBytes();let called=false;const getter=Object.defineProperty({},'title',{enumerable:true,get(){called=true;return 'X';}});
 for(const patch of [null,{},[],Object.create({title:'X'}),getter,{unknown:'x'},{[Symbol('x')]:'x'},{title:3},{title:'\ud800'},{title:'bad\u0000'},{title:'x'.repeat(4097)},{title:'Good',created:'2026-02-30T00:00:00Z'},{created:'2026-02-03'},{modified:'2026-02-03T01:00:00+00:00'},{lastPrinted:'2026-02-03T01:00:00.000Z'},{created:'0000-01-01T00:00:00Z'},{created:'2026-02-03T25:00:00Z'}]){expect(()=>d.setCoreProperties(patch as any)).toThrow();expect(d.package.toBytes()).toEqual(before);}expect(called).toBe(false);
});

test('duplicate unknown decorated revised lexical and wrongly qualified metadata refuse even no-op or removal',async()=>{
 for(const content of ['<dc:title>A</dc:title><dc:title>B</dc:title>','<title>A</title>','<dc:title xml:lang="en">A</dc:title>','<cp:unknown/>','<dc:title>A<!--keep--></dc:title>','<dc:title><![CDATA[A]]></dc:title>','<dc:title><cp:bad/></dc:title>','<!--keep--><dc:title>A</dc:title>','<dcterms:created xsi:type="cp:W3CDTF">2026-02-03T00:00:00Z</dcterms:created>','<dcterms:created>2026-02-03T00:00:00Z</dcterms:created>','<cp:lastPrinted xsi:type="dcterms:W3CDTF">2026-02-03T00:00:00Z</cp:lastPrinted>','<cp:lastPrinted>bad</cp:lastPrinted>']){const d=await fixture(wrap(content)),before=d.package.toBytes();expect(()=>d.getCoreProperties()).toThrow();expect(()=>d.setCoreProperties({title:'A'})).toThrow();expect(()=>d.setCoreProperties({title:null})).toThrow();expect(d.package.toBytes()).toEqual(before);}
});

test('ambiguous relationships, wrong types and orphan core parts refuse without adopting unrelated metadata',async()=>{
 const base=Document.create(),orphan=await OpcPackage.open(base.package.toBytes());addPart(orphan,'docProps/core.xml',wrap(''),MIME);const od=await Document.open(orphan.toBytes()),ob=od.package.toBytes();expect(()=>od.getCoreProperties()).toThrow();expect(()=>od.setCoreProperties({title:'New'})).toThrow();expect(od.package.toBytes()).toEqual(ob);
 const collision=await OpcPackage.open(base.package.toBytes());addPart(collision,'docProps/core.xml','<other/>','application/xml');const cd=await Document.open(collision.toBytes()),cb=cd.package.toBytes();expect(()=>cd.setCoreProperties({title:'New'})).toThrow();expect(cd.package.toBytes()).toEqual(cb);
 const wrong=await fixture(wrap(''),'metadata/core.xml','application/xml');expect(()=>wrong.getCoreProperties()).toThrow();
 for(const extra of ['external','duplicate','secondpart']){const d=await fixture(wrap('')),p=await OpcPackage.open(d.package.toBytes());if(extra==='external')addRelationship(p,'',REL,'https://example.test/core',{external:true,id:'rIdExternal'});if(extra==='duplicate')addRelationship(p,'',REL,'docProps/core.xml',{id:'rIdDuplicate'});if(extra==='secondpart')addPart(p,'docProps/second.xml',wrap(''),MIME);const doc=await Document.open(p.toBytes()),before=doc.package.toBytes();expect(()=>doc.setCoreProperties({title:'New'})).toThrow();expect(doc.package.toBytes()).toEqual(before);}
});

test('UTF16 core member retains endian/BOM and main-document handles across saved edits',async()=>{
 const d=await fixture(wrap('<dc:title>Old</dc:title>')),p=await OpcPackage.open(d.package.toBytes()),source='<?xml version="1.0" encoding="UTF-16"?>'+p.text('docProps/core.xml'),bytes=new Uint8Array(2+source.length*2);bytes[0]=254;bytes[1]=255;const view=new DataView(bytes.buffer);for(let i=0;i<source.length;i++)view.setUint16(2+2*i,source.charCodeAt(i),false);p.set('docProps/core.xml',bytes);const doc=await Document.open(p.toBytes()),held=doc.paragraphs[0]!,before=doc.package.parts;doc.setCoreProperties({title:'雪',modified:props.modified});expect(held.text).toBe('Untouched');const after=await Document.open(await doc.save());expect(after.getCoreProperties().title).toBe('雪');expect(after.getCoreProperties().modified).toBe(props.modified);expect([...after.package.get('docProps/core.xml')!.slice(0,2)]).toEqual([254,255]);for(const[n,b]of before)if(n!=='docProps/core.xml')expect(after.package.get(n)).toEqual(b);
});

test('creation and update faults roll back all metadata while preserving main handles',async()=>{
 for(const existing of [false,true])for(const stage of ['set','toBytes'] as const){const d=existing?await fixture(wrap('<dc:title>Old</dc:title>')):Document.create();if(!existing)d.addParagraph('Untouched');const held=d.paragraphs[0]!,before=d.package.toBytes(),p=(d as any).opcPackage as OpcPackage,original=p[stage].bind(p);if(stage==='set')p.set=(n,v)=>{(original as OpcPackage['set'])(n,v);throw Error('injected set');};else p.toBytes=()=>{throw Error('injected serialize');};try{expect(()=>d.setCoreProperties({title:'New'})).toThrow('injected');}finally{if(stage==='set')p.set=original as OpcPackage['set'];else p.toBytes=original as OpcPackage['toBytes'];}expect(d.package.toBytes()).toEqual(before);expect(held.text).toBe('Untouched');expect(d.getCoreProperties().title).toBe(existing?'Old':null);}
});

test('protected writes and external document changes refuse, while metadata reads remain nonmutating',async()=>{
 const d=await fixture(wrap('<dc:title>Old</dc:title>')),p=await OpcPackage.open(d.package.toBytes()),W='http://schemas.openxmlformats.org/wordprocessingml/2006/main';addPart(p,'word/settings.xml',`<w:settings xmlns:w="${W}"><w:documentProtection/></w:settings>`,'application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml');addRelationship(p,p.mainPart(),'http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings','settings.xml');const locked=await Document.open(p.toBytes()),before=locked.package.toBytes();expect(locked.getCoreProperties().title).toBe('Old');expect(()=>locked.setCoreProperties({title:'Old'})).toThrow();expect(locked.package.toBytes()).toEqual(before);
 d.package.setPart('word/document.xml',new TextEncoder().encode(new TextDecoder().decode(d.package.get('word/document.xml')).replace('Untouched','Changed')));const changed=d.package.toBytes();expect(()=>d.setCoreProperties({title:'New'})).toThrow();expect(()=>d.getCoreProperties()).toThrow();expect(d.package.toBytes()).toEqual(changed);
});

test('late relationship and content-type creation failures roll back every new part',()=>{
 for(const target of ['[Content_Types].xml','_rels/.rels']){const d=Document.create();d.addParagraph('Held');const held=d.paragraphs[0]!,before=d.package.toBytes(),p=(d as any).opcPackage as OpcPackage,original=p.set.bind(p);p.set=(name,value)=>{original(name,value);if(name===target)throw Error('injected late metadata');};try{expect(()=>d.setCoreProperties({title:'New'})).toThrow('injected late metadata');}finally{p.set=original;}expect(d.package.toBytes()).toEqual(before);expect(d.package.has('docProps/core.xml')).toBe(false);expect(held.text).toBe('Held');}
});

test('aliased timestamp type, valid leap dates and string values remain distinct with metadata-only external changes',async()=>{
 const source=`<c:coreProperties xmlns:c="${CP}" xmlns:t="${DCT}" xmlns:i="${XSI}"><t:created i:type="t:W3CDTF">2000-02-29T00:00:00Z</t:created><c:revision>not-numeric</c:revision></c:coreProperties>`,d=await fixture(source);expect(d.getCoreProperties().created).toBe('2000-02-29T00:00:00Z');expect(d.getCoreProperties().revision).toBe('not-numeric');const held=d.paragraphs[0]!;d.package.setPart('docProps/core.xml',new TextEncoder().encode(source.replace('not-numeric','External')));expect(d.getCoreProperties().revision).toBe('External');d.setCoreProperties({title:'New'});expect(d.getCoreProperties().revision).toBe('External');expect(held.text).toBe('Untouched');
 for(const value of ['1900-02-29T00:00:00Z','2026-02-03T00:60:00Z','2026-02-03T00:00:60Z']){const before=d.package.toBytes();expect(()=>d.setCoreProperties({created:value})).toThrow();expect(d.package.toBytes()).toEqual(before);}
});

test('canonical metadata case compares three chosen fields and detects each corrupted readback',async()=>{
 const {fixturesRoot}=await import('../../scripts/fixture-inputs.ts'),{selectSharedScenarios,executeAcceptance}=await import('../../scripts/gherkin.ts'),{bindings}=await import('../acceptance/steps.ts'),{scenarioIds}=await import('../acceptance/core-properties.ts');const path='workflows/docx/document-model.feature',source=await Bun.file(join(fixturesRoot(),path)).text(),count=(n:number)=>({implemented:n,planned:0,total:n});const inv=(text:string)=>({root:'.',features:[selectSharedScenarios(path,text,scenarioIds)],counts:{features:count(1),scenarios:count(1),cases:count(1),steps:count(7)}});
 const good=await executeAcceptance(inv(source),bindings,'core-properties-unit');expect(good.failures).toEqual([]);expect(good.counts.cases.passed).toBe(1);
 for(const values of ['Wrong, Doc Author and Doc Subject','Doc Title, Wrong and Doc Subject','Doc Title, Doc Author and Wrong']){const bad=await executeAcceptance(inv(source.replace('compared to Doc Title, Doc Author and Doc Subject','compared to '+values)),bindings,'core-expected-control');expect(bad.counts.cases.failed).toBe(1);expect(bad.counts.steps.failed).toBe(1);expect(bad.counts.steps.undefined).toBe(0);expect(bad.counts.steps.ambiguous).toBe(0);}
 for(const key of ['title','creator','subject']){const altered=bindings.map(b=>b.pattern.test('the setter and getter return no error')?{...b,run:async(c:Record<string,unknown>,...args:string[])=>{await b.run(c,...args);(c.state as {core:Record<string,string>}).core[key]='CORRUPT';}}:b);const bad=await executeAcceptance(inv(source),altered,'core-readback-control');expect(bad.counts.cases.failed).toBe(1);expect(bad.counts.steps.failed).toBe(1);expect(bad.counts.steps.undefined).toBe(0);}
});

test('changed UTF8-BOM core metadata retains BOM and exact untouched field bytes after reopen',async()=>{
 const d=await fixture(wrap('<dc:title>Old</dc:title><cp:category> Keep &#x26; 雪 </cp:category>')),p=await OpcPackage.open(d.package.toBytes()),raw=p.get('docProps/core.xml')!;p.set('docProps/core.xml',new Uint8Array([239,187,191,...raw]));const loaded=await Document.open(p.toBytes());loaded.setCoreProperties({title:'New'});const after=await Document.open(loaded.package.toBytes()),bytes=after.package.get('docProps/core.xml')!;expect([...bytes.slice(0,3)]).toEqual([239,187,191]);expect(after.getCoreProperties().title).toBe('New');expect(new TextDecoder().decode(bytes)).toContain('<cp:category> Keep &#x26; 雪 </cp:category>');
});

test('complete core XML output bound refuses while preserving bytes and live document handles',async()=>{
 const source=wrap('<dc:title>Old</dc:title>'),xml=source.replace('</cp:coreProperties>',' '.repeat(8*1024*1024-source.length-2)+'</cp:coreProperties>'),d=await fixture(source);d.package.setPart('docProps/core.xml',new TextEncoder().encode(xml));const before=d.package.toBytes(),held=d.paragraphs[0]!;expect(()=>d.setCoreProperties({description:'Added'})).toThrow(expect.objectContaining({code:'XML_EDIT_UNSAFE'}));expect(d.package.toBytes()).toEqual(before);expect(held.text).toBe('Untouched');expect(d.getCoreProperties().title).toBe('Old');
});
