import {test,expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {OpcPackage,addRelationship} from '../../src/opc/index.ts';import {parseXml,elements,attribute} from '../../src/xml/index.ts';import {inspectRevisions,resolveRevisions} from '../../src/docx/revisions.ts';import {openRevisionFixture} from '../acceptance/revisions-docx.ts';
const W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',profile='text-and-run-properties' as const;
const current='<w:b/><w:color w:val="112233"/>',previous='<w:i/><w:color w:val="445566"/>';
const change='<w:rPrChange w:id="80" w:author="Editor" w:date="2026-09-27T00:00:00Z"><w:rPr>'+previous+'</w:rPr></w:rPrChange>';
const properties='<w:rPr>'+current+change+'</w:rPr>',run='<w:r>'+properties+'<w:t>Stable</w:t></w:r>';
async function input(){const p=await openRevisionFixture('all-stories');const stories=[...new Set(inspectRevisions(p).revisions.map(r=>r.part))];for(const part of stories)p.set(part,p.text(part).replace('</w:p>',run+'</w:p>'));return {p,stories};}
const inspect=(p:OpcPackage)=>inspectRevisions(p,{profile});const resolve=(p:OpcPackage,a:'accept'|'reject',parts?:string[])=>resolveRevisions(p,a,{profile,...(parts?{parts}:{})});
async function bytesEqual(p:OpcPackage,b:OpcPackage,except:string[]=[]){expect(p.names()).toEqual(b.names());for(const n of b.names())if(!except.includes(n))expect(p.get(n)).toEqual(b.get(n));}
test('opt-in run-property profile resolves exact current or saved properties and text in all seven reachable stories through path reopen',async()=>{for(const action of ['accept','reject'] as const){const {p,stories}=await input(),source=p.toBytes(),baseline=await OpcPackage.open(source),report=inspect(p);expect(report.unsupported).toEqual([]);expect(report.revisions).toHaveLength(21);expect(report.revisions.filter(r=>r.kind==='run-properties').map(r=>[r.part,r.id,r.author,r.text])).toEqual(stories.map(part=>[part,'80','Editor','Stable']));expect(p.toBytes()).toEqual(source);const dir=await mkdtemp(join(tmpdir(),'property-review-'));try{const src=join(dir,'source.docx'),out=join(dir,'output.docx');await Bun.write(src,source);const receipt=resolve(p,action);expect(receipt).toEqual({resolved:21,changedParts:stories});await p.save(out);const read=await OpcPackage.open(out);expect(inspect(read)).toEqual({revisions:[],unsupported:[]});for(const part of stories){const original=baseline.text(part),xml=read.text(part);expect(xml).toContain(action==='accept'?'<w:rPr>'+current+'</w:rPr>':'<w:rPr>'+previous+'</w:rPr>');const noProps=await OpcPackage.open(source);noProps.set(part,original.replace(properties,action==='accept'?'<w:rPr>'+current+'</w:rPr>':'<w:rPr>'+previous+'</w:rPr>'));resolveRevisions(noProps,action,{parts:[part]});expect(xml).toBe(noProps.text(part));expect(elements(parseXml(xml),'t',W).map(t=>t.text).join('')).toContain(action==='accept'?'modernized.':'historic.');expect(xml).not.toContain('rPrChange');}await bytesEqual(read,baseline,stories);expect(await Bun.file(src).bytes()).toEqual(Uint8Array.from(source));const before=read.toBytes();expect(resolve(read,action)).toEqual({resolved:0,changedParts:[]});expect(read.toBytes()).toEqual(before);}finally{await rm(dir,{recursive:true,force:true});}}});
test('default text-only refusal stays unchanged and selected property profile leaves all other stories byte-identical',async()=>{const {p,stories}=await input(),before=p.toBytes(),base=await OpcPackage.open(before);expect(inspectRevisions(p).unsupported.filter(f=>f.kind==='format')).toHaveLength(7);expect(()=>resolveRevisions(p,'accept')).toThrow(expect.objectContaining({code:'docx-revisions-unsupported'}));expect(p.toBytes()).toEqual(before);expect(resolve(p,'reject',['word/header1.xml'])).toEqual({resolved:3,changedParts:['word/header1.xml']});await bytesEqual(p,base,['word/header1.xml']);expect(inspect(p).revisions).toHaveLength(18);expect(stories).toHaveLength(7);});
test('unsafe later run-property snapshots refuse both actions without partially resolving earlier text stories',async()=>{const defects:[string,(s:string)=>string][]=[
 ['missing',s=>s.replace('<w:rPr>'+previous+'</w:rPr>','')],
 ['duplicate-snapshot',s=>s.replace(previous,previous+'</w:rPr><w:rPr>')],
 ['duplicate-change',s=>s.replace(change,change+change.replace('80','81'))],
 ['nested',s=>s.replace(previous,previous+change.replace('80','81'))],
 ['wrong-parent',s=>s.replace(properties,properties.replace(change,'')+change)],
 ['drawing',s=>s.replace('<w:t>Stable</w:t>','<w:drawing/>')],
 ['unknown',s=>s.replace('<w:i/>','<w:glow/>')],
 ['duplicate-property',s=>s.replace('<w:i/>','<w:i/><w:i/>')],
 ['decorated',s=>s.replace('<w:i/>','<w:i vendor="x"/>')],
 ['invalid',s=>s.replace('<w:i/>','<w:i w:val="maybe"/>')],
 ['duplicate-id',s=>s.replace('w:id="80"',s.match(/w:id="\d+"/)![0])],
 ['bad-order',s=>s.replace(previous,'<w:color w:val="445566"/><w:i/>')],
 ['mixed',s=>s.replace(previous,'UNOWNED'+previous)],
 ['nested-text',s=>s.replace('<w:rPr>'+previous+'</w:rPr>','<w:rPr><w:ins w:id="81"/></w:rPr>')],
 ['foreign',s=>s.replace('<w:i/>','<x:i xmlns:x="urn:other"/>')],
 ['missing-author',s=>s.replace(' w:author="Editor"','')],
 ['unqualified-author',s=>s.replace('w:author="Editor"','author="Editor"')],
 ['paragraph-mark',s=>s.replace(run,'<w:pPr>'+properties+'</w:pPr>')],
 ['comment',s=>s.replace(previous,'<!--unowned-->'+previous)],
 ['conflicting-flags',s=>s.replace('<w:i/>','<w:caps/><w:smallCaps/>')],
 ['nested-insertion',s=>s.replace(run,'<w:ins w:id="90" w:author="Editor">'+run+'</w:ins>')],
 ];for(const [name,defect]of defects)for(const action of ['accept','reject'] as const){const {p}=await input(),part='word/header1.xml',xml=p.text(part),changed=defect(xml);expect(changed,name).not.toBe(xml);p.set(part,changed);const before=p.toBytes();expect(inspect(p).unsupported.length,name).toBeGreaterThan(0);expect(()=>resolve(p,action),name).toThrow(expect.objectContaining({code:'docx-revisions-unsupported'}));expect(p.toBytes(),name).toEqual(before);}});
test('run-property snapshot namespace meaning BOM and unrelated lexical bytes survive reject in three encodings',async()=>{for(const encoding of ['bom','le','be']){const {p}=await input(),part=p.mainPart();let xml=p.text(part).replace(properties,`<w:rPr xmlns:z="${W}">${current}<w:rPrChange xmlns:q="${W}" w:id="80" w:author="Editor"><q:rPr><q:i/><z:color z:val='445566'/></q:rPr></w:rPrChange></w:rPr>`);if(encoding==='bom')p.set(part,new Uint8Array([239,187,191,...new TextEncoder().encode(xml)]));else{xml=xml.replace(/encoding="UTF-8"/i,'encoding="UTF-16"');const bytes=new Uint8Array(2+xml.length*2);bytes.set(encoding==='le'?[255,254]:[254,255]);const v=new DataView(bytes.buffer);for(let i=0;i<xml.length;i++)v.setUint16(2+i*2,xml.charCodeAt(i),encoding==='le');p.set(part,bytes);}const baseline=await OpcPackage.open(p.toBytes());expect(resolve(p,'reject',[part])).toEqual({resolved:3,changedParts:[part]});const read=await OpcPackage.open(p.toBytes());const parsed=parseXml(read.text(part)),props=elements(parsed,'rPr',W).find(n=>n.children.some(c=>c.localName==='i'))!;expect(props.name).toBe('q:rPr');expect(props.children.map(c=>[c.namespaceURI,c.localName])).toEqual([[W,'i'],[W,'color']]);expect(attribute(props.children[1]!,'val',W)).toBe('445566');expect(read.text(part)).toContain("z:val='445566'");expect([...read.get(part)!.slice(0,encoding==='bom'?3:2)]).toEqual(encoding==='bom'?[239,187,191]:encoding==='le'?[255,254]:[254,255]);await bytesEqual(read,baseline,[part]);}});
test('run-property profile validates protected external-settings and invalid profile requests before no-op',async()=>{for(const defect of ['protected','external','invalid']){const {p}=await input();if(defect==='protected'){p.set('word/settings.xml',`<w:settings xmlns:w="${W}"><w:documentProtection w:enforcement="1"/></w:settings>`);addRelationship(p,p.mainPart(),'http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings','settings.xml');}if(defect==='external')addRelationship(p,p.mainPart(),'http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings','https://example.invalid/settings',{external:true});const before=p.toBytes();expect(()=>resolveRevisions(p,'accept',{profile:(defect==='invalid'?'bad':profile) as typeof profile})).toThrow();expect(p.toBytes()).toEqual(before);}});
test('reached later-write and serialization faults restore property snapshots text flags and prior unrelated edits',async()=>{for(const stage of ['write','serialize']){const {p}=await input();p.set(p.mainPart(),p.text(p.mainPart()).replace('</w:body>','<w:p><w:r><w:t>Prior edit</w:t></w:r></w:p></w:body>'));const before=p.toBytes(),set=p.set.bind(p),serialize=p.toBytes.bind(p);let reached=false;if(stage==='write')p.set=(n,v)=>{set(n,v);if(n==='word/header1.xml'){reached=true;throw Error('injected property write');}};else p.toBytes=()=>{reached=true;throw Error('injected property serialize');};try{expect(()=>resolve(p,'reject')).toThrow('injected');expect(reached).toBe(true);}finally{p.set=set;p.toBytes=serialize;}expect(p.toBytes()).toEqual(before);expect(inspect(p).revisions).toHaveLength(21);}});
test('empty previous properties restore the complete empty set and namespace shadowing stays local',async()=>{for(const saved of ['<w:rPr/>',`<w:rPr xmlns:q="${W}"><q:i/></w:rPr>`]){const {p}=await input(),part=p.mainPart();p.set(part,p.text(part).replace(change,`<w:rPrChange xmlns:q="urn:outer" w:id="80" w:author="Editor">${saved}</w:rPrChange>`));expect(resolve(p,'reject',[part]).resolved).toBe(3);const xml=p.text(part),r=elements(parseXml(xml),'r',W).find(r=>r.children.some(t=>t.localName==='t'&&t.text==='Stable'))!,pr=r.children[0]!;expect(pr.localName).toBe('rPr');expect(pr.children.map(c=>[c.namespaceURI,c.localName])).toEqual(saved.includes('q:i')?[[W,'i']]:[]);expect(xml).not.toContain('rPrChange');}});
test('extended-profile no-op still checks linked protection and external settings without changing bytes',async()=>{for(const defect of ['protected','external','wrong-root']){const {p}=await input();resolve(p,'accept');if(defect==='external')addRelationship(p,p.mainPart(),'http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings','https://example.invalid/settings',{external:true});else{p.set('word/settings.xml',defect==='wrong-root'?`<w:notSettings xmlns:w="${W}"/>`:`<w:settings xmlns:w="${W}"><w:documentProtection w:enforcement="1"/></w:settings>`);addRelationship(p,p.mainPart(),'http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings','settings.xml');}const before=p.toBytes();expect(()=>resolve(p,'reject')).toThrow(expect.objectContaining({code:'docx-revisions-protected'}));expect(p.toBytes()).toEqual(before);}});
test('default text revision writer also retains UTF8 BOM and extended profile refuses unknown selections and moves',async()=>{const p=await openRevisionFixture('all-stories'),part=p.mainPart();p.set(part,new Uint8Array([239,187,191,...new TextEncoder().encode(p.text(part))]));resolveRevisions(p,'accept',{parts:[part]});expect([...p.get(part)!.slice(0,3)]).toEqual([239,187,191]);const q=(await input()).p,before=q.toBytes();expect(()=>resolve(q,'accept',['word/unknown.xml'])).toThrow(expect.objectContaining({code:'docx-revisions-unknown-part'}));expect(()=>inspectRevisions(q,{profile:'bad' as typeof profile})).toThrow(expect.objectContaining({code:'docx-revisions-invalid-profile'}));expect(q.toBytes()).toEqual(before);q.set(part,q.text(part).replace(run,'<w:moveFrom w:id="90" w:author="Editor">'+run+'</w:moveFrom>'));const moved=q.toBytes();expect(()=>resolve(q,'accept')).toThrow(expect.objectContaining({code:'docx-revisions-unsupported'}));expect(q.toBytes()).toEqual(moved);});
test('all supported direct property families restore exact previous set and malformed scalar values refuse',async()=>{const saved='<w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b w:val="0"/><w:bCs/><w:i/><w:iCs/><w:strike/><w:shadow/><w:vanish/><w:color w:val="auto"/><w:sz w:val="28"/><w:szCs w:val="24"/><w:highlight w:val="yellow"/><w:u w:val="double"/><w:vertAlign w:val="superscript"/></w:rPr>';const {p}=await input(),part=p.mainPart();p.set(part,p.text(part).replace('<w:rPr>'+previous+'</w:rPr>',saved));expect(resolve(p,'reject',[part]).resolved).toBe(3);expect(p.text(part)).toContain(saved);for(const invalid of [saved.replace('w:val="28"','w:val="0"'),saved.replace('w:val="24"','w:val="1.5"'),saved.replace('w:hAnsi="Arial"','w:hAnsi="Calibri"'),saved.replace('w:val="yellow"','w:val="purple"'),saved.replace('w:val="double"','w:val="unknown"'),saved.replace('w:val="auto"','w:themeColor="accent1"')]){const q=(await input()).p;q.set(part,q.text(part).replace('<w:rPr>'+previous+'</w:rPr>',invalid));const before=q.toBytes();expect(()=>resolve(q,'accept')).toThrow(expect.objectContaining({code:'docx-revisions-unsupported'}));expect(q.toBytes()).toEqual(before);}});
test('post-write validation fault rolls back and unsupported unselected properties do not expand selected scope',async()=>{const {p}=await input(),part='word/header1.xml';p.set(part,p.text(part).replace('<w:i/>','<w:unknown/>'));const baseline=await OpcPackage.open(p.toBytes());expect(resolve(p,'accept',[p.mainPart()]).resolved).toBe(3);await bytesEqual(p,baseline,[p.mainPart()]);const q=(await input()).p,before=q.toBytes(),set=q.set.bind(q);let reached=false;q.set=(n,v)=>{set(n,v);if(n===part){reached=true;set(n,q.text(n).replace('<w:rPr>'+previous+'</w:rPr>',properties));}};try{expect(()=>resolve(q,'reject')).toThrow(expect.objectContaining({code:'docx-revisions-validation'}));expect(reached).toBe(true);}finally{q.set=set;}expect(q.toBytes()).toEqual(before);});
test('public entrypoints expose the opt-in profile without activating the broader shared or local revision obligations',async()=>{const root=await import('../../src/index.ts'),docx=await import('../../src/docx/index.ts');expect(root.inspectRevisions).toBe(inspectRevisions);expect(docx.resolveRevisions).toBe(resolveRevisions);const {inventoryFeatures}=await import('../../scripts/gherkin.ts'),inv=await inventoryFeatures(process.cwd());expect(inv.counts.cases.implemented).toBe(729);expect(inv.counts.cases.planned).toBe(59);const f=inv.features.find(f=>f.scenarios.some(s=>s.scenarioId==='@id-docx-review-multistory-resolution'))!,s=f.scenarios.find(s=>s.scenarioId==='@id-docx-review-multistory-resolution')!;expect(s.lifecycle??f.lifecycle).toBe('planned');});
