import {test,expect} from 'bun:test';import {outcomeMappingReport,reconcileOutcomeMappingSets,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';import {inventoryTestSource} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {join} from 'node:path';
const definitions=[
 {name:'pptx-text-boxes',path:'tests/unit/pptx-text-box.test.ts',canonical:'workflows/pptx/text-box.feature',count:11,assertions:40,cases:23,sources:['tests/acceptance/text-box.ts','src/pptx/index.ts','src/pptx/text-box.ts','src/opc/package.ts','src/xml/index.ts','src/errors.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts']},
 {name:'docx-page-layout',path:'tests/unit/docx-page-layout.test.ts',canonical:'workflows/docx/page-layout.feature',count:13,assertions:44,cases:22,sources:['tests/acceptance/page-layout.ts','src/docx/index.ts','src/docx/page-layout.ts','src/opc/package.ts','src/opc/graph.ts','src/xml/index.ts','src/errors.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts']},
];
async function sample(d:typeof definitions[number]){const ledger=await Bun.file(`docs/behaviors/${d.name}-mappings.json`).json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of [d.path,...d.sources,d.canonical])sources[p]=await Bun.file(p===d.canonical?join(fixturesRoot(),p):p).text();return {inventory:{cases:inventoryTestSource(d.path,sources[d.path]!),unresolved:[]},sets:[{name:d.name,expectedScopePaths:[d.path],ledger,features:[parseFeature(d.canonical,sources[d.canonical]!)],sources}]};}
test('geometry ledgers cover 24 declarations and 84 expressions with all 295 prior records preserved',async()=>{
 const r=await outcomeMappingReport();for(const d of definitions){const rows=r.mappings.filter(m=>m.ledger===d.name);expect(rows).toHaveLength(d.count);expect(rows.reduce((n,m)=>n+m.assertions.length,0)).toBe(d.assertions);expect(r.ledgers.find(l=>l.name===d.name)!.scopePaths).toEqual([d.path]);expect(rows.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([d.cases]);expect(rows.every(m=>m.status==='partial'&&m.executionCredit===false&&m.gaps.length&&m.outcomes.length)).toBe(true);}expect(r.mappedDeclarations).toBe(461);expect(r.unmappedTestIds.length).toBe(r.totalDeclarations-461);expect(r.runtimeLeafCount).toBeNull();expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(r.mappings.filter(m=>['slide-order','effective-formatting','xml-values','pptx-core','docx-model','docx-anchors','xlsx-comments','xlsx-styles','formula-references'].includes(m.ledger)))).digest('hex')).toBe('62cd07b9e6b8645d0e55b40a3513ae33738e01681a61c41cab1c193e681d8f56');
});
test('geometry mappings separate byte serialization disk readback and live getter scope',async()=>{
 const r=await outcomeMappingReport(),boxes=r.mappings.filter(m=>m.ledger==='pptx-text-boxes'),layouts=r.mappings.filter(m=>m.ledger==='docx-page-layout');for(const rows of [boxes,layouts]){expect(rows[0]!.gaps.join(' ')).toContain('aggregate');expect(rows[0]!.gaps.join(' ')).toContain('byte reopen');expect(rows[0]!.gaps.join(' ')).toContain('no path save');}expect(boxes[9]!.gaps.join(' ')).toContain('byte reopen');expect(boxes[10]!.outcomes.join(' ')).toContain('disk');expect(boxes[10]!.gaps.join(' ')).toContain('geometry');expect(layouts[3]!.gaps.join(' ')).toContain('live');expect(layouts[3]!.gaps.join(' ')).toContain('no reopened geometry');expect(layouts[6]!.gaps.join(' ')).toContain('live');expect(layouts[10]!.outcomes.join(' ')).toContain('disk');expect(layouts[10]!.caseKeys).toEqual([]);
});
test('each geometry suite and every literal assertion are mandatory and cannot borrow other feature cases',async()=>{
 for(const d of definitions){const a=await sample(d);a.sets[0]!.ledger.scopePaths=[];expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('scope');const b=await sample(d);b.sets[0]!.ledger.mappings.pop();expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('Missing scoped');const c=await sample(d);c.sets[0]!.ledger.mappings[0]!.assertions.pop();expect(()=>reconcileOutcomeMappingSets(c.inventory,c.sets)).toThrow('assertion');const e=await sample(d);e.sets[0]!.ledger.mappings[0]!.caseKeys=['@id-xlsx-cell-style-selection|{"kind":"assign"}'];expect(()=>reconcileOutcomeMappingSets(e.inventory,e.sets)).toThrow('case');}
});
test('geometry runtime binding fixture-helper and canonical source pins all fail independently when stale or missing',async()=>{
 for(const d of definitions)for(const p of [d.path,...d.sources,d.canonical]){const a=await sample(d);expect(Object.hasOwn(a.sets[0]!.ledger.sourceSha256,p)).toBe(true);a.sets[0]!.sources[p]+=' ';expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('Stale source');const b=await sample(d);delete b.sets[0]!.ledger.sourceSha256[p];expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('pin');}
});
test('geometry reconciliation preserves original inputs direct and deferred assertions and review flags',async()=>{
 for(const d of definitions){const a=await sample(d),before=JSON.stringify(a),r=reconcileOutcomeMappingSets(a.inventory,a.sets);expect(JSON.stringify(a)).toBe(before);expect(r.mappings.map(m=>m.assertions)).toEqual(a.inventory.cases.map(m=>m.assertions));expect(r.mappings.map(m=>m.deferredAssertions)).toEqual(a.inventory.cases.map(m=>m.deferredAssertions));expect(r.mappings.map(m=>m.reviewReasons)).toEqual(a.inventory.cases.map(m=>m.reviewReasons));expect(r.executionCredit).toBe(false);expect(r.runtimeLeafCount).toBeNull();}
});
