import {test,expect} from 'bun:test';import {outcomeMappingReport,reconcileOutcomeMappingSets,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';import {inventoryTestSource} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {join} from 'node:path';
const paths=['tests/unit/graph.test.ts','tests/unit/package-diff.test.ts'],canonical='workflows/package/graph.feature',ids=['@id-opc-add-related-part','@id-opc-graph-rollback','@id-opc-remove-related-part','@id-opc-diff-content-type'];
const pins=[...paths,'tests/acceptance/graph.ts','src/opc/graph.ts','src/opc/diff.ts','src/opc/package.ts','src/opc/content-types.ts','src/opc/zip.ts','src/xml/index.ts','src/errors.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts',canonical];
async function sample(){const ledger=await Bun.file('docs/behaviors/opc-graph-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of pins)sources[p]=await Bun.file(p===canonical?join(fixturesRoot(),p):p).text();return {inventory:{cases:paths.flatMap(p=>inventoryTestSource(p,sources[p]!)),unresolved:[]},sets:[{name:'opc-graph',expectedScopePaths:paths,ledger,features:[parseFeature(canonical,sources[canonical]!)],sources}]};}
test('OPC graph ledger enumerates 15 declarations and 56 expressions preserving 392 previous mappings',async()=>{
 const r=await outcomeMappingReport(),rows=r.mappings.filter(m=>m.ledger==='opc-graph');expect(rows).toHaveLength(15);expect(rows.reduce((n,m)=>n+m.assertions.length,0)).toBe(56);expect(r.ledgers.find(l=>l.name==='opc-graph')!.scopePaths).toEqual(paths);expect(rows.every(m=>m.caseKeys.length===0)).toBe(true);expect(new Set(rows.flatMap(m=>m.scenarioIds))).toEqual(new Set(ids));expect(rows.every(m=>m.status==='partial'&&m.executionCredit===false&&m.gaps.length&&m.outcomes.length)).toBe(true);expect(r.mappedDeclarations).toBe(516);expect(r.unmappedTestIds.length).toBe(r.totalDeclarations-516);expect(r.runtimeLeafCount).toBeNull();expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(r.mappings.filter(m=>['slide-order','effective-formatting','xml-values','pptx-core','docx-model','docx-anchors','xlsx-comments','xlsx-styles','pptx-text-boxes','docx-page-layout','docx-paragraph-styles','docx-style-authoring','xml-comparison','package-comparison','docx-comments','formula-references'].includes(m.ledger)))).digest('hex')).toBe('061c0d3b8ea7d4d3a38607be923b791ea7be2144bd6b3592cb22cc20787748fe');
});
test('OPC graph mapping limits byte reopen narrow payload checks live removals and direct diff construction',async()=>{
 const rows=(await outcomeMappingReport()).mappings.filter(m=>m.ledger==='opc-graph');expect(rows[0]!.gaps.join(' ')).toContain('byte reopen');expect(rows[0]!.gaps.join(' ')).toContain('new payload');expect(rows[3]!.gaps.join(' ')).toContain('encoding');expect(rows[7]!.gaps.join(' ')).toContain('external');expect(rows[9]!.gaps.join(' ')).toContain('live');expect(rows[11]!.gaps.join(' ')).toContain('ZIP comment');expect(rows[13]!.gaps.join(' ')).toContain('set/delete');expect(rows[14]!.gaps.join(' ')).toContain('custom/payload.bin');expect(rows.every(m=>m.gaps.join(' ').includes('no semantic XML'))).toBe(true);
});
test('OPC graph scope and literal assertions cannot shrink or borrow semantic diff cases',async()=>{
 for(const p of paths){const a=await sample();a.sets[0]!.ledger.scopePaths=a.sets[0]!.ledger.scopePaths.filter(x=>x!==p);expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('scope');const b=await sample();b.sets[0]!.ledger.mappings.splice(b.sets[0]!.ledger.mappings.findIndex(m=>m.testId.includes(p)),1);expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('Missing scoped');const c=await sample();c.sets[0]!.ledger.mappings.find(m=>m.testId.includes(p))!.assertions.pop();expect(()=>reconcileOutcomeMappingSets(c.inventory,c.sets)).toThrow('assertion');const d=await sample();d.sets[0]!.ledger.mappings.find(m=>m.testId.includes(p))!.caseKeys=['@id-package-diff-equivalent-xml-and-binary-changes'];expect(()=>reconcileOutcomeMappingSets(d.inventory,d.sets)).toThrow('case');}
});
test('OPC graph runtime fixture and canonical source pins fail independently when stale or absent',async()=>{
 for(const p of pins){const a=await sample();expect(Object.hasOwn(a.sets[0]!.ledger.sourceSha256,p)).toBe(true);a.sets[0]!.sources[p]+=' ';expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('Stale source');const b=await sample();delete b.sets[0]!.ledger.sourceSha256[p];expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('pin');}
});
test('OPC graph reconciliation retains original evidence direct deferred assertions flags and unknown runtime leaves',async()=>{
 const a=await sample(),before=JSON.stringify(a),r=reconcileOutcomeMappingSets(a.inventory,a.sets);expect(JSON.stringify(a)).toBe(before);expect(r.mappings.map(m=>m.assertions)).toEqual(a.inventory.cases.map(m=>m.assertions));expect(r.mappings.map(m=>m.deferredAssertions)).toEqual(a.inventory.cases.map(m=>m.deferredAssertions));expect(r.mappings.map(m=>m.reviewReasons)).toEqual(a.inventory.cases.map(m=>m.reviewReasons));expect(r.executionCredit).toBe(false);expect(r.runtimeLeafCount).toBeNull();
});
