import {beforeSharedPlannedExpansion} from './mapping-history.ts';
import {test,expect} from 'bun:test';import {outcomeMappingReport,reconcileOutcomeMappingSets,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';import {inventoryTestSource} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {join} from 'node:path';
const paths=['tests/unit/package.test.ts','tests/unit/opc-custody-bindings.test.ts'],canonical='workflows/package/preservation.feature';
const pins=[...paths,'tests/acceptance/opc-custody.ts','tests/acceptance/refusal-outcomes.ts','tests/acceptance/steps.ts','tests/fixtures/admission.ts','src/opc/package.ts','src/opc/zip.ts','src/xml/index.ts','src/xml/encoding.ts','src/errors.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts',canonical];
async function sample(){const ledger=await Bun.file('docs/behaviors/opc-custody-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of pins)sources[p]=await Bun.file(p===canonical?join(fixturesRoot(),p):p).text();return {inventory:{cases:paths.flatMap(p=>inventoryTestSource(p,sources[p]!)),unresolved:[]},sets:[{name:'opc-custody',expectedScopePaths:paths,ledger,features:[parseFeature(canonical,sources[canonical]!)],sources}]};}
test('OPC custody ledger enumerates 15 declarations and 66 expressions preserving 446 predecessor records',async()=>{
 const r=await outcomeMappingReport(),rows=r.mappings.filter(m=>m.ledger==='opc-custody');expect(rows).toHaveLength(15);expect(rows.reduce((n,m)=>n+m.assertions.length,0)).toBe(66);expect(r.ledgers.find(l=>l.name==='opc-custody')!.scopePaths).toEqual(paths);expect(rows.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([11]);expect(rows.every(m=>m.status==='partial'&&m.executionCredit===false&&m.gaps.length&&m.outcomes.length)).toBe(true);expect(r.mappedDeclarations).toBe(590);expect(r.unmappedTestIds.length).toBe(r.totalDeclarations-590);expect(r.runtimeLeafCount).toBeNull();expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(beforeSharedPlannedExpansion(r.mappings.filter(m=>['slide-order','effective-formatting','xml-values','pptx-core','docx-model','docx-anchors','xlsx-comments','xlsx-styles','pptx-text-boxes','docx-page-layout','docx-paragraph-styles','docx-style-authoring','xml-comparison','package-comparison','docx-comments','opc-graph','zip64','zip32','formula-references'].includes(m.ledger))))).digest('hex')).toBe('c25b25d5bd794ec103500d02ad68c4902fba0cb1fd94f4383bc2fe02966eb1bb');
});
test('OPC custody descriptions distinguish exact corpus archives native live reads and physical destinations',async()=>{
 const rows=(await outcomeMappingReport()).mappings.filter(m=>m.ledger==='opc-custody');expect(rows[0]!.gaps.join(' ')).toContain('relationship target');expect(rows[4]!.gaps.join(' ')).toContain('ZIP layer');expect(rows[5]!.gaps.join(' ')).toContain('live');expect(rows[6]!.outcomes.join(' ')).toContain('disk');expect(rows[7]!.gaps.join(' ')).toContain('symlink');expect(rows[8]!.gaps.join(' ')).toContain('combined');expect(rows[9]!.gaps.join(' ')).toContain('three planned');expect(rows[9]!.gaps.join(' ')).toContain('aggregate');expect(rows[10]!.gaps.join(' ')).toContain('nested');expect(rows[14]!.outcomes.join(' ')).toContain('ENOENT');expect(rows.every(m=>!m.scenarioIds.includes('@id-opc-package-transaction-rollback'))).toBe(true);
});
test('OPC custody scopes exact assertions and unrelated graph-case borrowing refuse',async()=>{
 for(const p of paths){const a=await sample();a.sets[0]!.ledger.scopePaths=a.sets[0]!.ledger.scopePaths.filter(x=>x!==p);expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('scope');const b=await sample();b.sets[0]!.ledger.mappings.splice(b.sets[0]!.ledger.mappings.findIndex(m=>m.testId.includes(p)),1);expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('Missing scoped');const c=await sample();c.sets[0]!.ledger.mappings.find(m=>m.testId.includes(p))!.assertions.pop();expect(()=>reconcileOutcomeMappingSets(c.inventory,c.sets)).toThrow('assertion');const d=await sample();d.sets[0]!.ledger.mappings.find(m=>m.testId.includes(p))!.caseKeys=['@id-opc-add-related-part'];expect(()=>reconcileOutcomeMappingSets(d.inventory,d.sets)).toThrow('case');}
});
test('OPC custody source pins independently reject stale or absent suite runtime helper and shared files',async()=>{
 for(const p of pins){const a=await sample();expect(Object.hasOwn(a.sets[0]!.ledger.sourceSha256,p)).toBe(true);a.sets[0]!.sources[p]+=' ';expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('Stale source');const b=await sample();delete b.sets[0]!.ledger.sourceSha256[p];expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('pin');}
});
test('OPC custody reconciliation retains direct versus nested assertions original inputs flags and unknown leaves',async()=>{
 const a=await sample(),before=JSON.stringify(a),r=reconcileOutcomeMappingSets(a.inventory,a.sets);expect(JSON.stringify(a)).toBe(before);expect(r.mappings.map(m=>m.assertions)).toEqual(a.inventory.cases.map(m=>m.assertions));expect(r.mappings.map(m=>m.deferredAssertions)).toEqual(a.inventory.cases.map(m=>m.deferredAssertions));expect(r.mappings.map(m=>m.reviewReasons)).toEqual(a.inventory.cases.map(m=>m.reviewReasons));expect(r.executionCredit).toBe(false);expect(r.runtimeLeafCount).toBeNull();expect(r.mappings[10]!.deferredAssertions).toHaveLength(1);
});
