import {test,expect} from 'bun:test';
import {Presentation} from '../../src/pptx/index.ts';
import {copyCases,copyInput,copyContract} from '../helpers/smartart-copy-inputs.ts';
import {archive,graph,xml,descendants,P,R,A} from '../helpers/contract20-oracle.ts';
import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
const decode=new TextDecoder(),D='http://schemas.openxmlformats.org/drawingml/2006/diagram',DSP='http://schemas.microsoft.com/office/drawing/2008/diagram';
for(const c of copyCases)test(`${c.scenarioId} [${c.caseId}]`,async()=>{
 const source=await Presentation.open(await copyInput(c)),from=source.slides[0]!,destination=c.request.sameSlide?source:Presentation.create(),to=c.request.sameSlide?from:destination.addTextSlide(copyContract.destinationRecipe.title);
 if(c.request.protectDestination)destination.package.set(destination.package.mainPart(),destination.package.text(destination.package.mainPart()).replace('</p:presentation>','<p:modifyVerifier/></p:presentation>'));
 const srcBefore=archive(source.package.toBytes()),dstBefore=archive(destination.package.toBytes()),version=destination.currentSlideVersion(to.partName);
 if(c.errorCode){expect(()=>to.copySmartArtFrom(from,c.request.shapeId)).toThrow(expect.objectContaining({code:c.errorCode}));const after=archive(destination.package.toBytes());expect([...after.keys()].sort()).toEqual([...dstBefore.keys()].sort());for(const[n,b]of dstBefore)expect(after.get(n)).toEqual(b);expect(destination.currentSlideVersion(to.partName)).toBe(version);return;}
 const previous=from.inspectSmartArt().find(r=>r.shapeId===c.request.shapeId)!,receipt=to.copySmartArtFrom(from,c.request.shapeId);expect(receipt.shapeId).toBe(c.expected.shapeId);expect(receipt.partName).toBe(to.partName);expect(Object.keys(receipt.partMap)).toHaveLength(c.expected.parts);expect(Object.keys(receipt.modelIdMap)).toHaveLength(c.expected.nodeIdentityCount);expect(Object.keys(receipt.drawingIdMap)).toHaveLength(c.expected.drawingIdentityCount);
 const after=archive(destination.package.toBytes()),g=graph(after),copy=to.inspectSmartArt().find(r=>r.shapeId===receipt.shapeId)!;expect(copy.roots.map(r=>r.role)).toEqual(c.expected.sourceRoles);expect(copy.parts.map(p=>p.partName).sort()).toEqual(Object.values(receipt.partMap).sort());
 for(const old of previous.parts){const mapped=receipt.partMap[old.partName]!;expect(mapped).not.toBe(old.partName);expect(dstBefore.has(mapped)).toBe(false);expect(g.types.get(mapped)).toBe(old.contentType);if(old.contentType.startsWith('image/'))expect(after.get(mapped)).toEqual(srcBefore.get(old.partName));}
 for(const edge of previous.edges){const copied=g.edges.find(e=>e.owner===receipt.partMap[edge.owner]&&e.id===edge.relationshipId)!;expect(copied.type).toBe(edge.type);expect(copied.external).toBe(edge.external);if(edge.external)expect(copied.target).toBe(edge.target);else expect(copied.resolved).toBe(receipt.partMap[edge.partName!]!);}
 const data=copy.roots.find(r=>r.role==='data')!,dataXml=xml(decode.decode(after.get(data.partName))),point=descendants(dataXml,'pt',D)[0]!,ref=descendants(dataXml,'prSet',D)[0]!;const oldId='{11111111-1111-1111-1111-111111111111}',newId=receipt.modelIdMap[oldId]!;expect(newId).not.toBe(oldId);expect(newId).toMatch(/^\{[0-9A-F-]{36}\}$/);expect(point.attrs.modelId).toBe(newId);expect(ref.attrs.presAssocID).toBe(newId);
 const drawing=copy.drawingParts[0]!,drawXml=xml(decode.decode(after.get(drawing))),id=descendants(drawXml,'cNvPr',DSP)[0]!.attrs.id;expect(id).toBe('6');expect(receipt.drawingIdMap['ppt/diagrams/drawing1.xml#5']).toBe(6);
 const targetXml=decode.decode(after.get(to.partName)),frame=descendants(xml(targetXml),'graphicFrame',P).find(n=>Number(descendants(n,'cNvPr',P)[0]?.attrs.id)===receipt.shapeId)!;expect(targetXml.slice(0,frame.start)+targetXml.slice(frame.end)).toBe(decode.decode(dstBefore.get(to.partName)));
 for(const[n,b]of dstBefore)if(![to.partName,'[Content_Types].xml',to.partName.replace('/slides/','/slides/_rels/')+'.rels'].includes(n))expect(after.get(n)).toEqual(b);
 const currentSource=archive(source.package.toBytes());for(const[n,b]of srcBefore)if(!c.request.sameSlide||![to.partName,'[Content_Types].xml','ppt/slides/_rels/slide1.xml.rels'].includes(n))expect(currentSource.get(n)).toEqual(b);
 const dir=await mkdtemp(join(tmpdir(),'smartart-copy-'));try{const path=join(dir,'saved.pptx');await destination.save(path);const bytes=await Bun.file(path).bytes(),saved=archive(bytes);for(const[n,b]of after)expect(saved.get(n)).toEqual(b);expect((await Presentation.open(bytes)).slides.find(s=>s.partName===to.partName)!.inspectSmartArt()).toEqual(to.inspectSmartArt());}finally{await rm(dir,{recursive:true,force:true});}
});
test('native SmartArt copy late failure rolls back the entire cloned graph',async()=>{
 const source=await Presentation.open(await copyInput(copyCases[0])),destination=Presentation.create(),target=destination.addTextSlide(copyContract.destinationRecipe.title),before=archive(destination.package.toBytes()),version=destination.currentSlideVersion(target.partName),serialize=destination.package.toBytes;
 destination.package.toBytes=()=>{if(destination.package.text(target.partName).includes('graphicData'))throw Error('copy serialization failed');return serialize.call(destination.package);};try{expect(()=>target.copySmartArtFrom(source.slides[0]!,2000)).toThrow('copy serialization failed');}finally{destination.package.toBytes=serialize;}
 const after=archive(destination.package.toBytes());expect([...after.keys()].sort()).toEqual([...before.keys()].sort());for(const[n,b]of before)expect(after.get(n)).toEqual(b);expect(destination.currentSlideVersion(target.partName)).toBe(version);expect(target.copySmartArtFrom(source.slides[0]!,2000).shapeId).toBe(3);
});
