import {test,expect} from 'bun:test';
import {Presentation} from '../../src/pptx/index.ts';import {OpcPackage} from '../../src/opc/index.ts';
import {fixturePath} from '../../scripts/fixture-inputs.ts';
import {parseXml,elements,type XmlElement} from '../../src/xml/index.ts';
const ID='fixture-84e7a8a3681d0e43d4c8a29c37e68386721dfb5df13a36b8bd17a3ebc1fb1fb2',A='http://schemas.openxmlformats.org/drawingml/2006/main',P='http://schemas.openxmlformats.org/presentationml/2006/main';
const enabled=!!process.env.OOXML_REFERENCE_PIN&&(await Bun.file(process.env.OOXML_REFERENCE_PIN).json()).commit==='f174097e68e4133ebbfb58daf0f336480d75f210';const native=enabled?test:test.skip;
const open=async()=>Presentation.open(await Bun.file(fixturePath(ID)).bytes());
const sp=(d:Presentation)=>elements(parseXml(d.package.text('ppt/slides/slide2.xml')),'sp',P).find(s=>elements(s,'cNvPr',P)[0]?.attributes.id==='4')!;
const one=(e:XmlElement,n:string)=>elements(e,n,A)[0]!;
async function altered(from:string,to:string,member='ppt/slides/slide2.xml'){const d=await open(),pkg=d.package,xml=pkg.text(member);expect(xml.split(from).length).toBe(2);pkg.set(member,xml.replace(from,to));return Presentation.open(pkg.toBytes());}
native('directrunflagsinsertbeforetext falseisoverride andnullremoval preserves language text/siblings',async()=>{const d=await open();d.slides[1]!.patchTextRun(4,0,1,{bold:true});d.slides[1]!.patchTextRun(4,0,0,{bold:false,italic:true,underline:'none'});let x=sp(d);expect(elements(x,'rPr',A)[0]!.attributes).toMatchObject({lang:'en-US',b:'0',i:'1',u:'none',sz:'1800'});const second=elements(x,'r',A)[1]!;expect(second.children.map(c=>c.localName)).toEqual(['rPr','t']);expect(one(second,'t').text).toBe(' suffix');d.slides[1]!.patchTextRun(4,0,0,{bold:null,italic:null,underline:null,size:null,typeface:null,color:null});x=sp(await Presentation.open(d.package.toBytes()));expect({...elements(x,'rPr',A)[0]!.attributes}).toEqual({lang:'en-US'});expect(elements(x,'t',A).map(t=>t.text)).toEqual(['Existing',' suffix','Second paragraph']);});
native('attribute patches ignore propertylike tokens insidequoted unrelated values and retain lexicalnoop spellings',async()=>{const d=await altered('<a:rPr lang="en-US"','<a:rPr lang="literal sz=\'1800\' text"');d.slides[1]!.patchTextRun(4,0,0,{size:2400});expect(elements(sp(d),'rPr',A)[0]!.attributes).toMatchObject({lang:"literal sz='1800' text",sz:'2400'});const before=d.package.toBytes();d.slides[1]!.patchTextRun(4,0,0,{size:2400});expect(d.package.toBytes()).toEqual(before);});
native('selfclosingproperty expansion inserts multiplechildren in schemaorder independentofpatch keyorder',async()=>{const d=await open(),pkg=d.package,xml=pkg.text('ppt/slides/slide2.xml');pkg.set('ppt/slides/slide2.xml',xml.replace(/<a:pPr algn="l"[^]*?<\/a:pPr>/,'<a:pPr algn="l"/>'));d.slides[1]!.patchParagraph(4,0,{spaceBefore:1200,spaceAfter:600,linePercent:150000});expect(elements(sp(d),'pPr',A)[0]!.children.map(c=>c.localName)).toEqual(['lnSpc','spcBef','spcAft']);d.slides[1]!.patchParagraph(4,0,{alignment:'ctr'});d.slides[1]!.patchTextRun(4,0,1,{typeface:'Aptos',color:'A1B2C3'});expect(elements(sp(d),'rPr',A)[1]!.children.map(c=>c.localName)).toEqual(['solidFill','latin']);});
native('directformat schemaorder and significant XMLsafe typeface remains literal afterreopen',async()=>{const d=await open();d.slides[1]!.patchTextRun(4,0,1,{color:'ABCDEF',typeface:' A&B "雪" ',size:1200});d.slides[1]!.patchParagraph(4,1,{alignment:'ctr',spaceBefore:1200,spaceAfter:600,linePercent:150000});const reopened=await Presentation.open(d.package.toBytes()),x=sp(reopened),second=elements(x,'r',A)[1]!,pr=one(second,'rPr');expect(pr.children.map(c=>c.localName)).toEqual(['solidFill','latin']);expect(one(pr,'latin').attributes.typeface).toBe(' A&B "雪" ');const ppr=elements(x,'pPr',A)[1]!;expect(ppr.children.map(c=>c.localName)).toEqual(['lnSpc','spcBef','spcAft']);});
native('formatting boolean/range/type/lateinvalid patches refuse atomically without consuming livehandle',async()=>{for(const op of [(d:Presentation)=>d.slides[1]!.setHidden('yes' as any),(d:Presentation)=>d.slides[1]!.patchShapeGeometry(4,{x:null as any}),(d:Presentation)=>d.slides[1]!.patchShapeGeometry(4,{x:914400,width:-1}),(d:Presentation)=>d.slides[1]!.patchShapeGeometry(4,{rotation:21600000}),(d:Presentation)=>d.slides[1]!.patchShapeGeometry(4,{flipV:0 as any}),(d:Presentation)=>d.slides[1]!.patchTextRun(4,0,0,{bold:1 as any}),(d:Presentation)=>d.slides[1]!.patchTextRun(4,0,0,{size:0}),(d:Presentation)=>d.slides[1]!.patchTextRun(4,0,0,{color:'bad'}),(d:Presentation)=>d.slides[1]!.patchTextRun(4,0,0,{typeface:'bad\u0000'}),(d:Presentation)=>d.slides[1]!.patchParagraph(4,0,{spaceAfter:158401}),(d:Presentation)=>d.slides[1]!.patchTextRun(4,0,99,{bold:true})]){const d=await open(),before=d.package.toBytes(),held=d.slides[1]!;expect(()=>op(d)).toThrow();expect(d.package.toBytes()).toEqual(before);expect(d.slides[1]).toBe(held);held.patchTextRun(4,0,0,{bold:false});}});
native('formatting inherited/executablepatches do notinvokegetters and XMLunsafe scalars refuse',async()=>{const d=await open(),before=d.package.toBytes();let calls=0;const p:any={};Object.defineProperty(p,'bold',{enumerable:true,get(){calls++;return true;}});expect(()=>d.slides[1]!.patchTextRun(4,0,0,p)).toThrow();expect(calls).toBe(0);expect(()=>d.slides[1]!.patchTextRun(4,0,0,Object.create({bold:true}))).toThrow();expect(d.package.toBytes()).toEqual(before);});
native('protection/grouped/duplicate/field/hyperlink/namespace/spacing/fill ambiguities refuse beforewriting',async()=>{for(const[from,to]of [
 ['<p:cNvPr id="4" name="Body"/>','<p:cNvPr id="3" name="Body"/>'],
 ['<a:rPr lang="en-US"','<a:rPr xmlns:a="urn:foreign" lang="en-US"'],
 ['<a:latin typeface="Arial"/>','<a:latin typeface="Arial"/><a:latin typeface="Arial"/>'],
 ['<a:srgbClr val="112233"/>','<a:srgbClr val="112233"/><a:srgbClr val="445566"/>'],
 ['<a:spcPts val="0"/></a:spcBef>','<a:spcPts val="0"/><a:spcPts val="1"/></a:spcBef>'],
 ['<a:t xml:space="preserve">Existing','<a:t xml:space="preserve"><!--barrier-->Existing'],
 ['<p:cNvSpPr txBox="1"/>','<p:cNvSpPr txBox="1"><a:spLocks noTextEdit="1"/></p:cNvSpPr>'],
 ['<a:latin typeface="Arial"/>','<a:latin typeface="Arial"/><a:hlinkClick r:id="rId1"/>'],
 ] as const){const d=await altered(from,to),before=d.package.toBytes();expect(()=>d.slides[1]!.patchTextRun(4,0,0,{bold:false})).toThrow();expect(d.package.toBytes()).toEqual(before);}
 const protectedDeck=await altered('</p:presentation>','<p:modifyVerifier/></p:presentation>','ppt/presentation.xml'),before=protectedDeck.package.toBytes();expect(()=>protectedDeck.slides[1]!.patchShapeGeometry(4,{x:10})).toThrow();expect(protectedDeck.package.toBytes()).toEqual(before);});
native('geometry preservesoff/extsiblings and rejects unknownchildren and nestedidentity',async()=>{const d=await open();d.slides[1]!.patchShapeGeometry(4,{rotation:5400000,flipH:true,flipV:false});d.slides[1]!.patchShapeGeometry(4,{x:914400,y:1828800,width:3657600,height:1828800});const x=one(sp(await Presentation.open(d.package.toBytes())),'xfrm');expect(x.attributes).toMatchObject({rot:'5400000',flipH:'1',flipV:'0'});expect(one(x,'off').attributes).toMatchObject({x:'914400',y:'1828800'});const bad=await altered('<a:ext cx="1000" cy="1000"/>','<a:ext cx="1000" cy="1000"/><a:chOff x="0" y="0"/>'),before=bad.package.toBytes();expect(()=>bad.slides[1]!.patchShapeGeometry(4,{x:10})).toThrow();expect(bad.package.toBytes()).toEqual(before);});
native('visibility accepts XMLboolean spellings refusesforeignshow andkeepsidentity throughreorder',async()=>{for(const raw of ['0','1','true','false']){const d=await altered('<p:sld xmlns:a=','<p:sld show="'+raw+'" xmlns:a=');expect(d.slides[1]!.hidden).toBe(raw==='0'||raw==='false');d.slides[1]!.setHidden(false);expect(parseXml(d.package.text(d.slides[1]!.partName)).root.attributes.show).toBe('1');}const bad=await altered('<p:sld xmlns:a=','<p:sld p:show="0" xmlns:a='),before=bad.package.toBytes();expect(()=>bad.slides[1]!.setHidden(true)).toThrow();expect(bad.package.toBytes()).toEqual(before);const d=await open(),slide=d.slides[1]!;slide.setHidden(true);d.reorderSlides([2,0,1]);expect(d.slides[2]).toBe(slide);expect(d.slides[2]!.hidden).toBe(true);});
native('formatting serialization failure rollsbackallbytes andversions andexistingtargetremains usable',async()=>{const d=await open(),before=d.package.toBytes(),pkg=d.package as OpcPackage,real=pkg.toBytes.bind(pkg);let reached=false;pkg.toBytes=()=>{reached=true;throw Error('injected validation');};try{expect(()=>d.slides[1]!.patchParagraph(4,0,{alignment:'ctr'})).toThrow('injected validation');}finally{pkg.toBytes=real;}expect(reached).toBe(true);expect(d.package.toBytes()).toEqual(before);d.slides[1]!.patchParagraph(4,0,{alignment:'ctr'});});
