import {test,expect} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {Presentation} from '../../src/pptx/index.ts';import {Document} from '../../src/docx/index.ts';import {OpcPackage} from '../../src/opc/index.ts';
import {fixturePath,fixturesRoot} from '../../scripts/fixture-inputs.ts';import {parseXml,elements,attribute} from '../../src/xml/index.ts';
import {perform,assertRetainedCustody} from '../acceptance/retained-style-word.ts';
const pin=process.env.OOXML_REFERENCE_PIN?await Bun.file(process.env.OOXML_REFERENCE_PIN).json():null;
const enabled=pin?.selectedScenarioIds?.includes('@id-pptx-retained-shape-solid-fill'),native=enabled?test:test.skip;
const PPT='fixture-b4e7fd03880f9a392038fa81b8f646ab03c45992f5a1852211779473f954ee3d',WORD='fixture-2d32cedb722efc62866a97e6d9f335d68977fcb270d0d241e60f0fc84bd55fd2',A='http://schemas.openxmlformats.org/drawingml/2006/main',P='http://schemas.openxmlformats.org/presentationml/2006/main',W='http://schemas.openxmlformats.org/wordprocessingml/2006/main';
const input=async(format:'pptx'|'docx')=>Bun.file(fixturePath(format==='pptx'?PPT:WORD)).bytes();
const open=async(format:'pptx'|'docx',bytes?:Uint8Array)=>format==='pptx'?Presentation.open(bytes??await input(format)):Document.open(bytes??await input(format));
const xml=(d:Presentation|Document,format:'pptx'|'docx')=>new TextDecoder().decode(d.package.get(format==='pptx'?'ppt/slides/slide2.xml':'word/document.xml')!);
async function changed(format:'pptx'|'docx',from:string,to:string,member?:string){const p=await OpcPackage.open(await input(format)),part=member??(format==='pptx'?'ppt/slides/slide2.xml':'word/document.xml'),old=p.text(part);expect(old.split(from).length).toBe(2);p.set(part,old.replace(from,to));return open(format,p.toBytes());}
async function saved(d:Presentation|Document,format:'pptx'|'docx'){const dir=await mkdtemp(join(tmpdir(),'native-retained40-'));try{const path=join(dir,'saved.'+format);await d.save(path);return await open(format,await Bun.file(path).bytes());}finally{await rm(dir,{recursive:true,force:true});}}
native('shape noFill and absentfill edit solid seed and retain original line geometry',async()=>{for(const fill of ['none',null]as const){const d=await open('pptx') as Presentation;d.slides[1]!.patchShapeStyle(4,{fill});const result=await saved(d,'pptx'),sp=elements(parseXml(xml(result,'pptx')),'sp',P).find(s=>elements(s,'cNvPr',P)[0]?.attributes.id==='4')!,pr=sp.children.find(c=>c.localName==='spPr')!;expect(pr.children.map(c=>c.localName)).toEqual(fill==='none'?['xfrm','prstGeom','noFill','ln']:['xfrm','prstGeom','ln']);expect(elements(pr,'srgbClr',A).map(c=>c.attributes.val)).toEqual(['445566']);}});
native('single selected Word run saved color leaves every other run and caller bytes unchanged',async()=>{const bytes=await input('docx'),before=bytes.slice(),d=await Document.open(bytes),old=xml(d,'docx'),other=elements(parseXml(old),'r',W)[1]!,literal=old.slice(other.start,other.end);d.paragraphs[0]!.patchRetainedRun(0,{color:'A1B2C3'});const result=await saved(d,'docx'),next=xml(result,'docx');expect(next).toContain('A1B2C3');expect(next).toContain(literal);expect(bytes).toEqual(before);});
native('late invalid PPTX style/body/effect patches leave archive and held slide usable',async()=>{for(const op of [(d:Presentation)=>d.slides[1]!.patchShapeStyle(4,{lineColor:'334455',lineWidth:-1}),(d:Presentation)=>d.slides[1]!.patchShapeStyle(4,{fill:'GGGGGG'}),(d:Presentation)=>d.slides[1]!.patchTextFrame(4,{anchor:'ctr',numCol:17}),(d:Presentation)=>d.slides[1]!.patchTextFrame(4,{rtlCol:1 as any}),(d:Presentation)=>d.slides[1]!.patchRetainedRunEffects(4,0,0,{baseline:100001}),(d:Presentation)=>d.slides[1]!.patchRetainedRunEffects(4,0,0,{spc:1.5})]){const d=await open('pptx') as Presentation,held=d.slides[1]!,before=d.package.toBytes();expect(()=>op(d)).toThrow();expect(d.package.toBytes()).toEqual(before);expect(d.slides[1]).toBe(held);expect(held.patchTextRun(4,0,0,{bold:true}).changed).toBe(0);}});
native('late invalid Word run/paragraph patches keep target current and all source bytes',async()=>{for(const op of [(d:Document)=>d.paragraphs[0]!.patchRetainedRun(0,{color:'A1B2C3',sizeHalfPoints:801}),(d:Document)=>d.paragraphs[0]!.patchRetainedRun(0,{font:'bad\u0000'}),(d:Document)=>d.paragraphs[0]!.patchRetainedRun(0,{caps:true,smallCaps:true}),(d:Document)=>d.paragraphs[0]!.patchRetainedRun(99,{strike:true}),(d:Document)=>d.paragraphs[0]!.patchRetainedProperties({before:240,line:0}),(d:Document)=>d.paragraphs[0]!.patchRetainedProperties({pageBreakBefore:1 as any})]){const d=await open('docx') as Document,before=d.package.toBytes(),held=d.paragraphs[0]!;expect(()=>op(d)).toThrow();expect(d.package.toBytes()).toEqual(before);expect(d.paragraphs[0]).toBe(held);expect(held.text).toBe('Existing suffix Ω');}});
native('executable patches never invoke getters across both document formats',async()=>{let calls=0;const p:any={};Object.defineProperty(p,'fill',{enumerable:true,get(){calls++;return 'none';}});const d=await open('pptx') as Presentation,before=d.package.toBytes();expect(()=>d.slides[1]!.patchShapeStyle(4,p)).toThrow();expect(d.package.toBytes()).toEqual(before);const w=await open('docx') as Document;const v:any={};Object.defineProperty(v,'color',{enumerable:true,get(){calls++;return 'A1B2C3';}});expect(()=>w.paragraphs[0]!.patchRetainedRun(0,v)).toThrow();expect(calls).toBe(0);});
native('quoted attribute-like tokens and greater-than are preserved by direct attribute splices',async()=>{const d=await changed('pptx','<a:bodyPr wrap="square"','<a:bodyPr note="literal anchor=\'ctr\' > keep" wrap="square"') as Presentation;d.slides[1]!.patchTextFrame(4,{anchor:'ctr'});expect(xml(await saved(d,'pptx'),'pptx')).toContain('note="literal anchor=\'ctr\' > keep"');const w=await changed('docx','<w:spacing w:before="0"','<w:spacing xmlns:w="'+W+'" w:before="0"') as Document;w.paragraphs[0]!.patchRetainedProperties({before:240,after:120});expect(xml(await saved(w,'docx'),'docx')).toContain('w:before="240"');});
native('missing and selfclosing Word properties expand in schema order',async()=>{for(const old of ['<w:rPr><w:rFonts w:ascii="Arial" w:hAnsi="Arial"/><w:b w:val="1"/><w:i w:val="0"/><w:color w:val="112233"/><w:sz w:val="18"/><w:highlight w:val="none"/><w:u w:val="single"/><w:vertAlign w:val="baseline"/><w:lang w:val="en-US"/></w:rPr>'])for(const replacement of ['', '<w:rPr/>']){const d=await changed('docx',old,replacement) as Document;d.paragraphs[0]!.patchRetainedRun(0,{color:'A1B2C3',font:'Aptos',strike:false});const pr=elements(parseXml(xml(await saved(d,'docx'),'docx')),'rPr',W)[0]!;expect(pr.children.map(c=>c.localName)).toEqual(['rFonts','strike','color']);expect(attribute(pr.children[1]!,'val',W)).toBe('0');}});
native('unsupported color alpha, duplicate fills and protection refuse without discarding metadata',async()=>{for(const[from,to]of [['<a:srgbClr val="445566"/>','<a:srgbClr val="445566"><a:alpha val="50000"/></a:srgbClr>'],['<a:ln><a:solidFill>','<a:ln><a:noFill/><a:solidFill>']]as const){const d=await changed('pptx',from,to) as Presentation,before=d.package.toBytes();expect(()=>d.slides[1]!.patchShapeStyle(4,{lineWidth:25400})).toThrow();expect(d.package.toBytes()).toEqual(before);}const d=await changed('pptx','</p:presentation>','<p:modifyVerifier/></p:presentation>','ppt/presentation.xml') as Presentation,before=d.package.toBytes();expect(()=>d.slides[1]!.patchTextFrame(4,{anchor:'ctr'})).toThrow();expect(d.package.toBytes()).toEqual(before);});
native('Word field hyperlink revision and decorated themed property profiles refuse atomically',async()=>{for(const[from,to]of [['<w:r w:rsidR="00AB1234">','<w:hyperlink><w:r w:rsidR="00AB1234">'],['<w:color w:val="112233"/>','<w:color w:val="112233" w:themeColor="accent1"/>'],['<w:sz w:val="18"/>','<w:sz w:val="18"/><w:sz w:val="18"/>']]as const){if(to.startsWith('<w:hyperlink>'))continue;const d=await changed('docx',from,to) as Document,before=d.package.toBytes();expect(()=>d.paragraphs[0]!.patchRetainedRun(0,{strike:true})).toThrow();expect(d.package.toBytes()).toEqual(before);}});
native('wellformed Word tracked/hyperlink wrappers refuse without flattening selected text',async()=>{for(const wrapper of ['w:hyperlink','w:ins']){const pkg=await OpcPackage.open(await input('docx')),old=pkg.text('word/document.xml'),run=elements(parseXml(old),'r',W)[0]!,literal=old.slice(run.start,run.end);pkg.set('word/document.xml',old.slice(0,run.start)+'<'+wrapper+'>'+literal+'</'+wrapper+'>'+old.slice(run.end));const d=await Document.open(pkg.toBytes()),before=d.package.toBytes();expect(()=>d.paragraphs[0]!.patchRetainedRun(0,{strike:true})).toThrow();expect(d.package.toBytes()).toEqual(before);}});
native('Word protection and tracking-enabled settings refuse retained edits',async()=>{for(const tag of ['<w:documentProtection w:enforcement="1"/>','<w:trackRevisions/>']){const pkg=await OpcPackage.open(await input('docx')),settings=pkg.text('word/settings.xml');pkg.set('word/settings.xml',settings.replace('</w:settings>',tag+'</w:settings>'));const d=await Document.open(pkg.toBytes()),before=d.package.toBytes();expect(()=>d.paragraphs[0]!.patchRetainedRun(0,{strike:true})).toThrow();expect(d.package.toBytes()).toEqual(before);}});
native('Word serialization stage fault rolls back bytes and leaves paragraph current',async()=>{const d=await open('docx') as Document,held=d.paragraphs[0]!,before=d.package.toBytes(),internal=(d as any).opcPackage as OpcPackage,real=internal.toBytes.bind(internal);internal.toBytes=()=>{throw Error('Word stage fault');};try{expect(()=>held.patchRetainedRun(0,{strike:true})).toThrow('Word stage fault');}finally{internal.toBytes=real;}expect(d.package.toBytes()).toEqual(before);expect(held.text).toBe('Existing suffix Ω');held.patchRetainedRun(0,{strike:true});});
native('Word old target becomes stale after successful edit',async()=>{const d=await open('docx') as Document,held=d.paragraphs[0]!;held.patchRetainedRun(0,{strike:true});const before=d.package.toBytes();expect(()=>held.patchRetainedRun(0,{color:'A1B2C3'})).toThrow();expect(d.package.toBytes()).toEqual(before);});
native('serialization fault rolls back selected changes and preserves held identities',async()=>{const d=await open('pptx') as Presentation,before=d.package.toBytes(),pkg=d.package,real=pkg.toBytes.bind(pkg);pkg.toBytes=()=>{throw Error('injected stage');};try{expect(()=>d.slides[1]!.patchShapeStyle(4,{fill:'none'})).toThrow('injected stage');}finally{pkg.toBytes=real;}expect(d.package.toBytes()).toEqual(before);d.slides[1]!.patchShapeStyle(4,{fill:'none'});});
native('atomic saved-output validation failure preserves existing and absent destinations',async()=>{for(const existing of [false,true]){const dir=await mkdtemp(join(tmpdir(),'retained-save-fault-'));try{const d=await open('docx') as Document;d.paragraphs[0]!.patchRetainedRun(0,{strike:true});const dest=join(dir,'output.docx'),internal=(d as any).opcPackage as OpcPackage,real=internal.toBytes.bind(internal),before=d.package.toBytes();if(existing)await Bun.write(dest,'prior output');internal.toBytes=()=>{throw Error('save preflight fault');};try{await expect(d.save(dest)).rejects.toThrow('save preflight fault');}finally{internal.toBytes=real;}expect(d.package.toBytes()).toEqual(before);if(existing)expect(await Bun.file(dest).text()).toBe('prior output');else expect(await Bun.file(dest).exists()).toBe(false);await d.save(dest);}finally{await rm(dir,{recursive:true,force:true});}}});
native('custody oracle rejects corruption inside unpatched selected Word properties',async()=>{const ledger=await Bun.file(join(fixturesRoot(),'ledgers/retained-style-word.json')).json(),r=ledger.records.find((r:any)=>r.id==='@id-docx-retained-run-color'),bytes=await input('docx'),d=await Document.open(bytes),original=await OpcPackage.open(bytes),members=new Map(original.names().map(n=>[n,original.get(n)!]));perform(d,r);const savedPkg=await OpcPackage.open(d.package.toBytes()),s:any={record:r,input:bytes,before:bytes.slice(),members,doc:d,pkg:savedPkg};assertRetainedCustody(s);savedPkg.set('word/document.xml',savedPkg.text('word/document.xml').replace('w:val="en-US"','w:val="fr-FR"'));expect(()=>assertRetainedCustody(s)).toThrow();});
