import {test,expect} from 'bun:test';import {join} from 'node:path';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {inventoryNativeTests} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {outcomeMappingReport,reconcileOutcomeMappings,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';
async function input(){const ledger=await Bun.file('docs/behaviors/revision-moves-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of Object.keys(ledger.sourceSha256))sources[p]=await Bun.file(p.startsWith('workflows/')?join(fixturesRoot(),p):p).text();const feature=parseFeature('workflows/docx/revisions.feature',sources['workflows/docx/revisions.feature']!,{allowDuplicateCaseNames:true});return {ledger,sources,inventory:await inventoryNativeTests(),features:[{...feature,scenarios:feature.scenarios.filter(s=>s.scenarioId.startsWith('@id-docx-paired-move-'))}]};}
test('move mappings add14partial records and45case wrapper preserving576prior rows except seven inventory assertions',async()=>{const x=await input(),r=reconcileOutcomeMappings(x.inventory,x.ledger,x.features,x.sources);expect(r.mappedDeclarations).toBe(14);expect(r.mappings.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([45]);expect(r.mappings.every(m=>m.status==='partial'&&m.gaps.length>0&&m.scenarioIds.every(id=>id.startsWith('@id-docx-paired-move-')))).toBe(true);const all=await outcomeMappingReport(),prior=structuredClone(all.mappings.filter(m=>m.ledger!=='revision-moves'));expect(prior).toHaveLength(576);let totals=0,neighbours=0;for(const row of prior){if(row.assertions.includes('expect(inv.counts.cases.implemented).toBe(726)')){row.assertions=row.assertions.map(a=>a.replace('counts.cases.implemented).toBe(726)','counts.cases.implemented).toBe(681)'));totals++;}if(row.testId.includes('revision-property-outcomes.test.ts:')&&row.assertions.includes('expect(r.counts.cases.planned).toBe(55)')){row.assertions=row.assertions.map(a=>a.replace('cases.planned).toBe(55)','cases.planned).toBe(10)'));neighbours++;}}expect(totals).toBe(6);expect(neighbours).toBe(1);expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(prior)).digest('hex')).toBe('2234e8c5389fe3f14242ad30cb5b70699e578132ccedb479727b80e712f9e43a');expect(all.mappedDeclarations).toBe(590);expect(all.executionCredit).toBe(false);});
test('move mappings reject stale sources omitted declarations property-profile credit and invented assertions',async()=>{const x=await input();for(const change of [(l:OutcomeMappingLedger)=>l.mappings.pop(),(l:OutcomeMappingLedger)=>{l.sourceSha256['tests/acceptance/revision-moves.ts']='0'.repeat(64);},(l:OutcomeMappingLedger)=>{l.mappings[0]!.scenarioIds=['@id-docx-run-property-revisions-roundtrip'];},(l:OutcomeMappingLedger)=>{l.mappings[0]!.assertions[0]='invented';}]){const l=structuredClone(x.ledger);change(l);expect(()=>reconcileOutcomeMappings(x.inventory,l,x.features,x.sources)).toThrow();}});
test('reviewed native move titles retain their own scenario families outcome predicates and gaps',async()=>{const l=await Bun.file('docs/behaviors/revision-moves-mappings.json').json();const expected:[string,string[],string][]=[
 ['paired same-story moves combine',['roundtrip'],'Thirty-five revisions'],
 ['previous profiles refuse moves',['defaults','scope'],'Both earlier profiles report/refuse'],
 ['malformed later move pairs refuse',['refusal'],'Later malformed pair variants'],
 ['cross-story pairs refuse',['refusal','ordering'],'Cross-story source/destination fragments'],
 ['reached later-write serialization',['rollback'],'Reached header-write, serialization'],
 ['strict move profile refuses',['guards'],'Already-resolved move input'],
 ['move aliases local wrapper declarations',['encoding'],'Both actions in three encodings'],
 ['multiple independent pairs',['ordering'],'wrapper order101,103,203,201'],
 ['unsafe namespace lifts decorated',['refusal'],'Unsafe namespace lift'],
 ['move namespaces compare expanded',['encoding','refusal'],'Alias-equivalent source/destination'],
 ['move range starts require valid',['dates'],'Both-side/both-action missing/unqualified/invalid dates'],
 ['move profile is exported',['defaults'],'Public exports match'],
 ];expect(expected).toHaveLength(12);for(const [title,scenarios,phrase]of expected){const rows=l.mappings.filter((m:any)=>m.testId.includes('docx-revision-moves.test.ts:'+title));expect(rows).toHaveLength(1);expect(rows[0].scenarioIds).toEqual(scenarios.map(n=>'@id-docx-paired-move-'+n));expect(rows[0].outcomes.join(' ')).toContain(phrase);expect(rows[0].gaps.length).toBeGreaterThan(0);expect(rows[0].caseKeys).toEqual([]);}});
