import {beforeSharedPlannedExpansion} from './mapping-history.ts';
import {test,expect} from 'bun:test';import {join} from 'node:path';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {inventoryNativeTests} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {outcomeMappingReport,reconcileOutcomeMappings,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';
async function input(){const ledger=await Bun.file('docs/behaviors/revision-properties-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of Object.keys(ledger.sourceSha256))sources[p]=await Bun.file(p.startsWith('workflows/')?join(fixturesRoot(),p):p).text();const feature=parseFeature('workflows/docx/revisions.feature',sources['workflows/docx/revisions.feature']!,{allowDuplicateCaseNames:true});return {ledger,sources,inventory:await inventoryNativeTests(),features:[{...feature,scenarios:feature.scenarios.filter(s=>s.scenarioId.startsWith('@id-docx-run-property-revisions-'))}]};}
test('property mappings add14partial records and33case wrapper preserving562prior rows except five inventory totals',async()=>{const x=await input(),r=reconcileOutcomeMappings(x.inventory,x.ledger,x.features,x.sources);expect(r.mappedDeclarations).toBe(14);expect(r.mappings.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([33]);expect(r.mappings.every(m=>m.status==='partial'&&m.gaps.length>0&&m.scenarioIds.every(id=>id.startsWith('@id-docx-run-property-revisions-')))).toBe(true);const all=await outcomeMappingReport(),prior=structuredClone(all.mappings.filter(m=>m.ledger!=='revision-properties'&&m.ledger!=='revision-moves'));expect(prior).toHaveLength(562);let corrected=0;for(const row of prior)if(row.assertions.includes('expect(inv.counts.cases.implemented).toBe(726)')){row.assertions=row.assertions.map(a=>a.replace('counts.cases.implemented).toBe(726)','counts.cases.implemented).toBe(648)'));corrected++;}expect(corrected).toBe(5);expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(beforeSharedPlannedExpansion(prior))).digest('hex')).toBe('b51d66bbd13702d5b30ba784bc74101877c7b454c9df9e38696b0050b1503ae5');expect(all.mappedDeclarations).toBe(590);expect(all.executionCredit).toBe(false);});
test('property mappings reject stale inputs omitted declarations text-only credit and invented assertions',async()=>{const x=await input();for(const change of [(l:OutcomeMappingLedger)=>l.mappings.pop(),(l:OutcomeMappingLedger)=>{l.sourceSha256['tests/acceptance/revision-properties.ts']='0'.repeat(64);},(l:OutcomeMappingLedger)=>{l.mappings[0]!.scenarioIds=['@id-docx-revisions-all-stories'];},(l:OutcomeMappingLedger)=>{l.mappings[0]!.assertions[0]='invented';}]){const l=structuredClone(x.ledger);change(l);expect(()=>reconcileOutcomeMappings(x.inventory,l,x.features,x.sources)).toThrow();}});
test('reviewed native property titles retain matching scenario families outcome predicates and explicit gaps',async()=>{const l=await Bun.file('docs/behaviors/revision-properties-mappings.json').json();const expected:[string,string[],string][]=[
 ['opt-in run-property profile resolves exact',['roundtrip'],'Twenty-one revisions across seven stories'],
 ['default text-only refusal stays unchanged',['scope','default'],'Default format findings'],
 ['unsafe later run-property snapshots refuse',['refusal'],'Malformed later header snapshot'],
 ['run-property snapshot namespace meaning',['encoding'],'UTF8 BOM and UTF16 LE/BE'],
 ['run-property profile validates protected',['guards'],'Linked enforced protection'],
 ['reached later-write and serialization faults',['rollback'],'Reached header write and serialization faults'],
 ['empty previous properties restore',['empty'],'Empty saved set removes all current properties'],
 ['extended-profile no-op still checks',['guards'],'After resolving all revisions'],
 ['default text revision writer also retains',['encoding','default','refusal'],'Default text writer retains UTF8 BOM'],
 ['all supported direct property families',['roundtrip','refusal'],'representative font/flag/appearance/size'],
 ['post-write validation fault rolls back',['scope','rollback'],'reached reinsertion fault'],
 ['public entrypoints expose the opt-in',['default'],'Public exports match'],
 ];expect(expected).toHaveLength(12);for(const [title,scenarios,phrase]of expected){const rows=l.mappings.filter((m:any)=>m.testId.includes('docx-revision-properties.test.ts:'+title));expect(rows).toHaveLength(1);expect(rows[0].scenarioIds).toEqual(scenarios.map(n=>'@id-docx-run-property-revisions-'+n));expect(rows[0].outcomes.join(' ')).toContain(phrase);expect(rows[0].gaps.length).toBeGreaterThan(0);expect(rows[0].caseKeys).toEqual([]);}});
