import {beforeSharedPlannedExpansion} from './mapping-history.ts';
import {verifyReferences} from '../../scripts/references.ts';
import {test,expect} from 'bun:test';import {join} from 'node:path';
import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {inventoryNativeTests} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';
import {outcomeMappingReport,reconcileOutcomeMappings,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';
async function input(){const ledger=await Bun.file('docs/behaviors/table-merging-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of Object.keys(ledger.sourceSha256))sources[p]=await Bun.file(p.startsWith('workflows/')?join(fixturesRoot(),p):p).text();if(process.env.OOXML_FIXTURES_ROOT){await verifyReferences(process.cwd());const pin=await Bun.file(process.env.OOXML_REFERENCE_PIN!).json(),review=await Bun.file('docs/behaviors/cell-runtime-candidate.json').json();if(pin.commit!==review.commit||pin.manifestSha256!==review.manifestSha256)throw Error('Unreviewed cell candidate');ledger.sourceSha256['workflows/docx/tables.feature']=review.tablesFeatureSha256;}return {ledger,sources,inventory:await inventoryNativeTests(),features:Object.entries(sources).filter(([p])=>p.startsWith('workflows/')).map(([p,s])=>parseFeature(p,s,{allowDuplicateCaseNames:true}))};}
test('physical merge mappings cover29 declarations and select26 cases for each axis without granting vertical profile credit',async()=>{
 const x=await input(),r=reconcileOutcomeMappings(x.inventory,x.ledger,x.features,x.sources);expect(r.mappedDeclarations).toBe(29);expect(r.mappings.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([26,26]);expect(r.mappings.every(m=>m.status==='partial'&&m.gaps.length>0)).toBe(true);expect(r.mappings.find(m=>m.scenarioIds.includes('@id-docx-go-table-merge-properties'))!.caseKeys).toEqual([]);
 const all=await outcomeMappingReport(),old=structuredClone(all.mappings.filter(m=>!['table-merging','template-inventory','comment-threads','revision-properties','revision-moves'].includes(m.ledger)));expect(old).toHaveLength(501);const adjusted=old.find(m=>m.testId.endsWith('empty style retains strict Bun policy and all five shared getter-profile cases stay planned'))!;expect(adjusted.assertions).toContain('expect(inv.counts.cases.implemented).toBe(732)');adjusted.assertions=adjusted.assertions.map(a=>a.replace('counts.cases.implemented).toBe(732)','counts.cases.implemented).toBe(551)'));expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(beforeSharedPlannedExpansion(old))).digest('hex')).toBe('b42a5938944fe55573864b1ef5e68c416e468c0fe351cf1ee7d2ad0c3c3be220');expect(all.mappedDeclarations).toBe(590);expect(all.executionCredit).toBe(false);
});
test('physical merge mapping omission stale helper pins unknown keys and invented assertions refuse',async()=>{
 const x=await input();for(const change of [(l:OutcomeMappingLedger)=>l.mappings.pop(),(l:OutcomeMappingLedger)=>{l.sourceSha256['tests/acceptance/table-merging.ts']='0'.repeat(64);},(l:OutcomeMappingLedger)=>{l.mappings[0]!.caseKeys=['unknown'];},(l:OutcomeMappingLedger)=>{l.mappings[0]!.assertions[0]='invented';}]){const l=structuredClone(x.ledger);change(l);expect(()=>reconcileOutcomeMappings(x.inventory,l,x.features,x.sources)).toThrow();}
});
