import {beforeUniformApi18Feature} from '../helpers/uniform-api18-history.ts';
import {test,expect} from 'bun:test';
import {readFileSync} from 'node:fs';
import {join} from 'node:path';
import {fixturesRoot} from '../../scripts/fixture-inputs.ts';
import {selectSharedScenarios,executeAcceptance} from '../../scripts/gherkin.ts';
import {bindings} from '../acceptance/steps.ts';
import {parseXml,applyEdits} from '../../src/xml/index.ts';
import {OoxmlError,classifyXmlOperationFailure} from '../../src/errors.ts';
export const ids=['xml-parse-offsets','xml-normalise-line-endings','xml-invalid-qname-components','xml-unicode-qname-components','xml-outside-root-nbsp','xml-parse-refusals','xml-parse-bounds','xml-escaping-values','xml-escaping-invalid-character','xml-apply-edits','xml-go-immutable-leaf-seed','xml-go-attribute-splice-custody','xml-go-attribute-batch-refusal','xml-go-element-removal-custody','xml-go-element-removal-refusal','xml-go-child-insertion-custody','xml-go-child-insertion-refusal','xml-go-child-namespace-matrix','xml-go-element-replacement-custody','xml-go-element-replacement-refusal'].map(s=>'@id-'+s);
const paths=['workflows/xml/parsing.feature','workflows/xml/names.feature','workflows/xml/editing.feature'];
const texts=await Promise.all(paths.map(p=>beforeUniformApi18Feature(p,readFileSync(join(fixturesRoot(),p),'utf8'))));
const enabled=texts[0]!.includes('the lexical XML input is JSON');
export async function runXmlAlignment(change=(s:string)=>s,active=bindings){const features=paths.map((p,i)=>selectSharedScenarios(p,change(texts[i]!),ids.filter(id=>texts[i]!.includes(id+'\n'))));const c=(n:number)=>({implemented:n,planned:0,total:n});return executeAcceptance({root:'.',features,counts:{features:c(3),scenarios:c(20),cases:c(29),steps:c(112)}},active,'xml-lexical-alignment');}
(enabled?test:test.skip)('twenty sealed XML IDs execute exactly29cases112steps through production APIs',async()=>{const r=await runXmlAlignment();expect(r.failures).toEqual([]);expect(r.counts.cases.passed).toBe(29);const ss=r.features.flatMap(f=>f.scenarios).filter(s=>s.lifecycle==='implemented');expect(ss).toHaveLength(20);expect(ss.flatMap(s=>s.cases).reduce((n,c)=>n+c.steps.length,0)).toBe(112);expect(ss.every(s=>s.cases.every(c=>c.steps.every(s=>s.status==='passed')))).toBe(true);});
(enabled?test:test.skip)('numeric coordinate, category and output discriminators fail with no ambiguous bindings',async()=>{for(const mutate of [(s:string)=>s.replace('| 115   | 129','| 114   | 129'),(s:string)=>s.replace('UTF-16 [65,69)','UTF-16 [65,68)'),(s:string)=>s.replace('[39,46)','[39,45)'),(s:string)=>s.replace('| dtd-forbidden','| malformed-xml'),(s:string)=>s.replace('"<r>1 &lt; 2 <x/></r>"','"<r>wrong</r>"')]){const r=await runXmlAlignment(mutate);expect(r.counts.cases.failed).toBeGreaterThan(0);expect(r.counts.steps.ambiguous).toBe(0);expect(r.counts.steps.undefined).toBe(0);}});
(enabled?test:test.skip)('runtime classifier and original-source custody faults are detected',async()=>{for(const mutate of [(s:any)=>{if(s.document)s.document.root.start++;},(s:any)=>{s.source+='changed';},(s:any)=>{s.error=new Error('unrelated');s.document=undefined;}]){const active=bindings.map(b=>b.pattern.test('the lexical XML input is parsed without rewriting its source')?{...b,run:async(c:Record<string,unknown>,...captures:string[])=>{await b.run(c,...captures);mutate(c.lexical);}}:b);const r=await runXmlAlignment(s=>s,active);expect(r.counts.cases.failed).toBeGreaterThan(0);expect(r.counts.steps.ambiguous).toBe(0);}});
test('production XML category mappings refuse unrelated errors and comments/CDATA do not create a DTD',()=>{expect(classifyXmlOperationFailure(new Error('XML_MALFORMED'))).toBeUndefined();expect(classifyXmlOperationFailure(new OoxmlError('OTHER','DTD'))).toBeUndefined();expect(classifyXmlOperationFailure(new OoxmlError('XML_MISMATCHED_TAG','irrelevant'))).toBe('mismatched-tag');for(const s of ['<!--<!DOCTYPE r>--><r/>','<r><![CDATA[<!DOCTYPE r>]]></r>'])expect(parseXml(s).root.name).toBe('r');const direct=parseXml('<r>a<!--c-->b<?pi x?>c<x>nested</x>d<![CDATA[e]]></r>');expect(direct.root.directText).toBe('abcde');expect(direct.root.text).toBe('abcnestedde');expect(direct.root.children[0]!.directText).toBe('nested');const source='<r>😀one</r>';expect(applyEdits(source,[{start:5,end:8,value:'two'}])).toBe('<r>😀two</r>');expect(source).toBe('<r>😀one</r>');});
