import {test,expect} from 'bun:test';import {outcomeMappingReport,reconcileOutcomeMappingSets,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';import {inventoryTestSource} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {join} from 'node:path';
const paths=['tests/unit/zip.test.ts','tests/unit/zip32-bindings.test.ts'],canonical='workflows/package/zip32.feature';
const pins=[...paths,'tests/acceptance/zip32.ts','tests/acceptance/refusal-outcomes.ts','tests/acceptance/steps.ts','tests/fixtures/zip32.ts','src/opc/zip.ts','src/errors.ts','scripts/fixture-inputs.ts','scripts/gherkin.ts','scripts/test-inventory.ts',canonical];
async function sample(){const ledger=await Bun.file('docs/behaviors/zip32-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of pins)sources[p]=await Bun.file(p===canonical?join(fixturesRoot(),p):p).text();return {inventory:{cases:paths.flatMap(p=>inventoryTestSource(p,sources[p]!)),unresolved:[]},sets:[{name:'zip32',expectedScopePaths:paths,ledger,features:[parseFeature(canonical,sources[canonical]!)],sources}]};}
test('ZIP32 ledger enumerates 24 declarations and 106 direct expressions preserving 422 predecessor rows',async()=>{
 const r=await outcomeMappingReport(),rows=r.mappings.filter(m=>m.ledger==='zip32');expect(rows).toHaveLength(24);expect(rows.reduce((n,m)=>n+m.assertions.length,0)).toBe(106);expect(rows.slice(0,19).reduce((n,m)=>n+m.assertions.length,0)).toBe(61);expect(r.ledgers.find(l=>l.name==='zip32')!.scopePaths).toEqual(paths);expect(rows.filter(m=>m.caseKeys.length).map(m=>m.caseKeys.length)).toEqual([20]);expect(rows.every(m=>m.status==='partial'&&m.executionCredit===false&&m.gaps.length&&m.outcomes.length)).toBe(true);expect(r.mappedDeclarations).toBe(576);expect(r.unmappedTestIds.length).toBe(r.totalDeclarations-576);expect(r.runtimeLeafCount).toBeNull();expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(r.mappings.filter(m=>['slide-order','effective-formatting','xml-values','pptx-core','docx-model','docx-anchors','xlsx-comments','xlsx-styles','pptx-text-boxes','docx-page-layout','docx-paragraph-styles','docx-style-authoring','xml-comparison','package-comparison','docx-comments','opc-graph','zip64','formula-references'].includes(m.ledger)))).digest('hex')).toBe('bcf430ee7c7abf86854a70035035cb33bec5c65f10214fce006b2a8935aa1c48');
});
test('ZIP32 mappings preserve corpus smoke BZIP2 bounds aggregate and nested-control limits',async()=>{
 const rows=(await outcomeMappingReport()).mappings.filter(m=>m.ledger==='zip32');expect(rows[9]!.gaps.join(' ')).toContain('BZIP2');expect(rows[17]!.gaps.join(' ')).toContain('deduplicated');expect(rows[18]!.gaps.join(' ')).toContain('smoke');expect(rows[19]!.gaps.join(' ')).toContain('aggregate');expect(rows[19]!.gaps.join(' ')).toContain('four planned');expect(rows[20]!.gaps.join(' ')).toContain('nested');expect(rows[21]!.gaps.join(' ')).toContain('signature');expect(rows[23]!.gaps.join(' ')).toContain('writer');expect(rows.filter(m=>m.caseKeys.length)[0]!.testId).toContain('twenty canonical');
});
test('ZIP32 suites and literal assertions cannot shrink or borrow ZIP64 case keys',async()=>{
 for(const p of paths){const a=await sample();a.sets[0]!.ledger.scopePaths=a.sets[0]!.ledger.scopePaths.filter(x=>x!==p);expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('scope');const b=await sample();b.sets[0]!.ledger.mappings.splice(b.sets[0]!.ledger.mappings.findIndex(m=>m.testId.includes(p)),1);expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('Missing scoped');const c=await sample();c.sets[0]!.ledger.mappings.find(m=>m.testId.includes(p))!.assertions.pop();expect(()=>reconcileOutcomeMappingSets(c.inventory,c.sets)).toThrow('assertion');const d=await sample();d.sets[0]!.ledger.mappings.find(m=>m.testId.includes(p))!.caseKeys=['@id-parity-zip64'];expect(()=>reconcileOutcomeMappingSets(d.inventory,d.sets)).toThrow('case');}
});
test('ZIP32 runtime fixture-builder binding and canonical source pins all reject stale or missing inputs',async()=>{
 for(const p of pins){const a=await sample();expect(Object.hasOwn(a.sets[0]!.ledger.sourceSha256,p)).toBe(true);a.sets[0]!.sources[p]+=' ';expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('Stale source');const b=await sample();delete b.sets[0]!.ledger.sourceSha256[p];expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('pin');}
});
test('ZIP32 reconciliation preserves original direct and nested evidence review flags and unknown leaves',async()=>{
 const a=await sample(),before=JSON.stringify(a),r=reconcileOutcomeMappingSets(a.inventory,a.sets);expect(JSON.stringify(a)).toBe(before);expect(r.mappings.map(m=>m.assertions)).toEqual(a.inventory.cases.map(m=>m.assertions));expect(r.mappings.map(m=>m.deferredAssertions)).toEqual(a.inventory.cases.map(m=>m.deferredAssertions));expect(r.mappings.map(m=>m.reviewReasons)).toEqual(a.inventory.cases.map(m=>m.reviewReasons));expect(r.executionCredit).toBe(false);expect(r.runtimeLeafCount).toBeNull();expect(r.mappings[20]!.deferredAssertions).toHaveLength(1);expect(r.mappings[21]!.deferredAssertions).toHaveLength(3);expect(r.mappings.every(m=>m.assertions.length>0)).toBe(true);
});
