import {test,expect} from 'bun:test';import {outcomeMappingReport,reconcileOutcomeMappingSets,type OutcomeMappingLedger} from '../../scripts/outcome-mappings.ts';import {inventoryTestSource} from '../../scripts/test-inventory.ts';import {parseFeature} from '../../scripts/gherkin.ts';import {fixturesRoot} from '../../scripts/fixture-inputs.ts';import {join} from 'node:path';
const path='tests/unit/zip64.test.ts',canonical='workflows/package/zip64.feature',ids=['@id-parity-zip64','@id-zip64-preflight-count','@id-zip64-unsafe-offset'];
const pins=[path,'tests/acceptance/zip64.ts','src/opc/zip.ts','src/errors.ts','scripts/gherkin.ts','scripts/test-inventory.ts',canonical];
async function sample(){const ledger=await Bun.file('docs/behaviors/zip64-mappings.json').json() as OutcomeMappingLedger,sources:Record<string,string>={};for(const p of pins)sources[p]=await Bun.file(p===canonical?join(fixturesRoot(),p):p).text();return {inventory:{cases:inventoryTestSource(path,sources[path]!),unresolved:[]},sets:[{name:'zip64',expectedScopePaths:[path],ledger,features:[parseFeature(canonical,sources[canonical]!)],sources}]};}
test('ZIP64 ledger enumerates 15 declarations and 46 direct expressions preserving 407 previous mappings',async()=>{
 const r=await outcomeMappingReport(),rows=r.mappings.filter(m=>m.ledger==='zip64');expect(rows).toHaveLength(15);expect(rows.reduce((n,m)=>n+m.assertions.length,0)).toBe(46);expect(r.ledgers.find(l=>l.name==='zip64')!.scopePaths).toEqual([path]);expect(rows.every(m=>m.caseKeys.length===0)).toBe(true);expect(new Set(rows.flatMap(m=>m.scenarioIds))).toEqual(new Set(ids));expect(rows.every(m=>m.status==='partial'&&m.executionCredit===false&&m.gaps.length&&m.outcomes.length)).toBe(true);expect(r.mappedDeclarations).toBe(562);expect(r.unmappedTestIds.length).toBe(r.totalDeclarations-562);expect(r.runtimeLeafCount).toBeNull();expect(new Bun.CryptoHasher('sha256').update(JSON.stringify(r.mappings.filter(m=>['slide-order','effective-formatting','xml-values','pptx-core','docx-model','docx-anchors','xlsx-comments','xlsx-styles','pptx-text-boxes','docx-page-layout','docx-paragraph-styles','docx-style-authoring','xml-comparison','package-comparison','docx-comments','opc-graph','formula-references'].includes(m.ledger)))).digest('hex')).toBe('a8610b73a7282223876eae9bd9f462eca0687d373ad5ffdacccac0b3c3b2dcdc');
});
test('ZIP64 mapping limits helper attribution tiny signed descriptors counts budgets and missing mutation workflow',async()=>{
 const rows=(await outcomeMappingReport()).mappings.filter(m=>m.ledger==='zip64');expect(rows[2]!.gaps.join(' ')).toContain('signed');expect(rows[4]!.gaps.join(' ')).toContain('allocation');expect(rows[5]!.gaps.join(' ')).toContain('locator');expect(rows[11]!.gaps.join(' ')).toContain('compressed');expect(rows[13]!.gaps.join(' ')).toContain('helper');expect(rows[13]!.gaps.join(' ')).toContain('changed-member');expect(rows[14]!.gaps.join(' ')).toContain('empty');expect(rows[14]!.gaps.join(' ')).toContain('resource-limit');expect(rows.every(m=>!m.scenarioIds.includes('@id-zip64-resource-limit'))).toBe(true);
});
test('ZIP64 scope assertions and semantic package-diff case borrowing refuse',async()=>{
 const a=await sample();a.sets[0]!.ledger.scopePaths=[];expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('scope');const b=await sample();b.sets[0]!.ledger.mappings.pop();expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('Missing scoped');const c=await sample();c.sets[0]!.ledger.mappings[0]!.assertions.pop();expect(()=>reconcileOutcomeMappingSets(c.inventory,c.sets)).toThrow('assertion');const d=await sample();d.sets[0]!.ledger.mappings[0]!.caseKeys=['@id-package-diff-equivalent-xml-and-binary-changes'];expect(()=>reconcileOutcomeMappingSets(d.inventory,d.sets)).toThrow('case');
});
test('ZIP64 source pins reject stale or absent suite runtime binding and shared inputs',async()=>{
 for(const p of pins){const a=await sample();expect(Object.hasOwn(a.sets[0]!.ledger.sourceSha256,p)).toBe(true);a.sets[0]!.sources[p]+=' ';expect(()=>reconcileOutcomeMappingSets(a.inventory,a.sets)).toThrow('Stale source');const b=await sample();delete b.sets[0]!.ledger.sourceSha256[p];expect(()=>reconcileOutcomeMappingSets(b.inventory,b.sets)).toThrow('pin');}
});
test('ZIP64 reconciliation retains direct refusal predicates review flags and uncounted helper separation',async()=>{
 const a=await sample(),before=JSON.stringify(a),r=reconcileOutcomeMappingSets(a.inventory,a.sets);expect(JSON.stringify(a)).toBe(before);expect(r.mappings.map(m=>m.assertions)).toEqual(a.inventory.cases.map(m=>m.assertions));expect(r.mappings.map(m=>m.deferredAssertions)).toEqual(a.inventory.cases.map(m=>m.deferredAssertions));expect(r.mappings.map(m=>m.reviewReasons)).toEqual(a.inventory.cases.map(m=>m.reviewReasons));expect(r.executionCredit).toBe(false);expect(r.runtimeLeafCount).toBeNull();const refusals=r.mappings.filter(m=>m.testId.includes('refuses'));expect(refusals).toHaveLength(11);expect(refusals.every(m=>m.assertions.length===3&&m.assertions.some(s=>s.includes('toBeInstanceOf(OoxmlError)')))).toBe(true);
});
