import assert from 'node:assert/strict';
import {inflateRawSync} from 'node:zlib';
import {posix} from 'node:path';
const decoder=new TextDecoder('utf-8',{fatal:true});
export type Node={name:string;local:string;ns:string;attrs:Record<string,string>;bindings:Record<string,string>;children:Node[];text:string;start:number;openEnd:number;closeStart:number;end:number;selfClosing:boolean};
export const S='http://schemas.openxmlformats.org/spreadsheetml/2006/main',P='http://schemas.openxmlformats.org/presentationml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships',PKG='http://schemas.openxmlformats.org/package/2006/relationships',CT='http://schemas.openxmlformats.org/package/2006/content-types';
const crcTable=Array.from({length:256},(_,i)=>{let n=i;for(let b=0;b<8;b++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(data:Uint8Array):number{let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&255]!^(c>>>8);return (c^0xffffffff)>>>0;}
export function archive(bytes:Uint8Array):Map<string,Uint8Array>{
 const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);assert(bytes.length>=22);let e=bytes.length-22;while(e>=Math.max(0,bytes.length-65557)&&view.getUint32(e,true)!==0x06054b50)e--;assert(e>=0);assert.equal(e+22+view.getUint16(e+20,true),bytes.length);assert.equal(view.getUint16(e+4,true),0);assert.equal(view.getUint16(e+6,true),0);
 const count=view.getUint16(e+10,true);assert.equal(view.getUint16(e+8,true),count);let cursor=view.getUint32(e+16,true);const centralEnd=cursor+view.getUint32(e+12,true);assert(centralEnd<=e);const parts=new Map<string,Uint8Array>();
 for(let i=0;i<count;i++){assert(cursor+46<=centralEnd);assert.equal(view.getUint32(cursor,true),0x02014b50);const flags=view.getUint16(cursor+8,true),method=view.getUint16(cursor+10,true),compressed=view.getUint32(cursor+20,true),size=view.getUint32(cursor+24,true),nameLen=view.getUint16(cursor+28,true),extra=view.getUint16(cursor+30,true),comment=view.getUint16(cursor+32,true),local=view.getUint32(cursor+42,true);assert(!(flags&1));assert(method===0||method===8);assert(cursor+46+nameLen+extra+comment<=centralEnd);const name=decoder.decode(bytes.subarray(cursor+46,cursor+46+nameLen));assert(!parts.has(name));assert(!name.startsWith('/')&&!name.split('/').some(p=>!p||p==='.'||p==='..'));assert(local+30<=bytes.length);assert.equal(view.getUint32(local,true),0x04034b50);assert.equal(view.getUint16(local+8,true),method);const localNameLen=view.getUint16(local+26,true),start=local+30+localNameLen+view.getUint16(local+28,true);assert.equal(decoder.decode(bytes.subarray(local+30,local+30+localNameLen)),name);assert(start+compressed<=view.getUint32(e+16,true));const payload=bytes.subarray(start,start+compressed),data=method===8?new Uint8Array(inflateRawSync(payload)):payload.slice();assert.equal(data.length,size);assert.equal(crc32(data),view.getUint32(cursor+16,true),'Independent ZIP CRC32');if(!(flags&8)){assert.equal(view.getUint32(local+14,true),view.getUint32(cursor+16,true));assert.equal(view.getUint32(local+18,true),compressed);assert.equal(view.getUint32(local+22,true),size);}parts.set(name,data);cursor+=46+nameLen+extra+comment;}
 assert.equal(cursor,centralEnd);return parts;
}
function decode(s:string):string {assert(!s.replace(/&(?:amp|lt|gt|quot|apos|#\d+|#x[0-9a-fA-F]+);/g,'').includes('&'));return s.replace(/&([^;]+);/g,(_,v:string)=>{const named:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"};if(named[v]!==undefined)return named[v]!;const n=v.startsWith('#x')?parseInt(v.slice(2),16):parseInt(v.slice(1),10);assert(n===9||n===10||n===13||(n>=32&&n<=0x10ffff&&!(n>=0xd800&&n<=0xdfff)&&n!==0xfffe&&n!==0xffff));return String.fromCodePoint(n);});}
export function xml(source:string):Node {
 const stack:Node[]=[],roots:Node[]=[];let cursor=0;
 while(cursor<source.length){if(source[cursor]!=='<'){const next=source.indexOf('<',cursor),end=next<0?source.length:next,value=decode(source.slice(cursor,end));if(stack.length)stack.at(-1)!.text+=value;else assert(!value.trim());cursor=end;continue;}
  if(source.startsWith('<!--',cursor)){const e=source.indexOf('-->',cursor+4);assert(e>=0);cursor=e+3;continue;}if(source.startsWith('<?',cursor)){const e=source.indexOf('?>',cursor+2);assert(e>=0);cursor=e+2;continue;}assert(!source.startsWith('<!',cursor),'DTD/CDATA outside bounded oracle');
  let end=cursor+1,quote='';for(;end<source.length;end++){const c=source[end]!;if(quote){if(c===quote)quote='';}else if(c==='"'||c==="'")quote=c;else if(c==='>')break;}assert(end<source.length);const token=source.slice(cursor+1,end);
  if(token.startsWith('/')){const node=stack.pop();assert(node);assert.equal(token.slice(1).trim(),node.name);node.closeStart=cursor;node.end=end+1;cursor=end+1;continue;}
  const match=/^([A-Za-z_][\w.:-]*)([\s\S]*?)(\/?)$/.exec(token);assert(match);const name=match[1]!,attrs:Record<string,string>=Object.create(null),tail=match[2]!;let a=0;while(a<tail.length){const m=/^\s+([A-Za-z_][\w.:-]*)\s*=\s*(["'])([\s\S]*?)\2/.exec(tail.slice(a));if(!m){assert(!tail.slice(a).trim());break;}assert(!Object.hasOwn(attrs,m[1]!));assert(!m[3]!.includes('<'));attrs[m[1]!]=decode(m[3]!);a+=m[0].length;}
  const bindings={...(stack.at(-1)?.bindings??{xml:'http://www.w3.org/XML/1998/namespace'})};for(const[k,v]of Object.entries(attrs)){if(k==='xmlns')bindings['']=v;else if(k.startsWith('xmlns:'))bindings[k.slice(6)]=v;}
  const pieces=name.split(':');assert(pieces.length<=2);const local=pieces.at(-1)!,prefix=pieces.length===2?pieces[0]!:'',ns=bindings[prefix]??'';if(prefix)assert(bindings[prefix]);const expanded=new Set<string>();for(const k of Object.keys(attrs)){if(k==='xmlns'||k.startsWith('xmlns:'))continue;const q=k.split(':');assert(q.length<=2);if(q.length===2)assert(bindings[q[0]!]);const key=(q.length===2?bindings[q[0]!]:'')+'/'+q.at(-1);assert(!expanded.has(key));expanded.add(key);}
  const selfClosing=match[3]==='/',node:Node={name,local,ns,attrs,bindings,children:[],text:'',start:cursor,openEnd:end+1,closeStart:end+1,end:end+1,selfClosing};if(stack.length)stack.at(-1)!.children.push(node);else roots.push(node);if(!selfClosing)stack.push(node);cursor=end+1;
 }
 assert.equal(stack.length,0);assert.equal(roots.length,1);return roots[0]!;
}
export function descendants(n:Node,local:string,ns?:string):Node[]{const result:Node[]=[];function walk(x:Node){if(x.local===local&&(ns===undefined||x.ns===ns))result.push(x);for(const c of x.children)walk(c);}walk(n);return result;}
export function partText(parts:Map<string,Uint8Array>,part:string):string{const data=parts.get(part);assert(data,'Missing '+part);return decoder.decode(data);}
export function child(n:Node,local:string,ns:string):Node|undefined{return n.children.find(c=>c.local===local&&c.ns===ns);}
export function relationshipOwner(path:string):string{if(path==='_rels/.rels')return '';const m=/^(.*\/)?_rels\/([^/]+)\.rels$/.exec(path);assert(m);return (m[1]??'')+m[2];}
export type Edge={owner:string;id:string;type:string;target:string;resolved:string;external:boolean};
export function graph(parts:Map<string,Uint8Array>):{edges:Edge[];types:Map<string,string>}{
 const content=xml(partText(parts,'[Content_Types].xml'));assert.equal(content.ns,CT);const defaults=new Map<string,string>(),overrides=new Map<string,string>();for(const c of content.children){assert.equal(c.ns,CT);assert(c.attrs.ContentType);if(c.local==='Default'){const key=c.attrs.Extension!.toLowerCase();assert(!defaults.has(key));defaults.set(key,c.attrs.ContentType!);}else{assert.equal(c.local,'Override');const key=c.attrs.PartName!.slice(1);assert(c.attrs.PartName!.startsWith('/')&&!overrides.has(key)&&parts.has(key));overrides.set(key,c.attrs.ContentType!);}}
 const types=new Map<string,string>(),edges:Edge[]=[];for(const p of parts.keys()){if(p==='[Content_Types].xml')continue;const type=overrides.get(p)??defaults.get(p.split('.').at(-1)!.toLowerCase());assert(type,'Content type '+p);types.set(p,type);if(!p.endsWith('.rels'))continue;const owner=relationshipOwner(p);if(owner)assert(parts.has(owner));const root=xml(partText(parts,p));assert.equal(root.ns,PKG);assert.equal(root.local,'Relationships');const ids=new Set<string>();for(const c of root.children){assert.equal(c.local,'Relationship');assert.equal(c.ns,PKG);const {Id:id,Type:type,Target:target}=c.attrs;assert(id&&type&&target&&!ids.has(id));ids.add(id);const external=c.attrs.TargetMode==='External';assert(!c.attrs.TargetMode||external);const resolved=external?'':posix.normalize(target.startsWith('/')?target.slice(1):posix.join(owner?posix.dirname(owner):'',target.split('#')[0]!));if(!external)assert(parts.has(resolved),'Unresolved '+p+' '+target);edges.push({owner,id,type,target,resolved,external});}}
 assert.equal(edges.filter(e=>e.owner===''&&e.type===R+'/officeDocument').length,1);return {edges,types};
}
export function masked(source:string,spans:readonly {start:number;end:number}[]):string{let end=0;return [...spans].sort((a,b)=>a.start-b.start).map(s=>{assert(s.start>=end&&s.end>=s.start);const text=source.slice(end,s.start);end=s.end;return text+'\u0000MASK\u0000';}).join('')+source.slice(end);}
export function sameMembers(before:Map<string,Uint8Array>,after:Map<string,Uint8Array>):void{assert.deepEqual([...after.keys()].sort(),[...before.keys()].sort());for(const[p,v]of before)assert.deepEqual(after.get(p),v,'Literal member '+p);}
