import assert from 'node:assert/strict';
import {archive,xml,descendants as all,child,graph,partText,S,P,A,R,CT,masked,type Node} from './contract20-oracle.ts';
export {archive,xml,all,child,graph,partText,S,P,A,R,CT,masked};
export function changed(before:Map<string,Uint8Array>,after:Map<string,Uint8Array>,expected:string[],added:string[]=[]):void{assert.deepEqual([...after.keys()].filter(p=>!before.has(p)).sort(),added.slice().sort());assert.deepEqual([...before.keys()].filter(p=>!after.has(p)),[]);assert.deepEqual([...before.keys()].filter(p=>!Buffer.from(before.get(p)!).equals(Buffer.from(after.get(p)!))).sort(),expected.slice().sort());for(const[p,b]of before)if(!expected.includes(p))assert.deepEqual(after.get(p),b,'unchanged '+p);}
export function sheets(parts:Map<string,Uint8Array>):{name:string;part:string}[]{const g=graph(parts),main=g.edges.find(e=>e.owner===''&&e.type===R+'/officeDocument')!.resolved;return all(xml(partText(parts,main)),'sheet',S).map(n=>{const attr=Object.entries(n.attrs).find(([k])=>k.includes(':')&&k.split(':').at(-1)==='id'&&n.bindings[k.split(':')[0]!]===R);assert(attr);const edge=g.edges.find(e=>e.owner===main&&e.id===attr[1]);assert(edge?.type===R+'/worksheet');return {name:n.attrs.name!,part:edge.resolved};});}
export function worksheetCell(parts:Map<string,Uint8Array>,sheet:string,reference:string):Node{const path=sheets(parts).find(s=>s.name===sheet)?.part;assert(path);const nodes=all(xml(partText(parts,path)),'c',S).filter(c=>c.attrs.r===reference);assert.equal(nodes.length,1);return nodes[0]!;}
function visible(n:Node):string{return n.children.filter(c=>c.ns===S&&(c.local==='t'||c.local==='r')).map(c=>c.local==='t'?c.text:visible(c)).join('');}
export function xlsxValue(parts:Map<string,Uint8Array>,sheet:string,ref:string):{kind:string;value?:unknown;formula?:string;cached?:unknown}{const c=worksheetCell(parts,sheet,ref),f=child(c,'f',S),v=child(c,'v',S),raw=v?.text;const scalar=()=>{if(raw===undefined||raw==='')return null;if(c.attrs.t==='b')return raw==='1';if(c.attrs.t==='s'){const g=graph(parts),main=g.edges.find(e=>e.owner===''&&e.type===R+'/officeDocument')!.resolved,part=g.edges.find(e=>e.owner===main&&e.type===R+'/sharedStrings')!.resolved,si=all(xml(partText(parts,part)),'si',S)[Number(raw)];assert(si);return visible(si);}if(c.attrs.t==='str'||c.attrs.t==='e')return raw;return Number(raw);};if(f)return {kind:'formula',formula:f.text,cached:scalar()};const inline=child(c,'is',S),value=inline?visible(inline):scalar();return {kind:value===null?'blank':typeof value==='string'?'string':typeof value==='boolean'?'boolean':'number',value};}
export function calc(parts:Map<string,Uint8Array>):void{const g=graph(parts),main=g.edges.find(e=>e.owner===''&&e.type===R+'/officeDocument')!.resolved,nodes=all(xml(partText(parts,main)),'calcPr',S);assert.equal(nodes.length,1);assert.equal(nodes[0]!.attrs.calcMode,'auto');assert.equal(nodes[0]!.attrs.fullCalcOnLoad,'1');assert.equal(nodes[0]!.attrs.forceFullCalc,'1');}
export function slideParts(parts:Map<string,Uint8Array>):string[]{const g=graph(parts),main=g.edges.find(e=>e.owner===''&&e.type===R+'/officeDocument')!.resolved;return all(xml(partText(parts,main)),'sldId',P).map(n=>{const attr=Object.entries(n.attrs).find(([k])=>k.includes(':')&&k.split(':').at(-1)==='id'&&n.bindings[k.split(':')[0]!]===R);assert(attr);const edge=g.edges.find(e=>e.owner===main&&e.id===attr[1]);assert(edge?.type===R+'/slide');return edge.resolved;});}
export function paragraphText(n:Node):string{return n.children.filter(c=>c.ns===A).map(c=>c.local==='br'?'\n':c.local==='r'||c.local==='fld'?child(c,'t',A)?.text??'':'').join('');}
export function placeholders(parts:Map<string,Uint8Array>):string[][]{return slideParts(parts).map(p=>{const root=xml(partText(parts,p));const values=(type:string)=>all(root,'sp',P).filter(n=>all(n,'ph',P).some(ph=>type==='title'?['title','ctrTitle'].includes(ph.attrs.type??''):ph.attrs.type===type)).map(n=>all(n,'p',A).map(paragraphText).join('\n'));const title=values('title'),subtitle=values('subTitle');assert.equal(title.length,1);assert(subtitle.length<=1);return [title[0]!,subtitle[0]??''];});}
export function notes(parts:Map<string,Uint8Array>,slide:number):{hasNotes:boolean;text:string}{const g=graph(parts),p=slideParts(parts)[slide];assert(p);const edges=g.edges.filter(e=>e.owner===p&&e.type===R+'/notesSlide');assert(edges.length<=1);if(!edges.length)return {hasNotes:false,text:''};const root=xml(partText(parts,edges[0]!.resolved)),body=all(root,'sp',P).filter(n=>all(n,'ph',P).some(ph=>ph.attrs.type==='body'));assert.equal(body.length,1);return {hasNotes:true,text:all(body[0]!,'p',A).map(paragraphText).join('\n')};}
export function table(parts:Map<string,Uint8Array>,part:string,shapeId:number):{frame:Node;tbl:Node;rows:Node[];cells:Node[][];widths:number[];heights:number[];x:number;y:number;width:number;height:number}{const frames=all(xml(partText(parts,part)),'graphicFrame',P).filter(n=>all(n,'cNvPr',P).some(c=>c.attrs.id===String(shapeId)));assert.equal(frames.length,1);const frame=frames[0]!,tables=all(frame,'tbl',A);assert.equal(tables.length,1);const tbl=tables[0]!,grid=child(tbl,'tblGrid',A);assert(grid);const rows=tbl.children.filter(c=>c.ns===A&&c.local==='tr'),cells=rows.map(r=>r.children.filter(c=>c.ns===A&&c.local==='tc')),xf=child(frame,'xfrm',P);assert(xf);const off=child(xf,'off',A)!,ext=child(xf,'ext',A)!;return {frame,tbl,rows,cells,widths:grid.children.map(c=>Number(c.attrs.w)),heights:rows.map(r=>Number(r.attrs.h)),x:Number(off.attrs.x),y:Number(off.attrs.y),width:Number(ext.attrs.cx),height:Number(ext.attrs.cy)};}
export function tableMatrix(t:ReturnType<typeof table>):string[][]{return t.cells.map(row=>row.map(c=>all(c,'p',A).map(paragraphText).join('\n')));}
export function creation(parts:Map<string,Uint8Array>,policy:any,count:number):void{
 const g=graph(parts),roles=new Map<string,string[]>();for(const [role,data]of Object.entries({...policy.requiredRoles,...policy.optionalRoles}) as [string,{contentType:string}][]){const names=[...g.types].filter(([p,t])=>!p.endsWith('.rels')&&t===data.contentType).map(([p])=>p);roles.set(role,names);const required=policy.requiredRoles[role];if(required)assert.equal(names.length,role==='slide'?count:required.count,role+' count');else assert(names.length<=1,role+' count');}
 const nameRole=new Map([...roles].flatMap(([role,names])=>names.map(p=>[p,role] as const)));for(const p of parts.keys()){if(p==='[Content_Types].xml'||p.endsWith('.rels'))continue;assert(nameRole.has(p),'Unknown creation role '+p);}
 const expand=(t:string)=>{const[prefix,suffix]=t.split(':');return policy.relationshipTypePrefixes[prefix!]+suffix;};const allowed=[...policy.requiredEdges,...policy.optionalEdges];for(const e of g.edges){assert(!e.external);const src=e.owner?nameRole.get(e.owner):'packageRoot',dst=nameRole.get(e.resolved);assert(allowed.some(a=>a.sourceRole===src&&a.targetRole===dst&&expand(a.type)===e.type),'Unknown edge '+e.type);}
 for(const a of policy.requiredEdges){const sources=a.sourceRole==='packageRoot'?['']:roles.get(a.sourceRole)!;for(const src of sources)assert.equal(g.edges.filter(e=>e.owner===src&&roles.get(a.targetRole)!.includes(e.resolved)&&e.type===expand(a.type)).length,a.targetRole==='slide'?count:1);}
 for(const a of policy.optionalEdges){const sources=a.sourceRole==='packageRoot'?['']:roles.get(a.sourceRole)!;for(const src of sources)assert(g.edges.filter(e=>e.owner===src&&roles.get(a.targetRole)!.includes(e.resolved)&&e.type===expand(a.type)).length<=a.maxCount);if(a.targetRole!=='theme')for(const target of roles.get(a.targetRole)!)assert.equal(g.edges.filter(e=>e.resolved===target&&e.type===expand(a.type)).length,1);}
 for(const p of parts.keys())if(p.endsWith('.rels'))assert(g.edges.some(e=>e.owner===(p==='_rels/.rels'?'':p.replace(/\/\_rels\/([^/]+)\.rels$/,'/$1'))),'Orphan/empty relationship part');
 const main=roles.get('presentation')![0]!,doc=xml(partText(parts,main)),ids=all(doc,'sldId',P);assert.equal(ids.length,count);assert.equal(new Set(ids.map(n=>n.attrs.id)).size,count);assert(ids.every(n=>/^[1-9][0-9]*$/.test(n.attrs.id!)));assert.deepEqual(slideParts(parts).slice().sort(),roles.get('slide')!.slice().sort());for(const slide of slideParts(parts)){const root=xml(partText(parts,slide));assert.equal(root.ns,P);assert.equal(root.local,'sld');const ids=all(root,'cNvPr',P).map(n=>n.attrs.id);assert(ids.every(id=>id!==undefined&&/^[1-9][0-9]*$/.test(id)));assert.equal(new Set(ids).size,ids.length);const shapes=all(root,'sp',P);for(const shape of shapes){const ph=all(shape,'ph',P);if(!ph.length)assert(!all(shape,'t',A).some(n=>n.text!==''),'Unrequested visible shape');}for(const paragraph of all(root,'p',A))assert(paragraph.children.every(n=>n.ns===A&&['pPr','r','endParaRPr'].includes(n.local)),'Unsupported authored text child');}const layout=xml(partText(parts,roles.get('slideLayout')![0]!));assert.equal(layout.attrs.type,'title');assert.equal(all(layout,'ph',P).filter(n=>n.attrs.type==='subTitle').length,1);assert.equal(all(layout,'ph',P).filter(n=>['title','ctrTitle'].includes(n.attrs.type??'')).length,1);
 const master=xml(partText(parts,roles.get('slideMaster')![0]!));assert.equal(all(doc,'sldMasterId',P).length,1);assert.equal(all(master,'sldLayoutId',P).length,1);for(const [root,list,owner]of [[doc,'sldMasterId',main],[master,'sldLayoutId',roles.get('slideMaster')![0]!]] as [Node,string,string][]){const node=all(root,list,P)[0]!,id=Object.entries(node.attrs).find(([k])=>k.endsWith(':id'))?.[1];assert(g.edges.some(e=>e.owner===owner&&e.id===id));}
}
